// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2019.1
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="CNN_ALU_Top,hls_ip_2019_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=1,HLS_INPUT_PART=xc7z020-clg484-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=8.510000,HLS_SYN_LAT=3,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=16,HLS_SYN_FF=1539,HLS_SYN_LUT=2129,HLS_VERSION=2019_1}" *)

module CNN_ALU_Top (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        rs1_data_V,
        rs2_data_V,
        cnn_op_V,
        rd_data_V
);

parameter    ap_ST_fsm_state1 = 14'd1;
parameter    ap_ST_fsm_state2 = 14'd2;
parameter    ap_ST_fsm_state3 = 14'd4;
parameter    ap_ST_fsm_state4 = 14'd8;
parameter    ap_ST_fsm_state5 = 14'd16;
parameter    ap_ST_fsm_state6 = 14'd32;
parameter    ap_ST_fsm_state7 = 14'd64;
parameter    ap_ST_fsm_state8 = 14'd128;
parameter    ap_ST_fsm_pp0_stage0 = 14'd256;
parameter    ap_ST_fsm_state11 = 14'd512;
parameter    ap_ST_fsm_pp1_stage0 = 14'd1024;
parameter    ap_ST_fsm_state14 = 14'd2048;
parameter    ap_ST_fsm_state15 = 14'd4096;
parameter    ap_ST_fsm_state16 = 14'd8192;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [31:0] rs1_data_V;
input  [31:0] rs2_data_V;
input  [3:0] cnn_op_V;
output  [31:0] rd_data_V;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg[31:0] rd_data_V;

(* fsm_encoding = "none" *) reg   [13:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg   [7:0] weight_buf_V_0;
reg   [7:0] weight_buf_V_1;
reg   [7:0] weight_buf_V_2;
reg   [7:0] weight_buf_V_3;
reg   [7:0] weight_buf_V_4;
reg   [7:0] weight_buf_V_5;
reg   [7:0] weight_buf_V_6;
reg   [7:0] weight_buf_V_7;
reg   [7:0] weight_buf_V_8;
reg   [7:0] weight_buf_V_9;
reg   [7:0] weight_buf_V_10;
reg   [7:0] weight_buf_V_11;
reg   [7:0] weight_buf_V_12;
reg   [7:0] weight_buf_V_13;
reg   [7:0] weight_buf_V_14;
reg   [7:0] weight_buf_V_15;
reg   [7:0] weight_buf_V_16;
reg   [7:0] weight_buf_V_17;
reg   [7:0] weight_buf_V_18;
reg   [7:0] weight_buf_V_19;
reg   [7:0] weight_buf_V_20;
reg   [7:0] weight_buf_V_21;
reg   [7:0] weight_buf_V_22;
reg   [7:0] weight_buf_V_23;
reg   [7:0] weight_buf_V_24;
reg   [7:0] act_buf_V_0;
reg   [7:0] act_buf_V_1;
reg   [7:0] act_buf_V_2;
reg   [7:0] act_buf_V_3;
reg   [7:0] act_buf_V_4;
reg   [7:0] act_buf_V_5;
reg   [7:0] act_buf_V_6;
reg   [7:0] act_buf_V_7;
reg   [7:0] act_buf_V_8;
reg   [7:0] act_buf_V_9;
reg   [7:0] act_buf_V_10;
reg   [7:0] act_buf_V_11;
reg   [7:0] act_buf_V_12;
reg   [7:0] act_buf_V_13;
reg   [7:0] act_buf_V_14;
reg   [7:0] act_buf_V_15;
reg   [7:0] act_buf_V_16;
reg   [7:0] act_buf_V_17;
reg   [7:0] act_buf_V_18;
reg   [7:0] act_buf_V_19;
reg   [7:0] act_buf_V_20;
reg   [7:0] act_buf_V_21;
reg   [7:0] act_buf_V_22;
reg   [7:0] act_buf_V_23;
reg   [7:0] act_buf_V_24;
reg   [31:0] acc_reg_V;
reg   [6:0] w_ptr;
reg   [6:0] a_ptr;
reg  signed [18:0] p_0217_0_i_reg_277;
reg  signed [18:0] p_0111_0_i_reg_289;
reg  signed [18:0] p_0107_0_i_reg_301;
reg  signed [18:0] p_0103_0_i_reg_313;
reg   [3:0] i_0_i_reg_325;
reg  signed [18:0] p_0217_0_i265_reg_359;
reg  signed [18:0] p_0111_0_i266_reg_371;
reg  signed [18:0] p_0107_0_i267_reg_383;
reg  signed [18:0] p_0103_0_i268_reg_395;
reg   [3:0] i_0_i269_reg_407;
wire   [3:0] cnn_op_V_read_read_fu_252_p2;
reg   [7:0] weight_buf_V_0_load_reg_2032;
reg   [7:0] weight_buf_V_1_load_reg_2038;
reg   [7:0] weight_buf_V_2_load_reg_2044;
reg   [7:0] weight_buf_V_3_load_reg_2050;
reg   [7:0] weight_buf_V_4_load_reg_2056;
reg   [7:0] weight_buf_V_5_load_reg_2062;
reg   [7:0] weight_buf_V_6_load_reg_2068;
reg   [7:0] weight_buf_V_7_load_reg_2074;
reg   [7:0] weight_buf_V_8_load_reg_2080;
reg   [7:0] weight_buf_V_9_load_reg_2086;
reg   [7:0] weight_buf_V_10_load_reg_2092;
reg   [7:0] weight_buf_V_11_load_reg_2098;
reg   [7:0] weight_buf_V_12_load_reg_2104;
reg   [7:0] weight_buf_V_13_load_reg_2110;
reg   [7:0] weight_buf_V_14_load_reg_2116;
reg   [7:0] weight_buf_V_15_load_reg_2122;
reg   [7:0] weight_buf_V_16_load_reg_2128;
reg   [7:0] weight_buf_V_17_load_reg_2134;
reg   [7:0] weight_buf_V_18_load_reg_2140;
reg   [7:0] weight_buf_V_19_load_reg_2146;
reg   [7:0] weight_buf_V_20_load_reg_2152;
reg   [7:0] weight_buf_V_21_load_reg_2158;
reg   [7:0] weight_buf_V_22_load_reg_2164;
reg   [7:0] weight_buf_V_23_load_reg_2170;
reg   [7:0] weight_buf_V_24_load_reg_2176;
reg   [7:0] act_buf_V_0_load_reg_2182;
reg   [7:0] act_buf_V_1_load_reg_2188;
reg   [7:0] act_buf_V_2_load_reg_2194;
reg   [7:0] act_buf_V_3_load_reg_2200;
reg   [7:0] act_buf_V_4_load_reg_2206;
reg   [7:0] act_buf_V_5_load_reg_2212;
reg   [7:0] act_buf_V_6_load_reg_2218;
reg   [7:0] act_buf_V_7_load_reg_2224;
reg   [7:0] act_buf_V_8_load_reg_2230;
reg   [7:0] act_buf_V_9_load_reg_2236;
reg   [7:0] act_buf_V_10_load_reg_2242;
reg   [7:0] act_buf_V_11_load_reg_2248;
reg   [7:0] act_buf_V_12_load_reg_2254;
reg   [7:0] act_buf_V_13_load_reg_2260;
reg   [7:0] act_buf_V_14_load_reg_2266;
reg   [7:0] act_buf_V_15_load_reg_2272;
reg   [7:0] act_buf_V_16_load_reg_2278;
reg   [7:0] act_buf_V_17_load_reg_2284;
reg   [7:0] act_buf_V_18_load_reg_2290;
reg   [7:0] act_buf_V_19_load_reg_2296;
reg   [7:0] act_buf_V_20_load_reg_2302;
reg   [7:0] act_buf_V_21_load_reg_2308;
reg   [7:0] act_buf_V_22_load_reg_2314;
reg   [7:0] act_buf_V_23_load_reg_2320;
reg   [7:0] act_buf_V_24_load_reg_2326;
reg   [31:0] acc_reg_V_load_reg_2332;
wire   [63:0] product_V_1_fu_710_p2;
reg   [63:0] product_V_1_reg_2339;
wire   [31:0] add_ln68_fu_736_p2;
reg   [31:0] add_ln68_reg_2347;
wire   [31:0] select_ln899_3_fu_1337_p3;
reg   [31:0] select_ln899_3_reg_2359;
wire    ap_CS_fsm_state2;
wire   [0:0] icmp_ln899_fu_1350_p2;
reg   [0:0] icmp_ln899_reg_2364;
wire    ap_CS_fsm_state4;
wire   [63:0] product_V_fu_1361_p2;
reg   [63:0] product_V_reg_2370;
wire   [31:0] select_ln899_1_fu_1410_p3;
reg   [31:0] select_ln899_1_reg_2375;
wire    ap_CS_fsm_state5;
wire   [17:0] grp_mac_pack4_delta_fu_441_ap_return;
reg   [17:0] p_0_reg_2381;
wire    ap_CS_fsm_state7;
wire    grp_mac_pack4_delta_fu_441_ap_ready;
wire    grp_mac_pack4_delta_fu_441_ap_done;
wire   [0:0] icmp_ln168_1_fu_1442_p2;
reg   [0:0] icmp_ln168_1_reg_2386;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_block_state9_pp0_stage0_iter0;
wire    ap_block_state10_pp0_stage0_iter1;
wire    ap_block_pp0_stage0_11001;
wire   [3:0] i_1_fu_1448_p2;
reg    ap_enable_reg_pp0_iter0;
wire   [2:0] trunc_ln68_1_fu_1454_p1;
wire   [7:0] phi_ln68_3_fu_1466_p34;
reg  signed [7:0] phi_ln68_3_reg_2399;
wire   [7:0] phi_ln68_5_fu_1529_p10;
reg  signed [7:0] phi_ln68_5_reg_2404;
wire   [7:0] phi_ln68_7_fu_1545_p10;
reg  signed [7:0] phi_ln68_7_reg_2409;
wire   [7:0] phi_ln68_9_fu_1561_p10;
reg  signed [7:0] phi_ln68_9_reg_2414;
wire   [7:0] phi_ln68_11_fu_1577_p10;
reg  signed [7:0] phi_ln68_11_reg_2419;
wire   [7:0] phi_ln68_13_fu_1593_p10;
reg  signed [7:0] phi_ln68_13_reg_2424;
wire   [7:0] phi_ln68_14_fu_1609_p10;
reg  signed [7:0] phi_ln68_14_reg_2429;
wire  signed [18:0] grp_fu_1953_p3;
reg    ap_enable_reg_pp0_iter1;
wire  signed [18:0] grp_fu_1961_p3;
wire  signed [18:0] grp_fu_1969_p3;
wire  signed [18:0] grp_fu_1977_p3;
wire   [31:0] add_ln700_2_fu_1687_p2;
reg   [31:0] add_ln700_2_reg_2454;
wire    ap_CS_fsm_state11;
wire   [0:0] icmp_ln168_fu_1693_p2;
reg   [0:0] icmp_ln168_reg_2459;
wire    ap_CS_fsm_pp1_stage0;
wire    ap_block_state12_pp1_stage0_iter0;
wire    ap_block_state13_pp1_stage0_iter1;
wire    ap_block_pp1_stage0_11001;
wire   [3:0] i_fu_1699_p2;
reg    ap_enable_reg_pp1_iter0;
wire   [2:0] trunc_ln68_fu_1705_p1;
wire   [7:0] phi_ln68_2_fu_1717_p34;
reg  signed [7:0] phi_ln68_2_reg_2472;
wire   [7:0] phi_ln68_4_fu_1780_p10;
reg  signed [7:0] phi_ln68_4_reg_2477;
wire   [7:0] phi_ln68_6_fu_1796_p10;
reg  signed [7:0] phi_ln68_6_reg_2482;
wire   [7:0] phi_ln68_8_fu_1812_p10;
reg  signed [7:0] phi_ln68_8_reg_2487;
wire   [7:0] phi_ln68_s_fu_1828_p10;
reg  signed [7:0] phi_ln68_s_reg_2492;
wire   [7:0] phi_ln68_10_fu_1844_p10;
reg  signed [7:0] phi_ln68_10_reg_2497;
wire   [7:0] phi_ln68_12_fu_1860_p10;
reg  signed [7:0] phi_ln68_12_reg_2502;
wire  signed [18:0] grp_fu_1985_p3;
reg    ap_enable_reg_pp1_iter1;
wire  signed [18:0] grp_fu_1993_p3;
wire  signed [18:0] grp_fu_2001_p3;
wire  signed [18:0] grp_fu_2009_p3;
wire    ap_block_pp0_stage0_subdone;
reg    ap_condition_pp0_exit_iter0_state9;
wire    ap_block_pp1_stage0_subdone;
reg    ap_condition_pp1_exit_iter0_state12;
wire    grp_mac_pack4_delta_fu_441_ap_start;
wire    grp_mac_pack4_delta_fu_441_ap_idle;
wire    ap_block_pp0_stage0;
wire   [7:0] ap_phi_reg_pp0_iter0_phi_ln68_1_reg_336;
reg  signed [7:0] ap_phi_reg_pp0_iter1_phi_ln68_1_reg_336;
wire    ap_block_pp1_stage0;
wire   [7:0] ap_phi_reg_pp1_iter0_phi_ln68_reg_418;
reg  signed [7:0] ap_phi_reg_pp1_iter1_phi_ln68_reg_418;
reg    grp_mac_pack4_delta_fu_441_ap_start_reg;
wire   [7:0] trunc_ln647_fu_1253_p1;
wire   [6:0] w_ptr_load_load_fu_1069_p1;
wire   [7:0] grp_fu_455_p4;
wire   [7:0] grp_fu_465_p4;
wire   [7:0] grp_fu_475_p4;
wire   [7:0] trunc_ln647_2_fu_1219_p1;
wire   [7:0] trunc_ln647_3_fu_1185_p1;
wire   [7:0] trunc_ln647_4_fu_1151_p1;
wire   [7:0] trunc_ln647_5_fu_1117_p1;
wire   [7:0] trunc_ln647_6_fu_1083_p1;
wire   [7:0] trunc_ln647_7_fu_1073_p1;
wire   [7:0] trunc_ln647_8_fu_1035_p1;
wire   [6:0] a_ptr_load_load_fu_851_p1;
wire   [7:0] trunc_ln647_9_fu_1001_p1;
wire   [7:0] trunc_ln647_10_fu_967_p1;
wire   [7:0] trunc_ln647_11_fu_933_p1;
wire   [7:0] trunc_ln647_12_fu_899_p1;
wire   [7:0] trunc_ln647_13_fu_865_p1;
wire   [7:0] trunc_ln647_14_fu_855_p1;
wire   [0:0] tmp_3_fu_716_p3;
wire   [31:0] add_ln700_1_fu_724_p2;
wire  signed [31:0] sext_ln68_11_fu_788_p1;
wire  signed [31:0] sext_ln68_fu_841_p1;
wire    ap_CS_fsm_state3;
wire    ap_CS_fsm_state6;
wire   [31:0] add_ln700_fu_1431_p2;
wire    ap_CS_fsm_state8;
wire  signed [31:0] sext_ln68_16_fu_1943_p1;
wire    ap_CS_fsm_state14;
reg   [31:0] rd_data_V_preg;
wire  signed [31:0] grp_fu_455_p1;
wire  signed [31:0] grp_fu_465_p1;
wire  signed [31:0] grp_fu_475_p1;
wire  signed [31:0] sext_ln68_13_fu_706_p0;
wire   [31:0] product_V_1_fu_710_p0;
wire  signed [31:0] product_V_1_fu_710_p1;
wire  signed [31:0] add_ln700_1_fu_724_p1;
wire  signed [31:0] add_ln68_fu_736_p0;
wire  signed [31:0] a0_V_fu_742_p0;
wire   [7:0] a0_V_fu_742_p1;
wire   [0:0] icmp_ln895_3_fu_746_p2;
wire   [0:0] icmp_ln895_4_fu_760_p2;
wire   [7:0] max1_V_1_fu_752_p3;
wire   [7:0] max2_V_1_fu_766_p3;
wire   [0:0] icmp_ln895_5_fu_774_p2;
wire   [7:0] select_ln68_fu_780_p3;
wire   [0:0] icmp_ln895_fu_799_p2;
wire   [0:0] icmp_ln895_1_fu_813_p2;
wire   [7:0] max1_V_fu_805_p3;
wire   [7:0] max2_V_fu_819_p3;
wire   [0:0] icmp_ln895_2_fu_827_p2;
wire   [7:0] final_max_V_fu_833_p3;
wire  signed [31:0] trunc_ln647_14_fu_855_p0;
wire  signed [31:0] trunc_ln647_13_fu_865_p0;
wire  signed [31:0] trunc_ln647_12_fu_899_p0;
wire  signed [31:0] trunc_ln647_11_fu_933_p0;
wire  signed [31:0] trunc_ln647_10_fu_967_p0;
wire  signed [31:0] trunc_ln647_9_fu_1001_p0;
wire  signed [31:0] trunc_ln647_8_fu_1035_p0;
wire  signed [31:0] trunc_ln647_7_fu_1073_p0;
wire  signed [31:0] trunc_ln647_6_fu_1083_p0;
wire  signed [31:0] trunc_ln647_5_fu_1117_p0;
wire  signed [31:0] trunc_ln647_4_fu_1151_p0;
wire  signed [31:0] trunc_ln647_3_fu_1185_p0;
wire  signed [31:0] trunc_ln647_2_fu_1219_p0;
wire  signed [31:0] trunc_ln647_fu_1253_p0;
wire   [63:0] rounded_V_1_fu_1292_p2;
wire   [24:0] tmp_4_fu_1307_p4;
wire   [0:0] icmp_ln899_1_fu_1287_p2;
wire   [0:0] icmp_ln895_7_fu_1317_p2;
wire   [0:0] or_ln899_1_fu_1331_p2;
wire   [31:0] select_ln899_2_fu_1323_p3;
wire   [31:0] scaled_V_1_fu_1297_p4;
wire  signed [31:0] sext_ln68_12_fu_1358_p0;
wire   [31:0] product_V_fu_1361_p0;
wire  signed [31:0] product_V_fu_1361_p1;
wire   [63:0] rounded_V_fu_1367_p2;
wire   [24:0] tmp_2_fu_1382_p4;
wire   [0:0] icmp_ln895_6_fu_1392_p2;
wire   [0:0] or_ln899_fu_1405_p2;
wire   [31:0] select_ln899_fu_1398_p3;
wire   [31:0] scaled_V_fu_1372_p4;
wire  signed [31:0] sext_ln700_fu_1428_p1;
wire   [4:0] phi_ln68_3_fu_1466_p33;
wire  signed [31:0] sext_ln168_6_fu_1658_p1;
wire  signed [19:0] sext_ln168_5_fu_1654_p1;
wire  signed [19:0] sext_ln168_4_fu_1650_p1;
wire   [19:0] add_ln700_4_fu_1671_p2;
wire  signed [19:0] sext_ln168_7_fu_1662_p1;
wire   [19:0] add_ln700_5_fu_1677_p2;
wire  signed [31:0] sext_ln700_1_fu_1683_p1;
wire   [31:0] add_ln700_3_fu_1666_p2;
wire   [4:0] phi_ln68_2_fu_1717_p33;
wire  signed [19:0] sext_ln168_2_fu_1909_p1;
wire  signed [19:0] sext_ln168_3_fu_1913_p1;
wire   [19:0] add_ln68_3_fu_1917_p2;
wire  signed [19:0] sext_ln168_1_fu_1905_p1;
wire  signed [19:0] sext_ln168_fu_1901_p1;
wire   [19:0] add_ln68_5_fu_1927_p2;
wire  signed [20:0] sext_ln68_15_fu_1933_p1;
wire  signed [20:0] sext_ln68_14_fu_1923_p1;
wire   [20:0] add_ln68_4_fu_1937_p2;
reg   [13:0] ap_NS_fsm;
reg    ap_idle_pp0;
wire    ap_enable_pp0;
reg    ap_idle_pp1;
wire    ap_enable_pp1;
wire   [63:0] product_V_1_fu_710_p00;
wire   [63:0] product_V_fu_1361_p00;
reg    ap_condition_291;
reg    ap_condition_350;

// power-on initialization
initial begin
#0 ap_CS_fsm = 14'd1;
#0 weight_buf_V_0 = 8'd0;
#0 weight_buf_V_1 = 8'd0;
#0 weight_buf_V_2 = 8'd0;
#0 weight_buf_V_3 = 8'd0;
#0 weight_buf_V_4 = 8'd0;
#0 weight_buf_V_5 = 8'd0;
#0 weight_buf_V_6 = 8'd0;
#0 weight_buf_V_7 = 8'd0;
#0 weight_buf_V_8 = 8'd0;
#0 weight_buf_V_9 = 8'd0;
#0 weight_buf_V_10 = 8'd0;
#0 weight_buf_V_11 = 8'd0;
#0 weight_buf_V_12 = 8'd0;
#0 weight_buf_V_13 = 8'd0;
#0 weight_buf_V_14 = 8'd0;
#0 weight_buf_V_15 = 8'd0;
#0 weight_buf_V_16 = 8'd0;
#0 weight_buf_V_17 = 8'd0;
#0 weight_buf_V_18 = 8'd0;
#0 weight_buf_V_19 = 8'd0;
#0 weight_buf_V_20 = 8'd0;
#0 weight_buf_V_21 = 8'd0;
#0 weight_buf_V_22 = 8'd0;
#0 weight_buf_V_23 = 8'd0;
#0 weight_buf_V_24 = 8'd0;
#0 act_buf_V_0 = 8'd0;
#0 act_buf_V_1 = 8'd0;
#0 act_buf_V_2 = 8'd0;
#0 act_buf_V_3 = 8'd0;
#0 act_buf_V_4 = 8'd0;
#0 act_buf_V_5 = 8'd0;
#0 act_buf_V_6 = 8'd0;
#0 act_buf_V_7 = 8'd0;
#0 act_buf_V_8 = 8'd0;
#0 act_buf_V_9 = 8'd0;
#0 act_buf_V_10 = 8'd0;
#0 act_buf_V_11 = 8'd0;
#0 act_buf_V_12 = 8'd0;
#0 act_buf_V_13 = 8'd0;
#0 act_buf_V_14 = 8'd0;
#0 act_buf_V_15 = 8'd0;
#0 act_buf_V_16 = 8'd0;
#0 act_buf_V_17 = 8'd0;
#0 act_buf_V_18 = 8'd0;
#0 act_buf_V_19 = 8'd0;
#0 act_buf_V_20 = 8'd0;
#0 act_buf_V_21 = 8'd0;
#0 act_buf_V_22 = 8'd0;
#0 act_buf_V_23 = 8'd0;
#0 act_buf_V_24 = 8'd0;
#0 acc_reg_V = 32'd0;
#0 w_ptr = 7'd0;
#0 a_ptr = 7'd0;
#0 ap_enable_reg_pp0_iter0 = 1'b0;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp1_iter0 = 1'b0;
#0 ap_enable_reg_pp1_iter1 = 1'b0;
#0 grp_mac_pack4_delta_fu_441_ap_start_reg = 1'b0;
#0 rd_data_V_preg = 32'd0;
end

mac_pack4_delta grp_mac_pack4_delta_fu_441(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_mac_pack4_delta_fu_441_ap_start),
    .ap_done(grp_mac_pack4_delta_fu_441_ap_done),
    .ap_idle(grp_mac_pack4_delta_fu_441_ap_idle),
    .ap_ready(grp_mac_pack4_delta_fu_441_ap_ready),
    .act_pack_V(rs1_data_V),
    .weight_pack_V(rs2_data_V),
    .ap_return(grp_mac_pack4_delta_fu_441_ap_return)
);

CNN_ALU_Top_mux_3bkb #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 8 ),
    .din4_WIDTH( 8 ),
    .din5_WIDTH( 8 ),
    .din6_WIDTH( 8 ),
    .din7_WIDTH( 8 ),
    .din8_WIDTH( 8 ),
    .din9_WIDTH( 8 ),
    .din10_WIDTH( 8 ),
    .din11_WIDTH( 8 ),
    .din12_WIDTH( 8 ),
    .din13_WIDTH( 8 ),
    .din14_WIDTH( 8 ),
    .din15_WIDTH( 8 ),
    .din16_WIDTH( 8 ),
    .din17_WIDTH( 8 ),
    .din18_WIDTH( 8 ),
    .din19_WIDTH( 8 ),
    .din20_WIDTH( 8 ),
    .din21_WIDTH( 8 ),
    .din22_WIDTH( 8 ),
    .din23_WIDTH( 8 ),
    .din24_WIDTH( 8 ),
    .din25_WIDTH( 8 ),
    .din26_WIDTH( 8 ),
    .din27_WIDTH( 8 ),
    .din28_WIDTH( 8 ),
    .din29_WIDTH( 8 ),
    .din30_WIDTH( 8 ),
    .din31_WIDTH( 8 ),
    .din32_WIDTH( 5 ),
    .dout_WIDTH( 8 ))
CNN_ALU_Top_mux_3bkb_U3(
    .din0(weight_buf_V_0_load_reg_2032),
    .din1(8'd0),
    .din2(8'd0),
    .din3(8'd0),
    .din4(weight_buf_V_4_load_reg_2056),
    .din5(8'd0),
    .din6(8'd0),
    .din7(8'd0),
    .din8(weight_buf_V_8_load_reg_2080),
    .din9(8'd0),
    .din10(8'd0),
    .din11(8'd0),
    .din12(weight_buf_V_12_load_reg_2104),
    .din13(8'd0),
    .din14(8'd0),
    .din15(8'd0),
    .din16(weight_buf_V_16_load_reg_2128),
    .din17(8'd0),
    .din18(8'd0),
    .din19(8'd0),
    .din20(weight_buf_V_20_load_reg_2152),
    .din21(8'd0),
    .din22(8'd0),
    .din23(8'd0),
    .din24(weight_buf_V_24_load_reg_2176),
    .din25(8'd0),
    .din26(8'd0),
    .din27(8'd0),
    .din28(8'd0),
    .din29(8'd0),
    .din30(8'd0),
    .din31(8'd0),
    .din32(phi_ln68_3_fu_1466_p33),
    .dout(phi_ln68_3_fu_1466_p34)
);

CNN_ALU_Top_mux_8cud #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 8 ),
    .din4_WIDTH( 8 ),
    .din5_WIDTH( 8 ),
    .din6_WIDTH( 8 ),
    .din7_WIDTH( 8 ),
    .din8_WIDTH( 3 ),
    .dout_WIDTH( 8 ))
CNN_ALU_Top_mux_8cud_U4(
    .din0(act_buf_V_1_load_reg_2188),
    .din1(act_buf_V_5_load_reg_2212),
    .din2(act_buf_V_9_load_reg_2236),
    .din3(act_buf_V_13_load_reg_2260),
    .din4(act_buf_V_17_load_reg_2284),
    .din5(act_buf_V_21_load_reg_2308),
    .din6(8'd0),
    .din7(8'd0),
    .din8(trunc_ln68_1_fu_1454_p1),
    .dout(phi_ln68_5_fu_1529_p10)
);

CNN_ALU_Top_mux_8cud #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 8 ),
    .din4_WIDTH( 8 ),
    .din5_WIDTH( 8 ),
    .din6_WIDTH( 8 ),
    .din7_WIDTH( 8 ),
    .din8_WIDTH( 3 ),
    .dout_WIDTH( 8 ))
CNN_ALU_Top_mux_8cud_U5(
    .din0(weight_buf_V_1_load_reg_2038),
    .din1(weight_buf_V_5_load_reg_2062),
    .din2(weight_buf_V_9_load_reg_2086),
    .din3(weight_buf_V_13_load_reg_2110),
    .din4(weight_buf_V_17_load_reg_2134),
    .din5(weight_buf_V_21_load_reg_2158),
    .din6(8'd0),
    .din7(8'd0),
    .din8(trunc_ln68_1_fu_1454_p1),
    .dout(phi_ln68_7_fu_1545_p10)
);

CNN_ALU_Top_mux_8cud #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 8 ),
    .din4_WIDTH( 8 ),
    .din5_WIDTH( 8 ),
    .din6_WIDTH( 8 ),
    .din7_WIDTH( 8 ),
    .din8_WIDTH( 3 ),
    .dout_WIDTH( 8 ))
CNN_ALU_Top_mux_8cud_U6(
    .din0(act_buf_V_2_load_reg_2194),
    .din1(act_buf_V_6_load_reg_2218),
    .din2(act_buf_V_10_load_reg_2242),
    .din3(act_buf_V_14_load_reg_2266),
    .din4(act_buf_V_18_load_reg_2290),
    .din5(act_buf_V_22_load_reg_2314),
    .din6(8'd0),
    .din7(8'd0),
    .din8(trunc_ln68_1_fu_1454_p1),
    .dout(phi_ln68_9_fu_1561_p10)
);

CNN_ALU_Top_mux_8cud #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 8 ),
    .din4_WIDTH( 8 ),
    .din5_WIDTH( 8 ),
    .din6_WIDTH( 8 ),
    .din7_WIDTH( 8 ),
    .din8_WIDTH( 3 ),
    .dout_WIDTH( 8 ))
CNN_ALU_Top_mux_8cud_U7(
    .din0(weight_buf_V_2_load_reg_2044),
    .din1(weight_buf_V_6_load_reg_2068),
    .din2(weight_buf_V_10_load_reg_2092),
    .din3(weight_buf_V_14_load_reg_2116),
    .din4(weight_buf_V_18_load_reg_2140),
    .din5(weight_buf_V_22_load_reg_2164),
    .din6(8'd0),
    .din7(8'd0),
    .din8(trunc_ln68_1_fu_1454_p1),
    .dout(phi_ln68_11_fu_1577_p10)
);

CNN_ALU_Top_mux_8cud #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 8 ),
    .din4_WIDTH( 8 ),
    .din5_WIDTH( 8 ),
    .din6_WIDTH( 8 ),
    .din7_WIDTH( 8 ),
    .din8_WIDTH( 3 ),
    .dout_WIDTH( 8 ))
CNN_ALU_Top_mux_8cud_U8(
    .din0(act_buf_V_3_load_reg_2200),
    .din1(act_buf_V_7_load_reg_2224),
    .din2(act_buf_V_11_load_reg_2248),
    .din3(act_buf_V_15_load_reg_2272),
    .din4(act_buf_V_19_load_reg_2296),
    .din5(act_buf_V_23_load_reg_2320),
    .din6(8'd0),
    .din7(8'd0),
    .din8(trunc_ln68_1_fu_1454_p1),
    .dout(phi_ln68_13_fu_1593_p10)
);

CNN_ALU_Top_mux_8cud #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 8 ),
    .din4_WIDTH( 8 ),
    .din5_WIDTH( 8 ),
    .din6_WIDTH( 8 ),
    .din7_WIDTH( 8 ),
    .din8_WIDTH( 3 ),
    .dout_WIDTH( 8 ))
CNN_ALU_Top_mux_8cud_U9(
    .din0(weight_buf_V_3_load_reg_2050),
    .din1(weight_buf_V_7_load_reg_2074),
    .din2(weight_buf_V_11_load_reg_2098),
    .din3(weight_buf_V_15_load_reg_2122),
    .din4(weight_buf_V_19_load_reg_2146),
    .din5(weight_buf_V_23_load_reg_2170),
    .din6(8'd0),
    .din7(8'd0),
    .din8(trunc_ln68_1_fu_1454_p1),
    .dout(phi_ln68_14_fu_1609_p10)
);

CNN_ALU_Top_mux_3bkb #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 8 ),
    .din4_WIDTH( 8 ),
    .din5_WIDTH( 8 ),
    .din6_WIDTH( 8 ),
    .din7_WIDTH( 8 ),
    .din8_WIDTH( 8 ),
    .din9_WIDTH( 8 ),
    .din10_WIDTH( 8 ),
    .din11_WIDTH( 8 ),
    .din12_WIDTH( 8 ),
    .din13_WIDTH( 8 ),
    .din14_WIDTH( 8 ),
    .din15_WIDTH( 8 ),
    .din16_WIDTH( 8 ),
    .din17_WIDTH( 8 ),
    .din18_WIDTH( 8 ),
    .din19_WIDTH( 8 ),
    .din20_WIDTH( 8 ),
    .din21_WIDTH( 8 ),
    .din22_WIDTH( 8 ),
    .din23_WIDTH( 8 ),
    .din24_WIDTH( 8 ),
    .din25_WIDTH( 8 ),
    .din26_WIDTH( 8 ),
    .din27_WIDTH( 8 ),
    .din28_WIDTH( 8 ),
    .din29_WIDTH( 8 ),
    .din30_WIDTH( 8 ),
    .din31_WIDTH( 8 ),
    .din32_WIDTH( 5 ),
    .dout_WIDTH( 8 ))
CNN_ALU_Top_mux_3bkb_U10(
    .din0(weight_buf_V_0_load_reg_2032),
    .din1(8'd0),
    .din2(8'd0),
    .din3(8'd0),
    .din4(weight_buf_V_4_load_reg_2056),
    .din5(8'd0),
    .din6(8'd0),
    .din7(8'd0),
    .din8(weight_buf_V_8_load_reg_2080),
    .din9(8'd0),
    .din10(8'd0),
    .din11(8'd0),
    .din12(weight_buf_V_12_load_reg_2104),
    .din13(8'd0),
    .din14(8'd0),
    .din15(8'd0),
    .din16(weight_buf_V_16_load_reg_2128),
    .din17(8'd0),
    .din18(8'd0),
    .din19(8'd0),
    .din20(weight_buf_V_20_load_reg_2152),
    .din21(8'd0),
    .din22(8'd0),
    .din23(8'd0),
    .din24(weight_buf_V_24_load_reg_2176),
    .din25(8'd0),
    .din26(8'd0),
    .din27(8'd0),
    .din28(8'd0),
    .din29(8'd0),
    .din30(8'd0),
    .din31(8'd0),
    .din32(phi_ln68_2_fu_1717_p33),
    .dout(phi_ln68_2_fu_1717_p34)
);

CNN_ALU_Top_mux_8cud #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 8 ),
    .din4_WIDTH( 8 ),
    .din5_WIDTH( 8 ),
    .din6_WIDTH( 8 ),
    .din7_WIDTH( 8 ),
    .din8_WIDTH( 3 ),
    .dout_WIDTH( 8 ))
CNN_ALU_Top_mux_8cud_U11(
    .din0(act_buf_V_1_load_reg_2188),
    .din1(act_buf_V_5_load_reg_2212),
    .din2(act_buf_V_9_load_reg_2236),
    .din3(act_buf_V_13_load_reg_2260),
    .din4(act_buf_V_17_load_reg_2284),
    .din5(act_buf_V_21_load_reg_2308),
    .din6(8'd0),
    .din7(8'd0),
    .din8(trunc_ln68_fu_1705_p1),
    .dout(phi_ln68_4_fu_1780_p10)
);

CNN_ALU_Top_mux_8cud #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 8 ),
    .din4_WIDTH( 8 ),
    .din5_WIDTH( 8 ),
    .din6_WIDTH( 8 ),
    .din7_WIDTH( 8 ),
    .din8_WIDTH( 3 ),
    .dout_WIDTH( 8 ))
CNN_ALU_Top_mux_8cud_U12(
    .din0(weight_buf_V_1_load_reg_2038),
    .din1(weight_buf_V_5_load_reg_2062),
    .din2(weight_buf_V_9_load_reg_2086),
    .din3(weight_buf_V_13_load_reg_2110),
    .din4(weight_buf_V_17_load_reg_2134),
    .din5(weight_buf_V_21_load_reg_2158),
    .din6(8'd0),
    .din7(8'd0),
    .din8(trunc_ln68_fu_1705_p1),
    .dout(phi_ln68_6_fu_1796_p10)
);

CNN_ALU_Top_mux_8cud #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 8 ),
    .din4_WIDTH( 8 ),
    .din5_WIDTH( 8 ),
    .din6_WIDTH( 8 ),
    .din7_WIDTH( 8 ),
    .din8_WIDTH( 3 ),
    .dout_WIDTH( 8 ))
CNN_ALU_Top_mux_8cud_U13(
    .din0(act_buf_V_2_load_reg_2194),
    .din1(act_buf_V_6_load_reg_2218),
    .din2(act_buf_V_10_load_reg_2242),
    .din3(act_buf_V_14_load_reg_2266),
    .din4(act_buf_V_18_load_reg_2290),
    .din5(act_buf_V_22_load_reg_2314),
    .din6(8'd0),
    .din7(8'd0),
    .din8(trunc_ln68_fu_1705_p1),
    .dout(phi_ln68_8_fu_1812_p10)
);

CNN_ALU_Top_mux_8cud #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 8 ),
    .din4_WIDTH( 8 ),
    .din5_WIDTH( 8 ),
    .din6_WIDTH( 8 ),
    .din7_WIDTH( 8 ),
    .din8_WIDTH( 3 ),
    .dout_WIDTH( 8 ))
CNN_ALU_Top_mux_8cud_U14(
    .din0(weight_buf_V_2_load_reg_2044),
    .din1(weight_buf_V_6_load_reg_2068),
    .din2(weight_buf_V_10_load_reg_2092),
    .din3(weight_buf_V_14_load_reg_2116),
    .din4(weight_buf_V_18_load_reg_2140),
    .din5(weight_buf_V_22_load_reg_2164),
    .din6(8'd0),
    .din7(8'd0),
    .din8(trunc_ln68_fu_1705_p1),
    .dout(phi_ln68_s_fu_1828_p10)
);

CNN_ALU_Top_mux_8cud #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 8 ),
    .din4_WIDTH( 8 ),
    .din5_WIDTH( 8 ),
    .din6_WIDTH( 8 ),
    .din7_WIDTH( 8 ),
    .din8_WIDTH( 3 ),
    .dout_WIDTH( 8 ))
CNN_ALU_Top_mux_8cud_U15(
    .din0(act_buf_V_3_load_reg_2200),
    .din1(act_buf_V_7_load_reg_2224),
    .din2(act_buf_V_11_load_reg_2248),
    .din3(act_buf_V_15_load_reg_2272),
    .din4(act_buf_V_19_load_reg_2296),
    .din5(act_buf_V_23_load_reg_2320),
    .din6(8'd0),
    .din7(8'd0),
    .din8(trunc_ln68_fu_1705_p1),
    .dout(phi_ln68_10_fu_1844_p10)
);

CNN_ALU_Top_mux_8cud #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 8 ),
    .din4_WIDTH( 8 ),
    .din5_WIDTH( 8 ),
    .din6_WIDTH( 8 ),
    .din7_WIDTH( 8 ),
    .din8_WIDTH( 3 ),
    .dout_WIDTH( 8 ))
CNN_ALU_Top_mux_8cud_U16(
    .din0(weight_buf_V_3_load_reg_2050),
    .din1(weight_buf_V_7_load_reg_2074),
    .din2(weight_buf_V_11_load_reg_2098),
    .din3(weight_buf_V_15_load_reg_2122),
    .din4(weight_buf_V_19_load_reg_2146),
    .din5(weight_buf_V_23_load_reg_2170),
    .din6(8'd0),
    .din7(8'd0),
    .din8(trunc_ln68_fu_1705_p1),
    .dout(phi_ln68_12_fu_1860_p10)
);

CNN_ALU_Top_mac_mdEe #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 19 ),
    .dout_WIDTH( 19 ))
CNN_ALU_Top_mac_mdEe_U17(
    .din0(ap_phi_reg_pp0_iter1_phi_ln68_1_reg_336),
    .din1(phi_ln68_3_reg_2399),
    .din2(p_0217_0_i_reg_277),
    .dout(grp_fu_1953_p3)
);

CNN_ALU_Top_mac_mdEe #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 19 ),
    .dout_WIDTH( 19 ))
CNN_ALU_Top_mac_mdEe_U18(
    .din0(phi_ln68_5_reg_2404),
    .din1(phi_ln68_7_reg_2409),
    .din2(p_0111_0_i_reg_289),
    .dout(grp_fu_1961_p3)
);

CNN_ALU_Top_mac_mdEe #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 19 ),
    .dout_WIDTH( 19 ))
CNN_ALU_Top_mac_mdEe_U19(
    .din0(phi_ln68_9_reg_2414),
    .din1(phi_ln68_11_reg_2419),
    .din2(p_0107_0_i_reg_301),
    .dout(grp_fu_1969_p3)
);

CNN_ALU_Top_mac_mdEe #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 19 ),
    .dout_WIDTH( 19 ))
CNN_ALU_Top_mac_mdEe_U20(
    .din0(phi_ln68_14_reg_2429),
    .din1(phi_ln68_13_reg_2424),
    .din2(p_0103_0_i_reg_313),
    .dout(grp_fu_1977_p3)
);

CNN_ALU_Top_mac_mdEe #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 19 ),
    .dout_WIDTH( 19 ))
CNN_ALU_Top_mac_mdEe_U21(
    .din0(ap_phi_reg_pp1_iter1_phi_ln68_reg_418),
    .din1(phi_ln68_2_reg_2472),
    .din2(p_0217_0_i265_reg_359),
    .dout(grp_fu_1985_p3)
);

CNN_ALU_Top_mac_mdEe #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 19 ),
    .dout_WIDTH( 19 ))
CNN_ALU_Top_mac_mdEe_U22(
    .din0(phi_ln68_4_reg_2477),
    .din1(phi_ln68_6_reg_2482),
    .din2(p_0111_0_i266_reg_371),
    .dout(grp_fu_1993_p3)
);

CNN_ALU_Top_mac_mdEe #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 19 ),
    .dout_WIDTH( 19 ))
CNN_ALU_Top_mac_mdEe_U23(
    .din0(phi_ln68_8_reg_2487),
    .din1(phi_ln68_s_reg_2492),
    .din2(p_0107_0_i267_reg_383),
    .dout(grp_fu_2001_p3)
);

CNN_ALU_Top_mac_mdEe #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 19 ),
    .dout_WIDTH( 19 ))
CNN_ALU_Top_mac_mdEe_U24(
    .din0(phi_ln68_12_reg_2502),
    .din1(phi_ln68_10_reg_2497),
    .din2(p_0103_0_i268_reg_395),
    .dout(grp_fu_2009_p3)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_condition_pp0_exit_iter0_state9) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter0 <= 1'b0;
        end else if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1) & (cnn_op_V_read_read_fu_252_p2 == 4'd6))) begin
            ap_enable_reg_pp0_iter0 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_condition_pp0_exit_iter0_state9))) begin
            ap_enable_reg_pp0_iter1 <= (1'b1 ^ ap_condition_pp0_exit_iter0_state9);
        end else if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
        end else if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1) & (cnn_op_V_read_read_fu_252_p2 == 4'd6))) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp1_iter0 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp1_stage0_subdone) & (1'b1 == ap_condition_pp1_exit_iter0_state12) & (1'b1 == ap_CS_fsm_pp1_stage0))) begin
            ap_enable_reg_pp1_iter0 <= 1'b0;
        end else if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1) & (cnn_op_V_read_read_fu_252_p2 == 4'd2))) begin
            ap_enable_reg_pp1_iter0 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp1_iter1 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp1_stage0_subdone) & (1'b1 == ap_condition_pp1_exit_iter0_state12))) begin
            ap_enable_reg_pp1_iter1 <= (1'b1 ^ ap_condition_pp1_exit_iter0_state12);
        end else if ((1'b0 == ap_block_pp1_stage0_subdone)) begin
            ap_enable_reg_pp1_iter1 <= ap_enable_reg_pp1_iter0;
        end else if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1) & (cnn_op_V_read_read_fu_252_p2 == 4'd2))) begin
            ap_enable_reg_pp1_iter1 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_mac_pack4_delta_fu_441_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1) & (cnn_op_V_read_read_fu_252_p2 == 4'd10))) begin
            grp_mac_pack4_delta_fu_441_ap_start_reg <= 1'b1;
        end else if ((grp_mac_pack4_delta_fu_441_ap_ready == 1'b1)) begin
            grp_mac_pack4_delta_fu_441_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        rd_data_V_preg <= 32'd0;
    end else begin
        if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
            if ((cnn_op_V_read_read_fu_252_p2 == 4'd3)) begin
                rd_data_V_preg <= acc_reg_V;
            end else if ((cnn_op_V_read_read_fu_252_p2 == 4'd11)) begin
                rd_data_V_preg <= sext_ln68_11_fu_788_p1;
            end
        end
    end
end

always @ (posedge ap_clk) begin
    if (((7'd0 == a_ptr_load_load_fu_851_p1) & (1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1) & (cnn_op_V_read_read_fu_252_p2 == 4'd1))) begin
                a_ptr[2] <= 1'b1;
        a_ptr[3] <= 1'b0;
        a_ptr[4] <= 1'b0;
    end else if (((7'd4 == a_ptr_load_load_fu_851_p1) & (1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1) & (cnn_op_V_read_read_fu_252_p2 == 4'd1))) begin
                a_ptr[2] <= 1'b0;
        a_ptr[3] <= 1'b1;
        a_ptr[4] <= 1'b0;
    end else if (((7'd8 == a_ptr_load_load_fu_851_p1) & (1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1) & (cnn_op_V_read_read_fu_252_p2 == 4'd1))) begin
                a_ptr[2] <= 1'b1;
        a_ptr[3] <= 1'b1;
        a_ptr[4] <= 1'b0;
    end else if (((7'd12 == a_ptr_load_load_fu_851_p1) & (1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1) & (cnn_op_V_read_read_fu_252_p2 == 4'd1))) begin
                a_ptr[2] <= 1'b0;
        a_ptr[3] <= 1'b0;
        a_ptr[4] <= 1'b1;
    end else if (((7'd16 == a_ptr_load_load_fu_851_p1) & (1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1) & (cnn_op_V_read_read_fu_252_p2 == 4'd1))) begin
                a_ptr[2] <= 1'b1;
        a_ptr[3] <= 1'b0;
        a_ptr[4] <= 1'b1;
    end else if (((7'd20 == a_ptr_load_load_fu_851_p1) & (1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1) & (cnn_op_V_read_read_fu_252_p2 == 4'd1))) begin
                a_ptr[2] <= 1'b0;
        a_ptr[3] <= 1'b1;
        a_ptr[4] <= 1'b1;
    end else if ((((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1) & (cnn_op_V_read_read_fu_252_p2 == 4'd5)) | (~(7'd24 == a_ptr_load_load_fu_851_p1) & ~(7'd20 == a_ptr_load_load_fu_851_p1) & ~(7'd16 == a_ptr_load_load_fu_851_p1) & ~(7'd12 == a_ptr_load_load_fu_851_p1) & ~(7'd8 == a_ptr_load_load_fu_851_p1) & ~(7'd4 == a_ptr_load_load_fu_851_p1) & ~(7'd0 == a_ptr_load_load_fu_851_p1) & (1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1) & (cnn_op_V_read_read_fu_252_p2 == 4'd1)) | ((7'd24 == a_ptr_load_load_fu_851_p1) & (1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1) & (cnn_op_V_read_read_fu_252_p2 == 4'd1)))) begin
                a_ptr[2] <= 1'b0;
        a_ptr[3] <= 1'b0;
        a_ptr[4] <= 1'b0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state14)) begin
        acc_reg_V <= sext_ln68_16_fu_1943_p1;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        acc_reg_V <= add_ln700_fu_1431_p2;
    end else if (((1'b1 == ap_CS_fsm_state6) & (cnn_op_V_read_read_fu_252_p2 == 4'd6))) begin
        acc_reg_V <= add_ln700_2_reg_2454;
    end else if (((1'b1 == ap_CS_fsm_state6) & (cnn_op_V_read_read_fu_252_p2 == 4'd12))) begin
        acc_reg_V <= select_ln899_1_reg_2375;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        acc_reg_V <= select_ln899_3_reg_2359;
    end else if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1) & (cnn_op_V_read_read_fu_252_p2 == 4'd4))) begin
        acc_reg_V <= sext_ln68_fu_841_p1;
    end else if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1) & (cnn_op_V_read_read_fu_252_p2 == 4'd11))) begin
        acc_reg_V <= sext_ln68_11_fu_788_p1;
    end else if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1) & (cnn_op_V_read_read_fu_252_p2 == 4'd8))) begin
        acc_reg_V <= add_ln700_1_fu_724_p2;
    end else if ((((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1) & (cnn_op_V_read_read_fu_252_p2 == 4'd5)) | ((tmp_3_fu_716_p3 == 1'd1) & (1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1) & (cnn_op_V_read_read_fu_252_p2 == 4'd7)))) begin
        acc_reg_V <= 32'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_291)) begin
        if (((trunc_ln68_1_fu_1454_p1 == 3'd6) & (icmp_ln168_1_fu_1442_p2 == 1'd0))) begin
            ap_phi_reg_pp0_iter1_phi_ln68_1_reg_336 <= act_buf_V_24_load_reg_2326;
        end else if (((trunc_ln68_1_fu_1454_p1 == 3'd5) & (icmp_ln168_1_fu_1442_p2 == 1'd0))) begin
            ap_phi_reg_pp0_iter1_phi_ln68_1_reg_336 <= act_buf_V_20_load_reg_2302;
        end else if (((trunc_ln68_1_fu_1454_p1 == 3'd4) & (icmp_ln168_1_fu_1442_p2 == 1'd0))) begin
            ap_phi_reg_pp0_iter1_phi_ln68_1_reg_336 <= act_buf_V_16_load_reg_2278;
        end else if (((trunc_ln68_1_fu_1454_p1 == 3'd3) & (icmp_ln168_1_fu_1442_p2 == 1'd0))) begin
            ap_phi_reg_pp0_iter1_phi_ln68_1_reg_336 <= act_buf_V_12_load_reg_2254;
        end else if (((trunc_ln68_1_fu_1454_p1 == 3'd2) & (icmp_ln168_1_fu_1442_p2 == 1'd0))) begin
            ap_phi_reg_pp0_iter1_phi_ln68_1_reg_336 <= act_buf_V_8_load_reg_2230;
        end else if (((trunc_ln68_1_fu_1454_p1 == 3'd1) & (icmp_ln168_1_fu_1442_p2 == 1'd0))) begin
            ap_phi_reg_pp0_iter1_phi_ln68_1_reg_336 <= act_buf_V_4_load_reg_2206;
        end else if (((trunc_ln68_1_fu_1454_p1 == 3'd0) & (icmp_ln168_1_fu_1442_p2 == 1'd0))) begin
            ap_phi_reg_pp0_iter1_phi_ln68_1_reg_336 <= act_buf_V_0_load_reg_2182;
        end else if (((trunc_ln68_1_fu_1454_p1 == 3'd7) & (icmp_ln168_1_fu_1442_p2 == 1'd0))) begin
            ap_phi_reg_pp0_iter1_phi_ln68_1_reg_336 <= 8'd0;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter1_phi_ln68_1_reg_336 <= ap_phi_reg_pp0_iter0_phi_ln68_1_reg_336;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_350)) begin
        if (((trunc_ln68_fu_1705_p1 == 3'd6) & (icmp_ln168_fu_1693_p2 == 1'd0))) begin
            ap_phi_reg_pp1_iter1_phi_ln68_reg_418 <= act_buf_V_24_load_reg_2326;
        end else if (((trunc_ln68_fu_1705_p1 == 3'd5) & (icmp_ln168_fu_1693_p2 == 1'd0))) begin
            ap_phi_reg_pp1_iter1_phi_ln68_reg_418 <= act_buf_V_20_load_reg_2302;
        end else if (((trunc_ln68_fu_1705_p1 == 3'd4) & (icmp_ln168_fu_1693_p2 == 1'd0))) begin
            ap_phi_reg_pp1_iter1_phi_ln68_reg_418 <= act_buf_V_16_load_reg_2278;
        end else if (((trunc_ln68_fu_1705_p1 == 3'd3) & (icmp_ln168_fu_1693_p2 == 1'd0))) begin
            ap_phi_reg_pp1_iter1_phi_ln68_reg_418 <= act_buf_V_12_load_reg_2254;
        end else if (((trunc_ln68_fu_1705_p1 == 3'd2) & (icmp_ln168_fu_1693_p2 == 1'd0))) begin
            ap_phi_reg_pp1_iter1_phi_ln68_reg_418 <= act_buf_V_8_load_reg_2230;
        end else if (((trunc_ln68_fu_1705_p1 == 3'd1) & (icmp_ln168_fu_1693_p2 == 1'd0))) begin
            ap_phi_reg_pp1_iter1_phi_ln68_reg_418 <= act_buf_V_4_load_reg_2206;
        end else if (((trunc_ln68_fu_1705_p1 == 3'd0) & (icmp_ln168_fu_1693_p2 == 1'd0))) begin
            ap_phi_reg_pp1_iter1_phi_ln68_reg_418 <= act_buf_V_0_load_reg_2182;
        end else if (((trunc_ln68_fu_1705_p1 == 3'd7) & (icmp_ln168_fu_1693_p2 == 1'd0))) begin
            ap_phi_reg_pp1_iter1_phi_ln68_reg_418 <= 8'd0;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp1_iter1_phi_ln68_reg_418 <= ap_phi_reg_pp1_iter0_phi_ln68_reg_418;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp1_stage0_11001) & (icmp_ln168_fu_1693_p2 == 1'd0) & (ap_enable_reg_pp1_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0))) begin
        i_0_i269_reg_407 <= i_fu_1699_p2;
    end else if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1) & (cnn_op_V_read_read_fu_252_p2 == 4'd2))) begin
        i_0_i269_reg_407 <= 4'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln168_1_fu_1442_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        i_0_i_reg_325 <= i_1_fu_1448_p2;
    end else if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1) & (cnn_op_V_read_read_fu_252_p2 == 4'd6))) begin
        i_0_i_reg_325 <= 4'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp1_stage0_11001) & (icmp_ln168_reg_2459 == 1'd0) & (ap_enable_reg_pp1_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0))) begin
        p_0103_0_i268_reg_395 <= grp_fu_2009_p3;
    end else if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1) & (cnn_op_V_read_read_fu_252_p2 == 4'd2))) begin
        p_0103_0_i268_reg_395 <= 19'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln168_1_reg_2386 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_0103_0_i_reg_313 <= grp_fu_1977_p3;
    end else if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1) & (cnn_op_V_read_read_fu_252_p2 == 4'd6))) begin
        p_0103_0_i_reg_313 <= 19'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp1_stage0_11001) & (icmp_ln168_reg_2459 == 1'd0) & (ap_enable_reg_pp1_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0))) begin
        p_0107_0_i267_reg_383 <= grp_fu_2001_p3;
    end else if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1) & (cnn_op_V_read_read_fu_252_p2 == 4'd2))) begin
        p_0107_0_i267_reg_383 <= 19'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln168_1_reg_2386 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_0107_0_i_reg_301 <= grp_fu_1969_p3;
    end else if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1) & (cnn_op_V_read_read_fu_252_p2 == 4'd6))) begin
        p_0107_0_i_reg_301 <= 19'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp1_stage0_11001) & (icmp_ln168_reg_2459 == 1'd0) & (ap_enable_reg_pp1_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0))) begin
        p_0111_0_i266_reg_371 <= grp_fu_1993_p3;
    end else if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1) & (cnn_op_V_read_read_fu_252_p2 == 4'd2))) begin
        p_0111_0_i266_reg_371 <= 19'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln168_1_reg_2386 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_0111_0_i_reg_289 <= grp_fu_1961_p3;
    end else if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1) & (cnn_op_V_read_read_fu_252_p2 == 4'd6))) begin
        p_0111_0_i_reg_289 <= 19'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp1_stage0_11001) & (icmp_ln168_reg_2459 == 1'd0) & (ap_enable_reg_pp1_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0))) begin
        p_0217_0_i265_reg_359 <= grp_fu_1985_p3;
    end else if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1) & (cnn_op_V_read_read_fu_252_p2 == 4'd2))) begin
        p_0217_0_i265_reg_359 <= 19'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln168_1_reg_2386 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_0217_0_i_reg_277 <= grp_fu_1953_p3;
    end else if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1) & (cnn_op_V_read_read_fu_252_p2 == 4'd6))) begin
        p_0217_0_i_reg_277 <= 19'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((w_ptr_load_load_fu_1069_p1 == 7'd0) & (1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1) & (cnn_op_V_read_read_fu_252_p2 == 4'd0))) begin
                w_ptr[2] <= 1'b1;
        w_ptr[3] <= 1'b0;
        w_ptr[4] <= 1'b0;
    end else if (((w_ptr_load_load_fu_1069_p1 == 7'd4) & (1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1) & (cnn_op_V_read_read_fu_252_p2 == 4'd0))) begin
                w_ptr[2] <= 1'b0;
        w_ptr[3] <= 1'b1;
        w_ptr[4] <= 1'b0;
    end else if (((w_ptr_load_load_fu_1069_p1 == 7'd8) & (1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1) & (cnn_op_V_read_read_fu_252_p2 == 4'd0))) begin
                w_ptr[2] <= 1'b1;
        w_ptr[3] <= 1'b1;
        w_ptr[4] <= 1'b0;
    end else if (((w_ptr_load_load_fu_1069_p1 == 7'd12) & (1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1) & (cnn_op_V_read_read_fu_252_p2 == 4'd0))) begin
                w_ptr[2] <= 1'b0;
        w_ptr[3] <= 1'b0;
        w_ptr[4] <= 1'b1;
    end else if (((w_ptr_load_load_fu_1069_p1 == 7'd16) & (1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1) & (cnn_op_V_read_read_fu_252_p2 == 4'd0))) begin
                w_ptr[2] <= 1'b1;
        w_ptr[3] <= 1'b0;
        w_ptr[4] <= 1'b1;
    end else if (((w_ptr_load_load_fu_1069_p1 == 7'd20) & (1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1) & (cnn_op_V_read_read_fu_252_p2 == 4'd0))) begin
                w_ptr[2] <= 1'b0;
        w_ptr[3] <= 1'b1;
        w_ptr[4] <= 1'b1;
    end else if ((((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1) & (cnn_op_V_read_read_fu_252_p2 == 4'd5)) | (~(w_ptr_load_load_fu_1069_p1 == 7'd24) & ~(w_ptr_load_load_fu_1069_p1 == 7'd20) & ~(w_ptr_load_load_fu_1069_p1 == 7'd16) & ~(w_ptr_load_load_fu_1069_p1 == 7'd12) & ~(w_ptr_load_load_fu_1069_p1 == 7'd8) & ~(w_ptr_load_load_fu_1069_p1 == 7'd4) & ~(w_ptr_load_load_fu_1069_p1 == 7'd0) & (1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1) & (cnn_op_V_read_read_fu_252_p2 == 4'd0)) | ((w_ptr_load_load_fu_1069_p1 == 7'd24) & (1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1) & (cnn_op_V_read_read_fu_252_p2 == 4'd0)))) begin
                w_ptr[2] <= 1'b0;
        w_ptr[3] <= 1'b0;
        w_ptr[4] <= 1'b0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        acc_reg_V_load_reg_2332 <= acc_reg_V;
        act_buf_V_0_load_reg_2182 <= act_buf_V_0;
        act_buf_V_10_load_reg_2242 <= act_buf_V_10;
        act_buf_V_11_load_reg_2248 <= act_buf_V_11;
        act_buf_V_12_load_reg_2254 <= act_buf_V_12;
        act_buf_V_13_load_reg_2260 <= act_buf_V_13;
        act_buf_V_14_load_reg_2266 <= act_buf_V_14;
        act_buf_V_15_load_reg_2272 <= act_buf_V_15;
        act_buf_V_16_load_reg_2278 <= act_buf_V_16;
        act_buf_V_17_load_reg_2284 <= act_buf_V_17;
        act_buf_V_18_load_reg_2290 <= act_buf_V_18;
        act_buf_V_19_load_reg_2296 <= act_buf_V_19;
        act_buf_V_1_load_reg_2188 <= act_buf_V_1;
        act_buf_V_20_load_reg_2302 <= act_buf_V_20;
        act_buf_V_21_load_reg_2308 <= act_buf_V_21;
        act_buf_V_22_load_reg_2314 <= act_buf_V_22;
        act_buf_V_23_load_reg_2320 <= act_buf_V_23;
        act_buf_V_24_load_reg_2326 <= act_buf_V_24;
        act_buf_V_2_load_reg_2194 <= act_buf_V_2;
        act_buf_V_3_load_reg_2200 <= act_buf_V_3;
        act_buf_V_4_load_reg_2206 <= act_buf_V_4;
        act_buf_V_5_load_reg_2212 <= act_buf_V_5;
        act_buf_V_6_load_reg_2218 <= act_buf_V_6;
        act_buf_V_7_load_reg_2224 <= act_buf_V_7;
        act_buf_V_8_load_reg_2230 <= act_buf_V_8;
        act_buf_V_9_load_reg_2236 <= act_buf_V_9;
        weight_buf_V_0_load_reg_2032 <= weight_buf_V_0;
        weight_buf_V_10_load_reg_2092 <= weight_buf_V_10;
        weight_buf_V_11_load_reg_2098 <= weight_buf_V_11;
        weight_buf_V_12_load_reg_2104 <= weight_buf_V_12;
        weight_buf_V_13_load_reg_2110 <= weight_buf_V_13;
        weight_buf_V_14_load_reg_2116 <= weight_buf_V_14;
        weight_buf_V_15_load_reg_2122 <= weight_buf_V_15;
        weight_buf_V_16_load_reg_2128 <= weight_buf_V_16;
        weight_buf_V_17_load_reg_2134 <= weight_buf_V_17;
        weight_buf_V_18_load_reg_2140 <= weight_buf_V_18;
        weight_buf_V_19_load_reg_2146 <= weight_buf_V_19;
        weight_buf_V_1_load_reg_2038 <= weight_buf_V_1;
        weight_buf_V_20_load_reg_2152 <= weight_buf_V_20;
        weight_buf_V_21_load_reg_2158 <= weight_buf_V_21;
        weight_buf_V_22_load_reg_2164 <= weight_buf_V_22;
        weight_buf_V_23_load_reg_2170 <= weight_buf_V_23;
        weight_buf_V_24_load_reg_2176 <= weight_buf_V_24;
        weight_buf_V_2_load_reg_2044 <= weight_buf_V_2;
        weight_buf_V_3_load_reg_2050 <= weight_buf_V_3;
        weight_buf_V_4_load_reg_2056 <= weight_buf_V_4;
        weight_buf_V_5_load_reg_2062 <= weight_buf_V_5;
        weight_buf_V_6_load_reg_2068 <= weight_buf_V_6;
        weight_buf_V_7_load_reg_2074 <= weight_buf_V_7;
        weight_buf_V_8_load_reg_2080 <= weight_buf_V_8;
        weight_buf_V_9_load_reg_2086 <= weight_buf_V_9;
    end
end

always @ (posedge ap_clk) begin
    if (((7'd0 == a_ptr_load_load_fu_851_p1) & (1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1) & (cnn_op_V_read_read_fu_252_p2 == 4'd1))) begin
        act_buf_V_0 <= trunc_ln647_8_fu_1035_p1;
        act_buf_V_1 <= {{grp_fu_455_p1[15:8]}};
        act_buf_V_2 <= {{grp_fu_465_p1[23:16]}};
        act_buf_V_3 <= {{grp_fu_475_p1[31:24]}};
    end
end

always @ (posedge ap_clk) begin
    if (((7'd8 == a_ptr_load_load_fu_851_p1) & (1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1) & (cnn_op_V_read_read_fu_252_p2 == 4'd1))) begin
        act_buf_V_10 <= {{grp_fu_465_p1[23:16]}};
        act_buf_V_11 <= {{grp_fu_475_p1[31:24]}};
        act_buf_V_8 <= trunc_ln647_10_fu_967_p1;
        act_buf_V_9 <= {{grp_fu_455_p1[15:8]}};
    end
end

always @ (posedge ap_clk) begin
    if (((7'd12 == a_ptr_load_load_fu_851_p1) & (1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1) & (cnn_op_V_read_read_fu_252_p2 == 4'd1))) begin
        act_buf_V_12 <= trunc_ln647_11_fu_933_p1;
        act_buf_V_13 <= {{grp_fu_455_p1[15:8]}};
        act_buf_V_14 <= {{grp_fu_465_p1[23:16]}};
        act_buf_V_15 <= {{grp_fu_475_p1[31:24]}};
    end
end

always @ (posedge ap_clk) begin
    if (((7'd16 == a_ptr_load_load_fu_851_p1) & (1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1) & (cnn_op_V_read_read_fu_252_p2 == 4'd1))) begin
        act_buf_V_16 <= trunc_ln647_12_fu_899_p1;
        act_buf_V_17 <= {{grp_fu_455_p1[15:8]}};
        act_buf_V_18 <= {{grp_fu_465_p1[23:16]}};
        act_buf_V_19 <= {{grp_fu_475_p1[31:24]}};
    end
end

always @ (posedge ap_clk) begin
    if (((7'd20 == a_ptr_load_load_fu_851_p1) & (1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1) & (cnn_op_V_read_read_fu_252_p2 == 4'd1))) begin
        act_buf_V_20 <= trunc_ln647_13_fu_865_p1;
        act_buf_V_21 <= {{grp_fu_455_p1[15:8]}};
        act_buf_V_22 <= {{grp_fu_465_p1[23:16]}};
        act_buf_V_23 <= {{grp_fu_475_p1[31:24]}};
    end
end

always @ (posedge ap_clk) begin
    if (((7'd24 == a_ptr_load_load_fu_851_p1) & (1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1) & (cnn_op_V_read_read_fu_252_p2 == 4'd1))) begin
        act_buf_V_24 <= trunc_ln647_14_fu_855_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((7'd4 == a_ptr_load_load_fu_851_p1) & (1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1) & (cnn_op_V_read_read_fu_252_p2 == 4'd1))) begin
        act_buf_V_4 <= trunc_ln647_9_fu_1001_p1;
        act_buf_V_5 <= {{grp_fu_455_p1[15:8]}};
        act_buf_V_6 <= {{grp_fu_465_p1[23:16]}};
        act_buf_V_7 <= {{grp_fu_475_p1[31:24]}};
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1) & (cnn_op_V_read_read_fu_252_p2 == 4'd12))) begin
        add_ln68_reg_2347 <= add_ln68_fu_736_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        add_ln700_2_reg_2454 <= add_ln700_2_fu_1687_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        icmp_ln168_1_reg_2386 <= icmp_ln168_1_fu_1442_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp1_stage0_11001) & (1'b1 == ap_CS_fsm_pp1_stage0))) begin
        icmp_ln168_reg_2459 <= icmp_ln168_fu_1693_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        icmp_ln899_reg_2364 <= icmp_ln899_fu_1350_p2;
        product_V_reg_2370 <= product_V_fu_1361_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_mac_pack4_delta_fu_441_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state7))) begin
        p_0_reg_2381 <= grp_mac_pack4_delta_fu_441_ap_return;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp1_stage0_11001) & (icmp_ln168_fu_1693_p2 == 1'd0) & (1'b1 == ap_CS_fsm_pp1_stage0))) begin
        phi_ln68_10_reg_2497 <= phi_ln68_10_fu_1844_p10;
        phi_ln68_12_reg_2502 <= phi_ln68_12_fu_1860_p10;
        phi_ln68_2_reg_2472 <= phi_ln68_2_fu_1717_p34;
        phi_ln68_4_reg_2477 <= phi_ln68_4_fu_1780_p10;
        phi_ln68_6_reg_2482 <= phi_ln68_6_fu_1796_p10;
        phi_ln68_8_reg_2487 <= phi_ln68_8_fu_1812_p10;
        phi_ln68_s_reg_2492 <= phi_ln68_s_fu_1828_p10;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln168_1_fu_1442_p2 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        phi_ln68_11_reg_2419 <= phi_ln68_11_fu_1577_p10;
        phi_ln68_13_reg_2424 <= phi_ln68_13_fu_1593_p10;
        phi_ln68_14_reg_2429 <= phi_ln68_14_fu_1609_p10;
        phi_ln68_3_reg_2399 <= phi_ln68_3_fu_1466_p34;
        phi_ln68_5_reg_2404 <= phi_ln68_5_fu_1529_p10;
        phi_ln68_7_reg_2409 <= phi_ln68_7_fu_1545_p10;
        phi_ln68_9_reg_2414 <= phi_ln68_9_fu_1561_p10;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1) & (cnn_op_V_read_read_fu_252_p2 == 4'd9))) begin
        product_V_1_reg_2339 <= product_V_1_fu_710_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        select_ln899_1_reg_2375 <= select_ln899_1_fu_1410_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        select_ln899_3_reg_2359 <= select_ln899_3_fu_1337_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((w_ptr_load_load_fu_1069_p1 == 7'd0) & (1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1) & (cnn_op_V_read_read_fu_252_p2 == 4'd0))) begin
        weight_buf_V_0 <= trunc_ln647_fu_1253_p1;
        weight_buf_V_1 <= {{grp_fu_455_p1[15:8]}};
        weight_buf_V_2 <= {{grp_fu_465_p1[23:16]}};
        weight_buf_V_3 <= {{grp_fu_475_p1[31:24]}};
    end
end

always @ (posedge ap_clk) begin
    if (((w_ptr_load_load_fu_1069_p1 == 7'd8) & (1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1) & (cnn_op_V_read_read_fu_252_p2 == 4'd0))) begin
        weight_buf_V_10 <= {{grp_fu_465_p1[23:16]}};
        weight_buf_V_11 <= {{grp_fu_475_p1[31:24]}};
        weight_buf_V_8 <= trunc_ln647_3_fu_1185_p1;
        weight_buf_V_9 <= {{grp_fu_455_p1[15:8]}};
    end
end

always @ (posedge ap_clk) begin
    if (((w_ptr_load_load_fu_1069_p1 == 7'd12) & (1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1) & (cnn_op_V_read_read_fu_252_p2 == 4'd0))) begin
        weight_buf_V_12 <= trunc_ln647_4_fu_1151_p1;
        weight_buf_V_13 <= {{grp_fu_455_p1[15:8]}};
        weight_buf_V_14 <= {{grp_fu_465_p1[23:16]}};
        weight_buf_V_15 <= {{grp_fu_475_p1[31:24]}};
    end
end

always @ (posedge ap_clk) begin
    if (((w_ptr_load_load_fu_1069_p1 == 7'd16) & (1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1) & (cnn_op_V_read_read_fu_252_p2 == 4'd0))) begin
        weight_buf_V_16 <= trunc_ln647_5_fu_1117_p1;
        weight_buf_V_17 <= {{grp_fu_455_p1[15:8]}};
        weight_buf_V_18 <= {{grp_fu_465_p1[23:16]}};
        weight_buf_V_19 <= {{grp_fu_475_p1[31:24]}};
    end
end

always @ (posedge ap_clk) begin
    if (((w_ptr_load_load_fu_1069_p1 == 7'd20) & (1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1) & (cnn_op_V_read_read_fu_252_p2 == 4'd0))) begin
        weight_buf_V_20 <= trunc_ln647_6_fu_1083_p1;
        weight_buf_V_21 <= {{grp_fu_455_p1[15:8]}};
        weight_buf_V_22 <= {{grp_fu_465_p1[23:16]}};
        weight_buf_V_23 <= {{grp_fu_475_p1[31:24]}};
    end
end

always @ (posedge ap_clk) begin
    if (((w_ptr_load_load_fu_1069_p1 == 7'd24) & (1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1) & (cnn_op_V_read_read_fu_252_p2 == 4'd0))) begin
        weight_buf_V_24 <= trunc_ln647_7_fu_1073_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((w_ptr_load_load_fu_1069_p1 == 7'd4) & (1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1) & (cnn_op_V_read_read_fu_252_p2 == 4'd0))) begin
        weight_buf_V_4 <= trunc_ln647_2_fu_1219_p1;
        weight_buf_V_5 <= {{grp_fu_455_p1[15:8]}};
        weight_buf_V_6 <= {{grp_fu_465_p1[23:16]}};
        weight_buf_V_7 <= {{grp_fu_475_p1[31:24]}};
    end
end

always @ (*) begin
    if ((icmp_ln168_1_fu_1442_p2 == 1'd1)) begin
        ap_condition_pp0_exit_iter0_state9 = 1'b1;
    end else begin
        ap_condition_pp0_exit_iter0_state9 = 1'b0;
    end
end

always @ (*) begin
    if ((icmp_ln168_fu_1693_p2 == 1'd1)) begin
        ap_condition_pp1_exit_iter0_state12 = 1'b1;
    end else begin
        ap_condition_pp1_exit_iter0_state12 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp1_iter1 == 1'b0) & (ap_enable_reg_pp1_iter0 == 1'b0))) begin
        ap_idle_pp1 = 1'b1;
    end else begin
        ap_idle_pp1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state6) & (cnn_op_V_read_read_fu_252_p2 == 4'd12))) begin
        rd_data_V = select_ln899_1_reg_2375;
    end else if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1) & (cnn_op_V_read_read_fu_252_p2 == 4'd3))) begin
        rd_data_V = acc_reg_V;
    end else if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1) & (cnn_op_V_read_read_fu_252_p2 == 4'd11))) begin
        rd_data_V = sext_ln68_11_fu_788_p1;
    end else begin
        rd_data_V = rd_data_V_preg;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1) & (cnn_op_V_read_read_fu_252_p2 == 4'd0))) begin
                ap_NS_fsm = ap_ST_fsm_state16;
            end else if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1) & (cnn_op_V_read_read_fu_252_p2 == 4'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state15;
            end else if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1) & (cnn_op_V_read_read_fu_252_p2 == 4'd2))) begin
                ap_NS_fsm = ap_ST_fsm_pp1_stage0;
            end else if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1) & (cnn_op_V_read_read_fu_252_p2 == 4'd6))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1) & (cnn_op_V_read_read_fu_252_p2 == 4'd10))) begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end else if ((~(cnn_op_V_read_read_fu_252_p2 == 4'd1) & ~(cnn_op_V_read_read_fu_252_p2 == 4'd0) & ~(cnn_op_V_read_read_fu_252_p2 == 4'd10) & ~(cnn_op_V_read_read_fu_252_p2 == 4'd2) & ~(cnn_op_V_read_read_fu_252_p2 == 4'd6) & ~(cnn_op_V_read_read_fu_252_p2 == 4'd12) & ~(cnn_op_V_read_read_fu_252_p2 == 4'd9) & (1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end else if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1) & (cnn_op_V_read_read_fu_252_p2 == 4'd12))) begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end else if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1) & (cnn_op_V_read_read_fu_252_p2 == 4'd9))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        ap_ST_fsm_state7 : begin
            if (((grp_mac_pack4_delta_fu_441_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state7))) begin
                ap_NS_fsm = ap_ST_fsm_state8;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_pp0_stage0 : begin
            if (~((1'b0 == ap_block_pp0_stage0_subdone) & (icmp_ln168_1_fu_1442_p2 == 1'd1) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (icmp_ln168_1_fu_1442_p2 == 1'd1) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state11;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_state11 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_pp1_stage0 : begin
            if (~((1'b0 == ap_block_pp1_stage0_subdone) & (icmp_ln168_fu_1693_p2 == 1'd1) & (ap_enable_reg_pp1_iter0 == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_pp1_stage0;
            end else if (((1'b0 == ap_block_pp1_stage0_subdone) & (icmp_ln168_fu_1693_p2 == 1'd1) & (ap_enable_reg_pp1_iter0 == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state14;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp1_stage0;
            end
        end
        ap_ST_fsm_state14 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state15 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state16 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign a0_V_fu_742_p0 = rs1_data_V;

assign a0_V_fu_742_p1 = a0_V_fu_742_p0[7:0];

assign a_ptr_load_load_fu_851_p1 = a_ptr;

assign add_ln68_3_fu_1917_p2 = ($signed(sext_ln168_2_fu_1909_p1) + $signed(sext_ln168_3_fu_1913_p1));

assign add_ln68_4_fu_1937_p2 = ($signed(sext_ln68_15_fu_1933_p1) + $signed(sext_ln68_14_fu_1923_p1));

assign add_ln68_5_fu_1927_p2 = ($signed(sext_ln168_1_fu_1905_p1) + $signed(sext_ln168_fu_1901_p1));

assign add_ln68_fu_736_p0 = rs1_data_V;

assign add_ln68_fu_736_p2 = ($signed(add_ln68_fu_736_p0) + $signed(acc_reg_V));

assign add_ln700_1_fu_724_p1 = rs1_data_V;

assign add_ln700_1_fu_724_p2 = ($signed(acc_reg_V) + $signed(add_ln700_1_fu_724_p1));

assign add_ln700_2_fu_1687_p2 = ($signed(sext_ln700_1_fu_1683_p1) + $signed(add_ln700_3_fu_1666_p2));

assign add_ln700_3_fu_1666_p2 = ($signed(acc_reg_V_load_reg_2332) + $signed(sext_ln168_6_fu_1658_p1));

assign add_ln700_4_fu_1671_p2 = ($signed(sext_ln168_5_fu_1654_p1) + $signed(sext_ln168_4_fu_1650_p1));

assign add_ln700_5_fu_1677_p2 = ($signed(add_ln700_4_fu_1671_p2) + $signed(sext_ln168_7_fu_1662_p1));

assign add_ln700_fu_1431_p2 = ($signed(acc_reg_V_load_reg_2332) + $signed(sext_ln700_fu_1428_p1));

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd8];

assign ap_CS_fsm_pp1_stage0 = ap_CS_fsm[32'd10];

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state11 = ap_CS_fsm[32'd9];

assign ap_CS_fsm_state14 = ap_CS_fsm[32'd11];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd7];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp1_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp1_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp1_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_block_state10_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state12_pp1_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state13_pp1_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state9_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_condition_291 = ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0));
end

always @ (*) begin
    ap_condition_350 = ((1'b0 == ap_block_pp1_stage0_11001) & (ap_enable_reg_pp1_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0));
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_pp1 = (ap_idle_pp1 ^ 1'b1);

assign ap_phi_reg_pp0_iter0_phi_ln68_1_reg_336 = 'bx;

assign ap_phi_reg_pp1_iter0_phi_ln68_reg_418 = 'bx;

assign cnn_op_V_read_read_fu_252_p2 = cnn_op_V;

assign final_max_V_fu_833_p3 = ((icmp_ln895_2_fu_827_p2[0:0] === 1'b1) ? max1_V_fu_805_p3 : max2_V_fu_819_p3);

assign grp_fu_455_p1 = rs1_data_V;

assign grp_fu_455_p4 = {{grp_fu_455_p1[15:8]}};

assign grp_fu_465_p1 = rs1_data_V;

assign grp_fu_465_p4 = {{grp_fu_465_p1[23:16]}};

assign grp_fu_475_p1 = rs1_data_V;

assign grp_fu_475_p4 = {{grp_fu_475_p1[31:24]}};

assign grp_mac_pack4_delta_fu_441_ap_start = grp_mac_pack4_delta_fu_441_ap_start_reg;

assign i_1_fu_1448_p2 = (i_0_i_reg_325 + 4'd1);

assign i_fu_1699_p2 = (i_0_i269_reg_407 + 4'd1);

assign icmp_ln168_1_fu_1442_p2 = ((i_0_i_reg_325 == 4'd8) ? 1'b1 : 1'b0);

assign icmp_ln168_fu_1693_p2 = ((i_0_i269_reg_407 == 4'd8) ? 1'b1 : 1'b0);

assign icmp_ln895_1_fu_813_p2 = (($signed(act_buf_V_2) > $signed(act_buf_V_3)) ? 1'b1 : 1'b0);

assign icmp_ln895_2_fu_827_p2 = (($signed(max1_V_fu_805_p3) > $signed(max2_V_fu_819_p3)) ? 1'b1 : 1'b0);

assign icmp_ln895_3_fu_746_p2 = (($signed(a0_V_fu_742_p1) > $signed(grp_fu_455_p4)) ? 1'b1 : 1'b0);

assign icmp_ln895_4_fu_760_p2 = (($signed(grp_fu_465_p4) > $signed(grp_fu_475_p4)) ? 1'b1 : 1'b0);

assign icmp_ln895_5_fu_774_p2 = (($signed(max1_V_1_fu_752_p3) > $signed(max2_V_1_fu_766_p3)) ? 1'b1 : 1'b0);

assign icmp_ln895_6_fu_1392_p2 = (($signed(tmp_2_fu_1382_p4) > $signed(25'd0)) ? 1'b1 : 1'b0);

assign icmp_ln895_7_fu_1317_p2 = (($signed(tmp_4_fu_1307_p4) > $signed(25'd0)) ? 1'b1 : 1'b0);

assign icmp_ln895_fu_799_p2 = (($signed(act_buf_V_0) > $signed(act_buf_V_1)) ? 1'b1 : 1'b0);

assign icmp_ln899_1_fu_1287_p2 = (($signed(acc_reg_V_load_reg_2332) < $signed(32'd1)) ? 1'b1 : 1'b0);

assign icmp_ln899_fu_1350_p2 = (($signed(add_ln68_reg_2347) < $signed(32'd1)) ? 1'b1 : 1'b0);

assign max1_V_1_fu_752_p3 = ((icmp_ln895_3_fu_746_p2[0:0] === 1'b1) ? a0_V_fu_742_p1 : grp_fu_455_p4);

assign max1_V_fu_805_p3 = ((icmp_ln895_fu_799_p2[0:0] === 1'b1) ? act_buf_V_0 : act_buf_V_1);

assign max2_V_1_fu_766_p3 = ((icmp_ln895_4_fu_760_p2[0:0] === 1'b1) ? grp_fu_465_p4 : grp_fu_475_p4);

assign max2_V_fu_819_p3 = ((icmp_ln895_1_fu_813_p2[0:0] === 1'b1) ? act_buf_V_2 : act_buf_V_3);

assign or_ln899_1_fu_1331_p2 = (icmp_ln899_1_fu_1287_p2 | icmp_ln895_7_fu_1317_p2);

assign or_ln899_fu_1405_p2 = (icmp_ln899_reg_2364 | icmp_ln895_6_fu_1392_p2);

assign phi_ln68_2_fu_1717_p33 = {{trunc_ln68_fu_1705_p1}, {2'd0}};

assign phi_ln68_3_fu_1466_p33 = {{trunc_ln68_1_fu_1454_p1}, {2'd0}};

assign product_V_1_fu_710_p0 = product_V_1_fu_710_p00;

assign product_V_1_fu_710_p00 = acc_reg_V;

assign product_V_1_fu_710_p1 = sext_ln68_13_fu_706_p0;

assign product_V_1_fu_710_p2 = ($signed({{1'b0}, {product_V_1_fu_710_p0}}) * $signed(product_V_1_fu_710_p1));

assign product_V_fu_1361_p0 = product_V_fu_1361_p00;

assign product_V_fu_1361_p00 = add_ln68_reg_2347;

assign product_V_fu_1361_p1 = sext_ln68_12_fu_1358_p0;

assign product_V_fu_1361_p2 = ($signed({{1'b0}, {product_V_fu_1361_p0}}) * $signed(product_V_fu_1361_p1));

assign rounded_V_1_fu_1292_p2 = (64'd524288 + product_V_1_reg_2339);

assign rounded_V_fu_1367_p2 = (64'd524288 + product_V_reg_2370);

assign scaled_V_1_fu_1297_p4 = {{rounded_V_1_fu_1292_p2[51:20]}};

assign scaled_V_fu_1372_p4 = {{rounded_V_fu_1367_p2[51:20]}};

assign select_ln68_fu_780_p3 = ((icmp_ln895_5_fu_774_p2[0:0] === 1'b1) ? max1_V_1_fu_752_p3 : max2_V_1_fu_766_p3);

assign select_ln899_1_fu_1410_p3 = ((or_ln899_fu_1405_p2[0:0] === 1'b1) ? select_ln899_fu_1398_p3 : scaled_V_fu_1372_p4);

assign select_ln899_2_fu_1323_p3 = ((icmp_ln899_1_fu_1287_p2[0:0] === 1'b1) ? 32'd0 : 32'd127);

assign select_ln899_3_fu_1337_p3 = ((or_ln899_1_fu_1331_p2[0:0] === 1'b1) ? select_ln899_2_fu_1323_p3 : scaled_V_1_fu_1297_p4);

assign select_ln899_fu_1398_p3 = ((icmp_ln899_reg_2364[0:0] === 1'b1) ? 32'd0 : 32'd127);

assign sext_ln168_1_fu_1905_p1 = p_0111_0_i266_reg_371;

assign sext_ln168_2_fu_1909_p1 = p_0107_0_i267_reg_383;

assign sext_ln168_3_fu_1913_p1 = p_0103_0_i268_reg_395;

assign sext_ln168_4_fu_1650_p1 = p_0217_0_i_reg_277;

assign sext_ln168_5_fu_1654_p1 = p_0111_0_i_reg_289;

assign sext_ln168_6_fu_1658_p1 = p_0107_0_i_reg_301;

assign sext_ln168_7_fu_1662_p1 = p_0103_0_i_reg_313;

assign sext_ln168_fu_1901_p1 = p_0217_0_i265_reg_359;

assign sext_ln68_11_fu_788_p1 = $signed(select_ln68_fu_780_p3);

assign sext_ln68_12_fu_1358_p0 = rs2_data_V;

assign sext_ln68_13_fu_706_p0 = rs1_data_V;

assign sext_ln68_14_fu_1923_p1 = $signed(add_ln68_3_fu_1917_p2);

assign sext_ln68_15_fu_1933_p1 = $signed(add_ln68_5_fu_1927_p2);

assign sext_ln68_16_fu_1943_p1 = $signed(add_ln68_4_fu_1937_p2);

assign sext_ln68_fu_841_p1 = $signed(final_max_V_fu_833_p3);

assign sext_ln700_1_fu_1683_p1 = $signed(add_ln700_5_fu_1677_p2);

assign sext_ln700_fu_1428_p1 = $signed(p_0_reg_2381);

assign tmp_2_fu_1382_p4 = {{rounded_V_fu_1367_p2[51:27]}};

assign tmp_3_fu_716_p3 = acc_reg_V[32'd31];

assign tmp_4_fu_1307_p4 = {{rounded_V_1_fu_1292_p2[51:27]}};

assign trunc_ln647_10_fu_967_p0 = rs1_data_V;

assign trunc_ln647_10_fu_967_p1 = trunc_ln647_10_fu_967_p0[7:0];

assign trunc_ln647_11_fu_933_p0 = rs1_data_V;

assign trunc_ln647_11_fu_933_p1 = trunc_ln647_11_fu_933_p0[7:0];

assign trunc_ln647_12_fu_899_p0 = rs1_data_V;

assign trunc_ln647_12_fu_899_p1 = trunc_ln647_12_fu_899_p0[7:0];

assign trunc_ln647_13_fu_865_p0 = rs1_data_V;

assign trunc_ln647_13_fu_865_p1 = trunc_ln647_13_fu_865_p0[7:0];

assign trunc_ln647_14_fu_855_p0 = rs1_data_V;

assign trunc_ln647_14_fu_855_p1 = trunc_ln647_14_fu_855_p0[7:0];

assign trunc_ln647_2_fu_1219_p0 = rs1_data_V;

assign trunc_ln647_2_fu_1219_p1 = trunc_ln647_2_fu_1219_p0[7:0];

assign trunc_ln647_3_fu_1185_p0 = rs1_data_V;

assign trunc_ln647_3_fu_1185_p1 = trunc_ln647_3_fu_1185_p0[7:0];

assign trunc_ln647_4_fu_1151_p0 = rs1_data_V;

assign trunc_ln647_4_fu_1151_p1 = trunc_ln647_4_fu_1151_p0[7:0];

assign trunc_ln647_5_fu_1117_p0 = rs1_data_V;

assign trunc_ln647_5_fu_1117_p1 = trunc_ln647_5_fu_1117_p0[7:0];

assign trunc_ln647_6_fu_1083_p0 = rs1_data_V;

assign trunc_ln647_6_fu_1083_p1 = trunc_ln647_6_fu_1083_p0[7:0];

assign trunc_ln647_7_fu_1073_p0 = rs1_data_V;

assign trunc_ln647_7_fu_1073_p1 = trunc_ln647_7_fu_1073_p0[7:0];

assign trunc_ln647_8_fu_1035_p0 = rs1_data_V;

assign trunc_ln647_8_fu_1035_p1 = trunc_ln647_8_fu_1035_p0[7:0];

assign trunc_ln647_9_fu_1001_p0 = rs1_data_V;

assign trunc_ln647_9_fu_1001_p1 = trunc_ln647_9_fu_1001_p0[7:0];

assign trunc_ln647_fu_1253_p0 = rs1_data_V;

assign trunc_ln647_fu_1253_p1 = trunc_ln647_fu_1253_p0[7:0];

assign trunc_ln68_1_fu_1454_p1 = i_0_i_reg_325[2:0];

assign trunc_ln68_fu_1705_p1 = i_0_i269_reg_407[2:0];

assign w_ptr_load_load_fu_1069_p1 = w_ptr;

always @ (posedge ap_clk) begin
    w_ptr[1:0] <= 2'b00;
    w_ptr[6:5] <= 2'b00;
    a_ptr[1:0] <= 2'b00;
    a_ptr[6:5] <= 2'b00;
end

endmodule //CNN_ALU_Top
