// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2019.1
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module mac_pack4_delta (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        act_pack_V,
        weight_pack_V,
        ap_return
);

parameter    ap_ST_fsm_state1 = 4'd1;
parameter    ap_ST_fsm_state2 = 4'd2;
parameter    ap_ST_fsm_state3 = 4'd4;
parameter    ap_ST_fsm_state4 = 4'd8;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [31:0] act_pack_V;
input  [31:0] weight_pack_V;
output  [17:0] ap_return;

reg ap_done;
reg ap_idle;
reg ap_ready;

(* fsm_encoding = "none" *) reg   [3:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg   [7:0] p_Result_4_reg_222;
wire    ap_CS_fsm_state3;
reg   [7:0] p_Result_5_reg_227;
reg   [7:0] p_Result_6_reg_232;
reg   [7:0] p_Result_7_reg_237;
wire   [16:0] add_ln1353_1_fu_173_p2;
reg   [16:0] add_ln1353_1_reg_242;
reg  signed [7:0] grp_fu_44_p0;
wire  signed [15:0] sext_ln68_fu_81_p1;
wire  signed [15:0] sext_ln68_4_fu_179_p1;
reg  signed [7:0] grp_fu_44_p1;
wire  signed [15:0] sext_ln68_1_fu_90_p1;
wire  signed [15:0] sext_ln68_5_fu_183_p1;
wire    ap_CS_fsm_state4;
reg  signed [7:0] grp_fu_45_p0;
wire  signed [15:0] sext_ln68_2_fu_105_p1;
wire  signed [15:0] sext_ln68_6_fu_187_p1;
reg  signed [7:0] grp_fu_45_p1;
wire  signed [15:0] sext_ln68_3_fu_120_p1;
wire  signed [15:0] sext_ln68_7_fu_191_p1;
wire   [7:0] trunc_ln647_fu_77_p1;
wire   [7:0] trunc_ln647_1_fu_86_p1;
wire   [7:0] p_Result_2_fu_95_p4;
wire   [7:0] p_Result_3_fu_110_p4;
wire   [15:0] grp_fu_44_p2;
wire   [15:0] grp_fu_45_p2;
wire  signed [16:0] sext_ln68_8_fu_165_p1;
wire  signed [16:0] sext_ln68_9_fu_169_p1;
wire  signed [16:0] sext_ln1353_fu_199_p1;
wire  signed [16:0] sext_ln68_10_fu_195_p1;
wire   [16:0] add_ln1353_2_fu_206_p2;
wire  signed [17:0] sext_ln1353_1_fu_203_p1;
wire  signed [17:0] sext_ln1353_2_fu_212_p1;
reg   [3:0] ap_NS_fsm;

// power-on initialization
initial begin
#0 ap_CS_fsm = 4'd1;
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        add_ln1353_1_reg_242 <= add_ln1353_1_fu_173_p2;
        p_Result_4_reg_222 <= {{act_pack_V[23:16]}};
        p_Result_5_reg_227 <= {{weight_pack_V[23:16]}};
        p_Result_6_reg_232 <= {{act_pack_V[31:24]}};
        p_Result_7_reg_237 <= {{weight_pack_V[31:24]}};
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) | ((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        grp_fu_44_p0 = sext_ln68_4_fu_179_p1;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        grp_fu_44_p0 = sext_ln68_fu_81_p1;
    end else begin
        grp_fu_44_p0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        grp_fu_44_p1 = sext_ln68_5_fu_183_p1;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        grp_fu_44_p1 = sext_ln68_1_fu_90_p1;
    end else begin
        grp_fu_44_p1 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        grp_fu_45_p0 = sext_ln68_6_fu_187_p1;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        grp_fu_45_p0 = sext_ln68_2_fu_105_p1;
    end else begin
        grp_fu_45_p0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        grp_fu_45_p1 = sext_ln68_7_fu_191_p1;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        grp_fu_45_p1 = sext_ln68_3_fu_120_p1;
    end else begin
        grp_fu_45_p1 = 'bx;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln1353_1_fu_173_p2 = ($signed(sext_ln68_8_fu_165_p1) + $signed(sext_ln68_9_fu_169_p1));

assign add_ln1353_2_fu_206_p2 = ($signed(sext_ln1353_fu_199_p1) + $signed(sext_ln68_10_fu_195_p1));

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_return = ($signed(sext_ln1353_1_fu_203_p1) + $signed(sext_ln1353_2_fu_212_p1));

assign grp_fu_44_p2 = ($signed(grp_fu_44_p0) * $signed(grp_fu_44_p1));

assign grp_fu_45_p2 = ($signed(grp_fu_45_p0) * $signed(grp_fu_45_p1));

assign p_Result_2_fu_95_p4 = {{act_pack_V[15:8]}};

assign p_Result_3_fu_110_p4 = {{weight_pack_V[15:8]}};

assign sext_ln1353_1_fu_203_p1 = $signed(add_ln1353_1_reg_242);

assign sext_ln1353_2_fu_212_p1 = $signed(add_ln1353_2_fu_206_p2);

assign sext_ln1353_fu_199_p1 = $signed(grp_fu_45_p2);

assign sext_ln68_10_fu_195_p1 = $signed(grp_fu_44_p2);

assign sext_ln68_1_fu_90_p1 = $signed(trunc_ln647_1_fu_86_p1);

assign sext_ln68_2_fu_105_p1 = $signed(p_Result_2_fu_95_p4);

assign sext_ln68_3_fu_120_p1 = $signed(p_Result_3_fu_110_p4);

assign sext_ln68_4_fu_179_p1 = $signed(p_Result_4_reg_222);

assign sext_ln68_5_fu_183_p1 = $signed(p_Result_5_reg_227);

assign sext_ln68_6_fu_187_p1 = $signed(p_Result_6_reg_232);

assign sext_ln68_7_fu_191_p1 = $signed(p_Result_7_reg_237);

assign sext_ln68_8_fu_165_p1 = $signed(grp_fu_44_p2);

assign sext_ln68_9_fu_169_p1 = $signed(grp_fu_45_p2);

assign sext_ln68_fu_81_p1 = $signed(trunc_ln647_fu_77_p1);

assign trunc_ln647_1_fu_86_p1 = weight_pack_V[7:0];

assign trunc_ln647_fu_77_p1 = act_pack_V[7:0];

endmodule //mac_pack4_delta
