-- ==============================================================
-- RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
-- Version: 2019.1
-- Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity CNN_ALU_Top is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    rs1_data_V : IN STD_LOGIC_VECTOR (31 downto 0);
    cnn_op_V : IN STD_LOGIC_VECTOR (3 downto 0);
    rd_data_V : OUT STD_LOGIC_VECTOR (31 downto 0) );
end;


architecture behav of CNN_ALU_Top is 
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "CNN_ALU_Top,hls_ip_2019_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=1,HLS_INPUT_PART=xc7z020-clg484-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=8.391000,HLS_SYN_LAT=3,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=8,HLS_SYN_FF=1236,HLS_SYN_LUT=1360,HLS_VERSION=2019_1}";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (7 downto 0) := "00000001";
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (7 downto 0) := "00000010";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (7 downto 0) := "00000100";
    constant ap_ST_fsm_state5 : STD_LOGIC_VECTOR (7 downto 0) := "00001000";
    constant ap_ST_fsm_pp1_stage0 : STD_LOGIC_VECTOR (7 downto 0) := "00010000";
    constant ap_ST_fsm_state8 : STD_LOGIC_VECTOR (7 downto 0) := "00100000";
    constant ap_ST_fsm_state9 : STD_LOGIC_VECTOR (7 downto 0) := "01000000";
    constant ap_ST_fsm_state10 : STD_LOGIC_VECTOR (7 downto 0) := "10000000";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv8_0 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    constant ap_const_lv7_0 : STD_LOGIC_VECTOR (6 downto 0) := "0000000";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv4_6 : STD_LOGIC_VECTOR (3 downto 0) := "0110";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv4_2 : STD_LOGIC_VECTOR (3 downto 0) := "0010";
    constant ap_const_lv19_0 : STD_LOGIC_VECTOR (18 downto 0) := "0000000000000000000";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv3_7 : STD_LOGIC_VECTOR (2 downto 0) := "111";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv3_1 : STD_LOGIC_VECTOR (2 downto 0) := "001";
    constant ap_const_lv3_2 : STD_LOGIC_VECTOR (2 downto 0) := "010";
    constant ap_const_lv3_3 : STD_LOGIC_VECTOR (2 downto 0) := "011";
    constant ap_const_lv3_4 : STD_LOGIC_VECTOR (2 downto 0) := "100";
    constant ap_const_lv3_5 : STD_LOGIC_VECTOR (2 downto 0) := "101";
    constant ap_const_lv3_6 : STD_LOGIC_VECTOR (2 downto 0) := "110";
    constant ap_const_lv7_4 : STD_LOGIC_VECTOR (6 downto 0) := "0000100";
    constant ap_const_lv7_8 : STD_LOGIC_VECTOR (6 downto 0) := "0001000";
    constant ap_const_lv7_C : STD_LOGIC_VECTOR (6 downto 0) := "0001100";
    constant ap_const_lv7_10 : STD_LOGIC_VECTOR (6 downto 0) := "0010000";
    constant ap_const_lv7_14 : STD_LOGIC_VECTOR (6 downto 0) := "0010100";
    constant ap_const_lv7_18 : STD_LOGIC_VECTOR (6 downto 0) := "0011000";
    constant ap_const_lv4_1 : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    constant ap_const_lv4_7 : STD_LOGIC_VECTOR (3 downto 0) := "0111";
    constant ap_const_lv4_8 : STD_LOGIC_VECTOR (3 downto 0) := "1000";
    constant ap_const_lv4_5 : STD_LOGIC_VECTOR (3 downto 0) := "0101";
    constant ap_const_lv4_4 : STD_LOGIC_VECTOR (3 downto 0) := "0100";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv32_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000101";
    constant ap_const_lv4_3 : STD_LOGIC_VECTOR (3 downto 0) := "0011";
    constant ap_const_lv32_8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001000";
    constant ap_const_lv32_F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001111";
    constant ap_const_lv32_10 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010000";
    constant ap_const_lv32_17 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010111";
    constant ap_const_lv32_18 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011000";
    constant ap_const_lv32_1F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011111";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";

    signal ap_CS_fsm : STD_LOGIC_VECTOR (7 downto 0) := "00000001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal weight_buf_V_0 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal weight_buf_V_1 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal weight_buf_V_2 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal weight_buf_V_3 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal weight_buf_V_4 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal weight_buf_V_5 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal weight_buf_V_6 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal weight_buf_V_7 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal weight_buf_V_8 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal weight_buf_V_9 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal weight_buf_V_10 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal weight_buf_V_11 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal weight_buf_V_12 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal weight_buf_V_13 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal weight_buf_V_14 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal weight_buf_V_15 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal weight_buf_V_16 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal weight_buf_V_17 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal weight_buf_V_18 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal weight_buf_V_19 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal weight_buf_V_20 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal weight_buf_V_21 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal weight_buf_V_22 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal weight_buf_V_23 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal weight_buf_V_24 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal act_buf_V_0 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal act_buf_V_1 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal act_buf_V_2 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal act_buf_V_3 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal act_buf_V_4 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal act_buf_V_5 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal act_buf_V_6 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal act_buf_V_7 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal act_buf_V_8 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal act_buf_V_9 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal act_buf_V_10 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal act_buf_V_11 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal act_buf_V_12 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal act_buf_V_13 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal act_buf_V_14 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal act_buf_V_15 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal act_buf_V_16 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal act_buf_V_17 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal act_buf_V_18 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal act_buf_V_19 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal act_buf_V_20 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal act_buf_V_21 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal act_buf_V_22 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal act_buf_V_23 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal act_buf_V_24 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal acc_reg_V : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal w_ptr : STD_LOGIC_VECTOR (6 downto 0) := "0000000";
    signal a_ptr : STD_LOGIC_VECTOR (6 downto 0) := "0000000";
    signal p_0217_0_i_reg_243 : STD_LOGIC_VECTOR (18 downto 0);
    signal p_0111_0_i_reg_255 : STD_LOGIC_VECTOR (18 downto 0);
    signal p_0107_0_i_reg_267 : STD_LOGIC_VECTOR (18 downto 0);
    signal p_0103_0_i_reg_279 : STD_LOGIC_VECTOR (18 downto 0);
    signal i_0_i_reg_291 : STD_LOGIC_VECTOR (3 downto 0);
    signal p_0217_0_i163_reg_325 : STD_LOGIC_VECTOR (18 downto 0);
    signal p_0111_0_i164_reg_337 : STD_LOGIC_VECTOR (18 downto 0);
    signal p_0107_0_i165_reg_349 : STD_LOGIC_VECTOR (18 downto 0);
    signal p_0103_0_i166_reg_361 : STD_LOGIC_VECTOR (18 downto 0);
    signal i_0_i167_reg_373 : STD_LOGIC_VECTOR (3 downto 0);
    signal cnn_op_V_read_read_fu_224_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal weight_buf_V_0_load_reg_1752 : STD_LOGIC_VECTOR (7 downto 0);
    signal weight_buf_V_1_load_reg_1758 : STD_LOGIC_VECTOR (7 downto 0);
    signal weight_buf_V_2_load_reg_1764 : STD_LOGIC_VECTOR (7 downto 0);
    signal weight_buf_V_3_load_reg_1770 : STD_LOGIC_VECTOR (7 downto 0);
    signal weight_buf_V_4_load_reg_1776 : STD_LOGIC_VECTOR (7 downto 0);
    signal weight_buf_V_5_load_reg_1782 : STD_LOGIC_VECTOR (7 downto 0);
    signal weight_buf_V_6_load_reg_1788 : STD_LOGIC_VECTOR (7 downto 0);
    signal weight_buf_V_7_load_reg_1794 : STD_LOGIC_VECTOR (7 downto 0);
    signal weight_buf_V_8_load_reg_1800 : STD_LOGIC_VECTOR (7 downto 0);
    signal weight_buf_V_9_load_reg_1806 : STD_LOGIC_VECTOR (7 downto 0);
    signal weight_buf_V_10_load_reg_1812 : STD_LOGIC_VECTOR (7 downto 0);
    signal weight_buf_V_11_load_reg_1818 : STD_LOGIC_VECTOR (7 downto 0);
    signal weight_buf_V_12_load_reg_1824 : STD_LOGIC_VECTOR (7 downto 0);
    signal weight_buf_V_13_load_reg_1830 : STD_LOGIC_VECTOR (7 downto 0);
    signal weight_buf_V_14_load_reg_1836 : STD_LOGIC_VECTOR (7 downto 0);
    signal weight_buf_V_15_load_reg_1842 : STD_LOGIC_VECTOR (7 downto 0);
    signal weight_buf_V_16_load_reg_1848 : STD_LOGIC_VECTOR (7 downto 0);
    signal weight_buf_V_17_load_reg_1854 : STD_LOGIC_VECTOR (7 downto 0);
    signal weight_buf_V_18_load_reg_1860 : STD_LOGIC_VECTOR (7 downto 0);
    signal weight_buf_V_19_load_reg_1866 : STD_LOGIC_VECTOR (7 downto 0);
    signal weight_buf_V_20_load_reg_1872 : STD_LOGIC_VECTOR (7 downto 0);
    signal weight_buf_V_21_load_reg_1878 : STD_LOGIC_VECTOR (7 downto 0);
    signal weight_buf_V_22_load_reg_1884 : STD_LOGIC_VECTOR (7 downto 0);
    signal weight_buf_V_23_load_reg_1890 : STD_LOGIC_VECTOR (7 downto 0);
    signal weight_buf_V_24_load_reg_1896 : STD_LOGIC_VECTOR (7 downto 0);
    signal act_buf_V_0_load_reg_1902 : STD_LOGIC_VECTOR (7 downto 0);
    signal act_buf_V_1_load_reg_1908 : STD_LOGIC_VECTOR (7 downto 0);
    signal act_buf_V_2_load_reg_1914 : STD_LOGIC_VECTOR (7 downto 0);
    signal act_buf_V_3_load_reg_1920 : STD_LOGIC_VECTOR (7 downto 0);
    signal act_buf_V_4_load_reg_1926 : STD_LOGIC_VECTOR (7 downto 0);
    signal act_buf_V_5_load_reg_1932 : STD_LOGIC_VECTOR (7 downto 0);
    signal act_buf_V_6_load_reg_1938 : STD_LOGIC_VECTOR (7 downto 0);
    signal act_buf_V_7_load_reg_1944 : STD_LOGIC_VECTOR (7 downto 0);
    signal act_buf_V_8_load_reg_1950 : STD_LOGIC_VECTOR (7 downto 0);
    signal act_buf_V_9_load_reg_1956 : STD_LOGIC_VECTOR (7 downto 0);
    signal act_buf_V_10_load_reg_1962 : STD_LOGIC_VECTOR (7 downto 0);
    signal act_buf_V_11_load_reg_1968 : STD_LOGIC_VECTOR (7 downto 0);
    signal act_buf_V_12_load_reg_1974 : STD_LOGIC_VECTOR (7 downto 0);
    signal act_buf_V_13_load_reg_1980 : STD_LOGIC_VECTOR (7 downto 0);
    signal act_buf_V_14_load_reg_1986 : STD_LOGIC_VECTOR (7 downto 0);
    signal act_buf_V_15_load_reg_1992 : STD_LOGIC_VECTOR (7 downto 0);
    signal act_buf_V_16_load_reg_1998 : STD_LOGIC_VECTOR (7 downto 0);
    signal act_buf_V_17_load_reg_2004 : STD_LOGIC_VECTOR (7 downto 0);
    signal act_buf_V_18_load_reg_2010 : STD_LOGIC_VECTOR (7 downto 0);
    signal act_buf_V_19_load_reg_2016 : STD_LOGIC_VECTOR (7 downto 0);
    signal act_buf_V_20_load_reg_2022 : STD_LOGIC_VECTOR (7 downto 0);
    signal act_buf_V_21_load_reg_2028 : STD_LOGIC_VECTOR (7 downto 0);
    signal act_buf_V_22_load_reg_2034 : STD_LOGIC_VECTOR (7 downto 0);
    signal act_buf_V_23_load_reg_2040 : STD_LOGIC_VECTOR (7 downto 0);
    signal act_buf_V_24_load_reg_2046 : STD_LOGIC_VECTOR (7 downto 0);
    signal acc_reg_V_load_reg_2052 : STD_LOGIC_VECTOR (31 downto 0);
    signal icmp_ln107_1_fu_1168_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln107_1_reg_2066 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_block_state2_pp0_stage0_iter0 : BOOLEAN;
    signal ap_block_state3_pp0_stage0_iter1 : BOOLEAN;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal i_1_fu_1174_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC := '0';
    signal trunc_ln68_1_fu_1180_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal phi_ln68_3_fu_1192_p34 : STD_LOGIC_VECTOR (7 downto 0);
    signal phi_ln68_3_reg_2079 : STD_LOGIC_VECTOR (7 downto 0);
    signal phi_ln68_5_fu_1255_p10 : STD_LOGIC_VECTOR (7 downto 0);
    signal phi_ln68_5_reg_2084 : STD_LOGIC_VECTOR (7 downto 0);
    signal phi_ln68_7_fu_1271_p10 : STD_LOGIC_VECTOR (7 downto 0);
    signal phi_ln68_7_reg_2089 : STD_LOGIC_VECTOR (7 downto 0);
    signal phi_ln68_9_fu_1287_p10 : STD_LOGIC_VECTOR (7 downto 0);
    signal phi_ln68_9_reg_2094 : STD_LOGIC_VECTOR (7 downto 0);
    signal phi_ln68_11_fu_1303_p10 : STD_LOGIC_VECTOR (7 downto 0);
    signal phi_ln68_11_reg_2099 : STD_LOGIC_VECTOR (7 downto 0);
    signal phi_ln68_13_fu_1319_p10 : STD_LOGIC_VECTOR (7 downto 0);
    signal phi_ln68_13_reg_2104 : STD_LOGIC_VECTOR (7 downto 0);
    signal phi_ln68_14_fu_1335_p10 : STD_LOGIC_VECTOR (7 downto 0);
    signal phi_ln68_14_reg_2109 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_fu_1684_p3 : STD_LOGIC_VECTOR (18 downto 0);
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal grp_fu_1692_p3 : STD_LOGIC_VECTOR (18 downto 0);
    signal grp_fu_1700_p3 : STD_LOGIC_VECTOR (18 downto 0);
    signal grp_fu_1708_p3 : STD_LOGIC_VECTOR (18 downto 0);
    signal add_ln700_1_fu_1413_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln700_1_reg_2134 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal icmp_ln107_fu_1424_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln107_reg_2139 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_pp1_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp1_stage0 : signal is "none";
    signal ap_block_state6_pp1_stage0_iter0 : BOOLEAN;
    signal ap_block_state7_pp1_stage0_iter1 : BOOLEAN;
    signal ap_block_pp1_stage0_11001 : BOOLEAN;
    signal i_fu_1430_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_enable_reg_pp1_iter0 : STD_LOGIC := '0';
    signal trunc_ln68_fu_1436_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal phi_ln68_2_fu_1448_p34 : STD_LOGIC_VECTOR (7 downto 0);
    signal phi_ln68_2_reg_2152 : STD_LOGIC_VECTOR (7 downto 0);
    signal phi_ln68_4_fu_1511_p10 : STD_LOGIC_VECTOR (7 downto 0);
    signal phi_ln68_4_reg_2157 : STD_LOGIC_VECTOR (7 downto 0);
    signal phi_ln68_6_fu_1527_p10 : STD_LOGIC_VECTOR (7 downto 0);
    signal phi_ln68_6_reg_2162 : STD_LOGIC_VECTOR (7 downto 0);
    signal phi_ln68_8_fu_1543_p10 : STD_LOGIC_VECTOR (7 downto 0);
    signal phi_ln68_8_reg_2167 : STD_LOGIC_VECTOR (7 downto 0);
    signal phi_ln68_s_fu_1559_p10 : STD_LOGIC_VECTOR (7 downto 0);
    signal phi_ln68_s_reg_2172 : STD_LOGIC_VECTOR (7 downto 0);
    signal phi_ln68_10_fu_1575_p10 : STD_LOGIC_VECTOR (7 downto 0);
    signal phi_ln68_10_reg_2177 : STD_LOGIC_VECTOR (7 downto 0);
    signal phi_ln68_12_fu_1591_p10 : STD_LOGIC_VECTOR (7 downto 0);
    signal phi_ln68_12_reg_2182 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_fu_1716_p3 : STD_LOGIC_VECTOR (18 downto 0);
    signal ap_enable_reg_pp1_iter1 : STD_LOGIC := '0';
    signal grp_fu_1724_p3 : STD_LOGIC_VECTOR (18 downto 0);
    signal grp_fu_1732_p3 : STD_LOGIC_VECTOR (18 downto 0);
    signal grp_fu_1740_p3 : STD_LOGIC_VECTOR (18 downto 0);
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal ap_condition_pp0_exit_iter0_state2 : STD_LOGIC;
    signal ap_block_pp1_stage0_subdone : BOOLEAN;
    signal ap_condition_pp1_exit_iter0_state6 : STD_LOGIC;
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal ap_phi_reg_pp0_iter0_phi_ln68_1_reg_302 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_reg_pp0_iter1_phi_ln68_1_reg_302 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_block_pp1_stage0 : BOOLEAN;
    signal ap_phi_reg_pp1_iter0_phi_ln68_reg_384 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_reg_pp1_iter1_phi_ln68_reg_384 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln647_fu_1134_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal w_ptr_load_load_fu_950_p1 : STD_LOGIC_VECTOR (6 downto 0);
    signal trunc_ln647_1_fu_1100_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln647_2_fu_1066_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln647_3_fu_1032_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln647_4_fu_998_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln647_5_fu_964_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln647_6_fu_954_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln647_7_fu_916_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal a_ptr_load_load_fu_732_p1 : STD_LOGIC_VECTOR (6 downto 0);
    signal trunc_ln647_8_fu_882_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln647_9_fu_848_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln647_10_fu_814_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln647_11_fu_780_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln647_12_fu_746_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln647_13_fu_736_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_2_fu_660_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln700_fu_668_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal sext_ln68_fu_722_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state5 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state5 : signal is "none";
    signal sext_ln68_3_fu_1674_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state8 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state8 : signal is "none";
    signal rd_data_V_preg : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal icmp_ln895_fu_680_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln895_1_fu_694_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal max1_V_fu_686_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal max2_V_fu_700_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal icmp_ln895_2_fu_708_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal final_max_V_fu_714_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal phi_ln68_3_fu_1192_p33 : STD_LOGIC_VECTOR (4 downto 0);
    signal sext_ln107_6_fu_1384_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal sext_ln107_5_fu_1380_p1 : STD_LOGIC_VECTOR (19 downto 0);
    signal sext_ln107_4_fu_1376_p1 : STD_LOGIC_VECTOR (19 downto 0);
    signal add_ln700_3_fu_1397_p2 : STD_LOGIC_VECTOR (19 downto 0);
    signal sext_ln107_7_fu_1388_p1 : STD_LOGIC_VECTOR (19 downto 0);
    signal add_ln700_4_fu_1403_p2 : STD_LOGIC_VECTOR (19 downto 0);
    signal sext_ln700_fu_1409_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln700_2_fu_1392_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal phi_ln68_2_fu_1448_p33 : STD_LOGIC_VECTOR (4 downto 0);
    signal sext_ln107_2_fu_1640_p1 : STD_LOGIC_VECTOR (19 downto 0);
    signal sext_ln107_3_fu_1644_p1 : STD_LOGIC_VECTOR (19 downto 0);
    signal add_ln68_fu_1648_p2 : STD_LOGIC_VECTOR (19 downto 0);
    signal sext_ln107_1_fu_1636_p1 : STD_LOGIC_VECTOR (19 downto 0);
    signal sext_ln107_fu_1632_p1 : STD_LOGIC_VECTOR (19 downto 0);
    signal add_ln68_1_fu_1658_p2 : STD_LOGIC_VECTOR (19 downto 0);
    signal sext_ln68_2_fu_1664_p1 : STD_LOGIC_VECTOR (20 downto 0);
    signal sext_ln68_1_fu_1654_p1 : STD_LOGIC_VECTOR (20 downto 0);
    signal add_ln68_2_fu_1668_p2 : STD_LOGIC_VECTOR (20 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_idle_pp1 : STD_LOGIC;
    signal ap_enable_pp1 : STD_LOGIC;
    signal ap_condition_235 : BOOLEAN;
    signal ap_condition_294 : BOOLEAN;

    component CNN_ALU_Top_mux_3bkb IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        din2_WIDTH : INTEGER;
        din3_WIDTH : INTEGER;
        din4_WIDTH : INTEGER;
        din5_WIDTH : INTEGER;
        din6_WIDTH : INTEGER;
        din7_WIDTH : INTEGER;
        din8_WIDTH : INTEGER;
        din9_WIDTH : INTEGER;
        din10_WIDTH : INTEGER;
        din11_WIDTH : INTEGER;
        din12_WIDTH : INTEGER;
        din13_WIDTH : INTEGER;
        din14_WIDTH : INTEGER;
        din15_WIDTH : INTEGER;
        din16_WIDTH : INTEGER;
        din17_WIDTH : INTEGER;
        din18_WIDTH : INTEGER;
        din19_WIDTH : INTEGER;
        din20_WIDTH : INTEGER;
        din21_WIDTH : INTEGER;
        din22_WIDTH : INTEGER;
        din23_WIDTH : INTEGER;
        din24_WIDTH : INTEGER;
        din25_WIDTH : INTEGER;
        din26_WIDTH : INTEGER;
        din27_WIDTH : INTEGER;
        din28_WIDTH : INTEGER;
        din29_WIDTH : INTEGER;
        din30_WIDTH : INTEGER;
        din31_WIDTH : INTEGER;
        din32_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (7 downto 0);
        din1 : IN STD_LOGIC_VECTOR (7 downto 0);
        din2 : IN STD_LOGIC_VECTOR (7 downto 0);
        din3 : IN STD_LOGIC_VECTOR (7 downto 0);
        din4 : IN STD_LOGIC_VECTOR (7 downto 0);
        din5 : IN STD_LOGIC_VECTOR (7 downto 0);
        din6 : IN STD_LOGIC_VECTOR (7 downto 0);
        din7 : IN STD_LOGIC_VECTOR (7 downto 0);
        din8 : IN STD_LOGIC_VECTOR (7 downto 0);
        din9 : IN STD_LOGIC_VECTOR (7 downto 0);
        din10 : IN STD_LOGIC_VECTOR (7 downto 0);
        din11 : IN STD_LOGIC_VECTOR (7 downto 0);
        din12 : IN STD_LOGIC_VECTOR (7 downto 0);
        din13 : IN STD_LOGIC_VECTOR (7 downto 0);
        din14 : IN STD_LOGIC_VECTOR (7 downto 0);
        din15 : IN STD_LOGIC_VECTOR (7 downto 0);
        din16 : IN STD_LOGIC_VECTOR (7 downto 0);
        din17 : IN STD_LOGIC_VECTOR (7 downto 0);
        din18 : IN STD_LOGIC_VECTOR (7 downto 0);
        din19 : IN STD_LOGIC_VECTOR (7 downto 0);
        din20 : IN STD_LOGIC_VECTOR (7 downto 0);
        din21 : IN STD_LOGIC_VECTOR (7 downto 0);
        din22 : IN STD_LOGIC_VECTOR (7 downto 0);
        din23 : IN STD_LOGIC_VECTOR (7 downto 0);
        din24 : IN STD_LOGIC_VECTOR (7 downto 0);
        din25 : IN STD_LOGIC_VECTOR (7 downto 0);
        din26 : IN STD_LOGIC_VECTOR (7 downto 0);
        din27 : IN STD_LOGIC_VECTOR (7 downto 0);
        din28 : IN STD_LOGIC_VECTOR (7 downto 0);
        din29 : IN STD_LOGIC_VECTOR (7 downto 0);
        din30 : IN STD_LOGIC_VECTOR (7 downto 0);
        din31 : IN STD_LOGIC_VECTOR (7 downto 0);
        din32 : IN STD_LOGIC_VECTOR (4 downto 0);
        dout : OUT STD_LOGIC_VECTOR (7 downto 0) );
    end component;


    component CNN_ALU_Top_mux_8cud IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        din2_WIDTH : INTEGER;
        din3_WIDTH : INTEGER;
        din4_WIDTH : INTEGER;
        din5_WIDTH : INTEGER;
        din6_WIDTH : INTEGER;
        din7_WIDTH : INTEGER;
        din8_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (7 downto 0);
        din1 : IN STD_LOGIC_VECTOR (7 downto 0);
        din2 : IN STD_LOGIC_VECTOR (7 downto 0);
        din3 : IN STD_LOGIC_VECTOR (7 downto 0);
        din4 : IN STD_LOGIC_VECTOR (7 downto 0);
        din5 : IN STD_LOGIC_VECTOR (7 downto 0);
        din6 : IN STD_LOGIC_VECTOR (7 downto 0);
        din7 : IN STD_LOGIC_VECTOR (7 downto 0);
        din8 : IN STD_LOGIC_VECTOR (2 downto 0);
        dout : OUT STD_LOGIC_VECTOR (7 downto 0) );
    end component;


    component CNN_ALU_Top_mac_mdEe IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        din2_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (7 downto 0);
        din1 : IN STD_LOGIC_VECTOR (7 downto 0);
        din2 : IN STD_LOGIC_VECTOR (18 downto 0);
        dout : OUT STD_LOGIC_VECTOR (18 downto 0) );
    end component;



begin
    CNN_ALU_Top_mux_3bkb_U1 : component CNN_ALU_Top_mux_3bkb
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 8,
        din1_WIDTH => 8,
        din2_WIDTH => 8,
        din3_WIDTH => 8,
        din4_WIDTH => 8,
        din5_WIDTH => 8,
        din6_WIDTH => 8,
        din7_WIDTH => 8,
        din8_WIDTH => 8,
        din9_WIDTH => 8,
        din10_WIDTH => 8,
        din11_WIDTH => 8,
        din12_WIDTH => 8,
        din13_WIDTH => 8,
        din14_WIDTH => 8,
        din15_WIDTH => 8,
        din16_WIDTH => 8,
        din17_WIDTH => 8,
        din18_WIDTH => 8,
        din19_WIDTH => 8,
        din20_WIDTH => 8,
        din21_WIDTH => 8,
        din22_WIDTH => 8,
        din23_WIDTH => 8,
        din24_WIDTH => 8,
        din25_WIDTH => 8,
        din26_WIDTH => 8,
        din27_WIDTH => 8,
        din28_WIDTH => 8,
        din29_WIDTH => 8,
        din30_WIDTH => 8,
        din31_WIDTH => 8,
        din32_WIDTH => 5,
        dout_WIDTH => 8)
    port map (
        din0 => weight_buf_V_0_load_reg_1752,
        din1 => ap_const_lv8_0,
        din2 => ap_const_lv8_0,
        din3 => ap_const_lv8_0,
        din4 => weight_buf_V_4_load_reg_1776,
        din5 => ap_const_lv8_0,
        din6 => ap_const_lv8_0,
        din7 => ap_const_lv8_0,
        din8 => weight_buf_V_8_load_reg_1800,
        din9 => ap_const_lv8_0,
        din10 => ap_const_lv8_0,
        din11 => ap_const_lv8_0,
        din12 => weight_buf_V_12_load_reg_1824,
        din13 => ap_const_lv8_0,
        din14 => ap_const_lv8_0,
        din15 => ap_const_lv8_0,
        din16 => weight_buf_V_16_load_reg_1848,
        din17 => ap_const_lv8_0,
        din18 => ap_const_lv8_0,
        din19 => ap_const_lv8_0,
        din20 => weight_buf_V_20_load_reg_1872,
        din21 => ap_const_lv8_0,
        din22 => ap_const_lv8_0,
        din23 => ap_const_lv8_0,
        din24 => weight_buf_V_24_load_reg_1896,
        din25 => ap_const_lv8_0,
        din26 => ap_const_lv8_0,
        din27 => ap_const_lv8_0,
        din28 => ap_const_lv8_0,
        din29 => ap_const_lv8_0,
        din30 => ap_const_lv8_0,
        din31 => ap_const_lv8_0,
        din32 => phi_ln68_3_fu_1192_p33,
        dout => phi_ln68_3_fu_1192_p34);

    CNN_ALU_Top_mux_8cud_U2 : component CNN_ALU_Top_mux_8cud
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 8,
        din1_WIDTH => 8,
        din2_WIDTH => 8,
        din3_WIDTH => 8,
        din4_WIDTH => 8,
        din5_WIDTH => 8,
        din6_WIDTH => 8,
        din7_WIDTH => 8,
        din8_WIDTH => 3,
        dout_WIDTH => 8)
    port map (
        din0 => act_buf_V_1_load_reg_1908,
        din1 => act_buf_V_5_load_reg_1932,
        din2 => act_buf_V_9_load_reg_1956,
        din3 => act_buf_V_13_load_reg_1980,
        din4 => act_buf_V_17_load_reg_2004,
        din5 => act_buf_V_21_load_reg_2028,
        din6 => ap_const_lv8_0,
        din7 => ap_const_lv8_0,
        din8 => trunc_ln68_1_fu_1180_p1,
        dout => phi_ln68_5_fu_1255_p10);

    CNN_ALU_Top_mux_8cud_U3 : component CNN_ALU_Top_mux_8cud
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 8,
        din1_WIDTH => 8,
        din2_WIDTH => 8,
        din3_WIDTH => 8,
        din4_WIDTH => 8,
        din5_WIDTH => 8,
        din6_WIDTH => 8,
        din7_WIDTH => 8,
        din8_WIDTH => 3,
        dout_WIDTH => 8)
    port map (
        din0 => weight_buf_V_1_load_reg_1758,
        din1 => weight_buf_V_5_load_reg_1782,
        din2 => weight_buf_V_9_load_reg_1806,
        din3 => weight_buf_V_13_load_reg_1830,
        din4 => weight_buf_V_17_load_reg_1854,
        din5 => weight_buf_V_21_load_reg_1878,
        din6 => ap_const_lv8_0,
        din7 => ap_const_lv8_0,
        din8 => trunc_ln68_1_fu_1180_p1,
        dout => phi_ln68_7_fu_1271_p10);

    CNN_ALU_Top_mux_8cud_U4 : component CNN_ALU_Top_mux_8cud
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 8,
        din1_WIDTH => 8,
        din2_WIDTH => 8,
        din3_WIDTH => 8,
        din4_WIDTH => 8,
        din5_WIDTH => 8,
        din6_WIDTH => 8,
        din7_WIDTH => 8,
        din8_WIDTH => 3,
        dout_WIDTH => 8)
    port map (
        din0 => act_buf_V_2_load_reg_1914,
        din1 => act_buf_V_6_load_reg_1938,
        din2 => act_buf_V_10_load_reg_1962,
        din3 => act_buf_V_14_load_reg_1986,
        din4 => act_buf_V_18_load_reg_2010,
        din5 => act_buf_V_22_load_reg_2034,
        din6 => ap_const_lv8_0,
        din7 => ap_const_lv8_0,
        din8 => trunc_ln68_1_fu_1180_p1,
        dout => phi_ln68_9_fu_1287_p10);

    CNN_ALU_Top_mux_8cud_U5 : component CNN_ALU_Top_mux_8cud
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 8,
        din1_WIDTH => 8,
        din2_WIDTH => 8,
        din3_WIDTH => 8,
        din4_WIDTH => 8,
        din5_WIDTH => 8,
        din6_WIDTH => 8,
        din7_WIDTH => 8,
        din8_WIDTH => 3,
        dout_WIDTH => 8)
    port map (
        din0 => weight_buf_V_2_load_reg_1764,
        din1 => weight_buf_V_6_load_reg_1788,
        din2 => weight_buf_V_10_load_reg_1812,
        din3 => weight_buf_V_14_load_reg_1836,
        din4 => weight_buf_V_18_load_reg_1860,
        din5 => weight_buf_V_22_load_reg_1884,
        din6 => ap_const_lv8_0,
        din7 => ap_const_lv8_0,
        din8 => trunc_ln68_1_fu_1180_p1,
        dout => phi_ln68_11_fu_1303_p10);

    CNN_ALU_Top_mux_8cud_U6 : component CNN_ALU_Top_mux_8cud
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 8,
        din1_WIDTH => 8,
        din2_WIDTH => 8,
        din3_WIDTH => 8,
        din4_WIDTH => 8,
        din5_WIDTH => 8,
        din6_WIDTH => 8,
        din7_WIDTH => 8,
        din8_WIDTH => 3,
        dout_WIDTH => 8)
    port map (
        din0 => act_buf_V_3_load_reg_1920,
        din1 => act_buf_V_7_load_reg_1944,
        din2 => act_buf_V_11_load_reg_1968,
        din3 => act_buf_V_15_load_reg_1992,
        din4 => act_buf_V_19_load_reg_2016,
        din5 => act_buf_V_23_load_reg_2040,
        din6 => ap_const_lv8_0,
        din7 => ap_const_lv8_0,
        din8 => trunc_ln68_1_fu_1180_p1,
        dout => phi_ln68_13_fu_1319_p10);

    CNN_ALU_Top_mux_8cud_U7 : component CNN_ALU_Top_mux_8cud
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 8,
        din1_WIDTH => 8,
        din2_WIDTH => 8,
        din3_WIDTH => 8,
        din4_WIDTH => 8,
        din5_WIDTH => 8,
        din6_WIDTH => 8,
        din7_WIDTH => 8,
        din8_WIDTH => 3,
        dout_WIDTH => 8)
    port map (
        din0 => weight_buf_V_3_load_reg_1770,
        din1 => weight_buf_V_7_load_reg_1794,
        din2 => weight_buf_V_11_load_reg_1818,
        din3 => weight_buf_V_15_load_reg_1842,
        din4 => weight_buf_V_19_load_reg_1866,
        din5 => weight_buf_V_23_load_reg_1890,
        din6 => ap_const_lv8_0,
        din7 => ap_const_lv8_0,
        din8 => trunc_ln68_1_fu_1180_p1,
        dout => phi_ln68_14_fu_1335_p10);

    CNN_ALU_Top_mux_3bkb_U8 : component CNN_ALU_Top_mux_3bkb
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 8,
        din1_WIDTH => 8,
        din2_WIDTH => 8,
        din3_WIDTH => 8,
        din4_WIDTH => 8,
        din5_WIDTH => 8,
        din6_WIDTH => 8,
        din7_WIDTH => 8,
        din8_WIDTH => 8,
        din9_WIDTH => 8,
        din10_WIDTH => 8,
        din11_WIDTH => 8,
        din12_WIDTH => 8,
        din13_WIDTH => 8,
        din14_WIDTH => 8,
        din15_WIDTH => 8,
        din16_WIDTH => 8,
        din17_WIDTH => 8,
        din18_WIDTH => 8,
        din19_WIDTH => 8,
        din20_WIDTH => 8,
        din21_WIDTH => 8,
        din22_WIDTH => 8,
        din23_WIDTH => 8,
        din24_WIDTH => 8,
        din25_WIDTH => 8,
        din26_WIDTH => 8,
        din27_WIDTH => 8,
        din28_WIDTH => 8,
        din29_WIDTH => 8,
        din30_WIDTH => 8,
        din31_WIDTH => 8,
        din32_WIDTH => 5,
        dout_WIDTH => 8)
    port map (
        din0 => weight_buf_V_0_load_reg_1752,
        din1 => ap_const_lv8_0,
        din2 => ap_const_lv8_0,
        din3 => ap_const_lv8_0,
        din4 => weight_buf_V_4_load_reg_1776,
        din5 => ap_const_lv8_0,
        din6 => ap_const_lv8_0,
        din7 => ap_const_lv8_0,
        din8 => weight_buf_V_8_load_reg_1800,
        din9 => ap_const_lv8_0,
        din10 => ap_const_lv8_0,
        din11 => ap_const_lv8_0,
        din12 => weight_buf_V_12_load_reg_1824,
        din13 => ap_const_lv8_0,
        din14 => ap_const_lv8_0,
        din15 => ap_const_lv8_0,
        din16 => weight_buf_V_16_load_reg_1848,
        din17 => ap_const_lv8_0,
        din18 => ap_const_lv8_0,
        din19 => ap_const_lv8_0,
        din20 => weight_buf_V_20_load_reg_1872,
        din21 => ap_const_lv8_0,
        din22 => ap_const_lv8_0,
        din23 => ap_const_lv8_0,
        din24 => weight_buf_V_24_load_reg_1896,
        din25 => ap_const_lv8_0,
        din26 => ap_const_lv8_0,
        din27 => ap_const_lv8_0,
        din28 => ap_const_lv8_0,
        din29 => ap_const_lv8_0,
        din30 => ap_const_lv8_0,
        din31 => ap_const_lv8_0,
        din32 => phi_ln68_2_fu_1448_p33,
        dout => phi_ln68_2_fu_1448_p34);

    CNN_ALU_Top_mux_8cud_U9 : component CNN_ALU_Top_mux_8cud
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 8,
        din1_WIDTH => 8,
        din2_WIDTH => 8,
        din3_WIDTH => 8,
        din4_WIDTH => 8,
        din5_WIDTH => 8,
        din6_WIDTH => 8,
        din7_WIDTH => 8,
        din8_WIDTH => 3,
        dout_WIDTH => 8)
    port map (
        din0 => act_buf_V_1_load_reg_1908,
        din1 => act_buf_V_5_load_reg_1932,
        din2 => act_buf_V_9_load_reg_1956,
        din3 => act_buf_V_13_load_reg_1980,
        din4 => act_buf_V_17_load_reg_2004,
        din5 => act_buf_V_21_load_reg_2028,
        din6 => ap_const_lv8_0,
        din7 => ap_const_lv8_0,
        din8 => trunc_ln68_fu_1436_p1,
        dout => phi_ln68_4_fu_1511_p10);

    CNN_ALU_Top_mux_8cud_U10 : component CNN_ALU_Top_mux_8cud
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 8,
        din1_WIDTH => 8,
        din2_WIDTH => 8,
        din3_WIDTH => 8,
        din4_WIDTH => 8,
        din5_WIDTH => 8,
        din6_WIDTH => 8,
        din7_WIDTH => 8,
        din8_WIDTH => 3,
        dout_WIDTH => 8)
    port map (
        din0 => weight_buf_V_1_load_reg_1758,
        din1 => weight_buf_V_5_load_reg_1782,
        din2 => weight_buf_V_9_load_reg_1806,
        din3 => weight_buf_V_13_load_reg_1830,
        din4 => weight_buf_V_17_load_reg_1854,
        din5 => weight_buf_V_21_load_reg_1878,
        din6 => ap_const_lv8_0,
        din7 => ap_const_lv8_0,
        din8 => trunc_ln68_fu_1436_p1,
        dout => phi_ln68_6_fu_1527_p10);

    CNN_ALU_Top_mux_8cud_U11 : component CNN_ALU_Top_mux_8cud
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 8,
        din1_WIDTH => 8,
        din2_WIDTH => 8,
        din3_WIDTH => 8,
        din4_WIDTH => 8,
        din5_WIDTH => 8,
        din6_WIDTH => 8,
        din7_WIDTH => 8,
        din8_WIDTH => 3,
        dout_WIDTH => 8)
    port map (
        din0 => act_buf_V_2_load_reg_1914,
        din1 => act_buf_V_6_load_reg_1938,
        din2 => act_buf_V_10_load_reg_1962,
        din3 => act_buf_V_14_load_reg_1986,
        din4 => act_buf_V_18_load_reg_2010,
        din5 => act_buf_V_22_load_reg_2034,
        din6 => ap_const_lv8_0,
        din7 => ap_const_lv8_0,
        din8 => trunc_ln68_fu_1436_p1,
        dout => phi_ln68_8_fu_1543_p10);

    CNN_ALU_Top_mux_8cud_U12 : component CNN_ALU_Top_mux_8cud
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 8,
        din1_WIDTH => 8,
        din2_WIDTH => 8,
        din3_WIDTH => 8,
        din4_WIDTH => 8,
        din5_WIDTH => 8,
        din6_WIDTH => 8,
        din7_WIDTH => 8,
        din8_WIDTH => 3,
        dout_WIDTH => 8)
    port map (
        din0 => weight_buf_V_2_load_reg_1764,
        din1 => weight_buf_V_6_load_reg_1788,
        din2 => weight_buf_V_10_load_reg_1812,
        din3 => weight_buf_V_14_load_reg_1836,
        din4 => weight_buf_V_18_load_reg_1860,
        din5 => weight_buf_V_22_load_reg_1884,
        din6 => ap_const_lv8_0,
        din7 => ap_const_lv8_0,
        din8 => trunc_ln68_fu_1436_p1,
        dout => phi_ln68_s_fu_1559_p10);

    CNN_ALU_Top_mux_8cud_U13 : component CNN_ALU_Top_mux_8cud
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 8,
        din1_WIDTH => 8,
        din2_WIDTH => 8,
        din3_WIDTH => 8,
        din4_WIDTH => 8,
        din5_WIDTH => 8,
        din6_WIDTH => 8,
        din7_WIDTH => 8,
        din8_WIDTH => 3,
        dout_WIDTH => 8)
    port map (
        din0 => act_buf_V_3_load_reg_1920,
        din1 => act_buf_V_7_load_reg_1944,
        din2 => act_buf_V_11_load_reg_1968,
        din3 => act_buf_V_15_load_reg_1992,
        din4 => act_buf_V_19_load_reg_2016,
        din5 => act_buf_V_23_load_reg_2040,
        din6 => ap_const_lv8_0,
        din7 => ap_const_lv8_0,
        din8 => trunc_ln68_fu_1436_p1,
        dout => phi_ln68_10_fu_1575_p10);

    CNN_ALU_Top_mux_8cud_U14 : component CNN_ALU_Top_mux_8cud
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 8,
        din1_WIDTH => 8,
        din2_WIDTH => 8,
        din3_WIDTH => 8,
        din4_WIDTH => 8,
        din5_WIDTH => 8,
        din6_WIDTH => 8,
        din7_WIDTH => 8,
        din8_WIDTH => 3,
        dout_WIDTH => 8)
    port map (
        din0 => weight_buf_V_3_load_reg_1770,
        din1 => weight_buf_V_7_load_reg_1794,
        din2 => weight_buf_V_11_load_reg_1818,
        din3 => weight_buf_V_15_load_reg_1842,
        din4 => weight_buf_V_19_load_reg_1866,
        din5 => weight_buf_V_23_load_reg_1890,
        din6 => ap_const_lv8_0,
        din7 => ap_const_lv8_0,
        din8 => trunc_ln68_fu_1436_p1,
        dout => phi_ln68_12_fu_1591_p10);

    CNN_ALU_Top_mac_mdEe_U15 : component CNN_ALU_Top_mac_mdEe
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 8,
        din1_WIDTH => 8,
        din2_WIDTH => 19,
        dout_WIDTH => 19)
    port map (
        din0 => ap_phi_reg_pp0_iter1_phi_ln68_1_reg_302,
        din1 => phi_ln68_3_reg_2079,
        din2 => p_0217_0_i_reg_243,
        dout => grp_fu_1684_p3);

    CNN_ALU_Top_mac_mdEe_U16 : component CNN_ALU_Top_mac_mdEe
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 8,
        din1_WIDTH => 8,
        din2_WIDTH => 19,
        dout_WIDTH => 19)
    port map (
        din0 => phi_ln68_5_reg_2084,
        din1 => phi_ln68_7_reg_2089,
        din2 => p_0111_0_i_reg_255,
        dout => grp_fu_1692_p3);

    CNN_ALU_Top_mac_mdEe_U17 : component CNN_ALU_Top_mac_mdEe
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 8,
        din1_WIDTH => 8,
        din2_WIDTH => 19,
        dout_WIDTH => 19)
    port map (
        din0 => phi_ln68_9_reg_2094,
        din1 => phi_ln68_11_reg_2099,
        din2 => p_0107_0_i_reg_267,
        dout => grp_fu_1700_p3);

    CNN_ALU_Top_mac_mdEe_U18 : component CNN_ALU_Top_mac_mdEe
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 8,
        din1_WIDTH => 8,
        din2_WIDTH => 19,
        dout_WIDTH => 19)
    port map (
        din0 => phi_ln68_14_reg_2109,
        din1 => phi_ln68_13_reg_2104,
        din2 => p_0103_0_i_reg_279,
        dout => grp_fu_1708_p3);

    CNN_ALU_Top_mac_mdEe_U19 : component CNN_ALU_Top_mac_mdEe
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 8,
        din1_WIDTH => 8,
        din2_WIDTH => 19,
        dout_WIDTH => 19)
    port map (
        din0 => ap_phi_reg_pp1_iter1_phi_ln68_reg_384,
        din1 => phi_ln68_2_reg_2152,
        din2 => p_0217_0_i163_reg_325,
        dout => grp_fu_1716_p3);

    CNN_ALU_Top_mac_mdEe_U20 : component CNN_ALU_Top_mac_mdEe
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 8,
        din1_WIDTH => 8,
        din2_WIDTH => 19,
        dout_WIDTH => 19)
    port map (
        din0 => phi_ln68_4_reg_2157,
        din1 => phi_ln68_6_reg_2162,
        din2 => p_0111_0_i164_reg_337,
        dout => grp_fu_1724_p3);

    CNN_ALU_Top_mac_mdEe_U21 : component CNN_ALU_Top_mac_mdEe
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 8,
        din1_WIDTH => 8,
        din2_WIDTH => 19,
        dout_WIDTH => 19)
    port map (
        din0 => phi_ln68_8_reg_2167,
        din1 => phi_ln68_s_reg_2172,
        din2 => p_0107_0_i165_reg_349,
        dout => grp_fu_1732_p3);

    CNN_ALU_Top_mac_mdEe_U22 : component CNN_ALU_Top_mac_mdEe
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 8,
        din1_WIDTH => 8,
        din2_WIDTH => 19,
        dout_WIDTH => 19)
    port map (
        din0 => phi_ln68_12_reg_2182,
        din1 => phi_ln68_10_reg_2177,
        din2 => p_0103_0_i166_reg_361,
        dout => grp_fu_1740_p3);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter0_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter0 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_condition_pp0_exit_iter0_state2) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter0 <= ap_const_logic_0;
                elsif (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1) and (cnn_op_V_read_read_fu_224_p2 = ap_const_lv4_6))) then 
                    ap_enable_reg_pp0_iter0 <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_condition_pp0_exit_iter0_state2))) then 
                    ap_enable_reg_pp0_iter1 <= (ap_const_logic_1 xor ap_condition_pp0_exit_iter0_state2);
                elsif ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
                elsif (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1) and (cnn_op_V_read_read_fu_224_p2 = ap_const_lv4_6))) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp1_iter0_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp1_iter0 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp1_stage0_subdone) and (ap_const_logic_1 = ap_condition_pp1_exit_iter0_state6) and (ap_const_logic_1 = ap_CS_fsm_pp1_stage0))) then 
                    ap_enable_reg_pp1_iter0 <= ap_const_logic_0;
                elsif (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1) and (cnn_op_V_read_read_fu_224_p2 = ap_const_lv4_2))) then 
                    ap_enable_reg_pp1_iter0 <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp1_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp1_iter1 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp1_stage0_subdone) and (ap_const_logic_1 = ap_condition_pp1_exit_iter0_state6))) then 
                    ap_enable_reg_pp1_iter1 <= (ap_const_logic_1 xor ap_condition_pp1_exit_iter0_state6);
                elsif ((ap_const_boolean_0 = ap_block_pp1_stage0_subdone)) then 
                    ap_enable_reg_pp1_iter1 <= ap_enable_reg_pp1_iter0;
                elsif (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1) and (cnn_op_V_read_read_fu_224_p2 = ap_const_lv4_2))) then 
                    ap_enable_reg_pp1_iter1 <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    rd_data_V_preg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                rd_data_V_preg <= ap_const_lv32_0;
            else
                if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1) and (cnn_op_V_read_read_fu_224_p2 = ap_const_lv4_3))) then 
                    rd_data_V_preg <= acc_reg_V;
                end if; 
            end if;
        end if;
    end process;


    a_ptr_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_lv7_0 = a_ptr_load_load_fu_732_p1) and (ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1) and (cnn_op_V_read_read_fu_224_p2 = ap_const_lv4_1))) then 
                a_ptr(2) <= '1';
                a_ptr(3) <= '0';
                a_ptr(4) <= '0';
            elsif (((ap_const_lv7_4 = a_ptr_load_load_fu_732_p1) and (ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1) and (cnn_op_V_read_read_fu_224_p2 = ap_const_lv4_1))) then 
                a_ptr(2) <= '0';
                a_ptr(3) <= '1';
                a_ptr(4) <= '0';
            elsif (((ap_const_lv7_8 = a_ptr_load_load_fu_732_p1) and (ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1) and (cnn_op_V_read_read_fu_224_p2 = ap_const_lv4_1))) then 
                a_ptr(2) <= '1';
                a_ptr(3) <= '1';
                a_ptr(4) <= '0';
            elsif (((ap_const_lv7_C = a_ptr_load_load_fu_732_p1) and (ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1) and (cnn_op_V_read_read_fu_224_p2 = ap_const_lv4_1))) then 
                a_ptr(2) <= '0';
                a_ptr(3) <= '0';
                a_ptr(4) <= '1';
            elsif (((ap_const_lv7_10 = a_ptr_load_load_fu_732_p1) and (ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1) and (cnn_op_V_read_read_fu_224_p2 = ap_const_lv4_1))) then 
                a_ptr(2) <= '1';
                a_ptr(3) <= '0';
                a_ptr(4) <= '1';
            elsif (((ap_const_lv7_14 = a_ptr_load_load_fu_732_p1) and (ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1) and (cnn_op_V_read_read_fu_224_p2 = ap_const_lv4_1))) then 
                a_ptr(2) <= '0';
                a_ptr(3) <= '1';
                a_ptr(4) <= '1';
            elsif ((((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1) and (cnn_op_V_read_read_fu_224_p2 = ap_const_lv4_5)) or (not((ap_const_lv7_18 = a_ptr_load_load_fu_732_p1)) and not((ap_const_lv7_14 = a_ptr_load_load_fu_732_p1)) and not((ap_const_lv7_10 = a_ptr_load_load_fu_732_p1)) and not((ap_const_lv7_C = a_ptr_load_load_fu_732_p1)) and not((ap_const_lv7_8 = a_ptr_load_load_fu_732_p1)) and not((ap_const_lv7_4 = a_ptr_load_load_fu_732_p1)) and not((ap_const_lv7_0 = a_ptr_load_load_fu_732_p1)) and (ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1) and (cnn_op_V_read_read_fu_224_p2 = ap_const_lv4_1)) or ((ap_const_lv7_18 = a_ptr_load_load_fu_732_p1) and (ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1) and (cnn_op_V_read_read_fu_224_p2 = ap_const_lv4_1)))) then 
                a_ptr(2) <= '0';
                a_ptr(3) <= '0';
                a_ptr(4) <= '0';
            end if; 
        end if;
    end process;

    acc_reg_V_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state8)) then 
                acc_reg_V <= sext_ln68_3_fu_1674_p1;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state5) and (cnn_op_V_read_read_fu_224_p2 = ap_const_lv4_6))) then 
                acc_reg_V <= add_ln700_1_reg_2134;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1) and (cnn_op_V_read_read_fu_224_p2 = ap_const_lv4_4))) then 
                acc_reg_V <= sext_ln68_fu_722_p1;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1) and (cnn_op_V_read_read_fu_224_p2 = ap_const_lv4_8))) then 
                acc_reg_V <= add_ln700_fu_668_p2;
            elsif ((((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1) and (cnn_op_V_read_read_fu_224_p2 = ap_const_lv4_5)) or ((tmp_2_fu_660_p3 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1) and (cnn_op_V_read_read_fu_224_p2 = ap_const_lv4_7)))) then 
                acc_reg_V <= ap_const_lv32_0;
            end if; 
        end if;
    end process;

    ap_phi_reg_pp0_iter1_phi_ln68_1_reg_302_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_235)) then
                if (((trunc_ln68_1_fu_1180_p1 = ap_const_lv3_6) and (icmp_ln107_1_fu_1168_p2 = ap_const_lv1_0))) then 
                    ap_phi_reg_pp0_iter1_phi_ln68_1_reg_302 <= act_buf_V_24_load_reg_2046;
                elsif (((trunc_ln68_1_fu_1180_p1 = ap_const_lv3_5) and (icmp_ln107_1_fu_1168_p2 = ap_const_lv1_0))) then 
                    ap_phi_reg_pp0_iter1_phi_ln68_1_reg_302 <= act_buf_V_20_load_reg_2022;
                elsif (((trunc_ln68_1_fu_1180_p1 = ap_const_lv3_4) and (icmp_ln107_1_fu_1168_p2 = ap_const_lv1_0))) then 
                    ap_phi_reg_pp0_iter1_phi_ln68_1_reg_302 <= act_buf_V_16_load_reg_1998;
                elsif (((trunc_ln68_1_fu_1180_p1 = ap_const_lv3_3) and (icmp_ln107_1_fu_1168_p2 = ap_const_lv1_0))) then 
                    ap_phi_reg_pp0_iter1_phi_ln68_1_reg_302 <= act_buf_V_12_load_reg_1974;
                elsif (((trunc_ln68_1_fu_1180_p1 = ap_const_lv3_2) and (icmp_ln107_1_fu_1168_p2 = ap_const_lv1_0))) then 
                    ap_phi_reg_pp0_iter1_phi_ln68_1_reg_302 <= act_buf_V_8_load_reg_1950;
                elsif (((trunc_ln68_1_fu_1180_p1 = ap_const_lv3_1) and (icmp_ln107_1_fu_1168_p2 = ap_const_lv1_0))) then 
                    ap_phi_reg_pp0_iter1_phi_ln68_1_reg_302 <= act_buf_V_4_load_reg_1926;
                elsif (((trunc_ln68_1_fu_1180_p1 = ap_const_lv3_0) and (icmp_ln107_1_fu_1168_p2 = ap_const_lv1_0))) then 
                    ap_phi_reg_pp0_iter1_phi_ln68_1_reg_302 <= act_buf_V_0_load_reg_1902;
                elsif (((trunc_ln68_1_fu_1180_p1 = ap_const_lv3_7) and (icmp_ln107_1_fu_1168_p2 = ap_const_lv1_0))) then 
                    ap_phi_reg_pp0_iter1_phi_ln68_1_reg_302 <= ap_const_lv8_0;
                elsif ((ap_const_boolean_1 = ap_const_boolean_1)) then 
                    ap_phi_reg_pp0_iter1_phi_ln68_1_reg_302 <= ap_phi_reg_pp0_iter0_phi_ln68_1_reg_302;
                end if;
            end if; 
        end if;
    end process;

    ap_phi_reg_pp1_iter1_phi_ln68_reg_384_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_294)) then
                if (((trunc_ln68_fu_1436_p1 = ap_const_lv3_6) and (icmp_ln107_fu_1424_p2 = ap_const_lv1_0))) then 
                    ap_phi_reg_pp1_iter1_phi_ln68_reg_384 <= act_buf_V_24_load_reg_2046;
                elsif (((trunc_ln68_fu_1436_p1 = ap_const_lv3_5) and (icmp_ln107_fu_1424_p2 = ap_const_lv1_0))) then 
                    ap_phi_reg_pp1_iter1_phi_ln68_reg_384 <= act_buf_V_20_load_reg_2022;
                elsif (((trunc_ln68_fu_1436_p1 = ap_const_lv3_4) and (icmp_ln107_fu_1424_p2 = ap_const_lv1_0))) then 
                    ap_phi_reg_pp1_iter1_phi_ln68_reg_384 <= act_buf_V_16_load_reg_1998;
                elsif (((trunc_ln68_fu_1436_p1 = ap_const_lv3_3) and (icmp_ln107_fu_1424_p2 = ap_const_lv1_0))) then 
                    ap_phi_reg_pp1_iter1_phi_ln68_reg_384 <= act_buf_V_12_load_reg_1974;
                elsif (((trunc_ln68_fu_1436_p1 = ap_const_lv3_2) and (icmp_ln107_fu_1424_p2 = ap_const_lv1_0))) then 
                    ap_phi_reg_pp1_iter1_phi_ln68_reg_384 <= act_buf_V_8_load_reg_1950;
                elsif (((trunc_ln68_fu_1436_p1 = ap_const_lv3_1) and (icmp_ln107_fu_1424_p2 = ap_const_lv1_0))) then 
                    ap_phi_reg_pp1_iter1_phi_ln68_reg_384 <= act_buf_V_4_load_reg_1926;
                elsif (((trunc_ln68_fu_1436_p1 = ap_const_lv3_0) and (icmp_ln107_fu_1424_p2 = ap_const_lv1_0))) then 
                    ap_phi_reg_pp1_iter1_phi_ln68_reg_384 <= act_buf_V_0_load_reg_1902;
                elsif (((trunc_ln68_fu_1436_p1 = ap_const_lv3_7) and (icmp_ln107_fu_1424_p2 = ap_const_lv1_0))) then 
                    ap_phi_reg_pp1_iter1_phi_ln68_reg_384 <= ap_const_lv8_0;
                elsif ((ap_const_boolean_1 = ap_const_boolean_1)) then 
                    ap_phi_reg_pp1_iter1_phi_ln68_reg_384 <= ap_phi_reg_pp1_iter0_phi_ln68_reg_384;
                end if;
            end if; 
        end if;
    end process;

    i_0_i167_reg_373_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp1_stage0_11001) and (icmp_ln107_fu_1424_p2 = ap_const_lv1_0) and (ap_enable_reg_pp1_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp1_stage0))) then 
                i_0_i167_reg_373 <= i_fu_1430_p2;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1) and (cnn_op_V_read_read_fu_224_p2 = ap_const_lv4_2))) then 
                i_0_i167_reg_373 <= ap_const_lv4_0;
            end if; 
        end if;
    end process;

    i_0_i_reg_291_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln107_1_fu_1168_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                i_0_i_reg_291 <= i_1_fu_1174_p2;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1) and (cnn_op_V_read_read_fu_224_p2 = ap_const_lv4_6))) then 
                i_0_i_reg_291 <= ap_const_lv4_0;
            end if; 
        end if;
    end process;

    p_0103_0_i166_reg_361_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp1_stage0_11001) and (icmp_ln107_reg_2139 = ap_const_lv1_0) and (ap_enable_reg_pp1_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp1_stage0))) then 
                p_0103_0_i166_reg_361 <= grp_fu_1740_p3;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1) and (cnn_op_V_read_read_fu_224_p2 = ap_const_lv4_2))) then 
                p_0103_0_i166_reg_361 <= ap_const_lv19_0;
            end if; 
        end if;
    end process;

    p_0103_0_i_reg_279_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln107_1_reg_2066 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                p_0103_0_i_reg_279 <= grp_fu_1708_p3;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1) and (cnn_op_V_read_read_fu_224_p2 = ap_const_lv4_6))) then 
                p_0103_0_i_reg_279 <= ap_const_lv19_0;
            end if; 
        end if;
    end process;

    p_0107_0_i165_reg_349_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp1_stage0_11001) and (icmp_ln107_reg_2139 = ap_const_lv1_0) and (ap_enable_reg_pp1_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp1_stage0))) then 
                p_0107_0_i165_reg_349 <= grp_fu_1732_p3;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1) and (cnn_op_V_read_read_fu_224_p2 = ap_const_lv4_2))) then 
                p_0107_0_i165_reg_349 <= ap_const_lv19_0;
            end if; 
        end if;
    end process;

    p_0107_0_i_reg_267_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln107_1_reg_2066 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                p_0107_0_i_reg_267 <= grp_fu_1700_p3;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1) and (cnn_op_V_read_read_fu_224_p2 = ap_const_lv4_6))) then 
                p_0107_0_i_reg_267 <= ap_const_lv19_0;
            end if; 
        end if;
    end process;

    p_0111_0_i164_reg_337_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp1_stage0_11001) and (icmp_ln107_reg_2139 = ap_const_lv1_0) and (ap_enable_reg_pp1_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp1_stage0))) then 
                p_0111_0_i164_reg_337 <= grp_fu_1724_p3;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1) and (cnn_op_V_read_read_fu_224_p2 = ap_const_lv4_2))) then 
                p_0111_0_i164_reg_337 <= ap_const_lv19_0;
            end if; 
        end if;
    end process;

    p_0111_0_i_reg_255_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln107_1_reg_2066 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                p_0111_0_i_reg_255 <= grp_fu_1692_p3;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1) and (cnn_op_V_read_read_fu_224_p2 = ap_const_lv4_6))) then 
                p_0111_0_i_reg_255 <= ap_const_lv19_0;
            end if; 
        end if;
    end process;

    p_0217_0_i163_reg_325_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp1_stage0_11001) and (icmp_ln107_reg_2139 = ap_const_lv1_0) and (ap_enable_reg_pp1_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp1_stage0))) then 
                p_0217_0_i163_reg_325 <= grp_fu_1716_p3;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1) and (cnn_op_V_read_read_fu_224_p2 = ap_const_lv4_2))) then 
                p_0217_0_i163_reg_325 <= ap_const_lv19_0;
            end if; 
        end if;
    end process;

    p_0217_0_i_reg_243_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln107_1_reg_2066 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                p_0217_0_i_reg_243 <= grp_fu_1684_p3;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1) and (cnn_op_V_read_read_fu_224_p2 = ap_const_lv4_6))) then 
                p_0217_0_i_reg_243 <= ap_const_lv19_0;
            end if; 
        end if;
    end process;

    w_ptr_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((w_ptr_load_load_fu_950_p1 = ap_const_lv7_0) and (ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1) and (cnn_op_V_read_read_fu_224_p2 = ap_const_lv4_0))) then 
                w_ptr(2) <= '1';
                w_ptr(3) <= '0';
                w_ptr(4) <= '0';
            elsif (((w_ptr_load_load_fu_950_p1 = ap_const_lv7_4) and (ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1) and (cnn_op_V_read_read_fu_224_p2 = ap_const_lv4_0))) then 
                w_ptr(2) <= '0';
                w_ptr(3) <= '1';
                w_ptr(4) <= '0';
            elsif (((w_ptr_load_load_fu_950_p1 = ap_const_lv7_8) and (ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1) and (cnn_op_V_read_read_fu_224_p2 = ap_const_lv4_0))) then 
                w_ptr(2) <= '1';
                w_ptr(3) <= '1';
                w_ptr(4) <= '0';
            elsif (((w_ptr_load_load_fu_950_p1 = ap_const_lv7_C) and (ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1) and (cnn_op_V_read_read_fu_224_p2 = ap_const_lv4_0))) then 
                w_ptr(2) <= '0';
                w_ptr(3) <= '0';
                w_ptr(4) <= '1';
            elsif (((w_ptr_load_load_fu_950_p1 = ap_const_lv7_10) and (ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1) and (cnn_op_V_read_read_fu_224_p2 = ap_const_lv4_0))) then 
                w_ptr(2) <= '1';
                w_ptr(3) <= '0';
                w_ptr(4) <= '1';
            elsif (((w_ptr_load_load_fu_950_p1 = ap_const_lv7_14) and (ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1) and (cnn_op_V_read_read_fu_224_p2 = ap_const_lv4_0))) then 
                w_ptr(2) <= '0';
                w_ptr(3) <= '1';
                w_ptr(4) <= '1';
            elsif ((((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1) and (cnn_op_V_read_read_fu_224_p2 = ap_const_lv4_5)) or (not((w_ptr_load_load_fu_950_p1 = ap_const_lv7_18)) and not((w_ptr_load_load_fu_950_p1 = ap_const_lv7_14)) and not((w_ptr_load_load_fu_950_p1 = ap_const_lv7_10)) and not((w_ptr_load_load_fu_950_p1 = ap_const_lv7_C)) and not((w_ptr_load_load_fu_950_p1 = ap_const_lv7_8)) and not((w_ptr_load_load_fu_950_p1 = ap_const_lv7_4)) and not((w_ptr_load_load_fu_950_p1 = ap_const_lv7_0)) and (ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1) and (cnn_op_V_read_read_fu_224_p2 = ap_const_lv4_0)) or ((w_ptr_load_load_fu_950_p1 = ap_const_lv7_18) and (ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1) and (cnn_op_V_read_read_fu_224_p2 = ap_const_lv4_0)))) then 
                w_ptr(2) <= '0';
                w_ptr(3) <= '0';
                w_ptr(4) <= '0';
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then
                acc_reg_V_load_reg_2052 <= acc_reg_V;
                act_buf_V_0_load_reg_1902 <= act_buf_V_0;
                act_buf_V_10_load_reg_1962 <= act_buf_V_10;
                act_buf_V_11_load_reg_1968 <= act_buf_V_11;
                act_buf_V_12_load_reg_1974 <= act_buf_V_12;
                act_buf_V_13_load_reg_1980 <= act_buf_V_13;
                act_buf_V_14_load_reg_1986 <= act_buf_V_14;
                act_buf_V_15_load_reg_1992 <= act_buf_V_15;
                act_buf_V_16_load_reg_1998 <= act_buf_V_16;
                act_buf_V_17_load_reg_2004 <= act_buf_V_17;
                act_buf_V_18_load_reg_2010 <= act_buf_V_18;
                act_buf_V_19_load_reg_2016 <= act_buf_V_19;
                act_buf_V_1_load_reg_1908 <= act_buf_V_1;
                act_buf_V_20_load_reg_2022 <= act_buf_V_20;
                act_buf_V_21_load_reg_2028 <= act_buf_V_21;
                act_buf_V_22_load_reg_2034 <= act_buf_V_22;
                act_buf_V_23_load_reg_2040 <= act_buf_V_23;
                act_buf_V_24_load_reg_2046 <= act_buf_V_24;
                act_buf_V_2_load_reg_1914 <= act_buf_V_2;
                act_buf_V_3_load_reg_1920 <= act_buf_V_3;
                act_buf_V_4_load_reg_1926 <= act_buf_V_4;
                act_buf_V_5_load_reg_1932 <= act_buf_V_5;
                act_buf_V_6_load_reg_1938 <= act_buf_V_6;
                act_buf_V_7_load_reg_1944 <= act_buf_V_7;
                act_buf_V_8_load_reg_1950 <= act_buf_V_8;
                act_buf_V_9_load_reg_1956 <= act_buf_V_9;
                weight_buf_V_0_load_reg_1752 <= weight_buf_V_0;
                weight_buf_V_10_load_reg_1812 <= weight_buf_V_10;
                weight_buf_V_11_load_reg_1818 <= weight_buf_V_11;
                weight_buf_V_12_load_reg_1824 <= weight_buf_V_12;
                weight_buf_V_13_load_reg_1830 <= weight_buf_V_13;
                weight_buf_V_14_load_reg_1836 <= weight_buf_V_14;
                weight_buf_V_15_load_reg_1842 <= weight_buf_V_15;
                weight_buf_V_16_load_reg_1848 <= weight_buf_V_16;
                weight_buf_V_17_load_reg_1854 <= weight_buf_V_17;
                weight_buf_V_18_load_reg_1860 <= weight_buf_V_18;
                weight_buf_V_19_load_reg_1866 <= weight_buf_V_19;
                weight_buf_V_1_load_reg_1758 <= weight_buf_V_1;
                weight_buf_V_20_load_reg_1872 <= weight_buf_V_20;
                weight_buf_V_21_load_reg_1878 <= weight_buf_V_21;
                weight_buf_V_22_load_reg_1884 <= weight_buf_V_22;
                weight_buf_V_23_load_reg_1890 <= weight_buf_V_23;
                weight_buf_V_24_load_reg_1896 <= weight_buf_V_24;
                weight_buf_V_2_load_reg_1764 <= weight_buf_V_2;
                weight_buf_V_3_load_reg_1770 <= weight_buf_V_3;
                weight_buf_V_4_load_reg_1776 <= weight_buf_V_4;
                weight_buf_V_5_load_reg_1782 <= weight_buf_V_5;
                weight_buf_V_6_load_reg_1788 <= weight_buf_V_6;
                weight_buf_V_7_load_reg_1794 <= weight_buf_V_7;
                weight_buf_V_8_load_reg_1800 <= weight_buf_V_8;
                weight_buf_V_9_load_reg_1806 <= weight_buf_V_9;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_lv7_0 = a_ptr_load_load_fu_732_p1) and (ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1) and (cnn_op_V_read_read_fu_224_p2 = ap_const_lv4_1))) then
                act_buf_V_0 <= trunc_ln647_7_fu_916_p1;
                act_buf_V_1 <= rs1_data_V(15 downto 8);
                act_buf_V_2 <= rs1_data_V(23 downto 16);
                act_buf_V_3 <= rs1_data_V(31 downto 24);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_lv7_8 = a_ptr_load_load_fu_732_p1) and (ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1) and (cnn_op_V_read_read_fu_224_p2 = ap_const_lv4_1))) then
                act_buf_V_10 <= rs1_data_V(23 downto 16);
                act_buf_V_11 <= rs1_data_V(31 downto 24);
                act_buf_V_8 <= trunc_ln647_9_fu_848_p1;
                act_buf_V_9 <= rs1_data_V(15 downto 8);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_lv7_C = a_ptr_load_load_fu_732_p1) and (ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1) and (cnn_op_V_read_read_fu_224_p2 = ap_const_lv4_1))) then
                act_buf_V_12 <= trunc_ln647_10_fu_814_p1;
                act_buf_V_13 <= rs1_data_V(15 downto 8);
                act_buf_V_14 <= rs1_data_V(23 downto 16);
                act_buf_V_15 <= rs1_data_V(31 downto 24);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_lv7_10 = a_ptr_load_load_fu_732_p1) and (ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1) and (cnn_op_V_read_read_fu_224_p2 = ap_const_lv4_1))) then
                act_buf_V_16 <= trunc_ln647_11_fu_780_p1;
                act_buf_V_17 <= rs1_data_V(15 downto 8);
                act_buf_V_18 <= rs1_data_V(23 downto 16);
                act_buf_V_19 <= rs1_data_V(31 downto 24);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_lv7_14 = a_ptr_load_load_fu_732_p1) and (ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1) and (cnn_op_V_read_read_fu_224_p2 = ap_const_lv4_1))) then
                act_buf_V_20 <= trunc_ln647_12_fu_746_p1;
                act_buf_V_21 <= rs1_data_V(15 downto 8);
                act_buf_V_22 <= rs1_data_V(23 downto 16);
                act_buf_V_23 <= rs1_data_V(31 downto 24);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_lv7_18 = a_ptr_load_load_fu_732_p1) and (ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1) and (cnn_op_V_read_read_fu_224_p2 = ap_const_lv4_1))) then
                act_buf_V_24 <= trunc_ln647_13_fu_736_p1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_lv7_4 = a_ptr_load_load_fu_732_p1) and (ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1) and (cnn_op_V_read_read_fu_224_p2 = ap_const_lv4_1))) then
                act_buf_V_4 <= trunc_ln647_8_fu_882_p1;
                act_buf_V_5 <= rs1_data_V(15 downto 8);
                act_buf_V_6 <= rs1_data_V(23 downto 16);
                act_buf_V_7 <= rs1_data_V(31 downto 24);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state4)) then
                add_ln700_1_reg_2134 <= add_ln700_1_fu_1413_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                icmp_ln107_1_reg_2066 <= icmp_ln107_1_fu_1168_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp1_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp1_stage0))) then
                icmp_ln107_reg_2139 <= icmp_ln107_fu_1424_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp1_stage0_11001) and (icmp_ln107_fu_1424_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_pp1_stage0))) then
                phi_ln68_10_reg_2177 <= phi_ln68_10_fu_1575_p10;
                phi_ln68_12_reg_2182 <= phi_ln68_12_fu_1591_p10;
                phi_ln68_2_reg_2152 <= phi_ln68_2_fu_1448_p34;
                phi_ln68_4_reg_2157 <= phi_ln68_4_fu_1511_p10;
                phi_ln68_6_reg_2162 <= phi_ln68_6_fu_1527_p10;
                phi_ln68_8_reg_2167 <= phi_ln68_8_fu_1543_p10;
                phi_ln68_s_reg_2172 <= phi_ln68_s_fu_1559_p10;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln107_1_fu_1168_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                phi_ln68_11_reg_2099 <= phi_ln68_11_fu_1303_p10;
                phi_ln68_13_reg_2104 <= phi_ln68_13_fu_1319_p10;
                phi_ln68_14_reg_2109 <= phi_ln68_14_fu_1335_p10;
                phi_ln68_3_reg_2079 <= phi_ln68_3_fu_1192_p34;
                phi_ln68_5_reg_2084 <= phi_ln68_5_fu_1255_p10;
                phi_ln68_7_reg_2089 <= phi_ln68_7_fu_1271_p10;
                phi_ln68_9_reg_2094 <= phi_ln68_9_fu_1287_p10;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((w_ptr_load_load_fu_950_p1 = ap_const_lv7_0) and (ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1) and (cnn_op_V_read_read_fu_224_p2 = ap_const_lv4_0))) then
                weight_buf_V_0 <= trunc_ln647_fu_1134_p1;
                weight_buf_V_1 <= rs1_data_V(15 downto 8);
                weight_buf_V_2 <= rs1_data_V(23 downto 16);
                weight_buf_V_3 <= rs1_data_V(31 downto 24);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((w_ptr_load_load_fu_950_p1 = ap_const_lv7_8) and (ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1) and (cnn_op_V_read_read_fu_224_p2 = ap_const_lv4_0))) then
                weight_buf_V_10 <= rs1_data_V(23 downto 16);
                weight_buf_V_11 <= rs1_data_V(31 downto 24);
                weight_buf_V_8 <= trunc_ln647_2_fu_1066_p1;
                weight_buf_V_9 <= rs1_data_V(15 downto 8);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((w_ptr_load_load_fu_950_p1 = ap_const_lv7_C) and (ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1) and (cnn_op_V_read_read_fu_224_p2 = ap_const_lv4_0))) then
                weight_buf_V_12 <= trunc_ln647_3_fu_1032_p1;
                weight_buf_V_13 <= rs1_data_V(15 downto 8);
                weight_buf_V_14 <= rs1_data_V(23 downto 16);
                weight_buf_V_15 <= rs1_data_V(31 downto 24);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((w_ptr_load_load_fu_950_p1 = ap_const_lv7_10) and (ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1) and (cnn_op_V_read_read_fu_224_p2 = ap_const_lv4_0))) then
                weight_buf_V_16 <= trunc_ln647_4_fu_998_p1;
                weight_buf_V_17 <= rs1_data_V(15 downto 8);
                weight_buf_V_18 <= rs1_data_V(23 downto 16);
                weight_buf_V_19 <= rs1_data_V(31 downto 24);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((w_ptr_load_load_fu_950_p1 = ap_const_lv7_14) and (ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1) and (cnn_op_V_read_read_fu_224_p2 = ap_const_lv4_0))) then
                weight_buf_V_20 <= trunc_ln647_5_fu_964_p1;
                weight_buf_V_21 <= rs1_data_V(15 downto 8);
                weight_buf_V_22 <= rs1_data_V(23 downto 16);
                weight_buf_V_23 <= rs1_data_V(31 downto 24);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((w_ptr_load_load_fu_950_p1 = ap_const_lv7_18) and (ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1) and (cnn_op_V_read_read_fu_224_p2 = ap_const_lv4_0))) then
                weight_buf_V_24 <= trunc_ln647_6_fu_954_p1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((w_ptr_load_load_fu_950_p1 = ap_const_lv7_4) and (ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1) and (cnn_op_V_read_read_fu_224_p2 = ap_const_lv4_0))) then
                weight_buf_V_4 <= trunc_ln647_1_fu_1100_p1;
                weight_buf_V_5 <= rs1_data_V(15 downto 8);
                weight_buf_V_6 <= rs1_data_V(23 downto 16);
                weight_buf_V_7 <= rs1_data_V(31 downto 24);
            end if;
        end if;
    end process;
    w_ptr(1 downto 0) <= "00";
    w_ptr(6 downto 5) <= "00";
    a_ptr(1 downto 0) <= "00";
    a_ptr(6 downto 5) <= "00";

    ap_NS_fsm_assign_proc : process (ap_start, ap_CS_fsm, ap_CS_fsm_state1, cnn_op_V_read_read_fu_224_p2, icmp_ln107_1_fu_1168_p2, ap_enable_reg_pp0_iter0, icmp_ln107_fu_1424_p2, ap_enable_reg_pp1_iter0, ap_block_pp0_stage0_subdone, ap_block_pp1_stage0_subdone)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1) and (cnn_op_V_read_read_fu_224_p2 = ap_const_lv4_0))) then
                    ap_NS_fsm <= ap_ST_fsm_state10;
                elsif (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1) and (cnn_op_V_read_read_fu_224_p2 = ap_const_lv4_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state9;
                elsif (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1) and (cnn_op_V_read_read_fu_224_p2 = ap_const_lv4_2))) then
                    ap_NS_fsm <= ap_ST_fsm_pp1_stage0;
                elsif (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1) and (cnn_op_V_read_read_fu_224_p2 = ap_const_lv4_6))) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                elsif ((not((cnn_op_V_read_read_fu_224_p2 = ap_const_lv4_1)) and not((cnn_op_V_read_read_fu_224_p2 = ap_const_lv4_0)) and not((cnn_op_V_read_read_fu_224_p2 = ap_const_lv4_2)) and not((cnn_op_V_read_read_fu_224_p2 = ap_const_lv4_6)) and (ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state5;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_pp0_stage0 => 
                if (not(((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (icmp_ln107_1_fu_1168_p2 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1)))) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (icmp_ln107_1_fu_1168_p2 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state4;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                end if;
            when ap_ST_fsm_state4 => 
                ap_NS_fsm <= ap_ST_fsm_state5;
            when ap_ST_fsm_state5 => 
                ap_NS_fsm <= ap_ST_fsm_state1;
            when ap_ST_fsm_pp1_stage0 => 
                if (not(((ap_const_boolean_0 = ap_block_pp1_stage0_subdone) and (icmp_ln107_fu_1424_p2 = ap_const_lv1_1) and (ap_enable_reg_pp1_iter0 = ap_const_logic_1)))) then
                    ap_NS_fsm <= ap_ST_fsm_pp1_stage0;
                elsif (((ap_const_boolean_0 = ap_block_pp1_stage0_subdone) and (icmp_ln107_fu_1424_p2 = ap_const_lv1_1) and (ap_enable_reg_pp1_iter0 = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state8;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp1_stage0;
                end if;
            when ap_ST_fsm_state8 => 
                ap_NS_fsm <= ap_ST_fsm_state5;
            when ap_ST_fsm_state9 => 
                ap_NS_fsm <= ap_ST_fsm_state5;
            when ap_ST_fsm_state10 => 
                ap_NS_fsm <= ap_ST_fsm_state5;
            when others =>  
                ap_NS_fsm <= "XXXXXXXX";
        end case;
    end process;
    a_ptr_load_load_fu_732_p1 <= a_ptr;
    add_ln68_1_fu_1658_p2 <= std_logic_vector(signed(sext_ln107_1_fu_1636_p1) + signed(sext_ln107_fu_1632_p1));
    add_ln68_2_fu_1668_p2 <= std_logic_vector(signed(sext_ln68_2_fu_1664_p1) + signed(sext_ln68_1_fu_1654_p1));
    add_ln68_fu_1648_p2 <= std_logic_vector(signed(sext_ln107_2_fu_1640_p1) + signed(sext_ln107_3_fu_1644_p1));
    add_ln700_1_fu_1413_p2 <= std_logic_vector(signed(sext_ln700_fu_1409_p1) + signed(add_ln700_2_fu_1392_p2));
    add_ln700_2_fu_1392_p2 <= std_logic_vector(unsigned(acc_reg_V_load_reg_2052) + unsigned(sext_ln107_6_fu_1384_p1));
    add_ln700_3_fu_1397_p2 <= std_logic_vector(signed(sext_ln107_5_fu_1380_p1) + signed(sext_ln107_4_fu_1376_p1));
    add_ln700_4_fu_1403_p2 <= std_logic_vector(unsigned(add_ln700_3_fu_1397_p2) + unsigned(sext_ln107_7_fu_1388_p1));
    add_ln700_fu_668_p2 <= std_logic_vector(unsigned(acc_reg_V) + unsigned(rs1_data_V));
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(1);
    ap_CS_fsm_pp1_stage0 <= ap_CS_fsm(4);
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state4 <= ap_CS_fsm(2);
    ap_CS_fsm_state5 <= ap_CS_fsm(3);
    ap_CS_fsm_state8 <= ap_CS_fsm(5);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp1_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp1_stage0_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp1_stage0_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state2_pp0_stage0_iter0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state3_pp0_stage0_iter1 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state6_pp1_stage0_iter0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state7_pp1_stage0_iter1 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_condition_235_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001, ap_enable_reg_pp0_iter0)
    begin
                ap_condition_235 <= ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0));
    end process;


    ap_condition_294_assign_proc : process(ap_CS_fsm_pp1_stage0, ap_block_pp1_stage0_11001, ap_enable_reg_pp1_iter0)
    begin
                ap_condition_294 <= ((ap_const_boolean_0 = ap_block_pp1_stage0_11001) and (ap_enable_reg_pp1_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp1_stage0));
    end process;


    ap_condition_pp0_exit_iter0_state2_assign_proc : process(icmp_ln107_1_fu_1168_p2)
    begin
        if ((icmp_ln107_1_fu_1168_p2 = ap_const_lv1_1)) then 
            ap_condition_pp0_exit_iter0_state2 <= ap_const_logic_1;
        else 
            ap_condition_pp0_exit_iter0_state2 <= ap_const_logic_0;
        end if; 
    end process;


    ap_condition_pp1_exit_iter0_state6_assign_proc : process(icmp_ln107_fu_1424_p2)
    begin
        if ((icmp_ln107_fu_1424_p2 = ap_const_lv1_1)) then 
            ap_condition_pp1_exit_iter0_state6 <= ap_const_logic_1;
        else 
            ap_condition_pp1_exit_iter0_state6 <= ap_const_logic_0;
        end if; 
    end process;


    ap_done_assign_proc : process(ap_CS_fsm_state5)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_pp1 <= (ap_idle_pp1 xor ap_const_logic_1);

    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp1_assign_proc : process(ap_enable_reg_pp1_iter0, ap_enable_reg_pp1_iter1)
    begin
        if (((ap_enable_reg_pp1_iter1 = ap_const_logic_0) and (ap_enable_reg_pp1_iter0 = ap_const_logic_0))) then 
            ap_idle_pp1 <= ap_const_logic_1;
        else 
            ap_idle_pp1 <= ap_const_logic_0;
        end if; 
    end process;

    ap_phi_reg_pp0_iter0_phi_ln68_1_reg_302 <= "XXXXXXXX";
    ap_phi_reg_pp1_iter0_phi_ln68_reg_384 <= "XXXXXXXX";

    ap_ready_assign_proc : process(ap_CS_fsm_state5)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;

    cnn_op_V_read_read_fu_224_p2 <= cnn_op_V;
    final_max_V_fu_714_p3 <= 
        max1_V_fu_686_p3 when (icmp_ln895_2_fu_708_p2(0) = '1') else 
        max2_V_fu_700_p3;
    i_1_fu_1174_p2 <= std_logic_vector(unsigned(i_0_i_reg_291) + unsigned(ap_const_lv4_1));
    i_fu_1430_p2 <= std_logic_vector(unsigned(i_0_i167_reg_373) + unsigned(ap_const_lv4_1));
    icmp_ln107_1_fu_1168_p2 <= "1" when (i_0_i_reg_291 = ap_const_lv4_8) else "0";
    icmp_ln107_fu_1424_p2 <= "1" when (i_0_i167_reg_373 = ap_const_lv4_8) else "0";
    icmp_ln895_1_fu_694_p2 <= "1" when (signed(act_buf_V_2) > signed(act_buf_V_3)) else "0";
    icmp_ln895_2_fu_708_p2 <= "1" when (signed(max1_V_fu_686_p3) > signed(max2_V_fu_700_p3)) else "0";
    icmp_ln895_fu_680_p2 <= "1" when (signed(act_buf_V_0) > signed(act_buf_V_1)) else "0";
    max1_V_fu_686_p3 <= 
        act_buf_V_0 when (icmp_ln895_fu_680_p2(0) = '1') else 
        act_buf_V_1;
    max2_V_fu_700_p3 <= 
        act_buf_V_2 when (icmp_ln895_1_fu_694_p2(0) = '1') else 
        act_buf_V_3;
    phi_ln68_2_fu_1448_p33 <= (trunc_ln68_fu_1436_p1 & ap_const_lv2_0);
    phi_ln68_3_fu_1192_p33 <= (trunc_ln68_1_fu_1180_p1 & ap_const_lv2_0);

    rd_data_V_assign_proc : process(ap_start, ap_CS_fsm_state1, acc_reg_V, cnn_op_V_read_read_fu_224_p2, rd_data_V_preg)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1) and (cnn_op_V_read_read_fu_224_p2 = ap_const_lv4_3))) then 
            rd_data_V <= acc_reg_V;
        else 
            rd_data_V <= rd_data_V_preg;
        end if; 
    end process;

        sext_ln107_1_fu_1636_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(p_0111_0_i164_reg_337),20));

        sext_ln107_2_fu_1640_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(p_0107_0_i165_reg_349),20));

        sext_ln107_3_fu_1644_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(p_0103_0_i166_reg_361),20));

        sext_ln107_4_fu_1376_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(p_0217_0_i_reg_243),20));

        sext_ln107_5_fu_1380_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(p_0111_0_i_reg_255),20));

        sext_ln107_6_fu_1384_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(p_0107_0_i_reg_267),32));

        sext_ln107_7_fu_1388_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(p_0103_0_i_reg_279),20));

        sext_ln107_fu_1632_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(p_0217_0_i163_reg_325),20));

        sext_ln68_1_fu_1654_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(add_ln68_fu_1648_p2),21));

        sext_ln68_2_fu_1664_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(add_ln68_1_fu_1658_p2),21));

        sext_ln68_3_fu_1674_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(add_ln68_2_fu_1668_p2),32));

        sext_ln68_fu_722_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(final_max_V_fu_714_p3),32));

        sext_ln700_fu_1409_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(add_ln700_4_fu_1403_p2),32));

    tmp_2_fu_660_p3 <= acc_reg_V(31 downto 31);
    trunc_ln647_10_fu_814_p1 <= rs1_data_V(8 - 1 downto 0);
    trunc_ln647_11_fu_780_p1 <= rs1_data_V(8 - 1 downto 0);
    trunc_ln647_12_fu_746_p1 <= rs1_data_V(8 - 1 downto 0);
    trunc_ln647_13_fu_736_p1 <= rs1_data_V(8 - 1 downto 0);
    trunc_ln647_1_fu_1100_p1 <= rs1_data_V(8 - 1 downto 0);
    trunc_ln647_2_fu_1066_p1 <= rs1_data_V(8 - 1 downto 0);
    trunc_ln647_3_fu_1032_p1 <= rs1_data_V(8 - 1 downto 0);
    trunc_ln647_4_fu_998_p1 <= rs1_data_V(8 - 1 downto 0);
    trunc_ln647_5_fu_964_p1 <= rs1_data_V(8 - 1 downto 0);
    trunc_ln647_6_fu_954_p1 <= rs1_data_V(8 - 1 downto 0);
    trunc_ln647_7_fu_916_p1 <= rs1_data_V(8 - 1 downto 0);
    trunc_ln647_8_fu_882_p1 <= rs1_data_V(8 - 1 downto 0);
    trunc_ln647_9_fu_848_p1 <= rs1_data_V(8 - 1 downto 0);
    trunc_ln647_fu_1134_p1 <= rs1_data_V(8 - 1 downto 0);
    trunc_ln68_1_fu_1180_p1 <= i_0_i_reg_291(3 - 1 downto 0);
    trunc_ln68_fu_1436_p1 <= i_0_i167_reg_373(3 - 1 downto 0);
    w_ptr_load_load_fu_950_p1 <= w_ptr;
end behav;
