import argparse
from pathlib import Path

import torch
import torch.nn.functional as F
from torch.utils.data import DataLoader, Subset
from torchvision import datasets, transforms

from train_lenet_relu_maxpool import LeNetReLUMaxPool


LAYERS = ("conv1", "conv2", "conv3", "fc1", "fc2")


def clamp_int8(x):
    return torch.round(x).clamp(-128, 127).to(torch.int8)


def tensor_max_abs(tensor):
    return float(tensor.detach().abs().max().item())


def scale_from_max(max_abs):
    if max_abs == 0.0:
        return 1.0
    return max_abs / 127.0


def quantize_weight_per_layer(weight):
    max_abs = tensor_max_abs(weight)
    scale = scale_from_max(max_abs)
    q = clamp_int8(weight / scale)
    return q, scale, max_abs


def quantize_bias_int32(bias, input_scale, weight_scale):
    bias_scale = input_scale * weight_scale
    q = torch.round(bias / bias_scale).to(torch.int32)
    return q, bias_scale


def requant_multiplier(input_scale, weight_scale, output_scale, shift):
    scale = input_scale * weight_scale / output_scale
    return int(round(scale * (1 << shift))), scale


def collect_activation_max(model, loader, device, limit):
    """Collect post-activation tensor ranges used as the next layer input scale."""
    model.eval()
    max_values = {
        "input": 1.0,
        "pool1": 0.0,
        "pool2": 0.0,
        "relu3": 0.0,
        "relu_fc1": 0.0,
        "fc2": 0.0,
    }

    seen = 0
    with torch.no_grad():
        for images, _ in loader:
            images = images.to(device)

            x = F.relu(model.conv1(images))
            x = F.max_pool2d(x, 2)
            max_values["pool1"] = max(max_values["pool1"], tensor_max_abs(x))

            x = F.relu(model.conv2(x))
            x = F.max_pool2d(x, 2)
            max_values["pool2"] = max(max_values["pool2"], tensor_max_abs(x))

            x = F.relu(model.conv3(x))
            max_values["relu3"] = max(max_values["relu3"], tensor_max_abs(x))

            x = torch.flatten(x, 1)
            x = F.relu(model.fc1(x))
            max_values["relu_fc1"] = max(max_values["relu_fc1"], tensor_max_abs(x))

            x = model.fc2(x)
            max_values["fc2"] = max(max_values["fc2"], tensor_max_abs(x))

            seen += images.size(0)
            if seen >= limit:
                break

    return max_values


def fake_quant_eval(model, params, loader, device):
    """Run an approximate INT8 inference path in PyTorch for a quick accuracy check."""
    model.eval()
    correct = 0
    total = 0

    input_scale = params["activation_scales"]["input"]
    act_scales = params["activation_scales"]
    w = params["weights"]
    b = params["bias_float"]

    with torch.no_grad():
        for images, labels in loader:
            labels = labels.to(device)

            x_q = clamp_int8(images.to(device) / input_scale)
            x = x_q.float() * input_scale

            x = F.conv2d(x, w["conv1"].float() * params["weight_scales"]["conv1"], b["conv1"])
            x = F.relu(x)
            x_q = clamp_int8(x / act_scales["relu1"])
            x = x_q.float() * act_scales["relu1"]
            x = F.max_pool2d(x, 2)
            x_q = clamp_int8(x / act_scales["pool1"])
            x = x_q.float() * act_scales["pool1"]

            x = F.conv2d(x, w["conv2"].float() * params["weight_scales"]["conv2"], b["conv2"])
            x = F.relu(x)
            x_q = clamp_int8(x / act_scales["relu2"])
            x = x_q.float() * act_scales["relu2"]
            x = F.max_pool2d(x, 2)
            x_q = clamp_int8(x / act_scales["pool2"])
            x = x_q.float() * act_scales["pool2"]

            x = F.conv2d(x, w["conv3"].float() * params["weight_scales"]["conv3"], b["conv3"])
            x = F.relu(x)
            x_q = clamp_int8(x / act_scales["relu3"])
            x = x_q.float() * act_scales["relu3"]

            x = torch.flatten(x, 1)
            x = F.linear(x, w["fc1"].float() * params["weight_scales"]["fc1"], b["fc1"])
            x = F.relu(x)
            x_q = clamp_int8(x / act_scales["relu_fc1"])
            x = x_q.float() * act_scales["relu_fc1"]

            logits = F.linear(x, w["fc2"].float() * params["weight_scales"]["fc2"], b["fc2"])

            pred = logits.argmax(dim=1)
            correct += (pred == labels).sum().item()
            total += labels.numel()

    return correct / total


def flatten_initializer(values, per_line=16):
    flat = values.reshape(-1).tolist()
    chunks = []
    for i in range(0, len(flat), per_line):
        chunks.append("    " + ", ".join(str(int(v)) for v in flat[i : i + per_line]))
    return ",\n".join(chunks)


def write_header(path, params):
    arrays = []
    arrays.append("// Auto-generated by export_lenet_int8.py")
    arrays.append("#ifndef LENET_INT8_PARAMS_H")
    arrays.append("#define LENET_INT8_PARAMS_H")
    arrays.append("")
    arrays.append("#include <stdint.h>")
    arrays.append("")
    arrays.append(f"#define LENET_REQUANT_SHIFT {params['requant_shift']}")
    arrays.append("")

    for name in LAYERS:
        arrays.append(
            f"static const int32_t {name}_requant_multiplier = "
            f"{params['requant_multipliers'][name]};"
        )
    arrays.append("")

    for name in LAYERS:
        weight = params["weights"][name].cpu().numpy()
        bias = params["bias_int32"][name].cpu().numpy()
        weight_shape = "".join(f"[{d}]" for d in weight.shape)
        bias_shape = f"[{bias.shape[0]}]"
        arrays.append(f"static const int8_t {name}_weight_int8{weight_shape} = {{")
        arrays.append(flatten_initializer(weight))
        arrays.append("};")
        arrays.append("")
        arrays.append(f"static const int32_t {name}_bias_int32{bias_shape} = {{")
        arrays.append(flatten_initializer(bias, per_line=8))
        arrays.append("};")
        arrays.append("")

    arrays.append("#endif")
    path.write_text("\n".join(arrays) + "\n", encoding="utf-8")


def write_scales(path, params, fake_quant_acc):
    lines = []
    lines.append("Auto-generated by export_lenet_int8.py")
    lines.append("")
    lines.append(f"checkpoint={params['checkpoint']}")
    lines.append(f"calibration_samples={params['calibration_samples']}")
    lines.append(f"fake_quant_test_acc={fake_quant_acc * 100:.2f}%")
    lines.append("")
    lines.append("[activation_scales]")
    for key, value in params["activation_scales"].items():
        lines.append(f"{key}={value:.10f}")
    lines.append("")
    lines.append("[weight_scales]")
    for key, value in params["weight_scales"].items():
        lines.append(f"{key}={value:.10f}")
    lines.append("")
    lines.append("[bias_scales]")
    for key, value in params["bias_scales"].items():
        lines.append(f"{key}={value:.10f}")
    lines.append("")
    lines.append("[requant]")
    lines.append(f"shift={params['requant_shift']}")
    for key in LAYERS:
        lines.append(
            f"{key}_scale={params['requant_scales'][key]:.10f}, "
            f"{key}_multiplier={params['requant_multipliers'][key]}"
        )
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--checkpoint", type=Path, default=Path("lenet_relu_maxpool_float_10epoch.pth"))
    parser.add_argument("--data-dir", type=Path, default=Path("data"))
    parser.add_argument("--calibration-samples", type=int, default=1024)
    parser.add_argument("--batch-size", type=int, default=256)
    parser.add_argument("--header-out", type=Path, default=Path("lenet_int8_params.h"))
    parser.add_argument("--scales-out", type=Path, default=Path("lenet_int8_scales.txt"))
    parser.add_argument("--requant-shift", type=int, default=20)
    args = parser.parse_args()

    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    ckpt = torch.load(args.checkpoint, map_location=device)
    model = LeNetReLUMaxPool().to(device)
    model.load_state_dict(ckpt["model"])

    transform = transforms.Compose(
        [
            transforms.Pad(2),
            transforms.ToTensor(),
            transforms.Normalize((0.5,), (0.5,)),
        ]
    )
    train_set = datasets.MNIST(args.data_dir, train=True, download=True, transform=transform)
    test_set = datasets.MNIST(args.data_dir, train=False, download=True, transform=transform)
    cal_set = Subset(train_set, range(min(args.calibration_samples, len(train_set))))
    cal_loader = DataLoader(cal_set, batch_size=args.batch_size, shuffle=False, num_workers=2)
    test_loader = DataLoader(test_set, batch_size=args.batch_size, shuffle=False, num_workers=2)

    activation_max = collect_activation_max(model, cal_loader, device, args.calibration_samples)
    activation_scales = {
        "input": 1.0 / 127.0,
        "relu1": scale_from_max(activation_max["pool1"]),
        "pool1": scale_from_max(activation_max["pool1"]),
        "relu2": scale_from_max(activation_max["pool2"]),
        "pool2": scale_from_max(activation_max["pool2"]),
        "relu3": scale_from_max(activation_max["relu3"]),
        "relu_fc1": scale_from_max(activation_max["relu_fc1"]),
        "fc2": scale_from_max(activation_max["fc2"]),
    }

    input_scale_for_layer = {
        "conv1": activation_scales["input"],
        "conv2": activation_scales["pool1"],
        "conv3": activation_scales["pool2"],
        "fc1": activation_scales["relu3"],
        "fc2": activation_scales["relu_fc1"],
    }
    output_scale_for_layer = {
        "conv1": activation_scales["relu1"],
        "conv2": activation_scales["relu2"],
        "conv3": activation_scales["relu3"],
        "fc1": activation_scales["relu_fc1"],
        "fc2": activation_scales["fc2"],
    }

    state = model.state_dict()
    params = {
        "checkpoint": str(args.checkpoint),
        "calibration_samples": args.calibration_samples,
        "requant_shift": args.requant_shift,
        "activation_scales": activation_scales,
        "weights": {},
        "bias_float": {},
        "bias_int32": {},
        "weight_scales": {},
        "bias_scales": {},
        "requant_multipliers": {},
        "requant_scales": {},
    }

    for name in LAYERS:
        q_weight, weight_scale, _ = quantize_weight_per_layer(state[f"{name}.weight"].cpu())
        q_bias, bias_scale = quantize_bias_int32(
            state[f"{name}.bias"].cpu(), input_scale_for_layer[name], weight_scale
        )
        params["weights"][name] = q_weight
        params["bias_float"][name] = state[f"{name}.bias"].to(device)
        params["bias_int32"][name] = q_bias
        params["weight_scales"][name] = weight_scale
        params["bias_scales"][name] = bias_scale
        mult, rq_scale = requant_multiplier(
            input_scale_for_layer[name],
            weight_scale,
            output_scale_for_layer[name],
            args.requant_shift,
        )
        params["requant_multipliers"][name] = mult
        params["requant_scales"][name] = rq_scale

    fake_quant_acc = fake_quant_eval(model, params, test_loader, device)

    write_header(args.header_out, params)
    write_scales(args.scales_out, params, fake_quant_acc)

    print(f"loaded={args.checkpoint}")
    print(f"float_test_acc={ckpt.get('test_acc', 0.0) * 100:.2f}%")
    print(f"fake_quant_test_acc={fake_quant_acc * 100:.2f}%")
    print(f"wrote={args.header_out}")
    print(f"wrote={args.scales_out}")


if __name__ == "__main__":
    main()
