import argparse
import csv
import re
from pathlib import Path


PARAM_ORDER = [
    ("conv1_weight_int8", "int8"),
    ("conv1_bias_int32", "int32"),
    ("conv1_requant_multiplier", "int32_scalar"),
    ("conv2_weight_int8", "int8"),
    ("conv2_bias_int32", "int32"),
    ("conv2_requant_multiplier", "int32_scalar"),
    ("conv3_weight_int8", "int8"),
    ("conv3_bias_int32", "int32"),
    ("conv3_requant_multiplier", "int32_scalar"),
    ("fc1_weight_int8", "int8"),
    ("fc1_bias_int32", "int32"),
    ("fc1_requant_multiplier", "int32_scalar"),
    ("fc2_weight_int8", "int8"),
    ("fc2_bias_int32", "int32"),
    ("fc2_requant_multiplier", "int32_scalar"),
]


def parse_array(text, name):
    pattern = rf"static const (?:int8_t|int32_t) {name}(?:\[[^\]]+\])+ = \{{(.*?)\}};"
    match = re.search(pattern, text, re.S)
    if not match:
        raise ValueError(f"array not found: {name}")
    return [int(x) for x in re.findall(r"-?\d+", match.group(1))]


def parse_scalar(text, name):
    pattern = rf"static const int32_t {name} = (-?\d+);"
    match = re.search(pattern, text)
    if not match:
        raise ValueError(f"scalar not found: {name}")
    return [int(match.group(1))]


def align4(data):
    while len(data) % 4 != 0:
        data.append(0)


def append_int8(data, values):
    for value in values:
        data.append(value & 0xFF)


def append_int32_le(data, values):
    for value in values:
        word = value & 0xFFFFFFFF
        data.append(word & 0xFF)
        data.append((word >> 8) & 0xFF)
        data.append((word >> 16) & 0xFF)
        data.append((word >> 24) & 0xFF)


def bytes_to_words(data):
    words = []
    for i in range(0, len(data), 4):
        b0 = data[i]
        b1 = data[i + 1]
        b2 = data[i + 2]
        b3 = data[i + 3]
        words.append(b0 | (b1 << 8) | (b2 << 16) | (b3 << 24))
    return words


def write_mem(path, words):
    lines = ["@00000000"]
    lines.extend(f"{word:08x}" for word in words)
    path.write_text("\n".join(lines) + "\n", encoding="ascii")


def write_csv(path, rows):
    with path.open("w", newline="", encoding="utf-8") as f:
        writer = csv.DictWriter(
            f,
            fieldnames=[
                "name",
                "type",
                "base_byte",
                "base_word",
                "byte_size",
                "element_count",
                "description",
            ],
        )
        writer.writeheader()
        writer.writerows(rows)


def write_c_header(path, rows):
    lines = [
        "/* Auto-generated by export_rv32i_mem.py */",
        "#ifndef LENET_PARAM_ADDR_H",
        "#define LENET_PARAM_ADDR_H",
        "",
    ]
    for row in rows:
        macro = row["name"].upper() + "_ADDR"
        lines.append(f"#define {macro} 0x{row['base_byte']:08X}")
    lines.extend(
        [
            "",
            "#define LENET_PARAM_TOTAL_BYTES "
            + f"0x{(rows[-1]['base_byte'] + rows[-1]['byte_size']):08X}",
            "",
            "#endif",
        ]
    )
    path.write_text("\n".join(lines) + "\n", encoding="ascii")


def write_markdown(path, rows, total_bytes, total_words, data_depth_words):
    lines = [
        "# RV32I Data Memory Map",
        "",
        "이 문서는 `lenet_int8_params.h`에서 추출한 INT8 weight, INT32 bias, requant multiplier를 RV32I data memory에 배치한 결과입니다.",
        "",
        "## 1. 메모리 포맷",
        "",
        "현재 `Pipeline/src/rtl/data_memory.v`는 32-bit word 배열입니다.",
        "",
        "```text",
        "reg [31:0] mem [0:DEPTH-1]",
        "address = byte_address >> 2",
        "word byte order = little-endian",
        "```",
        "",
        "INT8 weight 4개는 한 word에 다음 순서로 pack됩니다.",
        "",
        "```text",
        "byte address +0 -> word[7:0]",
        "byte address +1 -> word[15:8]",
        "byte address +2 -> word[23:16]",
        "byte address +3 -> word[31:24]",
        "```",
        "",
        "INT32 bias와 multiplier는 signed 32-bit two's complement word로 저장됩니다.",
        "",
        "## 2. 생성 파일",
        "",
        "```text",
        "mem/lenet_params.mem",
        "mem/lenet_params_map.csv",
        "mem/lenet_param_addr.h",
        "docs/Memory_Map.md",
        "```",
        "",
        "## 3. 파라미터 메모리 사용량",
        "",
        f"```text\n총 byte 수: {total_bytes} bytes\n총 word 수: {total_words} words\n기본 data_memory DEPTH: {data_depth_words} words ({data_depth_words * 4} bytes)\n```",
        "",
    ]

    if total_words <= data_depth_words:
        lines.append("파라미터만 저장하는 경우 현재 16K-word data memory 안에 들어갑니다.")
    else:
        lines.append("주의: 파라미터만으로도 현재 data memory DEPTH를 초과합니다. DEPTH를 늘리거나 별도 ROM/BRAM이 필요합니다.")

    lines.extend(
        [
            "",
            "중간 feature map과 stack/data 영역까지 같은 data memory에 넣으려면 현재 64KB는 부족할 수 있습니다. 보드 통합에서는 다음 중 하나를 권장합니다.",
            "",
            "```text",
            "1. data_memory DEPTH를 32768 words 이상으로 확장",
            "2. weight/bias는 별도 ROM/BRAM에 배치",
            "3. feature map buffer를 overwrite 방식으로 재사용",
            "```",
            "",
            "## 4. 파라미터 배치",
            "",
            "| Name | Type | Base Byte | Base Word | Size Bytes | Elements |",
            "|---|---:|---:|---:|---:|---:|",
        ]
    )

    for row in rows:
        lines.append(
            f"| `{row['name']}` | {row['type']} | "
            f"`0x{row['base_byte']:08X}` | `{row['base_word']}` | "
            f"{row['byte_size']} | {row['element_count']} |"
        )

    lines.extend(
        [
            "",
            "## 5. 펌웨어 접근 예시",
            "",
            "```c",
            "#include \"lenet_param_addr.h\"",
            "",
            "int8_t w0 = load_i8(CONV1_WEIGHT_INT8_ADDR + offset);",
            "int32_t b0 = load_i32(CONV1_BIAS_INT32_ADDR + oc * 4);",
            "int32_t mult = load_i32(CONV1_REQUANT_MULTIPLIER_ADDR);",
            "```",
            "",
            "CNN_ALU의 `CMD_LOAD_A_PACK4`, `CMD_LOAD_W_PACK4`는 data memory load가 아닙니다. RV32I가 위 주소에서 기존 `LB/LW`로 값을 읽고, 4개 INT8을 pack한 뒤 CNN_ALU custom instruction으로 전달해야 합니다.",
        ]
    )
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--params", type=Path, default=Path("lenet_int8_params.h"))
    parser.add_argument("--out-dir", type=Path, default=Path("mem"))
    parser.add_argument("--docs-dir", type=Path, default=Path("docs"))
    parser.add_argument("--data-depth-words", type=int, default=16384)
    args = parser.parse_args()

    text = args.params.read_text(encoding="utf-8")
    args.out_dir.mkdir(parents=True, exist_ok=True)
    args.docs_dir.mkdir(parents=True, exist_ok=True)

    data = []
    rows = []

    for name, kind in PARAM_ORDER:
        align4(data)
        base_byte = len(data)

        if kind == "int8":
            values = parse_array(text, name)
            append_int8(data, values)
        elif kind == "int32":
            values = parse_array(text, name)
            append_int32_le(data, values)
        elif kind == "int32_scalar":
            values = parse_scalar(text, name)
            append_int32_le(data, values)
        else:
            raise ValueError(f"unknown kind: {kind}")

        rows.append(
            {
                "name": name,
                "type": kind,
                "base_byte": base_byte,
                "base_word": base_byte // 4,
                "byte_size": len(data) - base_byte,
                "element_count": len(values),
                "description": "",
            }
        )

    align4(data)
    words = bytes_to_words(data)

    write_mem(args.out_dir / "lenet_params.mem", words)
    write_csv(args.out_dir / "lenet_params_map.csv", rows)
    write_c_header(args.out_dir / "lenet_param_addr.h", rows)
    write_markdown(
        args.docs_dir / "Memory_Map.md",
        rows,
        total_bytes=len(data),
        total_words=len(words),
        data_depth_words=args.data_depth_words,
    )

    print(f"wrote={args.out_dir / 'lenet_params.mem'} words={len(words)} bytes={len(data)}")
    print(f"wrote={args.out_dir / 'lenet_params_map.csv'}")
    print(f"wrote={args.out_dir / 'lenet_param_addr.h'}")
    print(f"wrote={args.docs_dir / 'Memory_Map.md'}")


if __name__ == "__main__":
    main()
