-- ==============================================================
-- RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
-- Version: 2019.1
-- Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity CNN_ALU_Top is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    rs1_data_V : IN STD_LOGIC_VECTOR (31 downto 0);
    cnn_op_V : IN STD_LOGIC_VECTOR (3 downto 0);
    rd_data_V : OUT STD_LOGIC_VECTOR (31 downto 0) );
end;


architecture behav of CNN_ALU_Top is 
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "CNN_ALU_Top,hls_ip_2019_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=1,HLS_INPUT_PART=xc7z020-clg484-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=8.510000,HLS_SYN_LAT=3,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=12,HLS_SYN_FF=1334,HLS_SYN_LUT=1540,HLS_VERSION=2019_1}";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (9 downto 0) := "0000000001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (9 downto 0) := "0000000010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (9 downto 0) := "0000000100";
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (9 downto 0) := "0000001000";
    constant ap_ST_fsm_state6 : STD_LOGIC_VECTOR (9 downto 0) := "0000010000";
    constant ap_ST_fsm_state7 : STD_LOGIC_VECTOR (9 downto 0) := "0000100000";
    constant ap_ST_fsm_pp1_stage0 : STD_LOGIC_VECTOR (9 downto 0) := "0001000000";
    constant ap_ST_fsm_state10 : STD_LOGIC_VECTOR (9 downto 0) := "0010000000";
    constant ap_ST_fsm_state11 : STD_LOGIC_VECTOR (9 downto 0) := "0100000000";
    constant ap_ST_fsm_state12 : STD_LOGIC_VECTOR (9 downto 0) := "1000000000";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv8_0 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    constant ap_const_lv7_0 : STD_LOGIC_VECTOR (6 downto 0) := "0000000";
    constant ap_const_lv4_9 : STD_LOGIC_VECTOR (3 downto 0) := "1001";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv32_6 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000110";
    constant ap_const_lv4_6 : STD_LOGIC_VECTOR (3 downto 0) := "0110";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv4_2 : STD_LOGIC_VECTOR (3 downto 0) := "0010";
    constant ap_const_lv19_0 : STD_LOGIC_VECTOR (18 downto 0) := "0000000000000000000";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv3_7 : STD_LOGIC_VECTOR (2 downto 0) := "111";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv3_1 : STD_LOGIC_VECTOR (2 downto 0) := "001";
    constant ap_const_lv3_2 : STD_LOGIC_VECTOR (2 downto 0) := "010";
    constant ap_const_lv3_3 : STD_LOGIC_VECTOR (2 downto 0) := "011";
    constant ap_const_lv3_4 : STD_LOGIC_VECTOR (2 downto 0) := "100";
    constant ap_const_lv3_5 : STD_LOGIC_VECTOR (2 downto 0) := "101";
    constant ap_const_lv3_6 : STD_LOGIC_VECTOR (2 downto 0) := "110";
    constant ap_const_lv7_4 : STD_LOGIC_VECTOR (6 downto 0) := "0000100";
    constant ap_const_lv7_8 : STD_LOGIC_VECTOR (6 downto 0) := "0001000";
    constant ap_const_lv7_C : STD_LOGIC_VECTOR (6 downto 0) := "0001100";
    constant ap_const_lv7_10 : STD_LOGIC_VECTOR (6 downto 0) := "0010000";
    constant ap_const_lv7_14 : STD_LOGIC_VECTOR (6 downto 0) := "0010100";
    constant ap_const_lv7_18 : STD_LOGIC_VECTOR (6 downto 0) := "0011000";
    constant ap_const_lv4_1 : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    constant ap_const_lv4_7 : STD_LOGIC_VECTOR (3 downto 0) := "0111";
    constant ap_const_lv4_8 : STD_LOGIC_VECTOR (3 downto 0) := "1000";
    constant ap_const_lv4_5 : STD_LOGIC_VECTOR (3 downto 0) := "0101";
    constant ap_const_lv4_4 : STD_LOGIC_VECTOR (3 downto 0) := "0100";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000101";
    constant ap_const_lv32_7 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000111";
    constant ap_const_lv4_3 : STD_LOGIC_VECTOR (3 downto 0) := "0011";
    constant ap_const_lv32_8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001000";
    constant ap_const_lv32_F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001111";
    constant ap_const_lv32_10 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010000";
    constant ap_const_lv32_17 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010111";
    constant ap_const_lv32_18 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011000";
    constant ap_const_lv32_1F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011111";
    constant ap_const_lv64_80000 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000010000000000000000000";
    constant ap_const_lv32_14 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010100";
    constant ap_const_lv32_33 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000110011";
    constant ap_const_lv32_1B : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011011";
    constant ap_const_lv25_0 : STD_LOGIC_VECTOR (24 downto 0) := "0000000000000000000000000";
    constant ap_const_lv32_7F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001111111";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";

    signal ap_CS_fsm : STD_LOGIC_VECTOR (9 downto 0) := "0000000001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal weight_buf_V_0 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal weight_buf_V_1 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal weight_buf_V_2 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal weight_buf_V_3 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal weight_buf_V_4 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal weight_buf_V_5 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal weight_buf_V_6 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal weight_buf_V_7 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal weight_buf_V_8 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal weight_buf_V_9 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal weight_buf_V_10 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal weight_buf_V_11 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal weight_buf_V_12 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal weight_buf_V_13 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal weight_buf_V_14 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal weight_buf_V_15 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal weight_buf_V_16 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal weight_buf_V_17 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal weight_buf_V_18 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal weight_buf_V_19 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal weight_buf_V_20 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal weight_buf_V_21 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal weight_buf_V_22 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal weight_buf_V_23 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal weight_buf_V_24 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal act_buf_V_0 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal act_buf_V_1 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal act_buf_V_2 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal act_buf_V_3 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal act_buf_V_4 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal act_buf_V_5 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal act_buf_V_6 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal act_buf_V_7 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal act_buf_V_8 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal act_buf_V_9 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal act_buf_V_10 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal act_buf_V_11 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal act_buf_V_12 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal act_buf_V_13 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal act_buf_V_14 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal act_buf_V_15 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal act_buf_V_16 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal act_buf_V_17 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal act_buf_V_18 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal act_buf_V_19 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal act_buf_V_20 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal act_buf_V_21 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal act_buf_V_22 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal act_buf_V_23 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal act_buf_V_24 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal acc_reg_V : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal w_ptr : STD_LOGIC_VECTOR (6 downto 0) := "0000000";
    signal a_ptr : STD_LOGIC_VECTOR (6 downto 0) := "0000000";
    signal p_0217_0_i_reg_261 : STD_LOGIC_VECTOR (18 downto 0);
    signal p_0111_0_i_reg_273 : STD_LOGIC_VECTOR (18 downto 0);
    signal p_0107_0_i_reg_285 : STD_LOGIC_VECTOR (18 downto 0);
    signal p_0103_0_i_reg_297 : STD_LOGIC_VECTOR (18 downto 0);
    signal i_0_i_reg_309 : STD_LOGIC_VECTOR (3 downto 0);
    signal p_0217_0_i168_reg_343 : STD_LOGIC_VECTOR (18 downto 0);
    signal p_0111_0_i169_reg_355 : STD_LOGIC_VECTOR (18 downto 0);
    signal p_0107_0_i170_reg_367 : STD_LOGIC_VECTOR (18 downto 0);
    signal p_0103_0_i171_reg_379 : STD_LOGIC_VECTOR (18 downto 0);
    signal i_0_i172_reg_391 : STD_LOGIC_VECTOR (3 downto 0);
    signal cnn_op_V_read_read_fu_242_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal weight_buf_V_0_load_reg_1847 : STD_LOGIC_VECTOR (7 downto 0);
    signal weight_buf_V_1_load_reg_1853 : STD_LOGIC_VECTOR (7 downto 0);
    signal weight_buf_V_2_load_reg_1859 : STD_LOGIC_VECTOR (7 downto 0);
    signal weight_buf_V_3_load_reg_1865 : STD_LOGIC_VECTOR (7 downto 0);
    signal weight_buf_V_4_load_reg_1871 : STD_LOGIC_VECTOR (7 downto 0);
    signal weight_buf_V_5_load_reg_1877 : STD_LOGIC_VECTOR (7 downto 0);
    signal weight_buf_V_6_load_reg_1883 : STD_LOGIC_VECTOR (7 downto 0);
    signal weight_buf_V_7_load_reg_1889 : STD_LOGIC_VECTOR (7 downto 0);
    signal weight_buf_V_8_load_reg_1895 : STD_LOGIC_VECTOR (7 downto 0);
    signal weight_buf_V_9_load_reg_1901 : STD_LOGIC_VECTOR (7 downto 0);
    signal weight_buf_V_10_load_reg_1907 : STD_LOGIC_VECTOR (7 downto 0);
    signal weight_buf_V_11_load_reg_1913 : STD_LOGIC_VECTOR (7 downto 0);
    signal weight_buf_V_12_load_reg_1919 : STD_LOGIC_VECTOR (7 downto 0);
    signal weight_buf_V_13_load_reg_1925 : STD_LOGIC_VECTOR (7 downto 0);
    signal weight_buf_V_14_load_reg_1931 : STD_LOGIC_VECTOR (7 downto 0);
    signal weight_buf_V_15_load_reg_1937 : STD_LOGIC_VECTOR (7 downto 0);
    signal weight_buf_V_16_load_reg_1943 : STD_LOGIC_VECTOR (7 downto 0);
    signal weight_buf_V_17_load_reg_1949 : STD_LOGIC_VECTOR (7 downto 0);
    signal weight_buf_V_18_load_reg_1955 : STD_LOGIC_VECTOR (7 downto 0);
    signal weight_buf_V_19_load_reg_1961 : STD_LOGIC_VECTOR (7 downto 0);
    signal weight_buf_V_20_load_reg_1967 : STD_LOGIC_VECTOR (7 downto 0);
    signal weight_buf_V_21_load_reg_1973 : STD_LOGIC_VECTOR (7 downto 0);
    signal weight_buf_V_22_load_reg_1979 : STD_LOGIC_VECTOR (7 downto 0);
    signal weight_buf_V_23_load_reg_1985 : STD_LOGIC_VECTOR (7 downto 0);
    signal weight_buf_V_24_load_reg_1991 : STD_LOGIC_VECTOR (7 downto 0);
    signal act_buf_V_0_load_reg_1997 : STD_LOGIC_VECTOR (7 downto 0);
    signal act_buf_V_1_load_reg_2003 : STD_LOGIC_VECTOR (7 downto 0);
    signal act_buf_V_2_load_reg_2009 : STD_LOGIC_VECTOR (7 downto 0);
    signal act_buf_V_3_load_reg_2015 : STD_LOGIC_VECTOR (7 downto 0);
    signal act_buf_V_4_load_reg_2021 : STD_LOGIC_VECTOR (7 downto 0);
    signal act_buf_V_5_load_reg_2027 : STD_LOGIC_VECTOR (7 downto 0);
    signal act_buf_V_6_load_reg_2033 : STD_LOGIC_VECTOR (7 downto 0);
    signal act_buf_V_7_load_reg_2039 : STD_LOGIC_VECTOR (7 downto 0);
    signal act_buf_V_8_load_reg_2045 : STD_LOGIC_VECTOR (7 downto 0);
    signal act_buf_V_9_load_reg_2051 : STD_LOGIC_VECTOR (7 downto 0);
    signal act_buf_V_10_load_reg_2057 : STD_LOGIC_VECTOR (7 downto 0);
    signal act_buf_V_11_load_reg_2063 : STD_LOGIC_VECTOR (7 downto 0);
    signal act_buf_V_12_load_reg_2069 : STD_LOGIC_VECTOR (7 downto 0);
    signal act_buf_V_13_load_reg_2075 : STD_LOGIC_VECTOR (7 downto 0);
    signal act_buf_V_14_load_reg_2081 : STD_LOGIC_VECTOR (7 downto 0);
    signal act_buf_V_15_load_reg_2087 : STD_LOGIC_VECTOR (7 downto 0);
    signal act_buf_V_16_load_reg_2093 : STD_LOGIC_VECTOR (7 downto 0);
    signal act_buf_V_17_load_reg_2099 : STD_LOGIC_VECTOR (7 downto 0);
    signal act_buf_V_18_load_reg_2105 : STD_LOGIC_VECTOR (7 downto 0);
    signal act_buf_V_19_load_reg_2111 : STD_LOGIC_VECTOR (7 downto 0);
    signal act_buf_V_20_load_reg_2117 : STD_LOGIC_VECTOR (7 downto 0);
    signal act_buf_V_21_load_reg_2123 : STD_LOGIC_VECTOR (7 downto 0);
    signal act_buf_V_22_load_reg_2129 : STD_LOGIC_VECTOR (7 downto 0);
    signal act_buf_V_23_load_reg_2135 : STD_LOGIC_VECTOR (7 downto 0);
    signal act_buf_V_24_load_reg_2141 : STD_LOGIC_VECTOR (7 downto 0);
    signal acc_reg_V_load_reg_2147 : STD_LOGIC_VECTOR (31 downto 0);
    signal product_V_fu_686_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal product_V_reg_2153 : STD_LOGIC_VECTOR (63 downto 0);
    signal select_ln899_1_fu_1250_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal select_ln899_1_reg_2167 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal icmp_ln168_1_fu_1263_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln168_1_reg_2172 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_block_state4_pp0_stage0_iter0 : BOOLEAN;
    signal ap_block_state5_pp0_stage0_iter1 : BOOLEAN;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal i_1_fu_1269_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC := '0';
    signal trunc_ln68_1_fu_1275_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal phi_ln68_3_fu_1287_p34 : STD_LOGIC_VECTOR (7 downto 0);
    signal phi_ln68_3_reg_2185 : STD_LOGIC_VECTOR (7 downto 0);
    signal phi_ln68_5_fu_1350_p10 : STD_LOGIC_VECTOR (7 downto 0);
    signal phi_ln68_5_reg_2190 : STD_LOGIC_VECTOR (7 downto 0);
    signal phi_ln68_7_fu_1366_p10 : STD_LOGIC_VECTOR (7 downto 0);
    signal phi_ln68_7_reg_2195 : STD_LOGIC_VECTOR (7 downto 0);
    signal phi_ln68_9_fu_1382_p10 : STD_LOGIC_VECTOR (7 downto 0);
    signal phi_ln68_9_reg_2200 : STD_LOGIC_VECTOR (7 downto 0);
    signal phi_ln68_11_fu_1398_p10 : STD_LOGIC_VECTOR (7 downto 0);
    signal phi_ln68_11_reg_2205 : STD_LOGIC_VECTOR (7 downto 0);
    signal phi_ln68_13_fu_1414_p10 : STD_LOGIC_VECTOR (7 downto 0);
    signal phi_ln68_13_reg_2210 : STD_LOGIC_VECTOR (7 downto 0);
    signal phi_ln68_14_fu_1430_p10 : STD_LOGIC_VECTOR (7 downto 0);
    signal phi_ln68_14_reg_2215 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_fu_1779_p3 : STD_LOGIC_VECTOR (18 downto 0);
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal grp_fu_1787_p3 : STD_LOGIC_VECTOR (18 downto 0);
    signal grp_fu_1795_p3 : STD_LOGIC_VECTOR (18 downto 0);
    signal grp_fu_1803_p3 : STD_LOGIC_VECTOR (18 downto 0);
    signal add_ln700_1_fu_1508_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln700_1_reg_2240 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state6 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state6 : signal is "none";
    signal icmp_ln168_fu_1519_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln168_reg_2245 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_pp1_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp1_stage0 : signal is "none";
    signal ap_block_state8_pp1_stage0_iter0 : BOOLEAN;
    signal ap_block_state9_pp1_stage0_iter1 : BOOLEAN;
    signal ap_block_pp1_stage0_11001 : BOOLEAN;
    signal i_fu_1525_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_enable_reg_pp1_iter0 : STD_LOGIC := '0';
    signal trunc_ln68_fu_1531_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal phi_ln68_2_fu_1543_p34 : STD_LOGIC_VECTOR (7 downto 0);
    signal phi_ln68_2_reg_2258 : STD_LOGIC_VECTOR (7 downto 0);
    signal phi_ln68_4_fu_1606_p10 : STD_LOGIC_VECTOR (7 downto 0);
    signal phi_ln68_4_reg_2263 : STD_LOGIC_VECTOR (7 downto 0);
    signal phi_ln68_6_fu_1622_p10 : STD_LOGIC_VECTOR (7 downto 0);
    signal phi_ln68_6_reg_2268 : STD_LOGIC_VECTOR (7 downto 0);
    signal phi_ln68_8_fu_1638_p10 : STD_LOGIC_VECTOR (7 downto 0);
    signal phi_ln68_8_reg_2273 : STD_LOGIC_VECTOR (7 downto 0);
    signal phi_ln68_s_fu_1654_p10 : STD_LOGIC_VECTOR (7 downto 0);
    signal phi_ln68_s_reg_2278 : STD_LOGIC_VECTOR (7 downto 0);
    signal phi_ln68_10_fu_1670_p10 : STD_LOGIC_VECTOR (7 downto 0);
    signal phi_ln68_10_reg_2283 : STD_LOGIC_VECTOR (7 downto 0);
    signal phi_ln68_12_fu_1686_p10 : STD_LOGIC_VECTOR (7 downto 0);
    signal phi_ln68_12_reg_2288 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_fu_1811_p3 : STD_LOGIC_VECTOR (18 downto 0);
    signal ap_enable_reg_pp1_iter1 : STD_LOGIC := '0';
    signal grp_fu_1819_p3 : STD_LOGIC_VECTOR (18 downto 0);
    signal grp_fu_1827_p3 : STD_LOGIC_VECTOR (18 downto 0);
    signal grp_fu_1835_p3 : STD_LOGIC_VECTOR (18 downto 0);
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal ap_condition_pp0_exit_iter0_state4 : STD_LOGIC;
    signal ap_block_pp1_stage0_subdone : BOOLEAN;
    signal ap_condition_pp1_exit_iter0_state8 : STD_LOGIC;
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal ap_phi_reg_pp0_iter0_phi_ln68_1_reg_320 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_reg_pp0_iter1_phi_ln68_1_reg_320 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_block_pp1_stage0 : BOOLEAN;
    signal ap_phi_reg_pp1_iter0_phi_ln68_reg_402 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_reg_pp1_iter1_phi_ln68_reg_402 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln647_fu_1166_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal w_ptr_load_load_fu_982_p1 : STD_LOGIC_VECTOR (6 downto 0);
    signal trunc_ln647_1_fu_1132_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln647_2_fu_1098_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln647_3_fu_1064_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln647_4_fu_1030_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln647_5_fu_996_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln647_6_fu_986_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln647_7_fu_948_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal a_ptr_load_load_fu_764_p1 : STD_LOGIC_VECTOR (6 downto 0);
    signal trunc_ln647_8_fu_914_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln647_9_fu_880_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln647_10_fu_846_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln647_11_fu_812_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln647_12_fu_778_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln647_13_fu_768_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_2_fu_692_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln700_fu_700_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal sext_ln68_fu_754_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal ap_CS_fsm_state7 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state7 : signal is "none";
    signal sext_ln68_4_fu_1769_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state10 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state10 : signal is "none";
    signal rd_data_V_preg : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal grp_fu_443_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_453_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_463_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal sext_ln68_1_fu_682_p0 : STD_LOGIC_VECTOR (31 downto 0);
    signal product_V_fu_686_p0 : STD_LOGIC_VECTOR (31 downto 0);
    signal product_V_fu_686_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln700_fu_700_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal icmp_ln895_fu_712_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln895_1_fu_726_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal max1_V_fu_718_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal max2_V_fu_732_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal icmp_ln895_2_fu_740_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal final_max_V_fu_746_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln647_13_fu_768_p0 : STD_LOGIC_VECTOR (31 downto 0);
    signal trunc_ln647_12_fu_778_p0 : STD_LOGIC_VECTOR (31 downto 0);
    signal trunc_ln647_11_fu_812_p0 : STD_LOGIC_VECTOR (31 downto 0);
    signal trunc_ln647_10_fu_846_p0 : STD_LOGIC_VECTOR (31 downto 0);
    signal trunc_ln647_9_fu_880_p0 : STD_LOGIC_VECTOR (31 downto 0);
    signal trunc_ln647_8_fu_914_p0 : STD_LOGIC_VECTOR (31 downto 0);
    signal trunc_ln647_7_fu_948_p0 : STD_LOGIC_VECTOR (31 downto 0);
    signal trunc_ln647_6_fu_986_p0 : STD_LOGIC_VECTOR (31 downto 0);
    signal trunc_ln647_5_fu_996_p0 : STD_LOGIC_VECTOR (31 downto 0);
    signal trunc_ln647_4_fu_1030_p0 : STD_LOGIC_VECTOR (31 downto 0);
    signal trunc_ln647_3_fu_1064_p0 : STD_LOGIC_VECTOR (31 downto 0);
    signal trunc_ln647_2_fu_1098_p0 : STD_LOGIC_VECTOR (31 downto 0);
    signal trunc_ln647_1_fu_1132_p0 : STD_LOGIC_VECTOR (31 downto 0);
    signal trunc_ln647_fu_1166_p0 : STD_LOGIC_VECTOR (31 downto 0);
    signal rounded_V_fu_1205_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal tmp_3_fu_1220_p4 : STD_LOGIC_VECTOR (24 downto 0);
    signal icmp_ln899_fu_1200_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln895_3_fu_1230_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln899_fu_1244_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln899_fu_1236_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal scaled_V_fu_1210_p4 : STD_LOGIC_VECTOR (31 downto 0);
    signal phi_ln68_3_fu_1287_p33 : STD_LOGIC_VECTOR (4 downto 0);
    signal sext_ln168_6_fu_1479_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal sext_ln168_5_fu_1475_p1 : STD_LOGIC_VECTOR (19 downto 0);
    signal sext_ln168_4_fu_1471_p1 : STD_LOGIC_VECTOR (19 downto 0);
    signal add_ln700_3_fu_1492_p2 : STD_LOGIC_VECTOR (19 downto 0);
    signal sext_ln168_7_fu_1483_p1 : STD_LOGIC_VECTOR (19 downto 0);
    signal add_ln700_4_fu_1498_p2 : STD_LOGIC_VECTOR (19 downto 0);
    signal sext_ln700_fu_1504_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln700_2_fu_1487_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal phi_ln68_2_fu_1543_p33 : STD_LOGIC_VECTOR (4 downto 0);
    signal sext_ln168_2_fu_1735_p1 : STD_LOGIC_VECTOR (19 downto 0);
    signal sext_ln168_3_fu_1739_p1 : STD_LOGIC_VECTOR (19 downto 0);
    signal add_ln68_fu_1743_p2 : STD_LOGIC_VECTOR (19 downto 0);
    signal sext_ln168_1_fu_1731_p1 : STD_LOGIC_VECTOR (19 downto 0);
    signal sext_ln168_fu_1727_p1 : STD_LOGIC_VECTOR (19 downto 0);
    signal add_ln68_1_fu_1753_p2 : STD_LOGIC_VECTOR (19 downto 0);
    signal sext_ln68_3_fu_1759_p1 : STD_LOGIC_VECTOR (20 downto 0);
    signal sext_ln68_2_fu_1749_p1 : STD_LOGIC_VECTOR (20 downto 0);
    signal add_ln68_2_fu_1763_p2 : STD_LOGIC_VECTOR (20 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (9 downto 0);
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_idle_pp1 : STD_LOGIC;
    signal ap_enable_pp1 : STD_LOGIC;
    signal product_V_fu_686_p00 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_condition_249 : BOOLEAN;
    signal ap_condition_308 : BOOLEAN;

    component CNN_ALU_Top_mux_3bkb IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        din2_WIDTH : INTEGER;
        din3_WIDTH : INTEGER;
        din4_WIDTH : INTEGER;
        din5_WIDTH : INTEGER;
        din6_WIDTH : INTEGER;
        din7_WIDTH : INTEGER;
        din8_WIDTH : INTEGER;
        din9_WIDTH : INTEGER;
        din10_WIDTH : INTEGER;
        din11_WIDTH : INTEGER;
        din12_WIDTH : INTEGER;
        din13_WIDTH : INTEGER;
        din14_WIDTH : INTEGER;
        din15_WIDTH : INTEGER;
        din16_WIDTH : INTEGER;
        din17_WIDTH : INTEGER;
        din18_WIDTH : INTEGER;
        din19_WIDTH : INTEGER;
        din20_WIDTH : INTEGER;
        din21_WIDTH : INTEGER;
        din22_WIDTH : INTEGER;
        din23_WIDTH : INTEGER;
        din24_WIDTH : INTEGER;
        din25_WIDTH : INTEGER;
        din26_WIDTH : INTEGER;
        din27_WIDTH : INTEGER;
        din28_WIDTH : INTEGER;
        din29_WIDTH : INTEGER;
        din30_WIDTH : INTEGER;
        din31_WIDTH : INTEGER;
        din32_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (7 downto 0);
        din1 : IN STD_LOGIC_VECTOR (7 downto 0);
        din2 : IN STD_LOGIC_VECTOR (7 downto 0);
        din3 : IN STD_LOGIC_VECTOR (7 downto 0);
        din4 : IN STD_LOGIC_VECTOR (7 downto 0);
        din5 : IN STD_LOGIC_VECTOR (7 downto 0);
        din6 : IN STD_LOGIC_VECTOR (7 downto 0);
        din7 : IN STD_LOGIC_VECTOR (7 downto 0);
        din8 : IN STD_LOGIC_VECTOR (7 downto 0);
        din9 : IN STD_LOGIC_VECTOR (7 downto 0);
        din10 : IN STD_LOGIC_VECTOR (7 downto 0);
        din11 : IN STD_LOGIC_VECTOR (7 downto 0);
        din12 : IN STD_LOGIC_VECTOR (7 downto 0);
        din13 : IN STD_LOGIC_VECTOR (7 downto 0);
        din14 : IN STD_LOGIC_VECTOR (7 downto 0);
        din15 : IN STD_LOGIC_VECTOR (7 downto 0);
        din16 : IN STD_LOGIC_VECTOR (7 downto 0);
        din17 : IN STD_LOGIC_VECTOR (7 downto 0);
        din18 : IN STD_LOGIC_VECTOR (7 downto 0);
        din19 : IN STD_LOGIC_VECTOR (7 downto 0);
        din20 : IN STD_LOGIC_VECTOR (7 downto 0);
        din21 : IN STD_LOGIC_VECTOR (7 downto 0);
        din22 : IN STD_LOGIC_VECTOR (7 downto 0);
        din23 : IN STD_LOGIC_VECTOR (7 downto 0);
        din24 : IN STD_LOGIC_VECTOR (7 downto 0);
        din25 : IN STD_LOGIC_VECTOR (7 downto 0);
        din26 : IN STD_LOGIC_VECTOR (7 downto 0);
        din27 : IN STD_LOGIC_VECTOR (7 downto 0);
        din28 : IN STD_LOGIC_VECTOR (7 downto 0);
        din29 : IN STD_LOGIC_VECTOR (7 downto 0);
        din30 : IN STD_LOGIC_VECTOR (7 downto 0);
        din31 : IN STD_LOGIC_VECTOR (7 downto 0);
        din32 : IN STD_LOGIC_VECTOR (4 downto 0);
        dout : OUT STD_LOGIC_VECTOR (7 downto 0) );
    end component;


    component CNN_ALU_Top_mux_8cud IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        din2_WIDTH : INTEGER;
        din3_WIDTH : INTEGER;
        din4_WIDTH : INTEGER;
        din5_WIDTH : INTEGER;
        din6_WIDTH : INTEGER;
        din7_WIDTH : INTEGER;
        din8_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (7 downto 0);
        din1 : IN STD_LOGIC_VECTOR (7 downto 0);
        din2 : IN STD_LOGIC_VECTOR (7 downto 0);
        din3 : IN STD_LOGIC_VECTOR (7 downto 0);
        din4 : IN STD_LOGIC_VECTOR (7 downto 0);
        din5 : IN STD_LOGIC_VECTOR (7 downto 0);
        din6 : IN STD_LOGIC_VECTOR (7 downto 0);
        din7 : IN STD_LOGIC_VECTOR (7 downto 0);
        din8 : IN STD_LOGIC_VECTOR (2 downto 0);
        dout : OUT STD_LOGIC_VECTOR (7 downto 0) );
    end component;


    component CNN_ALU_Top_mac_mdEe IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        din2_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (7 downto 0);
        din1 : IN STD_LOGIC_VECTOR (7 downto 0);
        din2 : IN STD_LOGIC_VECTOR (18 downto 0);
        dout : OUT STD_LOGIC_VECTOR (18 downto 0) );
    end component;



begin
    CNN_ALU_Top_mux_3bkb_U1 : component CNN_ALU_Top_mux_3bkb
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 8,
        din1_WIDTH => 8,
        din2_WIDTH => 8,
        din3_WIDTH => 8,
        din4_WIDTH => 8,
        din5_WIDTH => 8,
        din6_WIDTH => 8,
        din7_WIDTH => 8,
        din8_WIDTH => 8,
        din9_WIDTH => 8,
        din10_WIDTH => 8,
        din11_WIDTH => 8,
        din12_WIDTH => 8,
        din13_WIDTH => 8,
        din14_WIDTH => 8,
        din15_WIDTH => 8,
        din16_WIDTH => 8,
        din17_WIDTH => 8,
        din18_WIDTH => 8,
        din19_WIDTH => 8,
        din20_WIDTH => 8,
        din21_WIDTH => 8,
        din22_WIDTH => 8,
        din23_WIDTH => 8,
        din24_WIDTH => 8,
        din25_WIDTH => 8,
        din26_WIDTH => 8,
        din27_WIDTH => 8,
        din28_WIDTH => 8,
        din29_WIDTH => 8,
        din30_WIDTH => 8,
        din31_WIDTH => 8,
        din32_WIDTH => 5,
        dout_WIDTH => 8)
    port map (
        din0 => weight_buf_V_0_load_reg_1847,
        din1 => ap_const_lv8_0,
        din2 => ap_const_lv8_0,
        din3 => ap_const_lv8_0,
        din4 => weight_buf_V_4_load_reg_1871,
        din5 => ap_const_lv8_0,
        din6 => ap_const_lv8_0,
        din7 => ap_const_lv8_0,
        din8 => weight_buf_V_8_load_reg_1895,
        din9 => ap_const_lv8_0,
        din10 => ap_const_lv8_0,
        din11 => ap_const_lv8_0,
        din12 => weight_buf_V_12_load_reg_1919,
        din13 => ap_const_lv8_0,
        din14 => ap_const_lv8_0,
        din15 => ap_const_lv8_0,
        din16 => weight_buf_V_16_load_reg_1943,
        din17 => ap_const_lv8_0,
        din18 => ap_const_lv8_0,
        din19 => ap_const_lv8_0,
        din20 => weight_buf_V_20_load_reg_1967,
        din21 => ap_const_lv8_0,
        din22 => ap_const_lv8_0,
        din23 => ap_const_lv8_0,
        din24 => weight_buf_V_24_load_reg_1991,
        din25 => ap_const_lv8_0,
        din26 => ap_const_lv8_0,
        din27 => ap_const_lv8_0,
        din28 => ap_const_lv8_0,
        din29 => ap_const_lv8_0,
        din30 => ap_const_lv8_0,
        din31 => ap_const_lv8_0,
        din32 => phi_ln68_3_fu_1287_p33,
        dout => phi_ln68_3_fu_1287_p34);

    CNN_ALU_Top_mux_8cud_U2 : component CNN_ALU_Top_mux_8cud
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 8,
        din1_WIDTH => 8,
        din2_WIDTH => 8,
        din3_WIDTH => 8,
        din4_WIDTH => 8,
        din5_WIDTH => 8,
        din6_WIDTH => 8,
        din7_WIDTH => 8,
        din8_WIDTH => 3,
        dout_WIDTH => 8)
    port map (
        din0 => act_buf_V_1_load_reg_2003,
        din1 => act_buf_V_5_load_reg_2027,
        din2 => act_buf_V_9_load_reg_2051,
        din3 => act_buf_V_13_load_reg_2075,
        din4 => act_buf_V_17_load_reg_2099,
        din5 => act_buf_V_21_load_reg_2123,
        din6 => ap_const_lv8_0,
        din7 => ap_const_lv8_0,
        din8 => trunc_ln68_1_fu_1275_p1,
        dout => phi_ln68_5_fu_1350_p10);

    CNN_ALU_Top_mux_8cud_U3 : component CNN_ALU_Top_mux_8cud
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 8,
        din1_WIDTH => 8,
        din2_WIDTH => 8,
        din3_WIDTH => 8,
        din4_WIDTH => 8,
        din5_WIDTH => 8,
        din6_WIDTH => 8,
        din7_WIDTH => 8,
        din8_WIDTH => 3,
        dout_WIDTH => 8)
    port map (
        din0 => weight_buf_V_1_load_reg_1853,
        din1 => weight_buf_V_5_load_reg_1877,
        din2 => weight_buf_V_9_load_reg_1901,
        din3 => weight_buf_V_13_load_reg_1925,
        din4 => weight_buf_V_17_load_reg_1949,
        din5 => weight_buf_V_21_load_reg_1973,
        din6 => ap_const_lv8_0,
        din7 => ap_const_lv8_0,
        din8 => trunc_ln68_1_fu_1275_p1,
        dout => phi_ln68_7_fu_1366_p10);

    CNN_ALU_Top_mux_8cud_U4 : component CNN_ALU_Top_mux_8cud
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 8,
        din1_WIDTH => 8,
        din2_WIDTH => 8,
        din3_WIDTH => 8,
        din4_WIDTH => 8,
        din5_WIDTH => 8,
        din6_WIDTH => 8,
        din7_WIDTH => 8,
        din8_WIDTH => 3,
        dout_WIDTH => 8)
    port map (
        din0 => act_buf_V_2_load_reg_2009,
        din1 => act_buf_V_6_load_reg_2033,
        din2 => act_buf_V_10_load_reg_2057,
        din3 => act_buf_V_14_load_reg_2081,
        din4 => act_buf_V_18_load_reg_2105,
        din5 => act_buf_V_22_load_reg_2129,
        din6 => ap_const_lv8_0,
        din7 => ap_const_lv8_0,
        din8 => trunc_ln68_1_fu_1275_p1,
        dout => phi_ln68_9_fu_1382_p10);

    CNN_ALU_Top_mux_8cud_U5 : component CNN_ALU_Top_mux_8cud
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 8,
        din1_WIDTH => 8,
        din2_WIDTH => 8,
        din3_WIDTH => 8,
        din4_WIDTH => 8,
        din5_WIDTH => 8,
        din6_WIDTH => 8,
        din7_WIDTH => 8,
        din8_WIDTH => 3,
        dout_WIDTH => 8)
    port map (
        din0 => weight_buf_V_2_load_reg_1859,
        din1 => weight_buf_V_6_load_reg_1883,
        din2 => weight_buf_V_10_load_reg_1907,
        din3 => weight_buf_V_14_load_reg_1931,
        din4 => weight_buf_V_18_load_reg_1955,
        din5 => weight_buf_V_22_load_reg_1979,
        din6 => ap_const_lv8_0,
        din7 => ap_const_lv8_0,
        din8 => trunc_ln68_1_fu_1275_p1,
        dout => phi_ln68_11_fu_1398_p10);

    CNN_ALU_Top_mux_8cud_U6 : component CNN_ALU_Top_mux_8cud
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 8,
        din1_WIDTH => 8,
        din2_WIDTH => 8,
        din3_WIDTH => 8,
        din4_WIDTH => 8,
        din5_WIDTH => 8,
        din6_WIDTH => 8,
        din7_WIDTH => 8,
        din8_WIDTH => 3,
        dout_WIDTH => 8)
    port map (
        din0 => act_buf_V_3_load_reg_2015,
        din1 => act_buf_V_7_load_reg_2039,
        din2 => act_buf_V_11_load_reg_2063,
        din3 => act_buf_V_15_load_reg_2087,
        din4 => act_buf_V_19_load_reg_2111,
        din5 => act_buf_V_23_load_reg_2135,
        din6 => ap_const_lv8_0,
        din7 => ap_const_lv8_0,
        din8 => trunc_ln68_1_fu_1275_p1,
        dout => phi_ln68_13_fu_1414_p10);

    CNN_ALU_Top_mux_8cud_U7 : component CNN_ALU_Top_mux_8cud
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 8,
        din1_WIDTH => 8,
        din2_WIDTH => 8,
        din3_WIDTH => 8,
        din4_WIDTH => 8,
        din5_WIDTH => 8,
        din6_WIDTH => 8,
        din7_WIDTH => 8,
        din8_WIDTH => 3,
        dout_WIDTH => 8)
    port map (
        din0 => weight_buf_V_3_load_reg_1865,
        din1 => weight_buf_V_7_load_reg_1889,
        din2 => weight_buf_V_11_load_reg_1913,
        din3 => weight_buf_V_15_load_reg_1937,
        din4 => weight_buf_V_19_load_reg_1961,
        din5 => weight_buf_V_23_load_reg_1985,
        din6 => ap_const_lv8_0,
        din7 => ap_const_lv8_0,
        din8 => trunc_ln68_1_fu_1275_p1,
        dout => phi_ln68_14_fu_1430_p10);

    CNN_ALU_Top_mux_3bkb_U8 : component CNN_ALU_Top_mux_3bkb
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 8,
        din1_WIDTH => 8,
        din2_WIDTH => 8,
        din3_WIDTH => 8,
        din4_WIDTH => 8,
        din5_WIDTH => 8,
        din6_WIDTH => 8,
        din7_WIDTH => 8,
        din8_WIDTH => 8,
        din9_WIDTH => 8,
        din10_WIDTH => 8,
        din11_WIDTH => 8,
        din12_WIDTH => 8,
        din13_WIDTH => 8,
        din14_WIDTH => 8,
        din15_WIDTH => 8,
        din16_WIDTH => 8,
        din17_WIDTH => 8,
        din18_WIDTH => 8,
        din19_WIDTH => 8,
        din20_WIDTH => 8,
        din21_WIDTH => 8,
        din22_WIDTH => 8,
        din23_WIDTH => 8,
        din24_WIDTH => 8,
        din25_WIDTH => 8,
        din26_WIDTH => 8,
        din27_WIDTH => 8,
        din28_WIDTH => 8,
        din29_WIDTH => 8,
        din30_WIDTH => 8,
        din31_WIDTH => 8,
        din32_WIDTH => 5,
        dout_WIDTH => 8)
    port map (
        din0 => weight_buf_V_0_load_reg_1847,
        din1 => ap_const_lv8_0,
        din2 => ap_const_lv8_0,
        din3 => ap_const_lv8_0,
        din4 => weight_buf_V_4_load_reg_1871,
        din5 => ap_const_lv8_0,
        din6 => ap_const_lv8_0,
        din7 => ap_const_lv8_0,
        din8 => weight_buf_V_8_load_reg_1895,
        din9 => ap_const_lv8_0,
        din10 => ap_const_lv8_0,
        din11 => ap_const_lv8_0,
        din12 => weight_buf_V_12_load_reg_1919,
        din13 => ap_const_lv8_0,
        din14 => ap_const_lv8_0,
        din15 => ap_const_lv8_0,
        din16 => weight_buf_V_16_load_reg_1943,
        din17 => ap_const_lv8_0,
        din18 => ap_const_lv8_0,
        din19 => ap_const_lv8_0,
        din20 => weight_buf_V_20_load_reg_1967,
        din21 => ap_const_lv8_0,
        din22 => ap_const_lv8_0,
        din23 => ap_const_lv8_0,
        din24 => weight_buf_V_24_load_reg_1991,
        din25 => ap_const_lv8_0,
        din26 => ap_const_lv8_0,
        din27 => ap_const_lv8_0,
        din28 => ap_const_lv8_0,
        din29 => ap_const_lv8_0,
        din30 => ap_const_lv8_0,
        din31 => ap_const_lv8_0,
        din32 => phi_ln68_2_fu_1543_p33,
        dout => phi_ln68_2_fu_1543_p34);

    CNN_ALU_Top_mux_8cud_U9 : component CNN_ALU_Top_mux_8cud
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 8,
        din1_WIDTH => 8,
        din2_WIDTH => 8,
        din3_WIDTH => 8,
        din4_WIDTH => 8,
        din5_WIDTH => 8,
        din6_WIDTH => 8,
        din7_WIDTH => 8,
        din8_WIDTH => 3,
        dout_WIDTH => 8)
    port map (
        din0 => act_buf_V_1_load_reg_2003,
        din1 => act_buf_V_5_load_reg_2027,
        din2 => act_buf_V_9_load_reg_2051,
        din3 => act_buf_V_13_load_reg_2075,
        din4 => act_buf_V_17_load_reg_2099,
        din5 => act_buf_V_21_load_reg_2123,
        din6 => ap_const_lv8_0,
        din7 => ap_const_lv8_0,
        din8 => trunc_ln68_fu_1531_p1,
        dout => phi_ln68_4_fu_1606_p10);

    CNN_ALU_Top_mux_8cud_U10 : component CNN_ALU_Top_mux_8cud
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 8,
        din1_WIDTH => 8,
        din2_WIDTH => 8,
        din3_WIDTH => 8,
        din4_WIDTH => 8,
        din5_WIDTH => 8,
        din6_WIDTH => 8,
        din7_WIDTH => 8,
        din8_WIDTH => 3,
        dout_WIDTH => 8)
    port map (
        din0 => weight_buf_V_1_load_reg_1853,
        din1 => weight_buf_V_5_load_reg_1877,
        din2 => weight_buf_V_9_load_reg_1901,
        din3 => weight_buf_V_13_load_reg_1925,
        din4 => weight_buf_V_17_load_reg_1949,
        din5 => weight_buf_V_21_load_reg_1973,
        din6 => ap_const_lv8_0,
        din7 => ap_const_lv8_0,
        din8 => trunc_ln68_fu_1531_p1,
        dout => phi_ln68_6_fu_1622_p10);

    CNN_ALU_Top_mux_8cud_U11 : component CNN_ALU_Top_mux_8cud
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 8,
        din1_WIDTH => 8,
        din2_WIDTH => 8,
        din3_WIDTH => 8,
        din4_WIDTH => 8,
        din5_WIDTH => 8,
        din6_WIDTH => 8,
        din7_WIDTH => 8,
        din8_WIDTH => 3,
        dout_WIDTH => 8)
    port map (
        din0 => act_buf_V_2_load_reg_2009,
        din1 => act_buf_V_6_load_reg_2033,
        din2 => act_buf_V_10_load_reg_2057,
        din3 => act_buf_V_14_load_reg_2081,
        din4 => act_buf_V_18_load_reg_2105,
        din5 => act_buf_V_22_load_reg_2129,
        din6 => ap_const_lv8_0,
        din7 => ap_const_lv8_0,
        din8 => trunc_ln68_fu_1531_p1,
        dout => phi_ln68_8_fu_1638_p10);

    CNN_ALU_Top_mux_8cud_U12 : component CNN_ALU_Top_mux_8cud
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 8,
        din1_WIDTH => 8,
        din2_WIDTH => 8,
        din3_WIDTH => 8,
        din4_WIDTH => 8,
        din5_WIDTH => 8,
        din6_WIDTH => 8,
        din7_WIDTH => 8,
        din8_WIDTH => 3,
        dout_WIDTH => 8)
    port map (
        din0 => weight_buf_V_2_load_reg_1859,
        din1 => weight_buf_V_6_load_reg_1883,
        din2 => weight_buf_V_10_load_reg_1907,
        din3 => weight_buf_V_14_load_reg_1931,
        din4 => weight_buf_V_18_load_reg_1955,
        din5 => weight_buf_V_22_load_reg_1979,
        din6 => ap_const_lv8_0,
        din7 => ap_const_lv8_0,
        din8 => trunc_ln68_fu_1531_p1,
        dout => phi_ln68_s_fu_1654_p10);

    CNN_ALU_Top_mux_8cud_U13 : component CNN_ALU_Top_mux_8cud
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 8,
        din1_WIDTH => 8,
        din2_WIDTH => 8,
        din3_WIDTH => 8,
        din4_WIDTH => 8,
        din5_WIDTH => 8,
        din6_WIDTH => 8,
        din7_WIDTH => 8,
        din8_WIDTH => 3,
        dout_WIDTH => 8)
    port map (
        din0 => act_buf_V_3_load_reg_2015,
        din1 => act_buf_V_7_load_reg_2039,
        din2 => act_buf_V_11_load_reg_2063,
        din3 => act_buf_V_15_load_reg_2087,
        din4 => act_buf_V_19_load_reg_2111,
        din5 => act_buf_V_23_load_reg_2135,
        din6 => ap_const_lv8_0,
        din7 => ap_const_lv8_0,
        din8 => trunc_ln68_fu_1531_p1,
        dout => phi_ln68_10_fu_1670_p10);

    CNN_ALU_Top_mux_8cud_U14 : component CNN_ALU_Top_mux_8cud
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 8,
        din1_WIDTH => 8,
        din2_WIDTH => 8,
        din3_WIDTH => 8,
        din4_WIDTH => 8,
        din5_WIDTH => 8,
        din6_WIDTH => 8,
        din7_WIDTH => 8,
        din8_WIDTH => 3,
        dout_WIDTH => 8)
    port map (
        din0 => weight_buf_V_3_load_reg_1865,
        din1 => weight_buf_V_7_load_reg_1889,
        din2 => weight_buf_V_11_load_reg_1913,
        din3 => weight_buf_V_15_load_reg_1937,
        din4 => weight_buf_V_19_load_reg_1961,
        din5 => weight_buf_V_23_load_reg_1985,
        din6 => ap_const_lv8_0,
        din7 => ap_const_lv8_0,
        din8 => trunc_ln68_fu_1531_p1,
        dout => phi_ln68_12_fu_1686_p10);

    CNN_ALU_Top_mac_mdEe_U15 : component CNN_ALU_Top_mac_mdEe
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 8,
        din1_WIDTH => 8,
        din2_WIDTH => 19,
        dout_WIDTH => 19)
    port map (
        din0 => ap_phi_reg_pp0_iter1_phi_ln68_1_reg_320,
        din1 => phi_ln68_3_reg_2185,
        din2 => p_0217_0_i_reg_261,
        dout => grp_fu_1779_p3);

    CNN_ALU_Top_mac_mdEe_U16 : component CNN_ALU_Top_mac_mdEe
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 8,
        din1_WIDTH => 8,
        din2_WIDTH => 19,
        dout_WIDTH => 19)
    port map (
        din0 => phi_ln68_5_reg_2190,
        din1 => phi_ln68_7_reg_2195,
        din2 => p_0111_0_i_reg_273,
        dout => grp_fu_1787_p3);

    CNN_ALU_Top_mac_mdEe_U17 : component CNN_ALU_Top_mac_mdEe
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 8,
        din1_WIDTH => 8,
        din2_WIDTH => 19,
        dout_WIDTH => 19)
    port map (
        din0 => phi_ln68_9_reg_2200,
        din1 => phi_ln68_11_reg_2205,
        din2 => p_0107_0_i_reg_285,
        dout => grp_fu_1795_p3);

    CNN_ALU_Top_mac_mdEe_U18 : component CNN_ALU_Top_mac_mdEe
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 8,
        din1_WIDTH => 8,
        din2_WIDTH => 19,
        dout_WIDTH => 19)
    port map (
        din0 => phi_ln68_14_reg_2215,
        din1 => phi_ln68_13_reg_2210,
        din2 => p_0103_0_i_reg_297,
        dout => grp_fu_1803_p3);

    CNN_ALU_Top_mac_mdEe_U19 : component CNN_ALU_Top_mac_mdEe
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 8,
        din1_WIDTH => 8,
        din2_WIDTH => 19,
        dout_WIDTH => 19)
    port map (
        din0 => ap_phi_reg_pp1_iter1_phi_ln68_reg_402,
        din1 => phi_ln68_2_reg_2258,
        din2 => p_0217_0_i168_reg_343,
        dout => grp_fu_1811_p3);

    CNN_ALU_Top_mac_mdEe_U20 : component CNN_ALU_Top_mac_mdEe
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 8,
        din1_WIDTH => 8,
        din2_WIDTH => 19,
        dout_WIDTH => 19)
    port map (
        din0 => phi_ln68_4_reg_2263,
        din1 => phi_ln68_6_reg_2268,
        din2 => p_0111_0_i169_reg_355,
        dout => grp_fu_1819_p3);

    CNN_ALU_Top_mac_mdEe_U21 : component CNN_ALU_Top_mac_mdEe
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 8,
        din1_WIDTH => 8,
        din2_WIDTH => 19,
        dout_WIDTH => 19)
    port map (
        din0 => phi_ln68_8_reg_2273,
        din1 => phi_ln68_s_reg_2278,
        din2 => p_0107_0_i170_reg_367,
        dout => grp_fu_1827_p3);

    CNN_ALU_Top_mac_mdEe_U22 : component CNN_ALU_Top_mac_mdEe
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 8,
        din1_WIDTH => 8,
        din2_WIDTH => 19,
        dout_WIDTH => 19)
    port map (
        din0 => phi_ln68_12_reg_2288,
        din1 => phi_ln68_10_reg_2283,
        din2 => p_0103_0_i171_reg_379,
        dout => grp_fu_1835_p3);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter0_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter0 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_condition_pp0_exit_iter0_state4) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter0 <= ap_const_logic_0;
                elsif (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1) and (cnn_op_V_read_read_fu_242_p2 = ap_const_lv4_6))) then 
                    ap_enable_reg_pp0_iter0 <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_condition_pp0_exit_iter0_state4))) then 
                    ap_enable_reg_pp0_iter1 <= (ap_const_logic_1 xor ap_condition_pp0_exit_iter0_state4);
                elsif ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
                elsif (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1) and (cnn_op_V_read_read_fu_242_p2 = ap_const_lv4_6))) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp1_iter0_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp1_iter0 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp1_stage0_subdone) and (ap_const_logic_1 = ap_condition_pp1_exit_iter0_state8) and (ap_const_logic_1 = ap_CS_fsm_pp1_stage0))) then 
                    ap_enable_reg_pp1_iter0 <= ap_const_logic_0;
                elsif (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1) and (cnn_op_V_read_read_fu_242_p2 = ap_const_lv4_2))) then 
                    ap_enable_reg_pp1_iter0 <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp1_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp1_iter1 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp1_stage0_subdone) and (ap_const_logic_1 = ap_condition_pp1_exit_iter0_state8))) then 
                    ap_enable_reg_pp1_iter1 <= (ap_const_logic_1 xor ap_condition_pp1_exit_iter0_state8);
                elsif ((ap_const_boolean_0 = ap_block_pp1_stage0_subdone)) then 
                    ap_enable_reg_pp1_iter1 <= ap_enable_reg_pp1_iter0;
                elsif (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1) and (cnn_op_V_read_read_fu_242_p2 = ap_const_lv4_2))) then 
                    ap_enable_reg_pp1_iter1 <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    rd_data_V_preg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                rd_data_V_preg <= ap_const_lv32_0;
            else
                if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1) and (cnn_op_V_read_read_fu_242_p2 = ap_const_lv4_3))) then 
                    rd_data_V_preg <= acc_reg_V;
                end if; 
            end if;
        end if;
    end process;


    a_ptr_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_lv7_0 = a_ptr_load_load_fu_764_p1) and (ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1) and (cnn_op_V_read_read_fu_242_p2 = ap_const_lv4_1))) then 
                a_ptr(2) <= '1';
                a_ptr(3) <= '0';
                a_ptr(4) <= '0';
            elsif (((ap_const_lv7_4 = a_ptr_load_load_fu_764_p1) and (ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1) and (cnn_op_V_read_read_fu_242_p2 = ap_const_lv4_1))) then 
                a_ptr(2) <= '0';
                a_ptr(3) <= '1';
                a_ptr(4) <= '0';
            elsif (((ap_const_lv7_8 = a_ptr_load_load_fu_764_p1) and (ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1) and (cnn_op_V_read_read_fu_242_p2 = ap_const_lv4_1))) then 
                a_ptr(2) <= '1';
                a_ptr(3) <= '1';
                a_ptr(4) <= '0';
            elsif (((ap_const_lv7_C = a_ptr_load_load_fu_764_p1) and (ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1) and (cnn_op_V_read_read_fu_242_p2 = ap_const_lv4_1))) then 
                a_ptr(2) <= '0';
                a_ptr(3) <= '0';
                a_ptr(4) <= '1';
            elsif (((ap_const_lv7_10 = a_ptr_load_load_fu_764_p1) and (ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1) and (cnn_op_V_read_read_fu_242_p2 = ap_const_lv4_1))) then 
                a_ptr(2) <= '1';
                a_ptr(3) <= '0';
                a_ptr(4) <= '1';
            elsif (((ap_const_lv7_14 = a_ptr_load_load_fu_764_p1) and (ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1) and (cnn_op_V_read_read_fu_242_p2 = ap_const_lv4_1))) then 
                a_ptr(2) <= '0';
                a_ptr(3) <= '1';
                a_ptr(4) <= '1';
            elsif ((((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1) and (cnn_op_V_read_read_fu_242_p2 = ap_const_lv4_5)) or (not((ap_const_lv7_18 = a_ptr_load_load_fu_764_p1)) and not((ap_const_lv7_14 = a_ptr_load_load_fu_764_p1)) and not((ap_const_lv7_10 = a_ptr_load_load_fu_764_p1)) and not((ap_const_lv7_C = a_ptr_load_load_fu_764_p1)) and not((ap_const_lv7_8 = a_ptr_load_load_fu_764_p1)) and not((ap_const_lv7_4 = a_ptr_load_load_fu_764_p1)) and not((ap_const_lv7_0 = a_ptr_load_load_fu_764_p1)) and (ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1) and (cnn_op_V_read_read_fu_242_p2 = ap_const_lv4_1)) or ((ap_const_lv7_18 = a_ptr_load_load_fu_764_p1) and (ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1) and (cnn_op_V_read_read_fu_242_p2 = ap_const_lv4_1)))) then 
                a_ptr(2) <= '0';
                a_ptr(3) <= '0';
                a_ptr(4) <= '0';
            end if; 
        end if;
    end process;

    acc_reg_V_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state10)) then 
                acc_reg_V <= sext_ln68_4_fu_1769_p1;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state7) and (cnn_op_V_read_read_fu_242_p2 = ap_const_lv4_6))) then 
                acc_reg_V <= add_ln700_1_reg_2240;
            elsif ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
                acc_reg_V <= select_ln899_1_reg_2167;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1) and (cnn_op_V_read_read_fu_242_p2 = ap_const_lv4_4))) then 
                acc_reg_V <= sext_ln68_fu_754_p1;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1) and (cnn_op_V_read_read_fu_242_p2 = ap_const_lv4_8))) then 
                acc_reg_V <= add_ln700_fu_700_p2;
            elsif ((((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1) and (cnn_op_V_read_read_fu_242_p2 = ap_const_lv4_5)) or ((tmp_2_fu_692_p3 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1) and (cnn_op_V_read_read_fu_242_p2 = ap_const_lv4_7)))) then 
                acc_reg_V <= ap_const_lv32_0;
            end if; 
        end if;
    end process;

    ap_phi_reg_pp0_iter1_phi_ln68_1_reg_320_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_249)) then
                if (((trunc_ln68_1_fu_1275_p1 = ap_const_lv3_6) and (icmp_ln168_1_fu_1263_p2 = ap_const_lv1_0))) then 
                    ap_phi_reg_pp0_iter1_phi_ln68_1_reg_320 <= act_buf_V_24_load_reg_2141;
                elsif (((trunc_ln68_1_fu_1275_p1 = ap_const_lv3_5) and (icmp_ln168_1_fu_1263_p2 = ap_const_lv1_0))) then 
                    ap_phi_reg_pp0_iter1_phi_ln68_1_reg_320 <= act_buf_V_20_load_reg_2117;
                elsif (((trunc_ln68_1_fu_1275_p1 = ap_const_lv3_4) and (icmp_ln168_1_fu_1263_p2 = ap_const_lv1_0))) then 
                    ap_phi_reg_pp0_iter1_phi_ln68_1_reg_320 <= act_buf_V_16_load_reg_2093;
                elsif (((trunc_ln68_1_fu_1275_p1 = ap_const_lv3_3) and (icmp_ln168_1_fu_1263_p2 = ap_const_lv1_0))) then 
                    ap_phi_reg_pp0_iter1_phi_ln68_1_reg_320 <= act_buf_V_12_load_reg_2069;
                elsif (((trunc_ln68_1_fu_1275_p1 = ap_const_lv3_2) and (icmp_ln168_1_fu_1263_p2 = ap_const_lv1_0))) then 
                    ap_phi_reg_pp0_iter1_phi_ln68_1_reg_320 <= act_buf_V_8_load_reg_2045;
                elsif (((trunc_ln68_1_fu_1275_p1 = ap_const_lv3_1) and (icmp_ln168_1_fu_1263_p2 = ap_const_lv1_0))) then 
                    ap_phi_reg_pp0_iter1_phi_ln68_1_reg_320 <= act_buf_V_4_load_reg_2021;
                elsif (((trunc_ln68_1_fu_1275_p1 = ap_const_lv3_0) and (icmp_ln168_1_fu_1263_p2 = ap_const_lv1_0))) then 
                    ap_phi_reg_pp0_iter1_phi_ln68_1_reg_320 <= act_buf_V_0_load_reg_1997;
                elsif (((trunc_ln68_1_fu_1275_p1 = ap_const_lv3_7) and (icmp_ln168_1_fu_1263_p2 = ap_const_lv1_0))) then 
                    ap_phi_reg_pp0_iter1_phi_ln68_1_reg_320 <= ap_const_lv8_0;
                elsif ((ap_const_boolean_1 = ap_const_boolean_1)) then 
                    ap_phi_reg_pp0_iter1_phi_ln68_1_reg_320 <= ap_phi_reg_pp0_iter0_phi_ln68_1_reg_320;
                end if;
            end if; 
        end if;
    end process;

    ap_phi_reg_pp1_iter1_phi_ln68_reg_402_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_308)) then
                if (((trunc_ln68_fu_1531_p1 = ap_const_lv3_6) and (icmp_ln168_fu_1519_p2 = ap_const_lv1_0))) then 
                    ap_phi_reg_pp1_iter1_phi_ln68_reg_402 <= act_buf_V_24_load_reg_2141;
                elsif (((trunc_ln68_fu_1531_p1 = ap_const_lv3_5) and (icmp_ln168_fu_1519_p2 = ap_const_lv1_0))) then 
                    ap_phi_reg_pp1_iter1_phi_ln68_reg_402 <= act_buf_V_20_load_reg_2117;
                elsif (((trunc_ln68_fu_1531_p1 = ap_const_lv3_4) and (icmp_ln168_fu_1519_p2 = ap_const_lv1_0))) then 
                    ap_phi_reg_pp1_iter1_phi_ln68_reg_402 <= act_buf_V_16_load_reg_2093;
                elsif (((trunc_ln68_fu_1531_p1 = ap_const_lv3_3) and (icmp_ln168_fu_1519_p2 = ap_const_lv1_0))) then 
                    ap_phi_reg_pp1_iter1_phi_ln68_reg_402 <= act_buf_V_12_load_reg_2069;
                elsif (((trunc_ln68_fu_1531_p1 = ap_const_lv3_2) and (icmp_ln168_fu_1519_p2 = ap_const_lv1_0))) then 
                    ap_phi_reg_pp1_iter1_phi_ln68_reg_402 <= act_buf_V_8_load_reg_2045;
                elsif (((trunc_ln68_fu_1531_p1 = ap_const_lv3_1) and (icmp_ln168_fu_1519_p2 = ap_const_lv1_0))) then 
                    ap_phi_reg_pp1_iter1_phi_ln68_reg_402 <= act_buf_V_4_load_reg_2021;
                elsif (((trunc_ln68_fu_1531_p1 = ap_const_lv3_0) and (icmp_ln168_fu_1519_p2 = ap_const_lv1_0))) then 
                    ap_phi_reg_pp1_iter1_phi_ln68_reg_402 <= act_buf_V_0_load_reg_1997;
                elsif (((trunc_ln68_fu_1531_p1 = ap_const_lv3_7) and (icmp_ln168_fu_1519_p2 = ap_const_lv1_0))) then 
                    ap_phi_reg_pp1_iter1_phi_ln68_reg_402 <= ap_const_lv8_0;
                elsif ((ap_const_boolean_1 = ap_const_boolean_1)) then 
                    ap_phi_reg_pp1_iter1_phi_ln68_reg_402 <= ap_phi_reg_pp1_iter0_phi_ln68_reg_402;
                end if;
            end if; 
        end if;
    end process;

    i_0_i172_reg_391_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp1_stage0_11001) and (icmp_ln168_fu_1519_p2 = ap_const_lv1_0) and (ap_enable_reg_pp1_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp1_stage0))) then 
                i_0_i172_reg_391 <= i_fu_1525_p2;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1) and (cnn_op_V_read_read_fu_242_p2 = ap_const_lv4_2))) then 
                i_0_i172_reg_391 <= ap_const_lv4_0;
            end if; 
        end if;
    end process;

    i_0_i_reg_309_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln168_1_fu_1263_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                i_0_i_reg_309 <= i_1_fu_1269_p2;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1) and (cnn_op_V_read_read_fu_242_p2 = ap_const_lv4_6))) then 
                i_0_i_reg_309 <= ap_const_lv4_0;
            end if; 
        end if;
    end process;

    p_0103_0_i171_reg_379_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp1_stage0_11001) and (icmp_ln168_reg_2245 = ap_const_lv1_0) and (ap_enable_reg_pp1_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp1_stage0))) then 
                p_0103_0_i171_reg_379 <= grp_fu_1835_p3;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1) and (cnn_op_V_read_read_fu_242_p2 = ap_const_lv4_2))) then 
                p_0103_0_i171_reg_379 <= ap_const_lv19_0;
            end if; 
        end if;
    end process;

    p_0103_0_i_reg_297_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln168_1_reg_2172 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                p_0103_0_i_reg_297 <= grp_fu_1803_p3;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1) and (cnn_op_V_read_read_fu_242_p2 = ap_const_lv4_6))) then 
                p_0103_0_i_reg_297 <= ap_const_lv19_0;
            end if; 
        end if;
    end process;

    p_0107_0_i170_reg_367_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp1_stage0_11001) and (icmp_ln168_reg_2245 = ap_const_lv1_0) and (ap_enable_reg_pp1_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp1_stage0))) then 
                p_0107_0_i170_reg_367 <= grp_fu_1827_p3;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1) and (cnn_op_V_read_read_fu_242_p2 = ap_const_lv4_2))) then 
                p_0107_0_i170_reg_367 <= ap_const_lv19_0;
            end if; 
        end if;
    end process;

    p_0107_0_i_reg_285_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln168_1_reg_2172 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                p_0107_0_i_reg_285 <= grp_fu_1795_p3;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1) and (cnn_op_V_read_read_fu_242_p2 = ap_const_lv4_6))) then 
                p_0107_0_i_reg_285 <= ap_const_lv19_0;
            end if; 
        end if;
    end process;

    p_0111_0_i169_reg_355_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp1_stage0_11001) and (icmp_ln168_reg_2245 = ap_const_lv1_0) and (ap_enable_reg_pp1_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp1_stage0))) then 
                p_0111_0_i169_reg_355 <= grp_fu_1819_p3;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1) and (cnn_op_V_read_read_fu_242_p2 = ap_const_lv4_2))) then 
                p_0111_0_i169_reg_355 <= ap_const_lv19_0;
            end if; 
        end if;
    end process;

    p_0111_0_i_reg_273_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln168_1_reg_2172 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                p_0111_0_i_reg_273 <= grp_fu_1787_p3;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1) and (cnn_op_V_read_read_fu_242_p2 = ap_const_lv4_6))) then 
                p_0111_0_i_reg_273 <= ap_const_lv19_0;
            end if; 
        end if;
    end process;

    p_0217_0_i168_reg_343_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp1_stage0_11001) and (icmp_ln168_reg_2245 = ap_const_lv1_0) and (ap_enable_reg_pp1_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp1_stage0))) then 
                p_0217_0_i168_reg_343 <= grp_fu_1811_p3;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1) and (cnn_op_V_read_read_fu_242_p2 = ap_const_lv4_2))) then 
                p_0217_0_i168_reg_343 <= ap_const_lv19_0;
            end if; 
        end if;
    end process;

    p_0217_0_i_reg_261_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln168_1_reg_2172 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                p_0217_0_i_reg_261 <= grp_fu_1779_p3;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1) and (cnn_op_V_read_read_fu_242_p2 = ap_const_lv4_6))) then 
                p_0217_0_i_reg_261 <= ap_const_lv19_0;
            end if; 
        end if;
    end process;

    w_ptr_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((w_ptr_load_load_fu_982_p1 = ap_const_lv7_0) and (ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1) and (cnn_op_V_read_read_fu_242_p2 = ap_const_lv4_0))) then 
                w_ptr(2) <= '1';
                w_ptr(3) <= '0';
                w_ptr(4) <= '0';
            elsif (((w_ptr_load_load_fu_982_p1 = ap_const_lv7_4) and (ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1) and (cnn_op_V_read_read_fu_242_p2 = ap_const_lv4_0))) then 
                w_ptr(2) <= '0';
                w_ptr(3) <= '1';
                w_ptr(4) <= '0';
            elsif (((w_ptr_load_load_fu_982_p1 = ap_const_lv7_8) and (ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1) and (cnn_op_V_read_read_fu_242_p2 = ap_const_lv4_0))) then 
                w_ptr(2) <= '1';
                w_ptr(3) <= '1';
                w_ptr(4) <= '0';
            elsif (((w_ptr_load_load_fu_982_p1 = ap_const_lv7_C) and (ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1) and (cnn_op_V_read_read_fu_242_p2 = ap_const_lv4_0))) then 
                w_ptr(2) <= '0';
                w_ptr(3) <= '0';
                w_ptr(4) <= '1';
            elsif (((w_ptr_load_load_fu_982_p1 = ap_const_lv7_10) and (ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1) and (cnn_op_V_read_read_fu_242_p2 = ap_const_lv4_0))) then 
                w_ptr(2) <= '1';
                w_ptr(3) <= '0';
                w_ptr(4) <= '1';
            elsif (((w_ptr_load_load_fu_982_p1 = ap_const_lv7_14) and (ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1) and (cnn_op_V_read_read_fu_242_p2 = ap_const_lv4_0))) then 
                w_ptr(2) <= '0';
                w_ptr(3) <= '1';
                w_ptr(4) <= '1';
            elsif ((((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1) and (cnn_op_V_read_read_fu_242_p2 = ap_const_lv4_5)) or (not((w_ptr_load_load_fu_982_p1 = ap_const_lv7_18)) and not((w_ptr_load_load_fu_982_p1 = ap_const_lv7_14)) and not((w_ptr_load_load_fu_982_p1 = ap_const_lv7_10)) and not((w_ptr_load_load_fu_982_p1 = ap_const_lv7_C)) and not((w_ptr_load_load_fu_982_p1 = ap_const_lv7_8)) and not((w_ptr_load_load_fu_982_p1 = ap_const_lv7_4)) and not((w_ptr_load_load_fu_982_p1 = ap_const_lv7_0)) and (ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1) and (cnn_op_V_read_read_fu_242_p2 = ap_const_lv4_0)) or ((w_ptr_load_load_fu_982_p1 = ap_const_lv7_18) and (ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1) and (cnn_op_V_read_read_fu_242_p2 = ap_const_lv4_0)))) then 
                w_ptr(2) <= '0';
                w_ptr(3) <= '0';
                w_ptr(4) <= '0';
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then
                acc_reg_V_load_reg_2147 <= acc_reg_V;
                act_buf_V_0_load_reg_1997 <= act_buf_V_0;
                act_buf_V_10_load_reg_2057 <= act_buf_V_10;
                act_buf_V_11_load_reg_2063 <= act_buf_V_11;
                act_buf_V_12_load_reg_2069 <= act_buf_V_12;
                act_buf_V_13_load_reg_2075 <= act_buf_V_13;
                act_buf_V_14_load_reg_2081 <= act_buf_V_14;
                act_buf_V_15_load_reg_2087 <= act_buf_V_15;
                act_buf_V_16_load_reg_2093 <= act_buf_V_16;
                act_buf_V_17_load_reg_2099 <= act_buf_V_17;
                act_buf_V_18_load_reg_2105 <= act_buf_V_18;
                act_buf_V_19_load_reg_2111 <= act_buf_V_19;
                act_buf_V_1_load_reg_2003 <= act_buf_V_1;
                act_buf_V_20_load_reg_2117 <= act_buf_V_20;
                act_buf_V_21_load_reg_2123 <= act_buf_V_21;
                act_buf_V_22_load_reg_2129 <= act_buf_V_22;
                act_buf_V_23_load_reg_2135 <= act_buf_V_23;
                act_buf_V_24_load_reg_2141 <= act_buf_V_24;
                act_buf_V_2_load_reg_2009 <= act_buf_V_2;
                act_buf_V_3_load_reg_2015 <= act_buf_V_3;
                act_buf_V_4_load_reg_2021 <= act_buf_V_4;
                act_buf_V_5_load_reg_2027 <= act_buf_V_5;
                act_buf_V_6_load_reg_2033 <= act_buf_V_6;
                act_buf_V_7_load_reg_2039 <= act_buf_V_7;
                act_buf_V_8_load_reg_2045 <= act_buf_V_8;
                act_buf_V_9_load_reg_2051 <= act_buf_V_9;
                weight_buf_V_0_load_reg_1847 <= weight_buf_V_0;
                weight_buf_V_10_load_reg_1907 <= weight_buf_V_10;
                weight_buf_V_11_load_reg_1913 <= weight_buf_V_11;
                weight_buf_V_12_load_reg_1919 <= weight_buf_V_12;
                weight_buf_V_13_load_reg_1925 <= weight_buf_V_13;
                weight_buf_V_14_load_reg_1931 <= weight_buf_V_14;
                weight_buf_V_15_load_reg_1937 <= weight_buf_V_15;
                weight_buf_V_16_load_reg_1943 <= weight_buf_V_16;
                weight_buf_V_17_load_reg_1949 <= weight_buf_V_17;
                weight_buf_V_18_load_reg_1955 <= weight_buf_V_18;
                weight_buf_V_19_load_reg_1961 <= weight_buf_V_19;
                weight_buf_V_1_load_reg_1853 <= weight_buf_V_1;
                weight_buf_V_20_load_reg_1967 <= weight_buf_V_20;
                weight_buf_V_21_load_reg_1973 <= weight_buf_V_21;
                weight_buf_V_22_load_reg_1979 <= weight_buf_V_22;
                weight_buf_V_23_load_reg_1985 <= weight_buf_V_23;
                weight_buf_V_24_load_reg_1991 <= weight_buf_V_24;
                weight_buf_V_2_load_reg_1859 <= weight_buf_V_2;
                weight_buf_V_3_load_reg_1865 <= weight_buf_V_3;
                weight_buf_V_4_load_reg_1871 <= weight_buf_V_4;
                weight_buf_V_5_load_reg_1877 <= weight_buf_V_5;
                weight_buf_V_6_load_reg_1883 <= weight_buf_V_6;
                weight_buf_V_7_load_reg_1889 <= weight_buf_V_7;
                weight_buf_V_8_load_reg_1895 <= weight_buf_V_8;
                weight_buf_V_9_load_reg_1901 <= weight_buf_V_9;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_lv7_0 = a_ptr_load_load_fu_764_p1) and (ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1) and (cnn_op_V_read_read_fu_242_p2 = ap_const_lv4_1))) then
                act_buf_V_0 <= trunc_ln647_7_fu_948_p1;
                act_buf_V_1 <= grp_fu_443_p1(15 downto 8);
                act_buf_V_2 <= grp_fu_453_p1(23 downto 16);
                act_buf_V_3 <= grp_fu_463_p1(31 downto 24);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_lv7_8 = a_ptr_load_load_fu_764_p1) and (ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1) and (cnn_op_V_read_read_fu_242_p2 = ap_const_lv4_1))) then
                act_buf_V_10 <= grp_fu_453_p1(23 downto 16);
                act_buf_V_11 <= grp_fu_463_p1(31 downto 24);
                act_buf_V_8 <= trunc_ln647_9_fu_880_p1;
                act_buf_V_9 <= grp_fu_443_p1(15 downto 8);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_lv7_C = a_ptr_load_load_fu_764_p1) and (ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1) and (cnn_op_V_read_read_fu_242_p2 = ap_const_lv4_1))) then
                act_buf_V_12 <= trunc_ln647_10_fu_846_p1;
                act_buf_V_13 <= grp_fu_443_p1(15 downto 8);
                act_buf_V_14 <= grp_fu_453_p1(23 downto 16);
                act_buf_V_15 <= grp_fu_463_p1(31 downto 24);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_lv7_10 = a_ptr_load_load_fu_764_p1) and (ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1) and (cnn_op_V_read_read_fu_242_p2 = ap_const_lv4_1))) then
                act_buf_V_16 <= trunc_ln647_11_fu_812_p1;
                act_buf_V_17 <= grp_fu_443_p1(15 downto 8);
                act_buf_V_18 <= grp_fu_453_p1(23 downto 16);
                act_buf_V_19 <= grp_fu_463_p1(31 downto 24);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_lv7_14 = a_ptr_load_load_fu_764_p1) and (ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1) and (cnn_op_V_read_read_fu_242_p2 = ap_const_lv4_1))) then
                act_buf_V_20 <= trunc_ln647_12_fu_778_p1;
                act_buf_V_21 <= grp_fu_443_p1(15 downto 8);
                act_buf_V_22 <= grp_fu_453_p1(23 downto 16);
                act_buf_V_23 <= grp_fu_463_p1(31 downto 24);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_lv7_18 = a_ptr_load_load_fu_764_p1) and (ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1) and (cnn_op_V_read_read_fu_242_p2 = ap_const_lv4_1))) then
                act_buf_V_24 <= trunc_ln647_13_fu_768_p1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_lv7_4 = a_ptr_load_load_fu_764_p1) and (ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1) and (cnn_op_V_read_read_fu_242_p2 = ap_const_lv4_1))) then
                act_buf_V_4 <= trunc_ln647_8_fu_914_p1;
                act_buf_V_5 <= grp_fu_443_p1(15 downto 8);
                act_buf_V_6 <= grp_fu_453_p1(23 downto 16);
                act_buf_V_7 <= grp_fu_463_p1(31 downto 24);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state6)) then
                add_ln700_1_reg_2240 <= add_ln700_1_fu_1508_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                icmp_ln168_1_reg_2172 <= icmp_ln168_1_fu_1263_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp1_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp1_stage0))) then
                icmp_ln168_reg_2245 <= icmp_ln168_fu_1519_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp1_stage0_11001) and (icmp_ln168_fu_1519_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_pp1_stage0))) then
                phi_ln68_10_reg_2283 <= phi_ln68_10_fu_1670_p10;
                phi_ln68_12_reg_2288 <= phi_ln68_12_fu_1686_p10;
                phi_ln68_2_reg_2258 <= phi_ln68_2_fu_1543_p34;
                phi_ln68_4_reg_2263 <= phi_ln68_4_fu_1606_p10;
                phi_ln68_6_reg_2268 <= phi_ln68_6_fu_1622_p10;
                phi_ln68_8_reg_2273 <= phi_ln68_8_fu_1638_p10;
                phi_ln68_s_reg_2278 <= phi_ln68_s_fu_1654_p10;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln168_1_fu_1263_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                phi_ln68_11_reg_2205 <= phi_ln68_11_fu_1398_p10;
                phi_ln68_13_reg_2210 <= phi_ln68_13_fu_1414_p10;
                phi_ln68_14_reg_2215 <= phi_ln68_14_fu_1430_p10;
                phi_ln68_3_reg_2185 <= phi_ln68_3_fu_1287_p34;
                phi_ln68_5_reg_2190 <= phi_ln68_5_fu_1350_p10;
                phi_ln68_7_reg_2195 <= phi_ln68_7_fu_1366_p10;
                phi_ln68_9_reg_2200 <= phi_ln68_9_fu_1382_p10;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1) and (cnn_op_V_read_read_fu_242_p2 = ap_const_lv4_9))) then
                product_V_reg_2153 <= product_V_fu_686_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state2)) then
                select_ln899_1_reg_2167 <= select_ln899_1_fu_1250_p3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((w_ptr_load_load_fu_982_p1 = ap_const_lv7_0) and (ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1) and (cnn_op_V_read_read_fu_242_p2 = ap_const_lv4_0))) then
                weight_buf_V_0 <= trunc_ln647_fu_1166_p1;
                weight_buf_V_1 <= grp_fu_443_p1(15 downto 8);
                weight_buf_V_2 <= grp_fu_453_p1(23 downto 16);
                weight_buf_V_3 <= grp_fu_463_p1(31 downto 24);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((w_ptr_load_load_fu_982_p1 = ap_const_lv7_8) and (ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1) and (cnn_op_V_read_read_fu_242_p2 = ap_const_lv4_0))) then
                weight_buf_V_10 <= grp_fu_453_p1(23 downto 16);
                weight_buf_V_11 <= grp_fu_463_p1(31 downto 24);
                weight_buf_V_8 <= trunc_ln647_2_fu_1098_p1;
                weight_buf_V_9 <= grp_fu_443_p1(15 downto 8);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((w_ptr_load_load_fu_982_p1 = ap_const_lv7_C) and (ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1) and (cnn_op_V_read_read_fu_242_p2 = ap_const_lv4_0))) then
                weight_buf_V_12 <= trunc_ln647_3_fu_1064_p1;
                weight_buf_V_13 <= grp_fu_443_p1(15 downto 8);
                weight_buf_V_14 <= grp_fu_453_p1(23 downto 16);
                weight_buf_V_15 <= grp_fu_463_p1(31 downto 24);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((w_ptr_load_load_fu_982_p1 = ap_const_lv7_10) and (ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1) and (cnn_op_V_read_read_fu_242_p2 = ap_const_lv4_0))) then
                weight_buf_V_16 <= trunc_ln647_4_fu_1030_p1;
                weight_buf_V_17 <= grp_fu_443_p1(15 downto 8);
                weight_buf_V_18 <= grp_fu_453_p1(23 downto 16);
                weight_buf_V_19 <= grp_fu_463_p1(31 downto 24);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((w_ptr_load_load_fu_982_p1 = ap_const_lv7_14) and (ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1) and (cnn_op_V_read_read_fu_242_p2 = ap_const_lv4_0))) then
                weight_buf_V_20 <= trunc_ln647_5_fu_996_p1;
                weight_buf_V_21 <= grp_fu_443_p1(15 downto 8);
                weight_buf_V_22 <= grp_fu_453_p1(23 downto 16);
                weight_buf_V_23 <= grp_fu_463_p1(31 downto 24);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((w_ptr_load_load_fu_982_p1 = ap_const_lv7_18) and (ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1) and (cnn_op_V_read_read_fu_242_p2 = ap_const_lv4_0))) then
                weight_buf_V_24 <= trunc_ln647_6_fu_986_p1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((w_ptr_load_load_fu_982_p1 = ap_const_lv7_4) and (ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1) and (cnn_op_V_read_read_fu_242_p2 = ap_const_lv4_0))) then
                weight_buf_V_4 <= trunc_ln647_1_fu_1132_p1;
                weight_buf_V_5 <= grp_fu_443_p1(15 downto 8);
                weight_buf_V_6 <= grp_fu_453_p1(23 downto 16);
                weight_buf_V_7 <= grp_fu_463_p1(31 downto 24);
            end if;
        end if;
    end process;
    w_ptr(1 downto 0) <= "00";
    w_ptr(6 downto 5) <= "00";
    a_ptr(1 downto 0) <= "00";
    a_ptr(6 downto 5) <= "00";

    ap_NS_fsm_assign_proc : process (ap_start, ap_CS_fsm, ap_CS_fsm_state1, cnn_op_V_read_read_fu_242_p2, icmp_ln168_1_fu_1263_p2, ap_enable_reg_pp0_iter0, icmp_ln168_fu_1519_p2, ap_enable_reg_pp1_iter0, ap_block_pp0_stage0_subdone, ap_block_pp1_stage0_subdone)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1) and (cnn_op_V_read_read_fu_242_p2 = ap_const_lv4_0))) then
                    ap_NS_fsm <= ap_ST_fsm_state12;
                elsif (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1) and (cnn_op_V_read_read_fu_242_p2 = ap_const_lv4_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state11;
                elsif (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1) and (cnn_op_V_read_read_fu_242_p2 = ap_const_lv4_2))) then
                    ap_NS_fsm <= ap_ST_fsm_pp1_stage0;
                elsif (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1) and (cnn_op_V_read_read_fu_242_p2 = ap_const_lv4_6))) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                elsif ((not((cnn_op_V_read_read_fu_242_p2 = ap_const_lv4_1)) and not((cnn_op_V_read_read_fu_242_p2 = ap_const_lv4_0)) and not((cnn_op_V_read_read_fu_242_p2 = ap_const_lv4_2)) and not((cnn_op_V_read_read_fu_242_p2 = ap_const_lv4_6)) and not((cnn_op_V_read_read_fu_242_p2 = ap_const_lv4_9)) and (ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state7;
                elsif (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1) and (cnn_op_V_read_read_fu_242_p2 = ap_const_lv4_9))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                ap_NS_fsm <= ap_ST_fsm_state3;
            when ap_ST_fsm_state3 => 
                ap_NS_fsm <= ap_ST_fsm_state7;
            when ap_ST_fsm_pp0_stage0 => 
                if (not(((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (icmp_ln168_1_fu_1263_p2 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1)))) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (icmp_ln168_1_fu_1263_p2 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state6;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                end if;
            when ap_ST_fsm_state6 => 
                ap_NS_fsm <= ap_ST_fsm_state7;
            when ap_ST_fsm_state7 => 
                ap_NS_fsm <= ap_ST_fsm_state1;
            when ap_ST_fsm_pp1_stage0 => 
                if (not(((ap_const_boolean_0 = ap_block_pp1_stage0_subdone) and (icmp_ln168_fu_1519_p2 = ap_const_lv1_1) and (ap_enable_reg_pp1_iter0 = ap_const_logic_1)))) then
                    ap_NS_fsm <= ap_ST_fsm_pp1_stage0;
                elsif (((ap_const_boolean_0 = ap_block_pp1_stage0_subdone) and (icmp_ln168_fu_1519_p2 = ap_const_lv1_1) and (ap_enable_reg_pp1_iter0 = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state10;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp1_stage0;
                end if;
            when ap_ST_fsm_state10 => 
                ap_NS_fsm <= ap_ST_fsm_state7;
            when ap_ST_fsm_state11 => 
                ap_NS_fsm <= ap_ST_fsm_state7;
            when ap_ST_fsm_state12 => 
                ap_NS_fsm <= ap_ST_fsm_state7;
            when others =>  
                ap_NS_fsm <= "XXXXXXXXXX";
        end case;
    end process;
    a_ptr_load_load_fu_764_p1 <= a_ptr;
    add_ln68_1_fu_1753_p2 <= std_logic_vector(signed(sext_ln168_1_fu_1731_p1) + signed(sext_ln168_fu_1727_p1));
    add_ln68_2_fu_1763_p2 <= std_logic_vector(signed(sext_ln68_3_fu_1759_p1) + signed(sext_ln68_2_fu_1749_p1));
    add_ln68_fu_1743_p2 <= std_logic_vector(signed(sext_ln168_2_fu_1735_p1) + signed(sext_ln168_3_fu_1739_p1));
    add_ln700_1_fu_1508_p2 <= std_logic_vector(signed(sext_ln700_fu_1504_p1) + signed(add_ln700_2_fu_1487_p2));
    add_ln700_2_fu_1487_p2 <= std_logic_vector(unsigned(acc_reg_V_load_reg_2147) + unsigned(sext_ln168_6_fu_1479_p1));
    add_ln700_3_fu_1492_p2 <= std_logic_vector(signed(sext_ln168_5_fu_1475_p1) + signed(sext_ln168_4_fu_1471_p1));
    add_ln700_4_fu_1498_p2 <= std_logic_vector(unsigned(add_ln700_3_fu_1492_p2) + unsigned(sext_ln168_7_fu_1483_p1));
    add_ln700_fu_700_p1 <= rs1_data_V;
    add_ln700_fu_700_p2 <= std_logic_vector(unsigned(acc_reg_V) + unsigned(add_ln700_fu_700_p1));
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(3);
    ap_CS_fsm_pp1_stage0 <= ap_CS_fsm(6);
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state10 <= ap_CS_fsm(7);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);
    ap_CS_fsm_state6 <= ap_CS_fsm(4);
    ap_CS_fsm_state7 <= ap_CS_fsm(5);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp1_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp1_stage0_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp1_stage0_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state4_pp0_stage0_iter0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state5_pp0_stage0_iter1 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state8_pp1_stage0_iter0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state9_pp1_stage0_iter1 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_condition_249_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001, ap_enable_reg_pp0_iter0)
    begin
                ap_condition_249 <= ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0));
    end process;


    ap_condition_308_assign_proc : process(ap_CS_fsm_pp1_stage0, ap_block_pp1_stage0_11001, ap_enable_reg_pp1_iter0)
    begin
                ap_condition_308 <= ((ap_const_boolean_0 = ap_block_pp1_stage0_11001) and (ap_enable_reg_pp1_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp1_stage0));
    end process;


    ap_condition_pp0_exit_iter0_state4_assign_proc : process(icmp_ln168_1_fu_1263_p2)
    begin
        if ((icmp_ln168_1_fu_1263_p2 = ap_const_lv1_1)) then 
            ap_condition_pp0_exit_iter0_state4 <= ap_const_logic_1;
        else 
            ap_condition_pp0_exit_iter0_state4 <= ap_const_logic_0;
        end if; 
    end process;


    ap_condition_pp1_exit_iter0_state8_assign_proc : process(icmp_ln168_fu_1519_p2)
    begin
        if ((icmp_ln168_fu_1519_p2 = ap_const_lv1_1)) then 
            ap_condition_pp1_exit_iter0_state8 <= ap_const_logic_1;
        else 
            ap_condition_pp1_exit_iter0_state8 <= ap_const_logic_0;
        end if; 
    end process;


    ap_done_assign_proc : process(ap_CS_fsm_state7)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state7)) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_pp1 <= (ap_idle_pp1 xor ap_const_logic_1);

    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp1_assign_proc : process(ap_enable_reg_pp1_iter0, ap_enable_reg_pp1_iter1)
    begin
        if (((ap_enable_reg_pp1_iter1 = ap_const_logic_0) and (ap_enable_reg_pp1_iter0 = ap_const_logic_0))) then 
            ap_idle_pp1 <= ap_const_logic_1;
        else 
            ap_idle_pp1 <= ap_const_logic_0;
        end if; 
    end process;

    ap_phi_reg_pp0_iter0_phi_ln68_1_reg_320 <= "XXXXXXXX";
    ap_phi_reg_pp1_iter0_phi_ln68_reg_402 <= "XXXXXXXX";

    ap_ready_assign_proc : process(ap_CS_fsm_state7)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state7)) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;

    cnn_op_V_read_read_fu_242_p2 <= cnn_op_V;
    final_max_V_fu_746_p3 <= 
        max1_V_fu_718_p3 when (icmp_ln895_2_fu_740_p2(0) = '1') else 
        max2_V_fu_732_p3;
    grp_fu_443_p1 <= rs1_data_V;
    grp_fu_453_p1 <= rs1_data_V;
    grp_fu_463_p1 <= rs1_data_V;
    i_1_fu_1269_p2 <= std_logic_vector(unsigned(i_0_i_reg_309) + unsigned(ap_const_lv4_1));
    i_fu_1525_p2 <= std_logic_vector(unsigned(i_0_i172_reg_391) + unsigned(ap_const_lv4_1));
    icmp_ln168_1_fu_1263_p2 <= "1" when (i_0_i_reg_309 = ap_const_lv4_8) else "0";
    icmp_ln168_fu_1519_p2 <= "1" when (i_0_i172_reg_391 = ap_const_lv4_8) else "0";
    icmp_ln895_1_fu_726_p2 <= "1" when (signed(act_buf_V_2) > signed(act_buf_V_3)) else "0";
    icmp_ln895_2_fu_740_p2 <= "1" when (signed(max1_V_fu_718_p3) > signed(max2_V_fu_732_p3)) else "0";
    icmp_ln895_3_fu_1230_p2 <= "1" when (signed(tmp_3_fu_1220_p4) > signed(ap_const_lv25_0)) else "0";
    icmp_ln895_fu_712_p2 <= "1" when (signed(act_buf_V_0) > signed(act_buf_V_1)) else "0";
    icmp_ln899_fu_1200_p2 <= "1" when (signed(acc_reg_V_load_reg_2147) < signed(ap_const_lv32_1)) else "0";
    max1_V_fu_718_p3 <= 
        act_buf_V_0 when (icmp_ln895_fu_712_p2(0) = '1') else 
        act_buf_V_1;
    max2_V_fu_732_p3 <= 
        act_buf_V_2 when (icmp_ln895_1_fu_726_p2(0) = '1') else 
        act_buf_V_3;
    or_ln899_fu_1244_p2 <= (icmp_ln899_fu_1200_p2 or icmp_ln895_3_fu_1230_p2);
    phi_ln68_2_fu_1543_p33 <= (trunc_ln68_fu_1531_p1 & ap_const_lv2_0);
    phi_ln68_3_fu_1287_p33 <= (trunc_ln68_1_fu_1275_p1 & ap_const_lv2_0);
    product_V_fu_686_p0 <= product_V_fu_686_p00(32 - 1 downto 0);
    product_V_fu_686_p00 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(acc_reg_V),64));
    product_V_fu_686_p1 <= sext_ln68_1_fu_682_p0;
    product_V_fu_686_p2 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(std_logic_vector(signed('0' &product_V_fu_686_p0) * signed(product_V_fu_686_p1))), 64));

    rd_data_V_assign_proc : process(ap_start, ap_CS_fsm_state1, acc_reg_V, cnn_op_V_read_read_fu_242_p2, rd_data_V_preg)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1) and (cnn_op_V_read_read_fu_242_p2 = ap_const_lv4_3))) then 
            rd_data_V <= acc_reg_V;
        else 
            rd_data_V <= rd_data_V_preg;
        end if; 
    end process;

    rounded_V_fu_1205_p2 <= std_logic_vector(unsigned(ap_const_lv64_80000) + unsigned(product_V_reg_2153));
    scaled_V_fu_1210_p4 <= rounded_V_fu_1205_p2(51 downto 20);
    select_ln899_1_fu_1250_p3 <= 
        select_ln899_fu_1236_p3 when (or_ln899_fu_1244_p2(0) = '1') else 
        scaled_V_fu_1210_p4;
    select_ln899_fu_1236_p3 <= 
        ap_const_lv32_0 when (icmp_ln899_fu_1200_p2(0) = '1') else 
        ap_const_lv32_7F;
        sext_ln168_1_fu_1731_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(p_0111_0_i169_reg_355),20));

        sext_ln168_2_fu_1735_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(p_0107_0_i170_reg_367),20));

        sext_ln168_3_fu_1739_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(p_0103_0_i171_reg_379),20));

        sext_ln168_4_fu_1471_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(p_0217_0_i_reg_261),20));

        sext_ln168_5_fu_1475_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(p_0111_0_i_reg_273),20));

        sext_ln168_6_fu_1479_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(p_0107_0_i_reg_285),32));

        sext_ln168_7_fu_1483_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(p_0103_0_i_reg_297),20));

        sext_ln168_fu_1727_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(p_0217_0_i168_reg_343),20));

    sext_ln68_1_fu_682_p0 <= rs1_data_V;
        sext_ln68_2_fu_1749_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(add_ln68_fu_1743_p2),21));

        sext_ln68_3_fu_1759_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(add_ln68_1_fu_1753_p2),21));

        sext_ln68_4_fu_1769_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(add_ln68_2_fu_1763_p2),32));

        sext_ln68_fu_754_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(final_max_V_fu_746_p3),32));

        sext_ln700_fu_1504_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(add_ln700_4_fu_1498_p2),32));

    tmp_2_fu_692_p3 <= acc_reg_V(31 downto 31);
    tmp_3_fu_1220_p4 <= rounded_V_fu_1205_p2(51 downto 27);
    trunc_ln647_10_fu_846_p0 <= rs1_data_V;
    trunc_ln647_10_fu_846_p1 <= trunc_ln647_10_fu_846_p0(8 - 1 downto 0);
    trunc_ln647_11_fu_812_p0 <= rs1_data_V;
    trunc_ln647_11_fu_812_p1 <= trunc_ln647_11_fu_812_p0(8 - 1 downto 0);
    trunc_ln647_12_fu_778_p0 <= rs1_data_V;
    trunc_ln647_12_fu_778_p1 <= trunc_ln647_12_fu_778_p0(8 - 1 downto 0);
    trunc_ln647_13_fu_768_p0 <= rs1_data_V;
    trunc_ln647_13_fu_768_p1 <= trunc_ln647_13_fu_768_p0(8 - 1 downto 0);
    trunc_ln647_1_fu_1132_p0 <= rs1_data_V;
    trunc_ln647_1_fu_1132_p1 <= trunc_ln647_1_fu_1132_p0(8 - 1 downto 0);
    trunc_ln647_2_fu_1098_p0 <= rs1_data_V;
    trunc_ln647_2_fu_1098_p1 <= trunc_ln647_2_fu_1098_p0(8 - 1 downto 0);
    trunc_ln647_3_fu_1064_p0 <= rs1_data_V;
    trunc_ln647_3_fu_1064_p1 <= trunc_ln647_3_fu_1064_p0(8 - 1 downto 0);
    trunc_ln647_4_fu_1030_p0 <= rs1_data_V;
    trunc_ln647_4_fu_1030_p1 <= trunc_ln647_4_fu_1030_p0(8 - 1 downto 0);
    trunc_ln647_5_fu_996_p0 <= rs1_data_V;
    trunc_ln647_5_fu_996_p1 <= trunc_ln647_5_fu_996_p0(8 - 1 downto 0);
    trunc_ln647_6_fu_986_p0 <= rs1_data_V;
    trunc_ln647_6_fu_986_p1 <= trunc_ln647_6_fu_986_p0(8 - 1 downto 0);
    trunc_ln647_7_fu_948_p0 <= rs1_data_V;
    trunc_ln647_7_fu_948_p1 <= trunc_ln647_7_fu_948_p0(8 - 1 downto 0);
    trunc_ln647_8_fu_914_p0 <= rs1_data_V;
    trunc_ln647_8_fu_914_p1 <= trunc_ln647_8_fu_914_p0(8 - 1 downto 0);
    trunc_ln647_9_fu_880_p0 <= rs1_data_V;
    trunc_ln647_9_fu_880_p1 <= trunc_ln647_9_fu_880_p0(8 - 1 downto 0);
    trunc_ln647_fu_1166_p0 <= rs1_data_V;
    trunc_ln647_fu_1166_p1 <= trunc_ln647_fu_1166_p0(8 - 1 downto 0);
    trunc_ln68_1_fu_1275_p1 <= i_0_i_reg_309(3 - 1 downto 0);
    trunc_ln68_fu_1531_p1 <= i_0_i172_reg_391(3 - 1 downto 0);
    w_ptr_load_load_fu_982_p1 <= w_ptr;
end behav;
