// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2019.1
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="CNN_ALU_Top,hls_ip_2019_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=1,HLS_INPUT_PART=xc7z020-clg484-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=8.510000,HLS_SYN_LAT=3,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=12,HLS_SYN_FF=1334,HLS_SYN_LUT=1540,HLS_VERSION=2019_1}" *)

module CNN_ALU_Top (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        rs1_data_V,
        cnn_op_V,
        rd_data_V
);

parameter    ap_ST_fsm_state1 = 10'd1;
parameter    ap_ST_fsm_state2 = 10'd2;
parameter    ap_ST_fsm_state3 = 10'd4;
parameter    ap_ST_fsm_pp0_stage0 = 10'd8;
parameter    ap_ST_fsm_state6 = 10'd16;
parameter    ap_ST_fsm_state7 = 10'd32;
parameter    ap_ST_fsm_pp1_stage0 = 10'd64;
parameter    ap_ST_fsm_state10 = 10'd128;
parameter    ap_ST_fsm_state11 = 10'd256;
parameter    ap_ST_fsm_state12 = 10'd512;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [31:0] rs1_data_V;
input  [3:0] cnn_op_V;
output  [31:0] rd_data_V;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg[31:0] rd_data_V;

(* fsm_encoding = "none" *) reg   [9:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg   [7:0] weight_buf_V_0;
reg   [7:0] weight_buf_V_1;
reg   [7:0] weight_buf_V_2;
reg   [7:0] weight_buf_V_3;
reg   [7:0] weight_buf_V_4;
reg   [7:0] weight_buf_V_5;
reg   [7:0] weight_buf_V_6;
reg   [7:0] weight_buf_V_7;
reg   [7:0] weight_buf_V_8;
reg   [7:0] weight_buf_V_9;
reg   [7:0] weight_buf_V_10;
reg   [7:0] weight_buf_V_11;
reg   [7:0] weight_buf_V_12;
reg   [7:0] weight_buf_V_13;
reg   [7:0] weight_buf_V_14;
reg   [7:0] weight_buf_V_15;
reg   [7:0] weight_buf_V_16;
reg   [7:0] weight_buf_V_17;
reg   [7:0] weight_buf_V_18;
reg   [7:0] weight_buf_V_19;
reg   [7:0] weight_buf_V_20;
reg   [7:0] weight_buf_V_21;
reg   [7:0] weight_buf_V_22;
reg   [7:0] weight_buf_V_23;
reg   [7:0] weight_buf_V_24;
reg   [7:0] act_buf_V_0;
reg   [7:0] act_buf_V_1;
reg   [7:0] act_buf_V_2;
reg   [7:0] act_buf_V_3;
reg   [7:0] act_buf_V_4;
reg   [7:0] act_buf_V_5;
reg   [7:0] act_buf_V_6;
reg   [7:0] act_buf_V_7;
reg   [7:0] act_buf_V_8;
reg   [7:0] act_buf_V_9;
reg   [7:0] act_buf_V_10;
reg   [7:0] act_buf_V_11;
reg   [7:0] act_buf_V_12;
reg   [7:0] act_buf_V_13;
reg   [7:0] act_buf_V_14;
reg   [7:0] act_buf_V_15;
reg   [7:0] act_buf_V_16;
reg   [7:0] act_buf_V_17;
reg   [7:0] act_buf_V_18;
reg   [7:0] act_buf_V_19;
reg   [7:0] act_buf_V_20;
reg   [7:0] act_buf_V_21;
reg   [7:0] act_buf_V_22;
reg   [7:0] act_buf_V_23;
reg   [7:0] act_buf_V_24;
reg   [31:0] acc_reg_V;
reg   [6:0] w_ptr;
reg   [6:0] a_ptr;
reg  signed [18:0] p_0217_0_i_reg_261;
reg  signed [18:0] p_0111_0_i_reg_273;
reg  signed [18:0] p_0107_0_i_reg_285;
reg  signed [18:0] p_0103_0_i_reg_297;
reg   [3:0] i_0_i_reg_309;
reg  signed [18:0] p_0217_0_i168_reg_343;
reg  signed [18:0] p_0111_0_i169_reg_355;
reg  signed [18:0] p_0107_0_i170_reg_367;
reg  signed [18:0] p_0103_0_i171_reg_379;
reg   [3:0] i_0_i172_reg_391;
wire   [3:0] cnn_op_V_read_read_fu_242_p2;
reg   [7:0] weight_buf_V_0_load_reg_1847;
reg   [7:0] weight_buf_V_1_load_reg_1853;
reg   [7:0] weight_buf_V_2_load_reg_1859;
reg   [7:0] weight_buf_V_3_load_reg_1865;
reg   [7:0] weight_buf_V_4_load_reg_1871;
reg   [7:0] weight_buf_V_5_load_reg_1877;
reg   [7:0] weight_buf_V_6_load_reg_1883;
reg   [7:0] weight_buf_V_7_load_reg_1889;
reg   [7:0] weight_buf_V_8_load_reg_1895;
reg   [7:0] weight_buf_V_9_load_reg_1901;
reg   [7:0] weight_buf_V_10_load_reg_1907;
reg   [7:0] weight_buf_V_11_load_reg_1913;
reg   [7:0] weight_buf_V_12_load_reg_1919;
reg   [7:0] weight_buf_V_13_load_reg_1925;
reg   [7:0] weight_buf_V_14_load_reg_1931;
reg   [7:0] weight_buf_V_15_load_reg_1937;
reg   [7:0] weight_buf_V_16_load_reg_1943;
reg   [7:0] weight_buf_V_17_load_reg_1949;
reg   [7:0] weight_buf_V_18_load_reg_1955;
reg   [7:0] weight_buf_V_19_load_reg_1961;
reg   [7:0] weight_buf_V_20_load_reg_1967;
reg   [7:0] weight_buf_V_21_load_reg_1973;
reg   [7:0] weight_buf_V_22_load_reg_1979;
reg   [7:0] weight_buf_V_23_load_reg_1985;
reg   [7:0] weight_buf_V_24_load_reg_1991;
reg   [7:0] act_buf_V_0_load_reg_1997;
reg   [7:0] act_buf_V_1_load_reg_2003;
reg   [7:0] act_buf_V_2_load_reg_2009;
reg   [7:0] act_buf_V_3_load_reg_2015;
reg   [7:0] act_buf_V_4_load_reg_2021;
reg   [7:0] act_buf_V_5_load_reg_2027;
reg   [7:0] act_buf_V_6_load_reg_2033;
reg   [7:0] act_buf_V_7_load_reg_2039;
reg   [7:0] act_buf_V_8_load_reg_2045;
reg   [7:0] act_buf_V_9_load_reg_2051;
reg   [7:0] act_buf_V_10_load_reg_2057;
reg   [7:0] act_buf_V_11_load_reg_2063;
reg   [7:0] act_buf_V_12_load_reg_2069;
reg   [7:0] act_buf_V_13_load_reg_2075;
reg   [7:0] act_buf_V_14_load_reg_2081;
reg   [7:0] act_buf_V_15_load_reg_2087;
reg   [7:0] act_buf_V_16_load_reg_2093;
reg   [7:0] act_buf_V_17_load_reg_2099;
reg   [7:0] act_buf_V_18_load_reg_2105;
reg   [7:0] act_buf_V_19_load_reg_2111;
reg   [7:0] act_buf_V_20_load_reg_2117;
reg   [7:0] act_buf_V_21_load_reg_2123;
reg   [7:0] act_buf_V_22_load_reg_2129;
reg   [7:0] act_buf_V_23_load_reg_2135;
reg   [7:0] act_buf_V_24_load_reg_2141;
reg   [31:0] acc_reg_V_load_reg_2147;
wire   [63:0] product_V_fu_686_p2;
reg   [63:0] product_V_reg_2153;
wire   [31:0] select_ln899_1_fu_1250_p3;
reg   [31:0] select_ln899_1_reg_2167;
wire    ap_CS_fsm_state2;
wire   [0:0] icmp_ln168_1_fu_1263_p2;
reg   [0:0] icmp_ln168_1_reg_2172;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_block_state4_pp0_stage0_iter0;
wire    ap_block_state5_pp0_stage0_iter1;
wire    ap_block_pp0_stage0_11001;
wire   [3:0] i_1_fu_1269_p2;
reg    ap_enable_reg_pp0_iter0;
wire   [2:0] trunc_ln68_1_fu_1275_p1;
wire   [7:0] phi_ln68_3_fu_1287_p34;
reg  signed [7:0] phi_ln68_3_reg_2185;
wire   [7:0] phi_ln68_5_fu_1350_p10;
reg  signed [7:0] phi_ln68_5_reg_2190;
wire   [7:0] phi_ln68_7_fu_1366_p10;
reg  signed [7:0] phi_ln68_7_reg_2195;
wire   [7:0] phi_ln68_9_fu_1382_p10;
reg  signed [7:0] phi_ln68_9_reg_2200;
wire   [7:0] phi_ln68_11_fu_1398_p10;
reg  signed [7:0] phi_ln68_11_reg_2205;
wire   [7:0] phi_ln68_13_fu_1414_p10;
reg  signed [7:0] phi_ln68_13_reg_2210;
wire   [7:0] phi_ln68_14_fu_1430_p10;
reg  signed [7:0] phi_ln68_14_reg_2215;
wire  signed [18:0] grp_fu_1779_p3;
reg    ap_enable_reg_pp0_iter1;
wire  signed [18:0] grp_fu_1787_p3;
wire  signed [18:0] grp_fu_1795_p3;
wire  signed [18:0] grp_fu_1803_p3;
wire   [31:0] add_ln700_1_fu_1508_p2;
reg   [31:0] add_ln700_1_reg_2240;
wire    ap_CS_fsm_state6;
wire   [0:0] icmp_ln168_fu_1519_p2;
reg   [0:0] icmp_ln168_reg_2245;
wire    ap_CS_fsm_pp1_stage0;
wire    ap_block_state8_pp1_stage0_iter0;
wire    ap_block_state9_pp1_stage0_iter1;
wire    ap_block_pp1_stage0_11001;
wire   [3:0] i_fu_1525_p2;
reg    ap_enable_reg_pp1_iter0;
wire   [2:0] trunc_ln68_fu_1531_p1;
wire   [7:0] phi_ln68_2_fu_1543_p34;
reg  signed [7:0] phi_ln68_2_reg_2258;
wire   [7:0] phi_ln68_4_fu_1606_p10;
reg  signed [7:0] phi_ln68_4_reg_2263;
wire   [7:0] phi_ln68_6_fu_1622_p10;
reg  signed [7:0] phi_ln68_6_reg_2268;
wire   [7:0] phi_ln68_8_fu_1638_p10;
reg  signed [7:0] phi_ln68_8_reg_2273;
wire   [7:0] phi_ln68_s_fu_1654_p10;
reg  signed [7:0] phi_ln68_s_reg_2278;
wire   [7:0] phi_ln68_10_fu_1670_p10;
reg  signed [7:0] phi_ln68_10_reg_2283;
wire   [7:0] phi_ln68_12_fu_1686_p10;
reg  signed [7:0] phi_ln68_12_reg_2288;
wire  signed [18:0] grp_fu_1811_p3;
reg    ap_enable_reg_pp1_iter1;
wire  signed [18:0] grp_fu_1819_p3;
wire  signed [18:0] grp_fu_1827_p3;
wire  signed [18:0] grp_fu_1835_p3;
wire    ap_block_pp0_stage0_subdone;
reg    ap_condition_pp0_exit_iter0_state4;
wire    ap_block_pp1_stage0_subdone;
reg    ap_condition_pp1_exit_iter0_state8;
wire    ap_block_pp0_stage0;
wire   [7:0] ap_phi_reg_pp0_iter0_phi_ln68_1_reg_320;
reg  signed [7:0] ap_phi_reg_pp0_iter1_phi_ln68_1_reg_320;
wire    ap_block_pp1_stage0;
wire   [7:0] ap_phi_reg_pp1_iter0_phi_ln68_reg_402;
reg  signed [7:0] ap_phi_reg_pp1_iter1_phi_ln68_reg_402;
wire   [7:0] trunc_ln647_fu_1166_p1;
wire   [6:0] w_ptr_load_load_fu_982_p1;
wire   [7:0] trunc_ln647_1_fu_1132_p1;
wire   [7:0] trunc_ln647_2_fu_1098_p1;
wire   [7:0] trunc_ln647_3_fu_1064_p1;
wire   [7:0] trunc_ln647_4_fu_1030_p1;
wire   [7:0] trunc_ln647_5_fu_996_p1;
wire   [7:0] trunc_ln647_6_fu_986_p1;
wire   [7:0] trunc_ln647_7_fu_948_p1;
wire   [6:0] a_ptr_load_load_fu_764_p1;
wire   [7:0] trunc_ln647_8_fu_914_p1;
wire   [7:0] trunc_ln647_9_fu_880_p1;
wire   [7:0] trunc_ln647_10_fu_846_p1;
wire   [7:0] trunc_ln647_11_fu_812_p1;
wire   [7:0] trunc_ln647_12_fu_778_p1;
wire   [7:0] trunc_ln647_13_fu_768_p1;
wire   [0:0] tmp_2_fu_692_p3;
wire   [31:0] add_ln700_fu_700_p2;
wire  signed [31:0] sext_ln68_fu_754_p1;
wire    ap_CS_fsm_state3;
wire    ap_CS_fsm_state7;
wire  signed [31:0] sext_ln68_4_fu_1769_p1;
wire    ap_CS_fsm_state10;
reg   [31:0] rd_data_V_preg;
wire  signed [31:0] grp_fu_443_p1;
wire  signed [31:0] grp_fu_453_p1;
wire  signed [31:0] grp_fu_463_p1;
wire  signed [31:0] sext_ln68_1_fu_682_p0;
wire   [31:0] product_V_fu_686_p0;
wire  signed [31:0] product_V_fu_686_p1;
wire  signed [31:0] add_ln700_fu_700_p1;
wire   [0:0] icmp_ln895_fu_712_p2;
wire   [0:0] icmp_ln895_1_fu_726_p2;
wire   [7:0] max1_V_fu_718_p3;
wire   [7:0] max2_V_fu_732_p3;
wire   [0:0] icmp_ln895_2_fu_740_p2;
wire   [7:0] final_max_V_fu_746_p3;
wire  signed [31:0] trunc_ln647_13_fu_768_p0;
wire  signed [31:0] trunc_ln647_12_fu_778_p0;
wire  signed [31:0] trunc_ln647_11_fu_812_p0;
wire  signed [31:0] trunc_ln647_10_fu_846_p0;
wire  signed [31:0] trunc_ln647_9_fu_880_p0;
wire  signed [31:0] trunc_ln647_8_fu_914_p0;
wire  signed [31:0] trunc_ln647_7_fu_948_p0;
wire  signed [31:0] trunc_ln647_6_fu_986_p0;
wire  signed [31:0] trunc_ln647_5_fu_996_p0;
wire  signed [31:0] trunc_ln647_4_fu_1030_p0;
wire  signed [31:0] trunc_ln647_3_fu_1064_p0;
wire  signed [31:0] trunc_ln647_2_fu_1098_p0;
wire  signed [31:0] trunc_ln647_1_fu_1132_p0;
wire  signed [31:0] trunc_ln647_fu_1166_p0;
wire   [63:0] rounded_V_fu_1205_p2;
wire   [24:0] tmp_3_fu_1220_p4;
wire   [0:0] icmp_ln899_fu_1200_p2;
wire   [0:0] icmp_ln895_3_fu_1230_p2;
wire   [0:0] or_ln899_fu_1244_p2;
wire   [31:0] select_ln899_fu_1236_p3;
wire   [31:0] scaled_V_fu_1210_p4;
wire   [4:0] phi_ln68_3_fu_1287_p33;
wire  signed [31:0] sext_ln168_6_fu_1479_p1;
wire  signed [19:0] sext_ln168_5_fu_1475_p1;
wire  signed [19:0] sext_ln168_4_fu_1471_p1;
wire   [19:0] add_ln700_3_fu_1492_p2;
wire  signed [19:0] sext_ln168_7_fu_1483_p1;
wire   [19:0] add_ln700_4_fu_1498_p2;
wire  signed [31:0] sext_ln700_fu_1504_p1;
wire   [31:0] add_ln700_2_fu_1487_p2;
wire   [4:0] phi_ln68_2_fu_1543_p33;
wire  signed [19:0] sext_ln168_2_fu_1735_p1;
wire  signed [19:0] sext_ln168_3_fu_1739_p1;
wire   [19:0] add_ln68_fu_1743_p2;
wire  signed [19:0] sext_ln168_1_fu_1731_p1;
wire  signed [19:0] sext_ln168_fu_1727_p1;
wire   [19:0] add_ln68_1_fu_1753_p2;
wire  signed [20:0] sext_ln68_3_fu_1759_p1;
wire  signed [20:0] sext_ln68_2_fu_1749_p1;
wire   [20:0] add_ln68_2_fu_1763_p2;
reg   [9:0] ap_NS_fsm;
reg    ap_idle_pp0;
wire    ap_enable_pp0;
reg    ap_idle_pp1;
wire    ap_enable_pp1;
wire   [63:0] product_V_fu_686_p00;
reg    ap_condition_249;
reg    ap_condition_308;

// power-on initialization
initial begin
#0 ap_CS_fsm = 10'd1;
#0 weight_buf_V_0 = 8'd0;
#0 weight_buf_V_1 = 8'd0;
#0 weight_buf_V_2 = 8'd0;
#0 weight_buf_V_3 = 8'd0;
#0 weight_buf_V_4 = 8'd0;
#0 weight_buf_V_5 = 8'd0;
#0 weight_buf_V_6 = 8'd0;
#0 weight_buf_V_7 = 8'd0;
#0 weight_buf_V_8 = 8'd0;
#0 weight_buf_V_9 = 8'd0;
#0 weight_buf_V_10 = 8'd0;
#0 weight_buf_V_11 = 8'd0;
#0 weight_buf_V_12 = 8'd0;
#0 weight_buf_V_13 = 8'd0;
#0 weight_buf_V_14 = 8'd0;
#0 weight_buf_V_15 = 8'd0;
#0 weight_buf_V_16 = 8'd0;
#0 weight_buf_V_17 = 8'd0;
#0 weight_buf_V_18 = 8'd0;
#0 weight_buf_V_19 = 8'd0;
#0 weight_buf_V_20 = 8'd0;
#0 weight_buf_V_21 = 8'd0;
#0 weight_buf_V_22 = 8'd0;
#0 weight_buf_V_23 = 8'd0;
#0 weight_buf_V_24 = 8'd0;
#0 act_buf_V_0 = 8'd0;
#0 act_buf_V_1 = 8'd0;
#0 act_buf_V_2 = 8'd0;
#0 act_buf_V_3 = 8'd0;
#0 act_buf_V_4 = 8'd0;
#0 act_buf_V_5 = 8'd0;
#0 act_buf_V_6 = 8'd0;
#0 act_buf_V_7 = 8'd0;
#0 act_buf_V_8 = 8'd0;
#0 act_buf_V_9 = 8'd0;
#0 act_buf_V_10 = 8'd0;
#0 act_buf_V_11 = 8'd0;
#0 act_buf_V_12 = 8'd0;
#0 act_buf_V_13 = 8'd0;
#0 act_buf_V_14 = 8'd0;
#0 act_buf_V_15 = 8'd0;
#0 act_buf_V_16 = 8'd0;
#0 act_buf_V_17 = 8'd0;
#0 act_buf_V_18 = 8'd0;
#0 act_buf_V_19 = 8'd0;
#0 act_buf_V_20 = 8'd0;
#0 act_buf_V_21 = 8'd0;
#0 act_buf_V_22 = 8'd0;
#0 act_buf_V_23 = 8'd0;
#0 act_buf_V_24 = 8'd0;
#0 acc_reg_V = 32'd0;
#0 w_ptr = 7'd0;
#0 a_ptr = 7'd0;
#0 ap_enable_reg_pp0_iter0 = 1'b0;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp1_iter0 = 1'b0;
#0 ap_enable_reg_pp1_iter1 = 1'b0;
#0 rd_data_V_preg = 32'd0;
end

CNN_ALU_Top_mux_3bkb #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 8 ),
    .din4_WIDTH( 8 ),
    .din5_WIDTH( 8 ),
    .din6_WIDTH( 8 ),
    .din7_WIDTH( 8 ),
    .din8_WIDTH( 8 ),
    .din9_WIDTH( 8 ),
    .din10_WIDTH( 8 ),
    .din11_WIDTH( 8 ),
    .din12_WIDTH( 8 ),
    .din13_WIDTH( 8 ),
    .din14_WIDTH( 8 ),
    .din15_WIDTH( 8 ),
    .din16_WIDTH( 8 ),
    .din17_WIDTH( 8 ),
    .din18_WIDTH( 8 ),
    .din19_WIDTH( 8 ),
    .din20_WIDTH( 8 ),
    .din21_WIDTH( 8 ),
    .din22_WIDTH( 8 ),
    .din23_WIDTH( 8 ),
    .din24_WIDTH( 8 ),
    .din25_WIDTH( 8 ),
    .din26_WIDTH( 8 ),
    .din27_WIDTH( 8 ),
    .din28_WIDTH( 8 ),
    .din29_WIDTH( 8 ),
    .din30_WIDTH( 8 ),
    .din31_WIDTH( 8 ),
    .din32_WIDTH( 5 ),
    .dout_WIDTH( 8 ))
CNN_ALU_Top_mux_3bkb_U1(
    .din0(weight_buf_V_0_load_reg_1847),
    .din1(8'd0),
    .din2(8'd0),
    .din3(8'd0),
    .din4(weight_buf_V_4_load_reg_1871),
    .din5(8'd0),
    .din6(8'd0),
    .din7(8'd0),
    .din8(weight_buf_V_8_load_reg_1895),
    .din9(8'd0),
    .din10(8'd0),
    .din11(8'd0),
    .din12(weight_buf_V_12_load_reg_1919),
    .din13(8'd0),
    .din14(8'd0),
    .din15(8'd0),
    .din16(weight_buf_V_16_load_reg_1943),
    .din17(8'd0),
    .din18(8'd0),
    .din19(8'd0),
    .din20(weight_buf_V_20_load_reg_1967),
    .din21(8'd0),
    .din22(8'd0),
    .din23(8'd0),
    .din24(weight_buf_V_24_load_reg_1991),
    .din25(8'd0),
    .din26(8'd0),
    .din27(8'd0),
    .din28(8'd0),
    .din29(8'd0),
    .din30(8'd0),
    .din31(8'd0),
    .din32(phi_ln68_3_fu_1287_p33),
    .dout(phi_ln68_3_fu_1287_p34)
);

CNN_ALU_Top_mux_8cud #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 8 ),
    .din4_WIDTH( 8 ),
    .din5_WIDTH( 8 ),
    .din6_WIDTH( 8 ),
    .din7_WIDTH( 8 ),
    .din8_WIDTH( 3 ),
    .dout_WIDTH( 8 ))
CNN_ALU_Top_mux_8cud_U2(
    .din0(act_buf_V_1_load_reg_2003),
    .din1(act_buf_V_5_load_reg_2027),
    .din2(act_buf_V_9_load_reg_2051),
    .din3(act_buf_V_13_load_reg_2075),
    .din4(act_buf_V_17_load_reg_2099),
    .din5(act_buf_V_21_load_reg_2123),
    .din6(8'd0),
    .din7(8'd0),
    .din8(trunc_ln68_1_fu_1275_p1),
    .dout(phi_ln68_5_fu_1350_p10)
);

CNN_ALU_Top_mux_8cud #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 8 ),
    .din4_WIDTH( 8 ),
    .din5_WIDTH( 8 ),
    .din6_WIDTH( 8 ),
    .din7_WIDTH( 8 ),
    .din8_WIDTH( 3 ),
    .dout_WIDTH( 8 ))
CNN_ALU_Top_mux_8cud_U3(
    .din0(weight_buf_V_1_load_reg_1853),
    .din1(weight_buf_V_5_load_reg_1877),
    .din2(weight_buf_V_9_load_reg_1901),
    .din3(weight_buf_V_13_load_reg_1925),
    .din4(weight_buf_V_17_load_reg_1949),
    .din5(weight_buf_V_21_load_reg_1973),
    .din6(8'd0),
    .din7(8'd0),
    .din8(trunc_ln68_1_fu_1275_p1),
    .dout(phi_ln68_7_fu_1366_p10)
);

CNN_ALU_Top_mux_8cud #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 8 ),
    .din4_WIDTH( 8 ),
    .din5_WIDTH( 8 ),
    .din6_WIDTH( 8 ),
    .din7_WIDTH( 8 ),
    .din8_WIDTH( 3 ),
    .dout_WIDTH( 8 ))
CNN_ALU_Top_mux_8cud_U4(
    .din0(act_buf_V_2_load_reg_2009),
    .din1(act_buf_V_6_load_reg_2033),
    .din2(act_buf_V_10_load_reg_2057),
    .din3(act_buf_V_14_load_reg_2081),
    .din4(act_buf_V_18_load_reg_2105),
    .din5(act_buf_V_22_load_reg_2129),
    .din6(8'd0),
    .din7(8'd0),
    .din8(trunc_ln68_1_fu_1275_p1),
    .dout(phi_ln68_9_fu_1382_p10)
);

CNN_ALU_Top_mux_8cud #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 8 ),
    .din4_WIDTH( 8 ),
    .din5_WIDTH( 8 ),
    .din6_WIDTH( 8 ),
    .din7_WIDTH( 8 ),
    .din8_WIDTH( 3 ),
    .dout_WIDTH( 8 ))
CNN_ALU_Top_mux_8cud_U5(
    .din0(weight_buf_V_2_load_reg_1859),
    .din1(weight_buf_V_6_load_reg_1883),
    .din2(weight_buf_V_10_load_reg_1907),
    .din3(weight_buf_V_14_load_reg_1931),
    .din4(weight_buf_V_18_load_reg_1955),
    .din5(weight_buf_V_22_load_reg_1979),
    .din6(8'd0),
    .din7(8'd0),
    .din8(trunc_ln68_1_fu_1275_p1),
    .dout(phi_ln68_11_fu_1398_p10)
);

CNN_ALU_Top_mux_8cud #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 8 ),
    .din4_WIDTH( 8 ),
    .din5_WIDTH( 8 ),
    .din6_WIDTH( 8 ),
    .din7_WIDTH( 8 ),
    .din8_WIDTH( 3 ),
    .dout_WIDTH( 8 ))
CNN_ALU_Top_mux_8cud_U6(
    .din0(act_buf_V_3_load_reg_2015),
    .din1(act_buf_V_7_load_reg_2039),
    .din2(act_buf_V_11_load_reg_2063),
    .din3(act_buf_V_15_load_reg_2087),
    .din4(act_buf_V_19_load_reg_2111),
    .din5(act_buf_V_23_load_reg_2135),
    .din6(8'd0),
    .din7(8'd0),
    .din8(trunc_ln68_1_fu_1275_p1),
    .dout(phi_ln68_13_fu_1414_p10)
);

CNN_ALU_Top_mux_8cud #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 8 ),
    .din4_WIDTH( 8 ),
    .din5_WIDTH( 8 ),
    .din6_WIDTH( 8 ),
    .din7_WIDTH( 8 ),
    .din8_WIDTH( 3 ),
    .dout_WIDTH( 8 ))
CNN_ALU_Top_mux_8cud_U7(
    .din0(weight_buf_V_3_load_reg_1865),
    .din1(weight_buf_V_7_load_reg_1889),
    .din2(weight_buf_V_11_load_reg_1913),
    .din3(weight_buf_V_15_load_reg_1937),
    .din4(weight_buf_V_19_load_reg_1961),
    .din5(weight_buf_V_23_load_reg_1985),
    .din6(8'd0),
    .din7(8'd0),
    .din8(trunc_ln68_1_fu_1275_p1),
    .dout(phi_ln68_14_fu_1430_p10)
);

CNN_ALU_Top_mux_3bkb #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 8 ),
    .din4_WIDTH( 8 ),
    .din5_WIDTH( 8 ),
    .din6_WIDTH( 8 ),
    .din7_WIDTH( 8 ),
    .din8_WIDTH( 8 ),
    .din9_WIDTH( 8 ),
    .din10_WIDTH( 8 ),
    .din11_WIDTH( 8 ),
    .din12_WIDTH( 8 ),
    .din13_WIDTH( 8 ),
    .din14_WIDTH( 8 ),
    .din15_WIDTH( 8 ),
    .din16_WIDTH( 8 ),
    .din17_WIDTH( 8 ),
    .din18_WIDTH( 8 ),
    .din19_WIDTH( 8 ),
    .din20_WIDTH( 8 ),
    .din21_WIDTH( 8 ),
    .din22_WIDTH( 8 ),
    .din23_WIDTH( 8 ),
    .din24_WIDTH( 8 ),
    .din25_WIDTH( 8 ),
    .din26_WIDTH( 8 ),
    .din27_WIDTH( 8 ),
    .din28_WIDTH( 8 ),
    .din29_WIDTH( 8 ),
    .din30_WIDTH( 8 ),
    .din31_WIDTH( 8 ),
    .din32_WIDTH( 5 ),
    .dout_WIDTH( 8 ))
CNN_ALU_Top_mux_3bkb_U8(
    .din0(weight_buf_V_0_load_reg_1847),
    .din1(8'd0),
    .din2(8'd0),
    .din3(8'd0),
    .din4(weight_buf_V_4_load_reg_1871),
    .din5(8'd0),
    .din6(8'd0),
    .din7(8'd0),
    .din8(weight_buf_V_8_load_reg_1895),
    .din9(8'd0),
    .din10(8'd0),
    .din11(8'd0),
    .din12(weight_buf_V_12_load_reg_1919),
    .din13(8'd0),
    .din14(8'd0),
    .din15(8'd0),
    .din16(weight_buf_V_16_load_reg_1943),
    .din17(8'd0),
    .din18(8'd0),
    .din19(8'd0),
    .din20(weight_buf_V_20_load_reg_1967),
    .din21(8'd0),
    .din22(8'd0),
    .din23(8'd0),
    .din24(weight_buf_V_24_load_reg_1991),
    .din25(8'd0),
    .din26(8'd0),
    .din27(8'd0),
    .din28(8'd0),
    .din29(8'd0),
    .din30(8'd0),
    .din31(8'd0),
    .din32(phi_ln68_2_fu_1543_p33),
    .dout(phi_ln68_2_fu_1543_p34)
);

CNN_ALU_Top_mux_8cud #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 8 ),
    .din4_WIDTH( 8 ),
    .din5_WIDTH( 8 ),
    .din6_WIDTH( 8 ),
    .din7_WIDTH( 8 ),
    .din8_WIDTH( 3 ),
    .dout_WIDTH( 8 ))
CNN_ALU_Top_mux_8cud_U9(
    .din0(act_buf_V_1_load_reg_2003),
    .din1(act_buf_V_5_load_reg_2027),
    .din2(act_buf_V_9_load_reg_2051),
    .din3(act_buf_V_13_load_reg_2075),
    .din4(act_buf_V_17_load_reg_2099),
    .din5(act_buf_V_21_load_reg_2123),
    .din6(8'd0),
    .din7(8'd0),
    .din8(trunc_ln68_fu_1531_p1),
    .dout(phi_ln68_4_fu_1606_p10)
);

CNN_ALU_Top_mux_8cud #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 8 ),
    .din4_WIDTH( 8 ),
    .din5_WIDTH( 8 ),
    .din6_WIDTH( 8 ),
    .din7_WIDTH( 8 ),
    .din8_WIDTH( 3 ),
    .dout_WIDTH( 8 ))
CNN_ALU_Top_mux_8cud_U10(
    .din0(weight_buf_V_1_load_reg_1853),
    .din1(weight_buf_V_5_load_reg_1877),
    .din2(weight_buf_V_9_load_reg_1901),
    .din3(weight_buf_V_13_load_reg_1925),
    .din4(weight_buf_V_17_load_reg_1949),
    .din5(weight_buf_V_21_load_reg_1973),
    .din6(8'd0),
    .din7(8'd0),
    .din8(trunc_ln68_fu_1531_p1),
    .dout(phi_ln68_6_fu_1622_p10)
);

CNN_ALU_Top_mux_8cud #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 8 ),
    .din4_WIDTH( 8 ),
    .din5_WIDTH( 8 ),
    .din6_WIDTH( 8 ),
    .din7_WIDTH( 8 ),
    .din8_WIDTH( 3 ),
    .dout_WIDTH( 8 ))
CNN_ALU_Top_mux_8cud_U11(
    .din0(act_buf_V_2_load_reg_2009),
    .din1(act_buf_V_6_load_reg_2033),
    .din2(act_buf_V_10_load_reg_2057),
    .din3(act_buf_V_14_load_reg_2081),
    .din4(act_buf_V_18_load_reg_2105),
    .din5(act_buf_V_22_load_reg_2129),
    .din6(8'd0),
    .din7(8'd0),
    .din8(trunc_ln68_fu_1531_p1),
    .dout(phi_ln68_8_fu_1638_p10)
);

CNN_ALU_Top_mux_8cud #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 8 ),
    .din4_WIDTH( 8 ),
    .din5_WIDTH( 8 ),
    .din6_WIDTH( 8 ),
    .din7_WIDTH( 8 ),
    .din8_WIDTH( 3 ),
    .dout_WIDTH( 8 ))
CNN_ALU_Top_mux_8cud_U12(
    .din0(weight_buf_V_2_load_reg_1859),
    .din1(weight_buf_V_6_load_reg_1883),
    .din2(weight_buf_V_10_load_reg_1907),
    .din3(weight_buf_V_14_load_reg_1931),
    .din4(weight_buf_V_18_load_reg_1955),
    .din5(weight_buf_V_22_load_reg_1979),
    .din6(8'd0),
    .din7(8'd0),
    .din8(trunc_ln68_fu_1531_p1),
    .dout(phi_ln68_s_fu_1654_p10)
);

CNN_ALU_Top_mux_8cud #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 8 ),
    .din4_WIDTH( 8 ),
    .din5_WIDTH( 8 ),
    .din6_WIDTH( 8 ),
    .din7_WIDTH( 8 ),
    .din8_WIDTH( 3 ),
    .dout_WIDTH( 8 ))
CNN_ALU_Top_mux_8cud_U13(
    .din0(act_buf_V_3_load_reg_2015),
    .din1(act_buf_V_7_load_reg_2039),
    .din2(act_buf_V_11_load_reg_2063),
    .din3(act_buf_V_15_load_reg_2087),
    .din4(act_buf_V_19_load_reg_2111),
    .din5(act_buf_V_23_load_reg_2135),
    .din6(8'd0),
    .din7(8'd0),
    .din8(trunc_ln68_fu_1531_p1),
    .dout(phi_ln68_10_fu_1670_p10)
);

CNN_ALU_Top_mux_8cud #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 8 ),
    .din4_WIDTH( 8 ),
    .din5_WIDTH( 8 ),
    .din6_WIDTH( 8 ),
    .din7_WIDTH( 8 ),
    .din8_WIDTH( 3 ),
    .dout_WIDTH( 8 ))
CNN_ALU_Top_mux_8cud_U14(
    .din0(weight_buf_V_3_load_reg_1865),
    .din1(weight_buf_V_7_load_reg_1889),
    .din2(weight_buf_V_11_load_reg_1913),
    .din3(weight_buf_V_15_load_reg_1937),
    .din4(weight_buf_V_19_load_reg_1961),
    .din5(weight_buf_V_23_load_reg_1985),
    .din6(8'd0),
    .din7(8'd0),
    .din8(trunc_ln68_fu_1531_p1),
    .dout(phi_ln68_12_fu_1686_p10)
);

CNN_ALU_Top_mac_mdEe #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 19 ),
    .dout_WIDTH( 19 ))
CNN_ALU_Top_mac_mdEe_U15(
    .din0(ap_phi_reg_pp0_iter1_phi_ln68_1_reg_320),
    .din1(phi_ln68_3_reg_2185),
    .din2(p_0217_0_i_reg_261),
    .dout(grp_fu_1779_p3)
);

CNN_ALU_Top_mac_mdEe #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 19 ),
    .dout_WIDTH( 19 ))
CNN_ALU_Top_mac_mdEe_U16(
    .din0(phi_ln68_5_reg_2190),
    .din1(phi_ln68_7_reg_2195),
    .din2(p_0111_0_i_reg_273),
    .dout(grp_fu_1787_p3)
);

CNN_ALU_Top_mac_mdEe #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 19 ),
    .dout_WIDTH( 19 ))
CNN_ALU_Top_mac_mdEe_U17(
    .din0(phi_ln68_9_reg_2200),
    .din1(phi_ln68_11_reg_2205),
    .din2(p_0107_0_i_reg_285),
    .dout(grp_fu_1795_p3)
);

CNN_ALU_Top_mac_mdEe #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 19 ),
    .dout_WIDTH( 19 ))
CNN_ALU_Top_mac_mdEe_U18(
    .din0(phi_ln68_14_reg_2215),
    .din1(phi_ln68_13_reg_2210),
    .din2(p_0103_0_i_reg_297),
    .dout(grp_fu_1803_p3)
);

CNN_ALU_Top_mac_mdEe #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 19 ),
    .dout_WIDTH( 19 ))
CNN_ALU_Top_mac_mdEe_U19(
    .din0(ap_phi_reg_pp1_iter1_phi_ln68_reg_402),
    .din1(phi_ln68_2_reg_2258),
    .din2(p_0217_0_i168_reg_343),
    .dout(grp_fu_1811_p3)
);

CNN_ALU_Top_mac_mdEe #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 19 ),
    .dout_WIDTH( 19 ))
CNN_ALU_Top_mac_mdEe_U20(
    .din0(phi_ln68_4_reg_2263),
    .din1(phi_ln68_6_reg_2268),
    .din2(p_0111_0_i169_reg_355),
    .dout(grp_fu_1819_p3)
);

CNN_ALU_Top_mac_mdEe #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 19 ),
    .dout_WIDTH( 19 ))
CNN_ALU_Top_mac_mdEe_U21(
    .din0(phi_ln68_8_reg_2273),
    .din1(phi_ln68_s_reg_2278),
    .din2(p_0107_0_i170_reg_367),
    .dout(grp_fu_1827_p3)
);

CNN_ALU_Top_mac_mdEe #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 19 ),
    .dout_WIDTH( 19 ))
CNN_ALU_Top_mac_mdEe_U22(
    .din0(phi_ln68_12_reg_2288),
    .din1(phi_ln68_10_reg_2283),
    .din2(p_0103_0_i171_reg_379),
    .dout(grp_fu_1835_p3)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_condition_pp0_exit_iter0_state4) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter0 <= 1'b0;
        end else if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1) & (cnn_op_V_read_read_fu_242_p2 == 4'd6))) begin
            ap_enable_reg_pp0_iter0 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_condition_pp0_exit_iter0_state4))) begin
            ap_enable_reg_pp0_iter1 <= (1'b1 ^ ap_condition_pp0_exit_iter0_state4);
        end else if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
        end else if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1) & (cnn_op_V_read_read_fu_242_p2 == 4'd6))) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp1_iter0 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp1_stage0_subdone) & (1'b1 == ap_condition_pp1_exit_iter0_state8) & (1'b1 == ap_CS_fsm_pp1_stage0))) begin
            ap_enable_reg_pp1_iter0 <= 1'b0;
        end else if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1) & (cnn_op_V_read_read_fu_242_p2 == 4'd2))) begin
            ap_enable_reg_pp1_iter0 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp1_iter1 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp1_stage0_subdone) & (1'b1 == ap_condition_pp1_exit_iter0_state8))) begin
            ap_enable_reg_pp1_iter1 <= (1'b1 ^ ap_condition_pp1_exit_iter0_state8);
        end else if ((1'b0 == ap_block_pp1_stage0_subdone)) begin
            ap_enable_reg_pp1_iter1 <= ap_enable_reg_pp1_iter0;
        end else if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1) & (cnn_op_V_read_read_fu_242_p2 == 4'd2))) begin
            ap_enable_reg_pp1_iter1 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        rd_data_V_preg <= 32'd0;
    end else begin
        if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1) & (cnn_op_V_read_read_fu_242_p2 == 4'd3))) begin
            rd_data_V_preg <= acc_reg_V;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((7'd0 == a_ptr_load_load_fu_764_p1) & (1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1) & (cnn_op_V_read_read_fu_242_p2 == 4'd1))) begin
                a_ptr[2] <= 1'b1;
        a_ptr[3] <= 1'b0;
        a_ptr[4] <= 1'b0;
    end else if (((7'd4 == a_ptr_load_load_fu_764_p1) & (1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1) & (cnn_op_V_read_read_fu_242_p2 == 4'd1))) begin
                a_ptr[2] <= 1'b0;
        a_ptr[3] <= 1'b1;
        a_ptr[4] <= 1'b0;
    end else if (((7'd8 == a_ptr_load_load_fu_764_p1) & (1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1) & (cnn_op_V_read_read_fu_242_p2 == 4'd1))) begin
                a_ptr[2] <= 1'b1;
        a_ptr[3] <= 1'b1;
        a_ptr[4] <= 1'b0;
    end else if (((7'd12 == a_ptr_load_load_fu_764_p1) & (1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1) & (cnn_op_V_read_read_fu_242_p2 == 4'd1))) begin
                a_ptr[2] <= 1'b0;
        a_ptr[3] <= 1'b0;
        a_ptr[4] <= 1'b1;
    end else if (((7'd16 == a_ptr_load_load_fu_764_p1) & (1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1) & (cnn_op_V_read_read_fu_242_p2 == 4'd1))) begin
                a_ptr[2] <= 1'b1;
        a_ptr[3] <= 1'b0;
        a_ptr[4] <= 1'b1;
    end else if (((7'd20 == a_ptr_load_load_fu_764_p1) & (1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1) & (cnn_op_V_read_read_fu_242_p2 == 4'd1))) begin
                a_ptr[2] <= 1'b0;
        a_ptr[3] <= 1'b1;
        a_ptr[4] <= 1'b1;
    end else if ((((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1) & (cnn_op_V_read_read_fu_242_p2 == 4'd5)) | (~(7'd24 == a_ptr_load_load_fu_764_p1) & ~(7'd20 == a_ptr_load_load_fu_764_p1) & ~(7'd16 == a_ptr_load_load_fu_764_p1) & ~(7'd12 == a_ptr_load_load_fu_764_p1) & ~(7'd8 == a_ptr_load_load_fu_764_p1) & ~(7'd4 == a_ptr_load_load_fu_764_p1) & ~(7'd0 == a_ptr_load_load_fu_764_p1) & (1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1) & (cnn_op_V_read_read_fu_242_p2 == 4'd1)) | ((7'd24 == a_ptr_load_load_fu_764_p1) & (1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1) & (cnn_op_V_read_read_fu_242_p2 == 4'd1)))) begin
                a_ptr[2] <= 1'b0;
        a_ptr[3] <= 1'b0;
        a_ptr[4] <= 1'b0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        acc_reg_V <= sext_ln68_4_fu_1769_p1;
    end else if (((1'b1 == ap_CS_fsm_state7) & (cnn_op_V_read_read_fu_242_p2 == 4'd6))) begin
        acc_reg_V <= add_ln700_1_reg_2240;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        acc_reg_V <= select_ln899_1_reg_2167;
    end else if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1) & (cnn_op_V_read_read_fu_242_p2 == 4'd4))) begin
        acc_reg_V <= sext_ln68_fu_754_p1;
    end else if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1) & (cnn_op_V_read_read_fu_242_p2 == 4'd8))) begin
        acc_reg_V <= add_ln700_fu_700_p2;
    end else if ((((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1) & (cnn_op_V_read_read_fu_242_p2 == 4'd5)) | ((tmp_2_fu_692_p3 == 1'd1) & (1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1) & (cnn_op_V_read_read_fu_242_p2 == 4'd7)))) begin
        acc_reg_V <= 32'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_249)) begin
        if (((trunc_ln68_1_fu_1275_p1 == 3'd6) & (icmp_ln168_1_fu_1263_p2 == 1'd0))) begin
            ap_phi_reg_pp0_iter1_phi_ln68_1_reg_320 <= act_buf_V_24_load_reg_2141;
        end else if (((trunc_ln68_1_fu_1275_p1 == 3'd5) & (icmp_ln168_1_fu_1263_p2 == 1'd0))) begin
            ap_phi_reg_pp0_iter1_phi_ln68_1_reg_320 <= act_buf_V_20_load_reg_2117;
        end else if (((trunc_ln68_1_fu_1275_p1 == 3'd4) & (icmp_ln168_1_fu_1263_p2 == 1'd0))) begin
            ap_phi_reg_pp0_iter1_phi_ln68_1_reg_320 <= act_buf_V_16_load_reg_2093;
        end else if (((trunc_ln68_1_fu_1275_p1 == 3'd3) & (icmp_ln168_1_fu_1263_p2 == 1'd0))) begin
            ap_phi_reg_pp0_iter1_phi_ln68_1_reg_320 <= act_buf_V_12_load_reg_2069;
        end else if (((trunc_ln68_1_fu_1275_p1 == 3'd2) & (icmp_ln168_1_fu_1263_p2 == 1'd0))) begin
            ap_phi_reg_pp0_iter1_phi_ln68_1_reg_320 <= act_buf_V_8_load_reg_2045;
        end else if (((trunc_ln68_1_fu_1275_p1 == 3'd1) & (icmp_ln168_1_fu_1263_p2 == 1'd0))) begin
            ap_phi_reg_pp0_iter1_phi_ln68_1_reg_320 <= act_buf_V_4_load_reg_2021;
        end else if (((trunc_ln68_1_fu_1275_p1 == 3'd0) & (icmp_ln168_1_fu_1263_p2 == 1'd0))) begin
            ap_phi_reg_pp0_iter1_phi_ln68_1_reg_320 <= act_buf_V_0_load_reg_1997;
        end else if (((trunc_ln68_1_fu_1275_p1 == 3'd7) & (icmp_ln168_1_fu_1263_p2 == 1'd0))) begin
            ap_phi_reg_pp0_iter1_phi_ln68_1_reg_320 <= 8'd0;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter1_phi_ln68_1_reg_320 <= ap_phi_reg_pp0_iter0_phi_ln68_1_reg_320;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_308)) begin
        if (((trunc_ln68_fu_1531_p1 == 3'd6) & (icmp_ln168_fu_1519_p2 == 1'd0))) begin
            ap_phi_reg_pp1_iter1_phi_ln68_reg_402 <= act_buf_V_24_load_reg_2141;
        end else if (((trunc_ln68_fu_1531_p1 == 3'd5) & (icmp_ln168_fu_1519_p2 == 1'd0))) begin
            ap_phi_reg_pp1_iter1_phi_ln68_reg_402 <= act_buf_V_20_load_reg_2117;
        end else if (((trunc_ln68_fu_1531_p1 == 3'd4) & (icmp_ln168_fu_1519_p2 == 1'd0))) begin
            ap_phi_reg_pp1_iter1_phi_ln68_reg_402 <= act_buf_V_16_load_reg_2093;
        end else if (((trunc_ln68_fu_1531_p1 == 3'd3) & (icmp_ln168_fu_1519_p2 == 1'd0))) begin
            ap_phi_reg_pp1_iter1_phi_ln68_reg_402 <= act_buf_V_12_load_reg_2069;
        end else if (((trunc_ln68_fu_1531_p1 == 3'd2) & (icmp_ln168_fu_1519_p2 == 1'd0))) begin
            ap_phi_reg_pp1_iter1_phi_ln68_reg_402 <= act_buf_V_8_load_reg_2045;
        end else if (((trunc_ln68_fu_1531_p1 == 3'd1) & (icmp_ln168_fu_1519_p2 == 1'd0))) begin
            ap_phi_reg_pp1_iter1_phi_ln68_reg_402 <= act_buf_V_4_load_reg_2021;
        end else if (((trunc_ln68_fu_1531_p1 == 3'd0) & (icmp_ln168_fu_1519_p2 == 1'd0))) begin
            ap_phi_reg_pp1_iter1_phi_ln68_reg_402 <= act_buf_V_0_load_reg_1997;
        end else if (((trunc_ln68_fu_1531_p1 == 3'd7) & (icmp_ln168_fu_1519_p2 == 1'd0))) begin
            ap_phi_reg_pp1_iter1_phi_ln68_reg_402 <= 8'd0;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp1_iter1_phi_ln68_reg_402 <= ap_phi_reg_pp1_iter0_phi_ln68_reg_402;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp1_stage0_11001) & (icmp_ln168_fu_1519_p2 == 1'd0) & (ap_enable_reg_pp1_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0))) begin
        i_0_i172_reg_391 <= i_fu_1525_p2;
    end else if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1) & (cnn_op_V_read_read_fu_242_p2 == 4'd2))) begin
        i_0_i172_reg_391 <= 4'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln168_1_fu_1263_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        i_0_i_reg_309 <= i_1_fu_1269_p2;
    end else if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1) & (cnn_op_V_read_read_fu_242_p2 == 4'd6))) begin
        i_0_i_reg_309 <= 4'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp1_stage0_11001) & (icmp_ln168_reg_2245 == 1'd0) & (ap_enable_reg_pp1_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0))) begin
        p_0103_0_i171_reg_379 <= grp_fu_1835_p3;
    end else if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1) & (cnn_op_V_read_read_fu_242_p2 == 4'd2))) begin
        p_0103_0_i171_reg_379 <= 19'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln168_1_reg_2172 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_0103_0_i_reg_297 <= grp_fu_1803_p3;
    end else if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1) & (cnn_op_V_read_read_fu_242_p2 == 4'd6))) begin
        p_0103_0_i_reg_297 <= 19'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp1_stage0_11001) & (icmp_ln168_reg_2245 == 1'd0) & (ap_enable_reg_pp1_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0))) begin
        p_0107_0_i170_reg_367 <= grp_fu_1827_p3;
    end else if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1) & (cnn_op_V_read_read_fu_242_p2 == 4'd2))) begin
        p_0107_0_i170_reg_367 <= 19'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln168_1_reg_2172 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_0107_0_i_reg_285 <= grp_fu_1795_p3;
    end else if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1) & (cnn_op_V_read_read_fu_242_p2 == 4'd6))) begin
        p_0107_0_i_reg_285 <= 19'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp1_stage0_11001) & (icmp_ln168_reg_2245 == 1'd0) & (ap_enable_reg_pp1_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0))) begin
        p_0111_0_i169_reg_355 <= grp_fu_1819_p3;
    end else if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1) & (cnn_op_V_read_read_fu_242_p2 == 4'd2))) begin
        p_0111_0_i169_reg_355 <= 19'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln168_1_reg_2172 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_0111_0_i_reg_273 <= grp_fu_1787_p3;
    end else if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1) & (cnn_op_V_read_read_fu_242_p2 == 4'd6))) begin
        p_0111_0_i_reg_273 <= 19'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp1_stage0_11001) & (icmp_ln168_reg_2245 == 1'd0) & (ap_enable_reg_pp1_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0))) begin
        p_0217_0_i168_reg_343 <= grp_fu_1811_p3;
    end else if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1) & (cnn_op_V_read_read_fu_242_p2 == 4'd2))) begin
        p_0217_0_i168_reg_343 <= 19'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln168_1_reg_2172 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_0217_0_i_reg_261 <= grp_fu_1779_p3;
    end else if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1) & (cnn_op_V_read_read_fu_242_p2 == 4'd6))) begin
        p_0217_0_i_reg_261 <= 19'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((w_ptr_load_load_fu_982_p1 == 7'd0) & (1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1) & (cnn_op_V_read_read_fu_242_p2 == 4'd0))) begin
                w_ptr[2] <= 1'b1;
        w_ptr[3] <= 1'b0;
        w_ptr[4] <= 1'b0;
    end else if (((w_ptr_load_load_fu_982_p1 == 7'd4) & (1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1) & (cnn_op_V_read_read_fu_242_p2 == 4'd0))) begin
                w_ptr[2] <= 1'b0;
        w_ptr[3] <= 1'b1;
        w_ptr[4] <= 1'b0;
    end else if (((w_ptr_load_load_fu_982_p1 == 7'd8) & (1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1) & (cnn_op_V_read_read_fu_242_p2 == 4'd0))) begin
                w_ptr[2] <= 1'b1;
        w_ptr[3] <= 1'b1;
        w_ptr[4] <= 1'b0;
    end else if (((w_ptr_load_load_fu_982_p1 == 7'd12) & (1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1) & (cnn_op_V_read_read_fu_242_p2 == 4'd0))) begin
                w_ptr[2] <= 1'b0;
        w_ptr[3] <= 1'b0;
        w_ptr[4] <= 1'b1;
    end else if (((w_ptr_load_load_fu_982_p1 == 7'd16) & (1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1) & (cnn_op_V_read_read_fu_242_p2 == 4'd0))) begin
                w_ptr[2] <= 1'b1;
        w_ptr[3] <= 1'b0;
        w_ptr[4] <= 1'b1;
    end else if (((w_ptr_load_load_fu_982_p1 == 7'd20) & (1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1) & (cnn_op_V_read_read_fu_242_p2 == 4'd0))) begin
                w_ptr[2] <= 1'b0;
        w_ptr[3] <= 1'b1;
        w_ptr[4] <= 1'b1;
    end else if ((((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1) & (cnn_op_V_read_read_fu_242_p2 == 4'd5)) | (~(w_ptr_load_load_fu_982_p1 == 7'd24) & ~(w_ptr_load_load_fu_982_p1 == 7'd20) & ~(w_ptr_load_load_fu_982_p1 == 7'd16) & ~(w_ptr_load_load_fu_982_p1 == 7'd12) & ~(w_ptr_load_load_fu_982_p1 == 7'd8) & ~(w_ptr_load_load_fu_982_p1 == 7'd4) & ~(w_ptr_load_load_fu_982_p1 == 7'd0) & (1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1) & (cnn_op_V_read_read_fu_242_p2 == 4'd0)) | ((w_ptr_load_load_fu_982_p1 == 7'd24) & (1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1) & (cnn_op_V_read_read_fu_242_p2 == 4'd0)))) begin
                w_ptr[2] <= 1'b0;
        w_ptr[3] <= 1'b0;
        w_ptr[4] <= 1'b0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        acc_reg_V_load_reg_2147 <= acc_reg_V;
        act_buf_V_0_load_reg_1997 <= act_buf_V_0;
        act_buf_V_10_load_reg_2057 <= act_buf_V_10;
        act_buf_V_11_load_reg_2063 <= act_buf_V_11;
        act_buf_V_12_load_reg_2069 <= act_buf_V_12;
        act_buf_V_13_load_reg_2075 <= act_buf_V_13;
        act_buf_V_14_load_reg_2081 <= act_buf_V_14;
        act_buf_V_15_load_reg_2087 <= act_buf_V_15;
        act_buf_V_16_load_reg_2093 <= act_buf_V_16;
        act_buf_V_17_load_reg_2099 <= act_buf_V_17;
        act_buf_V_18_load_reg_2105 <= act_buf_V_18;
        act_buf_V_19_load_reg_2111 <= act_buf_V_19;
        act_buf_V_1_load_reg_2003 <= act_buf_V_1;
        act_buf_V_20_load_reg_2117 <= act_buf_V_20;
        act_buf_V_21_load_reg_2123 <= act_buf_V_21;
        act_buf_V_22_load_reg_2129 <= act_buf_V_22;
        act_buf_V_23_load_reg_2135 <= act_buf_V_23;
        act_buf_V_24_load_reg_2141 <= act_buf_V_24;
        act_buf_V_2_load_reg_2009 <= act_buf_V_2;
        act_buf_V_3_load_reg_2015 <= act_buf_V_3;
        act_buf_V_4_load_reg_2021 <= act_buf_V_4;
        act_buf_V_5_load_reg_2027 <= act_buf_V_5;
        act_buf_V_6_load_reg_2033 <= act_buf_V_6;
        act_buf_V_7_load_reg_2039 <= act_buf_V_7;
        act_buf_V_8_load_reg_2045 <= act_buf_V_8;
        act_buf_V_9_load_reg_2051 <= act_buf_V_9;
        weight_buf_V_0_load_reg_1847 <= weight_buf_V_0;
        weight_buf_V_10_load_reg_1907 <= weight_buf_V_10;
        weight_buf_V_11_load_reg_1913 <= weight_buf_V_11;
        weight_buf_V_12_load_reg_1919 <= weight_buf_V_12;
        weight_buf_V_13_load_reg_1925 <= weight_buf_V_13;
        weight_buf_V_14_load_reg_1931 <= weight_buf_V_14;
        weight_buf_V_15_load_reg_1937 <= weight_buf_V_15;
        weight_buf_V_16_load_reg_1943 <= weight_buf_V_16;
        weight_buf_V_17_load_reg_1949 <= weight_buf_V_17;
        weight_buf_V_18_load_reg_1955 <= weight_buf_V_18;
        weight_buf_V_19_load_reg_1961 <= weight_buf_V_19;
        weight_buf_V_1_load_reg_1853 <= weight_buf_V_1;
        weight_buf_V_20_load_reg_1967 <= weight_buf_V_20;
        weight_buf_V_21_load_reg_1973 <= weight_buf_V_21;
        weight_buf_V_22_load_reg_1979 <= weight_buf_V_22;
        weight_buf_V_23_load_reg_1985 <= weight_buf_V_23;
        weight_buf_V_24_load_reg_1991 <= weight_buf_V_24;
        weight_buf_V_2_load_reg_1859 <= weight_buf_V_2;
        weight_buf_V_3_load_reg_1865 <= weight_buf_V_3;
        weight_buf_V_4_load_reg_1871 <= weight_buf_V_4;
        weight_buf_V_5_load_reg_1877 <= weight_buf_V_5;
        weight_buf_V_6_load_reg_1883 <= weight_buf_V_6;
        weight_buf_V_7_load_reg_1889 <= weight_buf_V_7;
        weight_buf_V_8_load_reg_1895 <= weight_buf_V_8;
        weight_buf_V_9_load_reg_1901 <= weight_buf_V_9;
    end
end

always @ (posedge ap_clk) begin
    if (((7'd0 == a_ptr_load_load_fu_764_p1) & (1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1) & (cnn_op_V_read_read_fu_242_p2 == 4'd1))) begin
        act_buf_V_0 <= trunc_ln647_7_fu_948_p1;
        act_buf_V_1 <= {{grp_fu_443_p1[15:8]}};
        act_buf_V_2 <= {{grp_fu_453_p1[23:16]}};
        act_buf_V_3 <= {{grp_fu_463_p1[31:24]}};
    end
end

always @ (posedge ap_clk) begin
    if (((7'd8 == a_ptr_load_load_fu_764_p1) & (1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1) & (cnn_op_V_read_read_fu_242_p2 == 4'd1))) begin
        act_buf_V_10 <= {{grp_fu_453_p1[23:16]}};
        act_buf_V_11 <= {{grp_fu_463_p1[31:24]}};
        act_buf_V_8 <= trunc_ln647_9_fu_880_p1;
        act_buf_V_9 <= {{grp_fu_443_p1[15:8]}};
    end
end

always @ (posedge ap_clk) begin
    if (((7'd12 == a_ptr_load_load_fu_764_p1) & (1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1) & (cnn_op_V_read_read_fu_242_p2 == 4'd1))) begin
        act_buf_V_12 <= trunc_ln647_10_fu_846_p1;
        act_buf_V_13 <= {{grp_fu_443_p1[15:8]}};
        act_buf_V_14 <= {{grp_fu_453_p1[23:16]}};
        act_buf_V_15 <= {{grp_fu_463_p1[31:24]}};
    end
end

always @ (posedge ap_clk) begin
    if (((7'd16 == a_ptr_load_load_fu_764_p1) & (1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1) & (cnn_op_V_read_read_fu_242_p2 == 4'd1))) begin
        act_buf_V_16 <= trunc_ln647_11_fu_812_p1;
        act_buf_V_17 <= {{grp_fu_443_p1[15:8]}};
        act_buf_V_18 <= {{grp_fu_453_p1[23:16]}};
        act_buf_V_19 <= {{grp_fu_463_p1[31:24]}};
    end
end

always @ (posedge ap_clk) begin
    if (((7'd20 == a_ptr_load_load_fu_764_p1) & (1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1) & (cnn_op_V_read_read_fu_242_p2 == 4'd1))) begin
        act_buf_V_20 <= trunc_ln647_12_fu_778_p1;
        act_buf_V_21 <= {{grp_fu_443_p1[15:8]}};
        act_buf_V_22 <= {{grp_fu_453_p1[23:16]}};
        act_buf_V_23 <= {{grp_fu_463_p1[31:24]}};
    end
end

always @ (posedge ap_clk) begin
    if (((7'd24 == a_ptr_load_load_fu_764_p1) & (1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1) & (cnn_op_V_read_read_fu_242_p2 == 4'd1))) begin
        act_buf_V_24 <= trunc_ln647_13_fu_768_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((7'd4 == a_ptr_load_load_fu_764_p1) & (1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1) & (cnn_op_V_read_read_fu_242_p2 == 4'd1))) begin
        act_buf_V_4 <= trunc_ln647_8_fu_914_p1;
        act_buf_V_5 <= {{grp_fu_443_p1[15:8]}};
        act_buf_V_6 <= {{grp_fu_453_p1[23:16]}};
        act_buf_V_7 <= {{grp_fu_463_p1[31:24]}};
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        add_ln700_1_reg_2240 <= add_ln700_1_fu_1508_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        icmp_ln168_1_reg_2172 <= icmp_ln168_1_fu_1263_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp1_stage0_11001) & (1'b1 == ap_CS_fsm_pp1_stage0))) begin
        icmp_ln168_reg_2245 <= icmp_ln168_fu_1519_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp1_stage0_11001) & (icmp_ln168_fu_1519_p2 == 1'd0) & (1'b1 == ap_CS_fsm_pp1_stage0))) begin
        phi_ln68_10_reg_2283 <= phi_ln68_10_fu_1670_p10;
        phi_ln68_12_reg_2288 <= phi_ln68_12_fu_1686_p10;
        phi_ln68_2_reg_2258 <= phi_ln68_2_fu_1543_p34;
        phi_ln68_4_reg_2263 <= phi_ln68_4_fu_1606_p10;
        phi_ln68_6_reg_2268 <= phi_ln68_6_fu_1622_p10;
        phi_ln68_8_reg_2273 <= phi_ln68_8_fu_1638_p10;
        phi_ln68_s_reg_2278 <= phi_ln68_s_fu_1654_p10;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln168_1_fu_1263_p2 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        phi_ln68_11_reg_2205 <= phi_ln68_11_fu_1398_p10;
        phi_ln68_13_reg_2210 <= phi_ln68_13_fu_1414_p10;
        phi_ln68_14_reg_2215 <= phi_ln68_14_fu_1430_p10;
        phi_ln68_3_reg_2185 <= phi_ln68_3_fu_1287_p34;
        phi_ln68_5_reg_2190 <= phi_ln68_5_fu_1350_p10;
        phi_ln68_7_reg_2195 <= phi_ln68_7_fu_1366_p10;
        phi_ln68_9_reg_2200 <= phi_ln68_9_fu_1382_p10;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1) & (cnn_op_V_read_read_fu_242_p2 == 4'd9))) begin
        product_V_reg_2153 <= product_V_fu_686_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        select_ln899_1_reg_2167 <= select_ln899_1_fu_1250_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((w_ptr_load_load_fu_982_p1 == 7'd0) & (1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1) & (cnn_op_V_read_read_fu_242_p2 == 4'd0))) begin
        weight_buf_V_0 <= trunc_ln647_fu_1166_p1;
        weight_buf_V_1 <= {{grp_fu_443_p1[15:8]}};
        weight_buf_V_2 <= {{grp_fu_453_p1[23:16]}};
        weight_buf_V_3 <= {{grp_fu_463_p1[31:24]}};
    end
end

always @ (posedge ap_clk) begin
    if (((w_ptr_load_load_fu_982_p1 == 7'd8) & (1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1) & (cnn_op_V_read_read_fu_242_p2 == 4'd0))) begin
        weight_buf_V_10 <= {{grp_fu_453_p1[23:16]}};
        weight_buf_V_11 <= {{grp_fu_463_p1[31:24]}};
        weight_buf_V_8 <= trunc_ln647_2_fu_1098_p1;
        weight_buf_V_9 <= {{grp_fu_443_p1[15:8]}};
    end
end

always @ (posedge ap_clk) begin
    if (((w_ptr_load_load_fu_982_p1 == 7'd12) & (1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1) & (cnn_op_V_read_read_fu_242_p2 == 4'd0))) begin
        weight_buf_V_12 <= trunc_ln647_3_fu_1064_p1;
        weight_buf_V_13 <= {{grp_fu_443_p1[15:8]}};
        weight_buf_V_14 <= {{grp_fu_453_p1[23:16]}};
        weight_buf_V_15 <= {{grp_fu_463_p1[31:24]}};
    end
end

always @ (posedge ap_clk) begin
    if (((w_ptr_load_load_fu_982_p1 == 7'd16) & (1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1) & (cnn_op_V_read_read_fu_242_p2 == 4'd0))) begin
        weight_buf_V_16 <= trunc_ln647_4_fu_1030_p1;
        weight_buf_V_17 <= {{grp_fu_443_p1[15:8]}};
        weight_buf_V_18 <= {{grp_fu_453_p1[23:16]}};
        weight_buf_V_19 <= {{grp_fu_463_p1[31:24]}};
    end
end

always @ (posedge ap_clk) begin
    if (((w_ptr_load_load_fu_982_p1 == 7'd20) & (1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1) & (cnn_op_V_read_read_fu_242_p2 == 4'd0))) begin
        weight_buf_V_20 <= trunc_ln647_5_fu_996_p1;
        weight_buf_V_21 <= {{grp_fu_443_p1[15:8]}};
        weight_buf_V_22 <= {{grp_fu_453_p1[23:16]}};
        weight_buf_V_23 <= {{grp_fu_463_p1[31:24]}};
    end
end

always @ (posedge ap_clk) begin
    if (((w_ptr_load_load_fu_982_p1 == 7'd24) & (1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1) & (cnn_op_V_read_read_fu_242_p2 == 4'd0))) begin
        weight_buf_V_24 <= trunc_ln647_6_fu_986_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((w_ptr_load_load_fu_982_p1 == 7'd4) & (1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1) & (cnn_op_V_read_read_fu_242_p2 == 4'd0))) begin
        weight_buf_V_4 <= trunc_ln647_1_fu_1132_p1;
        weight_buf_V_5 <= {{grp_fu_443_p1[15:8]}};
        weight_buf_V_6 <= {{grp_fu_453_p1[23:16]}};
        weight_buf_V_7 <= {{grp_fu_463_p1[31:24]}};
    end
end

always @ (*) begin
    if ((icmp_ln168_1_fu_1263_p2 == 1'd1)) begin
        ap_condition_pp0_exit_iter0_state4 = 1'b1;
    end else begin
        ap_condition_pp0_exit_iter0_state4 = 1'b0;
    end
end

always @ (*) begin
    if ((icmp_ln168_fu_1519_p2 == 1'd1)) begin
        ap_condition_pp1_exit_iter0_state8 = 1'b1;
    end else begin
        ap_condition_pp1_exit_iter0_state8 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp1_iter1 == 1'b0) & (ap_enable_reg_pp1_iter0 == 1'b0))) begin
        ap_idle_pp1 = 1'b1;
    end else begin
        ap_idle_pp1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1) & (cnn_op_V_read_read_fu_242_p2 == 4'd3))) begin
        rd_data_V = acc_reg_V;
    end else begin
        rd_data_V = rd_data_V_preg;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1) & (cnn_op_V_read_read_fu_242_p2 == 4'd0))) begin
                ap_NS_fsm = ap_ST_fsm_state12;
            end else if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1) & (cnn_op_V_read_read_fu_242_p2 == 4'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state11;
            end else if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1) & (cnn_op_V_read_read_fu_242_p2 == 4'd2))) begin
                ap_NS_fsm = ap_ST_fsm_pp1_stage0;
            end else if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1) & (cnn_op_V_read_read_fu_242_p2 == 4'd6))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else if ((~(cnn_op_V_read_read_fu_242_p2 == 4'd1) & ~(cnn_op_V_read_read_fu_242_p2 == 4'd0) & ~(cnn_op_V_read_read_fu_242_p2 == 4'd2) & ~(cnn_op_V_read_read_fu_242_p2 == 4'd6) & ~(cnn_op_V_read_read_fu_242_p2 == 4'd9) & (1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end else if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1) & (cnn_op_V_read_read_fu_242_p2 == 4'd9))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_pp0_stage0 : begin
            if (~((1'b0 == ap_block_pp0_stage0_subdone) & (icmp_ln168_1_fu_1263_p2 == 1'd1) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (icmp_ln168_1_fu_1263_p2 == 1'd1) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        ap_ST_fsm_pp1_stage0 : begin
            if (~((1'b0 == ap_block_pp1_stage0_subdone) & (icmp_ln168_fu_1519_p2 == 1'd1) & (ap_enable_reg_pp1_iter0 == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_pp1_stage0;
            end else if (((1'b0 == ap_block_pp1_stage0_subdone) & (icmp_ln168_fu_1519_p2 == 1'd1) & (ap_enable_reg_pp1_iter0 == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state10;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp1_stage0;
            end
        end
        ap_ST_fsm_state10 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state11 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state12 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign a_ptr_load_load_fu_764_p1 = a_ptr;

assign add_ln68_1_fu_1753_p2 = ($signed(sext_ln168_1_fu_1731_p1) + $signed(sext_ln168_fu_1727_p1));

assign add_ln68_2_fu_1763_p2 = ($signed(sext_ln68_3_fu_1759_p1) + $signed(sext_ln68_2_fu_1749_p1));

assign add_ln68_fu_1743_p2 = ($signed(sext_ln168_2_fu_1735_p1) + $signed(sext_ln168_3_fu_1739_p1));

assign add_ln700_1_fu_1508_p2 = ($signed(sext_ln700_fu_1504_p1) + $signed(add_ln700_2_fu_1487_p2));

assign add_ln700_2_fu_1487_p2 = ($signed(acc_reg_V_load_reg_2147) + $signed(sext_ln168_6_fu_1479_p1));

assign add_ln700_3_fu_1492_p2 = ($signed(sext_ln168_5_fu_1475_p1) + $signed(sext_ln168_4_fu_1471_p1));

assign add_ln700_4_fu_1498_p2 = ($signed(add_ln700_3_fu_1492_p2) + $signed(sext_ln168_7_fu_1483_p1));

assign add_ln700_fu_700_p1 = rs1_data_V;

assign add_ln700_fu_700_p2 = ($signed(acc_reg_V) + $signed(add_ln700_fu_700_p1));

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_pp1_stage0 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state10 = ap_CS_fsm[32'd7];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd5];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp1_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp1_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp1_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_block_state4_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state5_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state8_pp1_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state9_pp1_stage0_iter1 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_condition_249 = ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0));
end

always @ (*) begin
    ap_condition_308 = ((1'b0 == ap_block_pp1_stage0_11001) & (ap_enable_reg_pp1_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0));
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_pp1 = (ap_idle_pp1 ^ 1'b1);

assign ap_phi_reg_pp0_iter0_phi_ln68_1_reg_320 = 'bx;

assign ap_phi_reg_pp1_iter0_phi_ln68_reg_402 = 'bx;

assign cnn_op_V_read_read_fu_242_p2 = cnn_op_V;

assign final_max_V_fu_746_p3 = ((icmp_ln895_2_fu_740_p2[0:0] === 1'b1) ? max1_V_fu_718_p3 : max2_V_fu_732_p3);

assign grp_fu_443_p1 = rs1_data_V;

assign grp_fu_453_p1 = rs1_data_V;

assign grp_fu_463_p1 = rs1_data_V;

assign i_1_fu_1269_p2 = (i_0_i_reg_309 + 4'd1);

assign i_fu_1525_p2 = (i_0_i172_reg_391 + 4'd1);

assign icmp_ln168_1_fu_1263_p2 = ((i_0_i_reg_309 == 4'd8) ? 1'b1 : 1'b0);

assign icmp_ln168_fu_1519_p2 = ((i_0_i172_reg_391 == 4'd8) ? 1'b1 : 1'b0);

assign icmp_ln895_1_fu_726_p2 = (($signed(act_buf_V_2) > $signed(act_buf_V_3)) ? 1'b1 : 1'b0);

assign icmp_ln895_2_fu_740_p2 = (($signed(max1_V_fu_718_p3) > $signed(max2_V_fu_732_p3)) ? 1'b1 : 1'b0);

assign icmp_ln895_3_fu_1230_p2 = (($signed(tmp_3_fu_1220_p4) > $signed(25'd0)) ? 1'b1 : 1'b0);

assign icmp_ln895_fu_712_p2 = (($signed(act_buf_V_0) > $signed(act_buf_V_1)) ? 1'b1 : 1'b0);

assign icmp_ln899_fu_1200_p2 = (($signed(acc_reg_V_load_reg_2147) < $signed(32'd1)) ? 1'b1 : 1'b0);

assign max1_V_fu_718_p3 = ((icmp_ln895_fu_712_p2[0:0] === 1'b1) ? act_buf_V_0 : act_buf_V_1);

assign max2_V_fu_732_p3 = ((icmp_ln895_1_fu_726_p2[0:0] === 1'b1) ? act_buf_V_2 : act_buf_V_3);

assign or_ln899_fu_1244_p2 = (icmp_ln899_fu_1200_p2 | icmp_ln895_3_fu_1230_p2);

assign phi_ln68_2_fu_1543_p33 = {{trunc_ln68_fu_1531_p1}, {2'd0}};

assign phi_ln68_3_fu_1287_p33 = {{trunc_ln68_1_fu_1275_p1}, {2'd0}};

assign product_V_fu_686_p0 = product_V_fu_686_p00;

assign product_V_fu_686_p00 = acc_reg_V;

assign product_V_fu_686_p1 = sext_ln68_1_fu_682_p0;

assign product_V_fu_686_p2 = ($signed({{1'b0}, {product_V_fu_686_p0}}) * $signed(product_V_fu_686_p1));

assign rounded_V_fu_1205_p2 = (64'd524288 + product_V_reg_2153);

assign scaled_V_fu_1210_p4 = {{rounded_V_fu_1205_p2[51:20]}};

assign select_ln899_1_fu_1250_p3 = ((or_ln899_fu_1244_p2[0:0] === 1'b1) ? select_ln899_fu_1236_p3 : scaled_V_fu_1210_p4);

assign select_ln899_fu_1236_p3 = ((icmp_ln899_fu_1200_p2[0:0] === 1'b1) ? 32'd0 : 32'd127);

assign sext_ln168_1_fu_1731_p1 = p_0111_0_i169_reg_355;

assign sext_ln168_2_fu_1735_p1 = p_0107_0_i170_reg_367;

assign sext_ln168_3_fu_1739_p1 = p_0103_0_i171_reg_379;

assign sext_ln168_4_fu_1471_p1 = p_0217_0_i_reg_261;

assign sext_ln168_5_fu_1475_p1 = p_0111_0_i_reg_273;

assign sext_ln168_6_fu_1479_p1 = p_0107_0_i_reg_285;

assign sext_ln168_7_fu_1483_p1 = p_0103_0_i_reg_297;

assign sext_ln168_fu_1727_p1 = p_0217_0_i168_reg_343;

assign sext_ln68_1_fu_682_p0 = rs1_data_V;

assign sext_ln68_2_fu_1749_p1 = $signed(add_ln68_fu_1743_p2);

assign sext_ln68_3_fu_1759_p1 = $signed(add_ln68_1_fu_1753_p2);

assign sext_ln68_4_fu_1769_p1 = $signed(add_ln68_2_fu_1763_p2);

assign sext_ln68_fu_754_p1 = $signed(final_max_V_fu_746_p3);

assign sext_ln700_fu_1504_p1 = $signed(add_ln700_4_fu_1498_p2);

assign tmp_2_fu_692_p3 = acc_reg_V[32'd31];

assign tmp_3_fu_1220_p4 = {{rounded_V_fu_1205_p2[51:27]}};

assign trunc_ln647_10_fu_846_p0 = rs1_data_V;

assign trunc_ln647_10_fu_846_p1 = trunc_ln647_10_fu_846_p0[7:0];

assign trunc_ln647_11_fu_812_p0 = rs1_data_V;

assign trunc_ln647_11_fu_812_p1 = trunc_ln647_11_fu_812_p0[7:0];

assign trunc_ln647_12_fu_778_p0 = rs1_data_V;

assign trunc_ln647_12_fu_778_p1 = trunc_ln647_12_fu_778_p0[7:0];

assign trunc_ln647_13_fu_768_p0 = rs1_data_V;

assign trunc_ln647_13_fu_768_p1 = trunc_ln647_13_fu_768_p0[7:0];

assign trunc_ln647_1_fu_1132_p0 = rs1_data_V;

assign trunc_ln647_1_fu_1132_p1 = trunc_ln647_1_fu_1132_p0[7:0];

assign trunc_ln647_2_fu_1098_p0 = rs1_data_V;

assign trunc_ln647_2_fu_1098_p1 = trunc_ln647_2_fu_1098_p0[7:0];

assign trunc_ln647_3_fu_1064_p0 = rs1_data_V;

assign trunc_ln647_3_fu_1064_p1 = trunc_ln647_3_fu_1064_p0[7:0];

assign trunc_ln647_4_fu_1030_p0 = rs1_data_V;

assign trunc_ln647_4_fu_1030_p1 = trunc_ln647_4_fu_1030_p0[7:0];

assign trunc_ln647_5_fu_996_p0 = rs1_data_V;

assign trunc_ln647_5_fu_996_p1 = trunc_ln647_5_fu_996_p0[7:0];

assign trunc_ln647_6_fu_986_p0 = rs1_data_V;

assign trunc_ln647_6_fu_986_p1 = trunc_ln647_6_fu_986_p0[7:0];

assign trunc_ln647_7_fu_948_p0 = rs1_data_V;

assign trunc_ln647_7_fu_948_p1 = trunc_ln647_7_fu_948_p0[7:0];

assign trunc_ln647_8_fu_914_p0 = rs1_data_V;

assign trunc_ln647_8_fu_914_p1 = trunc_ln647_8_fu_914_p0[7:0];

assign trunc_ln647_9_fu_880_p0 = rs1_data_V;

assign trunc_ln647_9_fu_880_p1 = trunc_ln647_9_fu_880_p0[7:0];

assign trunc_ln647_fu_1166_p0 = rs1_data_V;

assign trunc_ln647_fu_1166_p1 = trunc_ln647_fu_1166_p0[7:0];

assign trunc_ln68_1_fu_1275_p1 = i_0_i_reg_309[2:0];

assign trunc_ln68_fu_1531_p1 = i_0_i172_reg_391[2:0];

assign w_ptr_load_load_fu_982_p1 = w_ptr;

always @ (posedge ap_clk) begin
    w_ptr[1:0] <= 2'b00;
    w_ptr[6:5] <= 2'b00;
    a_ptr[1:0] <= 2'b00;
    a_ptr[6:5] <= 2'b00;
end

endmodule //CNN_ALU_Top
