#ifndef LENET_MEM_MAP_H
#define LENET_MEM_MAP_H

#define LENET_INPUT_BASE_ADDR   0x00010000u
#define LENET_EXPECTED_ADDR     0x00010EFCu
#define LENET_RESULT_ADDR       0x00010F00u
#define LENET_DONE_ADDR         0x00010F40u
#define LENET_DEBUG_ADDR        0x0001F000u

#define LENET_EXPECTED_WORD     (LENET_EXPECTED_ADDR >> 2)
#define LENET_RESULT_WORD       (LENET_RESULT_ADDR >> 2)
#define LENET_DONE_WORD         (LENET_DONE_ADDR >> 2)
#define LENET_DEBUG_WORD        (LENET_DEBUG_ADDR >> 2)

#endif
