// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2019.1
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="CNN_ALU_Top,hls_ip_2019_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=1,HLS_INPUT_PART=xc7z020-clg484-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=8.391000,HLS_SYN_LAT=3,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=8,HLS_SYN_FF=1236,HLS_SYN_LUT=1360,HLS_VERSION=2019_1}" *)

module CNN_ALU_Top (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        rs1_data_V,
        cnn_op_V,
        rd_data_V
);

parameter    ap_ST_fsm_state1 = 8'd1;
parameter    ap_ST_fsm_pp0_stage0 = 8'd2;
parameter    ap_ST_fsm_state4 = 8'd4;
parameter    ap_ST_fsm_state5 = 8'd8;
parameter    ap_ST_fsm_pp1_stage0 = 8'd16;
parameter    ap_ST_fsm_state8 = 8'd32;
parameter    ap_ST_fsm_state9 = 8'd64;
parameter    ap_ST_fsm_state10 = 8'd128;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [31:0] rs1_data_V;
input  [3:0] cnn_op_V;
output  [31:0] rd_data_V;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg[31:0] rd_data_V;

(* fsm_encoding = "none" *) reg   [7:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg   [7:0] weight_buf_V_0;
reg   [7:0] weight_buf_V_1;
reg   [7:0] weight_buf_V_2;
reg   [7:0] weight_buf_V_3;
reg   [7:0] weight_buf_V_4;
reg   [7:0] weight_buf_V_5;
reg   [7:0] weight_buf_V_6;
reg   [7:0] weight_buf_V_7;
reg   [7:0] weight_buf_V_8;
reg   [7:0] weight_buf_V_9;
reg   [7:0] weight_buf_V_10;
reg   [7:0] weight_buf_V_11;
reg   [7:0] weight_buf_V_12;
reg   [7:0] weight_buf_V_13;
reg   [7:0] weight_buf_V_14;
reg   [7:0] weight_buf_V_15;
reg   [7:0] weight_buf_V_16;
reg   [7:0] weight_buf_V_17;
reg   [7:0] weight_buf_V_18;
reg   [7:0] weight_buf_V_19;
reg   [7:0] weight_buf_V_20;
reg   [7:0] weight_buf_V_21;
reg   [7:0] weight_buf_V_22;
reg   [7:0] weight_buf_V_23;
reg   [7:0] weight_buf_V_24;
reg   [7:0] act_buf_V_0;
reg   [7:0] act_buf_V_1;
reg   [7:0] act_buf_V_2;
reg   [7:0] act_buf_V_3;
reg   [7:0] act_buf_V_4;
reg   [7:0] act_buf_V_5;
reg   [7:0] act_buf_V_6;
reg   [7:0] act_buf_V_7;
reg   [7:0] act_buf_V_8;
reg   [7:0] act_buf_V_9;
reg   [7:0] act_buf_V_10;
reg   [7:0] act_buf_V_11;
reg   [7:0] act_buf_V_12;
reg   [7:0] act_buf_V_13;
reg   [7:0] act_buf_V_14;
reg   [7:0] act_buf_V_15;
reg   [7:0] act_buf_V_16;
reg   [7:0] act_buf_V_17;
reg   [7:0] act_buf_V_18;
reg   [7:0] act_buf_V_19;
reg   [7:0] act_buf_V_20;
reg   [7:0] act_buf_V_21;
reg   [7:0] act_buf_V_22;
reg   [7:0] act_buf_V_23;
reg   [7:0] act_buf_V_24;
reg   [31:0] acc_reg_V;
reg   [6:0] w_ptr;
reg   [6:0] a_ptr;
reg  signed [18:0] p_0217_0_i_reg_243;
reg  signed [18:0] p_0111_0_i_reg_255;
reg  signed [18:0] p_0107_0_i_reg_267;
reg  signed [18:0] p_0103_0_i_reg_279;
reg   [3:0] i_0_i_reg_291;
reg  signed [18:0] p_0217_0_i163_reg_325;
reg  signed [18:0] p_0111_0_i164_reg_337;
reg  signed [18:0] p_0107_0_i165_reg_349;
reg  signed [18:0] p_0103_0_i166_reg_361;
reg   [3:0] i_0_i167_reg_373;
wire   [3:0] cnn_op_V_read_read_fu_224_p2;
reg   [7:0] weight_buf_V_0_load_reg_1752;
reg   [7:0] weight_buf_V_1_load_reg_1758;
reg   [7:0] weight_buf_V_2_load_reg_1764;
reg   [7:0] weight_buf_V_3_load_reg_1770;
reg   [7:0] weight_buf_V_4_load_reg_1776;
reg   [7:0] weight_buf_V_5_load_reg_1782;
reg   [7:0] weight_buf_V_6_load_reg_1788;
reg   [7:0] weight_buf_V_7_load_reg_1794;
reg   [7:0] weight_buf_V_8_load_reg_1800;
reg   [7:0] weight_buf_V_9_load_reg_1806;
reg   [7:0] weight_buf_V_10_load_reg_1812;
reg   [7:0] weight_buf_V_11_load_reg_1818;
reg   [7:0] weight_buf_V_12_load_reg_1824;
reg   [7:0] weight_buf_V_13_load_reg_1830;
reg   [7:0] weight_buf_V_14_load_reg_1836;
reg   [7:0] weight_buf_V_15_load_reg_1842;
reg   [7:0] weight_buf_V_16_load_reg_1848;
reg   [7:0] weight_buf_V_17_load_reg_1854;
reg   [7:0] weight_buf_V_18_load_reg_1860;
reg   [7:0] weight_buf_V_19_load_reg_1866;
reg   [7:0] weight_buf_V_20_load_reg_1872;
reg   [7:0] weight_buf_V_21_load_reg_1878;
reg   [7:0] weight_buf_V_22_load_reg_1884;
reg   [7:0] weight_buf_V_23_load_reg_1890;
reg   [7:0] weight_buf_V_24_load_reg_1896;
reg   [7:0] act_buf_V_0_load_reg_1902;
reg   [7:0] act_buf_V_1_load_reg_1908;
reg   [7:0] act_buf_V_2_load_reg_1914;
reg   [7:0] act_buf_V_3_load_reg_1920;
reg   [7:0] act_buf_V_4_load_reg_1926;
reg   [7:0] act_buf_V_5_load_reg_1932;
reg   [7:0] act_buf_V_6_load_reg_1938;
reg   [7:0] act_buf_V_7_load_reg_1944;
reg   [7:0] act_buf_V_8_load_reg_1950;
reg   [7:0] act_buf_V_9_load_reg_1956;
reg   [7:0] act_buf_V_10_load_reg_1962;
reg   [7:0] act_buf_V_11_load_reg_1968;
reg   [7:0] act_buf_V_12_load_reg_1974;
reg   [7:0] act_buf_V_13_load_reg_1980;
reg   [7:0] act_buf_V_14_load_reg_1986;
reg   [7:0] act_buf_V_15_load_reg_1992;
reg   [7:0] act_buf_V_16_load_reg_1998;
reg   [7:0] act_buf_V_17_load_reg_2004;
reg   [7:0] act_buf_V_18_load_reg_2010;
reg   [7:0] act_buf_V_19_load_reg_2016;
reg   [7:0] act_buf_V_20_load_reg_2022;
reg   [7:0] act_buf_V_21_load_reg_2028;
reg   [7:0] act_buf_V_22_load_reg_2034;
reg   [7:0] act_buf_V_23_load_reg_2040;
reg   [7:0] act_buf_V_24_load_reg_2046;
reg   [31:0] acc_reg_V_load_reg_2052;
wire   [0:0] icmp_ln107_1_fu_1168_p2;
reg   [0:0] icmp_ln107_1_reg_2066;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_block_state2_pp0_stage0_iter0;
wire    ap_block_state3_pp0_stage0_iter1;
wire    ap_block_pp0_stage0_11001;
wire   [3:0] i_1_fu_1174_p2;
reg    ap_enable_reg_pp0_iter0;
wire   [2:0] trunc_ln68_1_fu_1180_p1;
wire   [7:0] phi_ln68_3_fu_1192_p34;
reg  signed [7:0] phi_ln68_3_reg_2079;
wire   [7:0] phi_ln68_5_fu_1255_p10;
reg  signed [7:0] phi_ln68_5_reg_2084;
wire   [7:0] phi_ln68_7_fu_1271_p10;
reg  signed [7:0] phi_ln68_7_reg_2089;
wire   [7:0] phi_ln68_9_fu_1287_p10;
reg  signed [7:0] phi_ln68_9_reg_2094;
wire   [7:0] phi_ln68_11_fu_1303_p10;
reg  signed [7:0] phi_ln68_11_reg_2099;
wire   [7:0] phi_ln68_13_fu_1319_p10;
reg  signed [7:0] phi_ln68_13_reg_2104;
wire   [7:0] phi_ln68_14_fu_1335_p10;
reg  signed [7:0] phi_ln68_14_reg_2109;
wire  signed [18:0] grp_fu_1684_p3;
reg    ap_enable_reg_pp0_iter1;
wire  signed [18:0] grp_fu_1692_p3;
wire  signed [18:0] grp_fu_1700_p3;
wire  signed [18:0] grp_fu_1708_p3;
wire   [31:0] add_ln700_1_fu_1413_p2;
reg   [31:0] add_ln700_1_reg_2134;
wire    ap_CS_fsm_state4;
wire   [0:0] icmp_ln107_fu_1424_p2;
reg   [0:0] icmp_ln107_reg_2139;
wire    ap_CS_fsm_pp1_stage0;
wire    ap_block_state6_pp1_stage0_iter0;
wire    ap_block_state7_pp1_stage0_iter1;
wire    ap_block_pp1_stage0_11001;
wire   [3:0] i_fu_1430_p2;
reg    ap_enable_reg_pp1_iter0;
wire   [2:0] trunc_ln68_fu_1436_p1;
wire   [7:0] phi_ln68_2_fu_1448_p34;
reg  signed [7:0] phi_ln68_2_reg_2152;
wire   [7:0] phi_ln68_4_fu_1511_p10;
reg  signed [7:0] phi_ln68_4_reg_2157;
wire   [7:0] phi_ln68_6_fu_1527_p10;
reg  signed [7:0] phi_ln68_6_reg_2162;
wire   [7:0] phi_ln68_8_fu_1543_p10;
reg  signed [7:0] phi_ln68_8_reg_2167;
wire   [7:0] phi_ln68_s_fu_1559_p10;
reg  signed [7:0] phi_ln68_s_reg_2172;
wire   [7:0] phi_ln68_10_fu_1575_p10;
reg  signed [7:0] phi_ln68_10_reg_2177;
wire   [7:0] phi_ln68_12_fu_1591_p10;
reg  signed [7:0] phi_ln68_12_reg_2182;
wire  signed [18:0] grp_fu_1716_p3;
reg    ap_enable_reg_pp1_iter1;
wire  signed [18:0] grp_fu_1724_p3;
wire  signed [18:0] grp_fu_1732_p3;
wire  signed [18:0] grp_fu_1740_p3;
wire    ap_block_pp0_stage0_subdone;
reg    ap_condition_pp0_exit_iter0_state2;
wire    ap_block_pp1_stage0_subdone;
reg    ap_condition_pp1_exit_iter0_state6;
wire    ap_block_pp0_stage0;
wire   [7:0] ap_phi_reg_pp0_iter0_phi_ln68_1_reg_302;
reg  signed [7:0] ap_phi_reg_pp0_iter1_phi_ln68_1_reg_302;
wire    ap_block_pp1_stage0;
wire   [7:0] ap_phi_reg_pp1_iter0_phi_ln68_reg_384;
reg  signed [7:0] ap_phi_reg_pp1_iter1_phi_ln68_reg_384;
wire   [7:0] trunc_ln647_fu_1134_p1;
wire   [6:0] w_ptr_load_load_fu_950_p1;
wire   [7:0] trunc_ln647_1_fu_1100_p1;
wire   [7:0] trunc_ln647_2_fu_1066_p1;
wire   [7:0] trunc_ln647_3_fu_1032_p1;
wire   [7:0] trunc_ln647_4_fu_998_p1;
wire   [7:0] trunc_ln647_5_fu_964_p1;
wire   [7:0] trunc_ln647_6_fu_954_p1;
wire   [7:0] trunc_ln647_7_fu_916_p1;
wire   [6:0] a_ptr_load_load_fu_732_p1;
wire   [7:0] trunc_ln647_8_fu_882_p1;
wire   [7:0] trunc_ln647_9_fu_848_p1;
wire   [7:0] trunc_ln647_10_fu_814_p1;
wire   [7:0] trunc_ln647_11_fu_780_p1;
wire   [7:0] trunc_ln647_12_fu_746_p1;
wire   [7:0] trunc_ln647_13_fu_736_p1;
wire   [0:0] tmp_2_fu_660_p3;
wire   [31:0] add_ln700_fu_668_p2;
wire  signed [31:0] sext_ln68_fu_722_p1;
wire    ap_CS_fsm_state5;
wire  signed [31:0] sext_ln68_3_fu_1674_p1;
wire    ap_CS_fsm_state8;
reg   [31:0] rd_data_V_preg;
wire   [0:0] icmp_ln895_fu_680_p2;
wire   [0:0] icmp_ln895_1_fu_694_p2;
wire   [7:0] max1_V_fu_686_p3;
wire   [7:0] max2_V_fu_700_p3;
wire   [0:0] icmp_ln895_2_fu_708_p2;
wire   [7:0] final_max_V_fu_714_p3;
wire   [4:0] phi_ln68_3_fu_1192_p33;
wire  signed [31:0] sext_ln107_6_fu_1384_p1;
wire  signed [19:0] sext_ln107_5_fu_1380_p1;
wire  signed [19:0] sext_ln107_4_fu_1376_p1;
wire   [19:0] add_ln700_3_fu_1397_p2;
wire  signed [19:0] sext_ln107_7_fu_1388_p1;
wire   [19:0] add_ln700_4_fu_1403_p2;
wire  signed [31:0] sext_ln700_fu_1409_p1;
wire   [31:0] add_ln700_2_fu_1392_p2;
wire   [4:0] phi_ln68_2_fu_1448_p33;
wire  signed [19:0] sext_ln107_2_fu_1640_p1;
wire  signed [19:0] sext_ln107_3_fu_1644_p1;
wire   [19:0] add_ln68_fu_1648_p2;
wire  signed [19:0] sext_ln107_1_fu_1636_p1;
wire  signed [19:0] sext_ln107_fu_1632_p1;
wire   [19:0] add_ln68_1_fu_1658_p2;
wire  signed [20:0] sext_ln68_2_fu_1664_p1;
wire  signed [20:0] sext_ln68_1_fu_1654_p1;
wire   [20:0] add_ln68_2_fu_1668_p2;
reg   [7:0] ap_NS_fsm;
reg    ap_idle_pp0;
wire    ap_enable_pp0;
reg    ap_idle_pp1;
wire    ap_enable_pp1;
reg    ap_condition_235;
reg    ap_condition_294;

// power-on initialization
initial begin
#0 ap_CS_fsm = 8'd1;
#0 weight_buf_V_0 = 8'd0;
#0 weight_buf_V_1 = 8'd0;
#0 weight_buf_V_2 = 8'd0;
#0 weight_buf_V_3 = 8'd0;
#0 weight_buf_V_4 = 8'd0;
#0 weight_buf_V_5 = 8'd0;
#0 weight_buf_V_6 = 8'd0;
#0 weight_buf_V_7 = 8'd0;
#0 weight_buf_V_8 = 8'd0;
#0 weight_buf_V_9 = 8'd0;
#0 weight_buf_V_10 = 8'd0;
#0 weight_buf_V_11 = 8'd0;
#0 weight_buf_V_12 = 8'd0;
#0 weight_buf_V_13 = 8'd0;
#0 weight_buf_V_14 = 8'd0;
#0 weight_buf_V_15 = 8'd0;
#0 weight_buf_V_16 = 8'd0;
#0 weight_buf_V_17 = 8'd0;
#0 weight_buf_V_18 = 8'd0;
#0 weight_buf_V_19 = 8'd0;
#0 weight_buf_V_20 = 8'd0;
#0 weight_buf_V_21 = 8'd0;
#0 weight_buf_V_22 = 8'd0;
#0 weight_buf_V_23 = 8'd0;
#0 weight_buf_V_24 = 8'd0;
#0 act_buf_V_0 = 8'd0;
#0 act_buf_V_1 = 8'd0;
#0 act_buf_V_2 = 8'd0;
#0 act_buf_V_3 = 8'd0;
#0 act_buf_V_4 = 8'd0;
#0 act_buf_V_5 = 8'd0;
#0 act_buf_V_6 = 8'd0;
#0 act_buf_V_7 = 8'd0;
#0 act_buf_V_8 = 8'd0;
#0 act_buf_V_9 = 8'd0;
#0 act_buf_V_10 = 8'd0;
#0 act_buf_V_11 = 8'd0;
#0 act_buf_V_12 = 8'd0;
#0 act_buf_V_13 = 8'd0;
#0 act_buf_V_14 = 8'd0;
#0 act_buf_V_15 = 8'd0;
#0 act_buf_V_16 = 8'd0;
#0 act_buf_V_17 = 8'd0;
#0 act_buf_V_18 = 8'd0;
#0 act_buf_V_19 = 8'd0;
#0 act_buf_V_20 = 8'd0;
#0 act_buf_V_21 = 8'd0;
#0 act_buf_V_22 = 8'd0;
#0 act_buf_V_23 = 8'd0;
#0 act_buf_V_24 = 8'd0;
#0 acc_reg_V = 32'd0;
#0 w_ptr = 7'd0;
#0 a_ptr = 7'd0;
#0 ap_enable_reg_pp0_iter0 = 1'b0;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp1_iter0 = 1'b0;
#0 ap_enable_reg_pp1_iter1 = 1'b0;
#0 rd_data_V_preg = 32'd0;
end

CNN_ALU_Top_mux_3bkb #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 8 ),
    .din4_WIDTH( 8 ),
    .din5_WIDTH( 8 ),
    .din6_WIDTH( 8 ),
    .din7_WIDTH( 8 ),
    .din8_WIDTH( 8 ),
    .din9_WIDTH( 8 ),
    .din10_WIDTH( 8 ),
    .din11_WIDTH( 8 ),
    .din12_WIDTH( 8 ),
    .din13_WIDTH( 8 ),
    .din14_WIDTH( 8 ),
    .din15_WIDTH( 8 ),
    .din16_WIDTH( 8 ),
    .din17_WIDTH( 8 ),
    .din18_WIDTH( 8 ),
    .din19_WIDTH( 8 ),
    .din20_WIDTH( 8 ),
    .din21_WIDTH( 8 ),
    .din22_WIDTH( 8 ),
    .din23_WIDTH( 8 ),
    .din24_WIDTH( 8 ),
    .din25_WIDTH( 8 ),
    .din26_WIDTH( 8 ),
    .din27_WIDTH( 8 ),
    .din28_WIDTH( 8 ),
    .din29_WIDTH( 8 ),
    .din30_WIDTH( 8 ),
    .din31_WIDTH( 8 ),
    .din32_WIDTH( 5 ),
    .dout_WIDTH( 8 ))
CNN_ALU_Top_mux_3bkb_U1(
    .din0(weight_buf_V_0_load_reg_1752),
    .din1(8'd0),
    .din2(8'd0),
    .din3(8'd0),
    .din4(weight_buf_V_4_load_reg_1776),
    .din5(8'd0),
    .din6(8'd0),
    .din7(8'd0),
    .din8(weight_buf_V_8_load_reg_1800),
    .din9(8'd0),
    .din10(8'd0),
    .din11(8'd0),
    .din12(weight_buf_V_12_load_reg_1824),
    .din13(8'd0),
    .din14(8'd0),
    .din15(8'd0),
    .din16(weight_buf_V_16_load_reg_1848),
    .din17(8'd0),
    .din18(8'd0),
    .din19(8'd0),
    .din20(weight_buf_V_20_load_reg_1872),
    .din21(8'd0),
    .din22(8'd0),
    .din23(8'd0),
    .din24(weight_buf_V_24_load_reg_1896),
    .din25(8'd0),
    .din26(8'd0),
    .din27(8'd0),
    .din28(8'd0),
    .din29(8'd0),
    .din30(8'd0),
    .din31(8'd0),
    .din32(phi_ln68_3_fu_1192_p33),
    .dout(phi_ln68_3_fu_1192_p34)
);

CNN_ALU_Top_mux_8cud #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 8 ),
    .din4_WIDTH( 8 ),
    .din5_WIDTH( 8 ),
    .din6_WIDTH( 8 ),
    .din7_WIDTH( 8 ),
    .din8_WIDTH( 3 ),
    .dout_WIDTH( 8 ))
CNN_ALU_Top_mux_8cud_U2(
    .din0(act_buf_V_1_load_reg_1908),
    .din1(act_buf_V_5_load_reg_1932),
    .din2(act_buf_V_9_load_reg_1956),
    .din3(act_buf_V_13_load_reg_1980),
    .din4(act_buf_V_17_load_reg_2004),
    .din5(act_buf_V_21_load_reg_2028),
    .din6(8'd0),
    .din7(8'd0),
    .din8(trunc_ln68_1_fu_1180_p1),
    .dout(phi_ln68_5_fu_1255_p10)
);

CNN_ALU_Top_mux_8cud #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 8 ),
    .din4_WIDTH( 8 ),
    .din5_WIDTH( 8 ),
    .din6_WIDTH( 8 ),
    .din7_WIDTH( 8 ),
    .din8_WIDTH( 3 ),
    .dout_WIDTH( 8 ))
CNN_ALU_Top_mux_8cud_U3(
    .din0(weight_buf_V_1_load_reg_1758),
    .din1(weight_buf_V_5_load_reg_1782),
    .din2(weight_buf_V_9_load_reg_1806),
    .din3(weight_buf_V_13_load_reg_1830),
    .din4(weight_buf_V_17_load_reg_1854),
    .din5(weight_buf_V_21_load_reg_1878),
    .din6(8'd0),
    .din7(8'd0),
    .din8(trunc_ln68_1_fu_1180_p1),
    .dout(phi_ln68_7_fu_1271_p10)
);

CNN_ALU_Top_mux_8cud #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 8 ),
    .din4_WIDTH( 8 ),
    .din5_WIDTH( 8 ),
    .din6_WIDTH( 8 ),
    .din7_WIDTH( 8 ),
    .din8_WIDTH( 3 ),
    .dout_WIDTH( 8 ))
CNN_ALU_Top_mux_8cud_U4(
    .din0(act_buf_V_2_load_reg_1914),
    .din1(act_buf_V_6_load_reg_1938),
    .din2(act_buf_V_10_load_reg_1962),
    .din3(act_buf_V_14_load_reg_1986),
    .din4(act_buf_V_18_load_reg_2010),
    .din5(act_buf_V_22_load_reg_2034),
    .din6(8'd0),
    .din7(8'd0),
    .din8(trunc_ln68_1_fu_1180_p1),
    .dout(phi_ln68_9_fu_1287_p10)
);

CNN_ALU_Top_mux_8cud #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 8 ),
    .din4_WIDTH( 8 ),
    .din5_WIDTH( 8 ),
    .din6_WIDTH( 8 ),
    .din7_WIDTH( 8 ),
    .din8_WIDTH( 3 ),
    .dout_WIDTH( 8 ))
CNN_ALU_Top_mux_8cud_U5(
    .din0(weight_buf_V_2_load_reg_1764),
    .din1(weight_buf_V_6_load_reg_1788),
    .din2(weight_buf_V_10_load_reg_1812),
    .din3(weight_buf_V_14_load_reg_1836),
    .din4(weight_buf_V_18_load_reg_1860),
    .din5(weight_buf_V_22_load_reg_1884),
    .din6(8'd0),
    .din7(8'd0),
    .din8(trunc_ln68_1_fu_1180_p1),
    .dout(phi_ln68_11_fu_1303_p10)
);

CNN_ALU_Top_mux_8cud #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 8 ),
    .din4_WIDTH( 8 ),
    .din5_WIDTH( 8 ),
    .din6_WIDTH( 8 ),
    .din7_WIDTH( 8 ),
    .din8_WIDTH( 3 ),
    .dout_WIDTH( 8 ))
CNN_ALU_Top_mux_8cud_U6(
    .din0(act_buf_V_3_load_reg_1920),
    .din1(act_buf_V_7_load_reg_1944),
    .din2(act_buf_V_11_load_reg_1968),
    .din3(act_buf_V_15_load_reg_1992),
    .din4(act_buf_V_19_load_reg_2016),
    .din5(act_buf_V_23_load_reg_2040),
    .din6(8'd0),
    .din7(8'd0),
    .din8(trunc_ln68_1_fu_1180_p1),
    .dout(phi_ln68_13_fu_1319_p10)
);

CNN_ALU_Top_mux_8cud #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 8 ),
    .din4_WIDTH( 8 ),
    .din5_WIDTH( 8 ),
    .din6_WIDTH( 8 ),
    .din7_WIDTH( 8 ),
    .din8_WIDTH( 3 ),
    .dout_WIDTH( 8 ))
CNN_ALU_Top_mux_8cud_U7(
    .din0(weight_buf_V_3_load_reg_1770),
    .din1(weight_buf_V_7_load_reg_1794),
    .din2(weight_buf_V_11_load_reg_1818),
    .din3(weight_buf_V_15_load_reg_1842),
    .din4(weight_buf_V_19_load_reg_1866),
    .din5(weight_buf_V_23_load_reg_1890),
    .din6(8'd0),
    .din7(8'd0),
    .din8(trunc_ln68_1_fu_1180_p1),
    .dout(phi_ln68_14_fu_1335_p10)
);

CNN_ALU_Top_mux_3bkb #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 8 ),
    .din4_WIDTH( 8 ),
    .din5_WIDTH( 8 ),
    .din6_WIDTH( 8 ),
    .din7_WIDTH( 8 ),
    .din8_WIDTH( 8 ),
    .din9_WIDTH( 8 ),
    .din10_WIDTH( 8 ),
    .din11_WIDTH( 8 ),
    .din12_WIDTH( 8 ),
    .din13_WIDTH( 8 ),
    .din14_WIDTH( 8 ),
    .din15_WIDTH( 8 ),
    .din16_WIDTH( 8 ),
    .din17_WIDTH( 8 ),
    .din18_WIDTH( 8 ),
    .din19_WIDTH( 8 ),
    .din20_WIDTH( 8 ),
    .din21_WIDTH( 8 ),
    .din22_WIDTH( 8 ),
    .din23_WIDTH( 8 ),
    .din24_WIDTH( 8 ),
    .din25_WIDTH( 8 ),
    .din26_WIDTH( 8 ),
    .din27_WIDTH( 8 ),
    .din28_WIDTH( 8 ),
    .din29_WIDTH( 8 ),
    .din30_WIDTH( 8 ),
    .din31_WIDTH( 8 ),
    .din32_WIDTH( 5 ),
    .dout_WIDTH( 8 ))
CNN_ALU_Top_mux_3bkb_U8(
    .din0(weight_buf_V_0_load_reg_1752),
    .din1(8'd0),
    .din2(8'd0),
    .din3(8'd0),
    .din4(weight_buf_V_4_load_reg_1776),
    .din5(8'd0),
    .din6(8'd0),
    .din7(8'd0),
    .din8(weight_buf_V_8_load_reg_1800),
    .din9(8'd0),
    .din10(8'd0),
    .din11(8'd0),
    .din12(weight_buf_V_12_load_reg_1824),
    .din13(8'd0),
    .din14(8'd0),
    .din15(8'd0),
    .din16(weight_buf_V_16_load_reg_1848),
    .din17(8'd0),
    .din18(8'd0),
    .din19(8'd0),
    .din20(weight_buf_V_20_load_reg_1872),
    .din21(8'd0),
    .din22(8'd0),
    .din23(8'd0),
    .din24(weight_buf_V_24_load_reg_1896),
    .din25(8'd0),
    .din26(8'd0),
    .din27(8'd0),
    .din28(8'd0),
    .din29(8'd0),
    .din30(8'd0),
    .din31(8'd0),
    .din32(phi_ln68_2_fu_1448_p33),
    .dout(phi_ln68_2_fu_1448_p34)
);

CNN_ALU_Top_mux_8cud #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 8 ),
    .din4_WIDTH( 8 ),
    .din5_WIDTH( 8 ),
    .din6_WIDTH( 8 ),
    .din7_WIDTH( 8 ),
    .din8_WIDTH( 3 ),
    .dout_WIDTH( 8 ))
CNN_ALU_Top_mux_8cud_U9(
    .din0(act_buf_V_1_load_reg_1908),
    .din1(act_buf_V_5_load_reg_1932),
    .din2(act_buf_V_9_load_reg_1956),
    .din3(act_buf_V_13_load_reg_1980),
    .din4(act_buf_V_17_load_reg_2004),
    .din5(act_buf_V_21_load_reg_2028),
    .din6(8'd0),
    .din7(8'd0),
    .din8(trunc_ln68_fu_1436_p1),
    .dout(phi_ln68_4_fu_1511_p10)
);

CNN_ALU_Top_mux_8cud #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 8 ),
    .din4_WIDTH( 8 ),
    .din5_WIDTH( 8 ),
    .din6_WIDTH( 8 ),
    .din7_WIDTH( 8 ),
    .din8_WIDTH( 3 ),
    .dout_WIDTH( 8 ))
CNN_ALU_Top_mux_8cud_U10(
    .din0(weight_buf_V_1_load_reg_1758),
    .din1(weight_buf_V_5_load_reg_1782),
    .din2(weight_buf_V_9_load_reg_1806),
    .din3(weight_buf_V_13_load_reg_1830),
    .din4(weight_buf_V_17_load_reg_1854),
    .din5(weight_buf_V_21_load_reg_1878),
    .din6(8'd0),
    .din7(8'd0),
    .din8(trunc_ln68_fu_1436_p1),
    .dout(phi_ln68_6_fu_1527_p10)
);

CNN_ALU_Top_mux_8cud #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 8 ),
    .din4_WIDTH( 8 ),
    .din5_WIDTH( 8 ),
    .din6_WIDTH( 8 ),
    .din7_WIDTH( 8 ),
    .din8_WIDTH( 3 ),
    .dout_WIDTH( 8 ))
CNN_ALU_Top_mux_8cud_U11(
    .din0(act_buf_V_2_load_reg_1914),
    .din1(act_buf_V_6_load_reg_1938),
    .din2(act_buf_V_10_load_reg_1962),
    .din3(act_buf_V_14_load_reg_1986),
    .din4(act_buf_V_18_load_reg_2010),
    .din5(act_buf_V_22_load_reg_2034),
    .din6(8'd0),
    .din7(8'd0),
    .din8(trunc_ln68_fu_1436_p1),
    .dout(phi_ln68_8_fu_1543_p10)
);

CNN_ALU_Top_mux_8cud #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 8 ),
    .din4_WIDTH( 8 ),
    .din5_WIDTH( 8 ),
    .din6_WIDTH( 8 ),
    .din7_WIDTH( 8 ),
    .din8_WIDTH( 3 ),
    .dout_WIDTH( 8 ))
CNN_ALU_Top_mux_8cud_U12(
    .din0(weight_buf_V_2_load_reg_1764),
    .din1(weight_buf_V_6_load_reg_1788),
    .din2(weight_buf_V_10_load_reg_1812),
    .din3(weight_buf_V_14_load_reg_1836),
    .din4(weight_buf_V_18_load_reg_1860),
    .din5(weight_buf_V_22_load_reg_1884),
    .din6(8'd0),
    .din7(8'd0),
    .din8(trunc_ln68_fu_1436_p1),
    .dout(phi_ln68_s_fu_1559_p10)
);

CNN_ALU_Top_mux_8cud #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 8 ),
    .din4_WIDTH( 8 ),
    .din5_WIDTH( 8 ),
    .din6_WIDTH( 8 ),
    .din7_WIDTH( 8 ),
    .din8_WIDTH( 3 ),
    .dout_WIDTH( 8 ))
CNN_ALU_Top_mux_8cud_U13(
    .din0(act_buf_V_3_load_reg_1920),
    .din1(act_buf_V_7_load_reg_1944),
    .din2(act_buf_V_11_load_reg_1968),
    .din3(act_buf_V_15_load_reg_1992),
    .din4(act_buf_V_19_load_reg_2016),
    .din5(act_buf_V_23_load_reg_2040),
    .din6(8'd0),
    .din7(8'd0),
    .din8(trunc_ln68_fu_1436_p1),
    .dout(phi_ln68_10_fu_1575_p10)
);

CNN_ALU_Top_mux_8cud #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 8 ),
    .din4_WIDTH( 8 ),
    .din5_WIDTH( 8 ),
    .din6_WIDTH( 8 ),
    .din7_WIDTH( 8 ),
    .din8_WIDTH( 3 ),
    .dout_WIDTH( 8 ))
CNN_ALU_Top_mux_8cud_U14(
    .din0(weight_buf_V_3_load_reg_1770),
    .din1(weight_buf_V_7_load_reg_1794),
    .din2(weight_buf_V_11_load_reg_1818),
    .din3(weight_buf_V_15_load_reg_1842),
    .din4(weight_buf_V_19_load_reg_1866),
    .din5(weight_buf_V_23_load_reg_1890),
    .din6(8'd0),
    .din7(8'd0),
    .din8(trunc_ln68_fu_1436_p1),
    .dout(phi_ln68_12_fu_1591_p10)
);

CNN_ALU_Top_mac_mdEe #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 19 ),
    .dout_WIDTH( 19 ))
CNN_ALU_Top_mac_mdEe_U15(
    .din0(ap_phi_reg_pp0_iter1_phi_ln68_1_reg_302),
    .din1(phi_ln68_3_reg_2079),
    .din2(p_0217_0_i_reg_243),
    .dout(grp_fu_1684_p3)
);

CNN_ALU_Top_mac_mdEe #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 19 ),
    .dout_WIDTH( 19 ))
CNN_ALU_Top_mac_mdEe_U16(
    .din0(phi_ln68_5_reg_2084),
    .din1(phi_ln68_7_reg_2089),
    .din2(p_0111_0_i_reg_255),
    .dout(grp_fu_1692_p3)
);

CNN_ALU_Top_mac_mdEe #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 19 ),
    .dout_WIDTH( 19 ))
CNN_ALU_Top_mac_mdEe_U17(
    .din0(phi_ln68_9_reg_2094),
    .din1(phi_ln68_11_reg_2099),
    .din2(p_0107_0_i_reg_267),
    .dout(grp_fu_1700_p3)
);

CNN_ALU_Top_mac_mdEe #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 19 ),
    .dout_WIDTH( 19 ))
CNN_ALU_Top_mac_mdEe_U18(
    .din0(phi_ln68_14_reg_2109),
    .din1(phi_ln68_13_reg_2104),
    .din2(p_0103_0_i_reg_279),
    .dout(grp_fu_1708_p3)
);

CNN_ALU_Top_mac_mdEe #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 19 ),
    .dout_WIDTH( 19 ))
CNN_ALU_Top_mac_mdEe_U19(
    .din0(ap_phi_reg_pp1_iter1_phi_ln68_reg_384),
    .din1(phi_ln68_2_reg_2152),
    .din2(p_0217_0_i163_reg_325),
    .dout(grp_fu_1716_p3)
);

CNN_ALU_Top_mac_mdEe #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 19 ),
    .dout_WIDTH( 19 ))
CNN_ALU_Top_mac_mdEe_U20(
    .din0(phi_ln68_4_reg_2157),
    .din1(phi_ln68_6_reg_2162),
    .din2(p_0111_0_i164_reg_337),
    .dout(grp_fu_1724_p3)
);

CNN_ALU_Top_mac_mdEe #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 19 ),
    .dout_WIDTH( 19 ))
CNN_ALU_Top_mac_mdEe_U21(
    .din0(phi_ln68_8_reg_2167),
    .din1(phi_ln68_s_reg_2172),
    .din2(p_0107_0_i165_reg_349),
    .dout(grp_fu_1732_p3)
);

CNN_ALU_Top_mac_mdEe #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 19 ),
    .dout_WIDTH( 19 ))
CNN_ALU_Top_mac_mdEe_U22(
    .din0(phi_ln68_12_reg_2182),
    .din1(phi_ln68_10_reg_2177),
    .din2(p_0103_0_i166_reg_361),
    .dout(grp_fu_1740_p3)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_condition_pp0_exit_iter0_state2) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter0 <= 1'b0;
        end else if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1) & (cnn_op_V_read_read_fu_224_p2 == 4'd6))) begin
            ap_enable_reg_pp0_iter0 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_condition_pp0_exit_iter0_state2))) begin
            ap_enable_reg_pp0_iter1 <= (1'b1 ^ ap_condition_pp0_exit_iter0_state2);
        end else if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
        end else if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1) & (cnn_op_V_read_read_fu_224_p2 == 4'd6))) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp1_iter0 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp1_stage0_subdone) & (1'b1 == ap_condition_pp1_exit_iter0_state6) & (1'b1 == ap_CS_fsm_pp1_stage0))) begin
            ap_enable_reg_pp1_iter0 <= 1'b0;
        end else if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1) & (cnn_op_V_read_read_fu_224_p2 == 4'd2))) begin
            ap_enable_reg_pp1_iter0 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp1_iter1 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp1_stage0_subdone) & (1'b1 == ap_condition_pp1_exit_iter0_state6))) begin
            ap_enable_reg_pp1_iter1 <= (1'b1 ^ ap_condition_pp1_exit_iter0_state6);
        end else if ((1'b0 == ap_block_pp1_stage0_subdone)) begin
            ap_enable_reg_pp1_iter1 <= ap_enable_reg_pp1_iter0;
        end else if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1) & (cnn_op_V_read_read_fu_224_p2 == 4'd2))) begin
            ap_enable_reg_pp1_iter1 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        rd_data_V_preg <= 32'd0;
    end else begin
        if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1) & (cnn_op_V_read_read_fu_224_p2 == 4'd3))) begin
            rd_data_V_preg <= acc_reg_V;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((7'd0 == a_ptr_load_load_fu_732_p1) & (1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1) & (cnn_op_V_read_read_fu_224_p2 == 4'd1))) begin
                a_ptr[2] <= 1'b1;
        a_ptr[3] <= 1'b0;
        a_ptr[4] <= 1'b0;
    end else if (((7'd4 == a_ptr_load_load_fu_732_p1) & (1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1) & (cnn_op_V_read_read_fu_224_p2 == 4'd1))) begin
                a_ptr[2] <= 1'b0;
        a_ptr[3] <= 1'b1;
        a_ptr[4] <= 1'b0;
    end else if (((7'd8 == a_ptr_load_load_fu_732_p1) & (1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1) & (cnn_op_V_read_read_fu_224_p2 == 4'd1))) begin
                a_ptr[2] <= 1'b1;
        a_ptr[3] <= 1'b1;
        a_ptr[4] <= 1'b0;
    end else if (((7'd12 == a_ptr_load_load_fu_732_p1) & (1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1) & (cnn_op_V_read_read_fu_224_p2 == 4'd1))) begin
                a_ptr[2] <= 1'b0;
        a_ptr[3] <= 1'b0;
        a_ptr[4] <= 1'b1;
    end else if (((7'd16 == a_ptr_load_load_fu_732_p1) & (1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1) & (cnn_op_V_read_read_fu_224_p2 == 4'd1))) begin
                a_ptr[2] <= 1'b1;
        a_ptr[3] <= 1'b0;
        a_ptr[4] <= 1'b1;
    end else if (((7'd20 == a_ptr_load_load_fu_732_p1) & (1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1) & (cnn_op_V_read_read_fu_224_p2 == 4'd1))) begin
                a_ptr[2] <= 1'b0;
        a_ptr[3] <= 1'b1;
        a_ptr[4] <= 1'b1;
    end else if ((((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1) & (cnn_op_V_read_read_fu_224_p2 == 4'd5)) | (~(7'd24 == a_ptr_load_load_fu_732_p1) & ~(7'd20 == a_ptr_load_load_fu_732_p1) & ~(7'd16 == a_ptr_load_load_fu_732_p1) & ~(7'd12 == a_ptr_load_load_fu_732_p1) & ~(7'd8 == a_ptr_load_load_fu_732_p1) & ~(7'd4 == a_ptr_load_load_fu_732_p1) & ~(7'd0 == a_ptr_load_load_fu_732_p1) & (1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1) & (cnn_op_V_read_read_fu_224_p2 == 4'd1)) | ((7'd24 == a_ptr_load_load_fu_732_p1) & (1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1) & (cnn_op_V_read_read_fu_224_p2 == 4'd1)))) begin
                a_ptr[2] <= 1'b0;
        a_ptr[3] <= 1'b0;
        a_ptr[4] <= 1'b0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        acc_reg_V <= sext_ln68_3_fu_1674_p1;
    end else if (((1'b1 == ap_CS_fsm_state5) & (cnn_op_V_read_read_fu_224_p2 == 4'd6))) begin
        acc_reg_V <= add_ln700_1_reg_2134;
    end else if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1) & (cnn_op_V_read_read_fu_224_p2 == 4'd4))) begin
        acc_reg_V <= sext_ln68_fu_722_p1;
    end else if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1) & (cnn_op_V_read_read_fu_224_p2 == 4'd8))) begin
        acc_reg_V <= add_ln700_fu_668_p2;
    end else if ((((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1) & (cnn_op_V_read_read_fu_224_p2 == 4'd5)) | ((tmp_2_fu_660_p3 == 1'd1) & (1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1) & (cnn_op_V_read_read_fu_224_p2 == 4'd7)))) begin
        acc_reg_V <= 32'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_235)) begin
        if (((trunc_ln68_1_fu_1180_p1 == 3'd6) & (icmp_ln107_1_fu_1168_p2 == 1'd0))) begin
            ap_phi_reg_pp0_iter1_phi_ln68_1_reg_302 <= act_buf_V_24_load_reg_2046;
        end else if (((trunc_ln68_1_fu_1180_p1 == 3'd5) & (icmp_ln107_1_fu_1168_p2 == 1'd0))) begin
            ap_phi_reg_pp0_iter1_phi_ln68_1_reg_302 <= act_buf_V_20_load_reg_2022;
        end else if (((trunc_ln68_1_fu_1180_p1 == 3'd4) & (icmp_ln107_1_fu_1168_p2 == 1'd0))) begin
            ap_phi_reg_pp0_iter1_phi_ln68_1_reg_302 <= act_buf_V_16_load_reg_1998;
        end else if (((trunc_ln68_1_fu_1180_p1 == 3'd3) & (icmp_ln107_1_fu_1168_p2 == 1'd0))) begin
            ap_phi_reg_pp0_iter1_phi_ln68_1_reg_302 <= act_buf_V_12_load_reg_1974;
        end else if (((trunc_ln68_1_fu_1180_p1 == 3'd2) & (icmp_ln107_1_fu_1168_p2 == 1'd0))) begin
            ap_phi_reg_pp0_iter1_phi_ln68_1_reg_302 <= act_buf_V_8_load_reg_1950;
        end else if (((trunc_ln68_1_fu_1180_p1 == 3'd1) & (icmp_ln107_1_fu_1168_p2 == 1'd0))) begin
            ap_phi_reg_pp0_iter1_phi_ln68_1_reg_302 <= act_buf_V_4_load_reg_1926;
        end else if (((trunc_ln68_1_fu_1180_p1 == 3'd0) & (icmp_ln107_1_fu_1168_p2 == 1'd0))) begin
            ap_phi_reg_pp0_iter1_phi_ln68_1_reg_302 <= act_buf_V_0_load_reg_1902;
        end else if (((trunc_ln68_1_fu_1180_p1 == 3'd7) & (icmp_ln107_1_fu_1168_p2 == 1'd0))) begin
            ap_phi_reg_pp0_iter1_phi_ln68_1_reg_302 <= 8'd0;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter1_phi_ln68_1_reg_302 <= ap_phi_reg_pp0_iter0_phi_ln68_1_reg_302;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_294)) begin
        if (((trunc_ln68_fu_1436_p1 == 3'd6) & (icmp_ln107_fu_1424_p2 == 1'd0))) begin
            ap_phi_reg_pp1_iter1_phi_ln68_reg_384 <= act_buf_V_24_load_reg_2046;
        end else if (((trunc_ln68_fu_1436_p1 == 3'd5) & (icmp_ln107_fu_1424_p2 == 1'd0))) begin
            ap_phi_reg_pp1_iter1_phi_ln68_reg_384 <= act_buf_V_20_load_reg_2022;
        end else if (((trunc_ln68_fu_1436_p1 == 3'd4) & (icmp_ln107_fu_1424_p2 == 1'd0))) begin
            ap_phi_reg_pp1_iter1_phi_ln68_reg_384 <= act_buf_V_16_load_reg_1998;
        end else if (((trunc_ln68_fu_1436_p1 == 3'd3) & (icmp_ln107_fu_1424_p2 == 1'd0))) begin
            ap_phi_reg_pp1_iter1_phi_ln68_reg_384 <= act_buf_V_12_load_reg_1974;
        end else if (((trunc_ln68_fu_1436_p1 == 3'd2) & (icmp_ln107_fu_1424_p2 == 1'd0))) begin
            ap_phi_reg_pp1_iter1_phi_ln68_reg_384 <= act_buf_V_8_load_reg_1950;
        end else if (((trunc_ln68_fu_1436_p1 == 3'd1) & (icmp_ln107_fu_1424_p2 == 1'd0))) begin
            ap_phi_reg_pp1_iter1_phi_ln68_reg_384 <= act_buf_V_4_load_reg_1926;
        end else if (((trunc_ln68_fu_1436_p1 == 3'd0) & (icmp_ln107_fu_1424_p2 == 1'd0))) begin
            ap_phi_reg_pp1_iter1_phi_ln68_reg_384 <= act_buf_V_0_load_reg_1902;
        end else if (((trunc_ln68_fu_1436_p1 == 3'd7) & (icmp_ln107_fu_1424_p2 == 1'd0))) begin
            ap_phi_reg_pp1_iter1_phi_ln68_reg_384 <= 8'd0;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp1_iter1_phi_ln68_reg_384 <= ap_phi_reg_pp1_iter0_phi_ln68_reg_384;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp1_stage0_11001) & (icmp_ln107_fu_1424_p2 == 1'd0) & (ap_enable_reg_pp1_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0))) begin
        i_0_i167_reg_373 <= i_fu_1430_p2;
    end else if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1) & (cnn_op_V_read_read_fu_224_p2 == 4'd2))) begin
        i_0_i167_reg_373 <= 4'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln107_1_fu_1168_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        i_0_i_reg_291 <= i_1_fu_1174_p2;
    end else if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1) & (cnn_op_V_read_read_fu_224_p2 == 4'd6))) begin
        i_0_i_reg_291 <= 4'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp1_stage0_11001) & (icmp_ln107_reg_2139 == 1'd0) & (ap_enable_reg_pp1_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0))) begin
        p_0103_0_i166_reg_361 <= grp_fu_1740_p3;
    end else if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1) & (cnn_op_V_read_read_fu_224_p2 == 4'd2))) begin
        p_0103_0_i166_reg_361 <= 19'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln107_1_reg_2066 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_0103_0_i_reg_279 <= grp_fu_1708_p3;
    end else if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1) & (cnn_op_V_read_read_fu_224_p2 == 4'd6))) begin
        p_0103_0_i_reg_279 <= 19'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp1_stage0_11001) & (icmp_ln107_reg_2139 == 1'd0) & (ap_enable_reg_pp1_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0))) begin
        p_0107_0_i165_reg_349 <= grp_fu_1732_p3;
    end else if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1) & (cnn_op_V_read_read_fu_224_p2 == 4'd2))) begin
        p_0107_0_i165_reg_349 <= 19'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln107_1_reg_2066 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_0107_0_i_reg_267 <= grp_fu_1700_p3;
    end else if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1) & (cnn_op_V_read_read_fu_224_p2 == 4'd6))) begin
        p_0107_0_i_reg_267 <= 19'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp1_stage0_11001) & (icmp_ln107_reg_2139 == 1'd0) & (ap_enable_reg_pp1_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0))) begin
        p_0111_0_i164_reg_337 <= grp_fu_1724_p3;
    end else if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1) & (cnn_op_V_read_read_fu_224_p2 == 4'd2))) begin
        p_0111_0_i164_reg_337 <= 19'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln107_1_reg_2066 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_0111_0_i_reg_255 <= grp_fu_1692_p3;
    end else if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1) & (cnn_op_V_read_read_fu_224_p2 == 4'd6))) begin
        p_0111_0_i_reg_255 <= 19'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp1_stage0_11001) & (icmp_ln107_reg_2139 == 1'd0) & (ap_enable_reg_pp1_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0))) begin
        p_0217_0_i163_reg_325 <= grp_fu_1716_p3;
    end else if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1) & (cnn_op_V_read_read_fu_224_p2 == 4'd2))) begin
        p_0217_0_i163_reg_325 <= 19'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln107_1_reg_2066 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_0217_0_i_reg_243 <= grp_fu_1684_p3;
    end else if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1) & (cnn_op_V_read_read_fu_224_p2 == 4'd6))) begin
        p_0217_0_i_reg_243 <= 19'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((w_ptr_load_load_fu_950_p1 == 7'd0) & (1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1) & (cnn_op_V_read_read_fu_224_p2 == 4'd0))) begin
                w_ptr[2] <= 1'b1;
        w_ptr[3] <= 1'b0;
        w_ptr[4] <= 1'b0;
    end else if (((w_ptr_load_load_fu_950_p1 == 7'd4) & (1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1) & (cnn_op_V_read_read_fu_224_p2 == 4'd0))) begin
                w_ptr[2] <= 1'b0;
        w_ptr[3] <= 1'b1;
        w_ptr[4] <= 1'b0;
    end else if (((w_ptr_load_load_fu_950_p1 == 7'd8) & (1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1) & (cnn_op_V_read_read_fu_224_p2 == 4'd0))) begin
                w_ptr[2] <= 1'b1;
        w_ptr[3] <= 1'b1;
        w_ptr[4] <= 1'b0;
    end else if (((w_ptr_load_load_fu_950_p1 == 7'd12) & (1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1) & (cnn_op_V_read_read_fu_224_p2 == 4'd0))) begin
                w_ptr[2] <= 1'b0;
        w_ptr[3] <= 1'b0;
        w_ptr[4] <= 1'b1;
    end else if (((w_ptr_load_load_fu_950_p1 == 7'd16) & (1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1) & (cnn_op_V_read_read_fu_224_p2 == 4'd0))) begin
                w_ptr[2] <= 1'b1;
        w_ptr[3] <= 1'b0;
        w_ptr[4] <= 1'b1;
    end else if (((w_ptr_load_load_fu_950_p1 == 7'd20) & (1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1) & (cnn_op_V_read_read_fu_224_p2 == 4'd0))) begin
                w_ptr[2] <= 1'b0;
        w_ptr[3] <= 1'b1;
        w_ptr[4] <= 1'b1;
    end else if ((((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1) & (cnn_op_V_read_read_fu_224_p2 == 4'd5)) | (~(w_ptr_load_load_fu_950_p1 == 7'd24) & ~(w_ptr_load_load_fu_950_p1 == 7'd20) & ~(w_ptr_load_load_fu_950_p1 == 7'd16) & ~(w_ptr_load_load_fu_950_p1 == 7'd12) & ~(w_ptr_load_load_fu_950_p1 == 7'd8) & ~(w_ptr_load_load_fu_950_p1 == 7'd4) & ~(w_ptr_load_load_fu_950_p1 == 7'd0) & (1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1) & (cnn_op_V_read_read_fu_224_p2 == 4'd0)) | ((w_ptr_load_load_fu_950_p1 == 7'd24) & (1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1) & (cnn_op_V_read_read_fu_224_p2 == 4'd0)))) begin
                w_ptr[2] <= 1'b0;
        w_ptr[3] <= 1'b0;
        w_ptr[4] <= 1'b0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        acc_reg_V_load_reg_2052 <= acc_reg_V;
        act_buf_V_0_load_reg_1902 <= act_buf_V_0;
        act_buf_V_10_load_reg_1962 <= act_buf_V_10;
        act_buf_V_11_load_reg_1968 <= act_buf_V_11;
        act_buf_V_12_load_reg_1974 <= act_buf_V_12;
        act_buf_V_13_load_reg_1980 <= act_buf_V_13;
        act_buf_V_14_load_reg_1986 <= act_buf_V_14;
        act_buf_V_15_load_reg_1992 <= act_buf_V_15;
        act_buf_V_16_load_reg_1998 <= act_buf_V_16;
        act_buf_V_17_load_reg_2004 <= act_buf_V_17;
        act_buf_V_18_load_reg_2010 <= act_buf_V_18;
        act_buf_V_19_load_reg_2016 <= act_buf_V_19;
        act_buf_V_1_load_reg_1908 <= act_buf_V_1;
        act_buf_V_20_load_reg_2022 <= act_buf_V_20;
        act_buf_V_21_load_reg_2028 <= act_buf_V_21;
        act_buf_V_22_load_reg_2034 <= act_buf_V_22;
        act_buf_V_23_load_reg_2040 <= act_buf_V_23;
        act_buf_V_24_load_reg_2046 <= act_buf_V_24;
        act_buf_V_2_load_reg_1914 <= act_buf_V_2;
        act_buf_V_3_load_reg_1920 <= act_buf_V_3;
        act_buf_V_4_load_reg_1926 <= act_buf_V_4;
        act_buf_V_5_load_reg_1932 <= act_buf_V_5;
        act_buf_V_6_load_reg_1938 <= act_buf_V_6;
        act_buf_V_7_load_reg_1944 <= act_buf_V_7;
        act_buf_V_8_load_reg_1950 <= act_buf_V_8;
        act_buf_V_9_load_reg_1956 <= act_buf_V_9;
        weight_buf_V_0_load_reg_1752 <= weight_buf_V_0;
        weight_buf_V_10_load_reg_1812 <= weight_buf_V_10;
        weight_buf_V_11_load_reg_1818 <= weight_buf_V_11;
        weight_buf_V_12_load_reg_1824 <= weight_buf_V_12;
        weight_buf_V_13_load_reg_1830 <= weight_buf_V_13;
        weight_buf_V_14_load_reg_1836 <= weight_buf_V_14;
        weight_buf_V_15_load_reg_1842 <= weight_buf_V_15;
        weight_buf_V_16_load_reg_1848 <= weight_buf_V_16;
        weight_buf_V_17_load_reg_1854 <= weight_buf_V_17;
        weight_buf_V_18_load_reg_1860 <= weight_buf_V_18;
        weight_buf_V_19_load_reg_1866 <= weight_buf_V_19;
        weight_buf_V_1_load_reg_1758 <= weight_buf_V_1;
        weight_buf_V_20_load_reg_1872 <= weight_buf_V_20;
        weight_buf_V_21_load_reg_1878 <= weight_buf_V_21;
        weight_buf_V_22_load_reg_1884 <= weight_buf_V_22;
        weight_buf_V_23_load_reg_1890 <= weight_buf_V_23;
        weight_buf_V_24_load_reg_1896 <= weight_buf_V_24;
        weight_buf_V_2_load_reg_1764 <= weight_buf_V_2;
        weight_buf_V_3_load_reg_1770 <= weight_buf_V_3;
        weight_buf_V_4_load_reg_1776 <= weight_buf_V_4;
        weight_buf_V_5_load_reg_1782 <= weight_buf_V_5;
        weight_buf_V_6_load_reg_1788 <= weight_buf_V_6;
        weight_buf_V_7_load_reg_1794 <= weight_buf_V_7;
        weight_buf_V_8_load_reg_1800 <= weight_buf_V_8;
        weight_buf_V_9_load_reg_1806 <= weight_buf_V_9;
    end
end

always @ (posedge ap_clk) begin
    if (((7'd0 == a_ptr_load_load_fu_732_p1) & (1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1) & (cnn_op_V_read_read_fu_224_p2 == 4'd1))) begin
        act_buf_V_0 <= trunc_ln647_7_fu_916_p1;
        act_buf_V_1 <= {{rs1_data_V[15:8]}};
        act_buf_V_2 <= {{rs1_data_V[23:16]}};
        act_buf_V_3 <= {{rs1_data_V[31:24]}};
    end
end

always @ (posedge ap_clk) begin
    if (((7'd8 == a_ptr_load_load_fu_732_p1) & (1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1) & (cnn_op_V_read_read_fu_224_p2 == 4'd1))) begin
        act_buf_V_10 <= {{rs1_data_V[23:16]}};
        act_buf_V_11 <= {{rs1_data_V[31:24]}};
        act_buf_V_8 <= trunc_ln647_9_fu_848_p1;
        act_buf_V_9 <= {{rs1_data_V[15:8]}};
    end
end

always @ (posedge ap_clk) begin
    if (((7'd12 == a_ptr_load_load_fu_732_p1) & (1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1) & (cnn_op_V_read_read_fu_224_p2 == 4'd1))) begin
        act_buf_V_12 <= trunc_ln647_10_fu_814_p1;
        act_buf_V_13 <= {{rs1_data_V[15:8]}};
        act_buf_V_14 <= {{rs1_data_V[23:16]}};
        act_buf_V_15 <= {{rs1_data_V[31:24]}};
    end
end

always @ (posedge ap_clk) begin
    if (((7'd16 == a_ptr_load_load_fu_732_p1) & (1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1) & (cnn_op_V_read_read_fu_224_p2 == 4'd1))) begin
        act_buf_V_16 <= trunc_ln647_11_fu_780_p1;
        act_buf_V_17 <= {{rs1_data_V[15:8]}};
        act_buf_V_18 <= {{rs1_data_V[23:16]}};
        act_buf_V_19 <= {{rs1_data_V[31:24]}};
    end
end

always @ (posedge ap_clk) begin
    if (((7'd20 == a_ptr_load_load_fu_732_p1) & (1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1) & (cnn_op_V_read_read_fu_224_p2 == 4'd1))) begin
        act_buf_V_20 <= trunc_ln647_12_fu_746_p1;
        act_buf_V_21 <= {{rs1_data_V[15:8]}};
        act_buf_V_22 <= {{rs1_data_V[23:16]}};
        act_buf_V_23 <= {{rs1_data_V[31:24]}};
    end
end

always @ (posedge ap_clk) begin
    if (((7'd24 == a_ptr_load_load_fu_732_p1) & (1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1) & (cnn_op_V_read_read_fu_224_p2 == 4'd1))) begin
        act_buf_V_24 <= trunc_ln647_13_fu_736_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((7'd4 == a_ptr_load_load_fu_732_p1) & (1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1) & (cnn_op_V_read_read_fu_224_p2 == 4'd1))) begin
        act_buf_V_4 <= trunc_ln647_8_fu_882_p1;
        act_buf_V_5 <= {{rs1_data_V[15:8]}};
        act_buf_V_6 <= {{rs1_data_V[23:16]}};
        act_buf_V_7 <= {{rs1_data_V[31:24]}};
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        add_ln700_1_reg_2134 <= add_ln700_1_fu_1413_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        icmp_ln107_1_reg_2066 <= icmp_ln107_1_fu_1168_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp1_stage0_11001) & (1'b1 == ap_CS_fsm_pp1_stage0))) begin
        icmp_ln107_reg_2139 <= icmp_ln107_fu_1424_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp1_stage0_11001) & (icmp_ln107_fu_1424_p2 == 1'd0) & (1'b1 == ap_CS_fsm_pp1_stage0))) begin
        phi_ln68_10_reg_2177 <= phi_ln68_10_fu_1575_p10;
        phi_ln68_12_reg_2182 <= phi_ln68_12_fu_1591_p10;
        phi_ln68_2_reg_2152 <= phi_ln68_2_fu_1448_p34;
        phi_ln68_4_reg_2157 <= phi_ln68_4_fu_1511_p10;
        phi_ln68_6_reg_2162 <= phi_ln68_6_fu_1527_p10;
        phi_ln68_8_reg_2167 <= phi_ln68_8_fu_1543_p10;
        phi_ln68_s_reg_2172 <= phi_ln68_s_fu_1559_p10;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln107_1_fu_1168_p2 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        phi_ln68_11_reg_2099 <= phi_ln68_11_fu_1303_p10;
        phi_ln68_13_reg_2104 <= phi_ln68_13_fu_1319_p10;
        phi_ln68_14_reg_2109 <= phi_ln68_14_fu_1335_p10;
        phi_ln68_3_reg_2079 <= phi_ln68_3_fu_1192_p34;
        phi_ln68_5_reg_2084 <= phi_ln68_5_fu_1255_p10;
        phi_ln68_7_reg_2089 <= phi_ln68_7_fu_1271_p10;
        phi_ln68_9_reg_2094 <= phi_ln68_9_fu_1287_p10;
    end
end

always @ (posedge ap_clk) begin
    if (((w_ptr_load_load_fu_950_p1 == 7'd0) & (1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1) & (cnn_op_V_read_read_fu_224_p2 == 4'd0))) begin
        weight_buf_V_0 <= trunc_ln647_fu_1134_p1;
        weight_buf_V_1 <= {{rs1_data_V[15:8]}};
        weight_buf_V_2 <= {{rs1_data_V[23:16]}};
        weight_buf_V_3 <= {{rs1_data_V[31:24]}};
    end
end

always @ (posedge ap_clk) begin
    if (((w_ptr_load_load_fu_950_p1 == 7'd8) & (1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1) & (cnn_op_V_read_read_fu_224_p2 == 4'd0))) begin
        weight_buf_V_10 <= {{rs1_data_V[23:16]}};
        weight_buf_V_11 <= {{rs1_data_V[31:24]}};
        weight_buf_V_8 <= trunc_ln647_2_fu_1066_p1;
        weight_buf_V_9 <= {{rs1_data_V[15:8]}};
    end
end

always @ (posedge ap_clk) begin
    if (((w_ptr_load_load_fu_950_p1 == 7'd12) & (1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1) & (cnn_op_V_read_read_fu_224_p2 == 4'd0))) begin
        weight_buf_V_12 <= trunc_ln647_3_fu_1032_p1;
        weight_buf_V_13 <= {{rs1_data_V[15:8]}};
        weight_buf_V_14 <= {{rs1_data_V[23:16]}};
        weight_buf_V_15 <= {{rs1_data_V[31:24]}};
    end
end

always @ (posedge ap_clk) begin
    if (((w_ptr_load_load_fu_950_p1 == 7'd16) & (1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1) & (cnn_op_V_read_read_fu_224_p2 == 4'd0))) begin
        weight_buf_V_16 <= trunc_ln647_4_fu_998_p1;
        weight_buf_V_17 <= {{rs1_data_V[15:8]}};
        weight_buf_V_18 <= {{rs1_data_V[23:16]}};
        weight_buf_V_19 <= {{rs1_data_V[31:24]}};
    end
end

always @ (posedge ap_clk) begin
    if (((w_ptr_load_load_fu_950_p1 == 7'd20) & (1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1) & (cnn_op_V_read_read_fu_224_p2 == 4'd0))) begin
        weight_buf_V_20 <= trunc_ln647_5_fu_964_p1;
        weight_buf_V_21 <= {{rs1_data_V[15:8]}};
        weight_buf_V_22 <= {{rs1_data_V[23:16]}};
        weight_buf_V_23 <= {{rs1_data_V[31:24]}};
    end
end

always @ (posedge ap_clk) begin
    if (((w_ptr_load_load_fu_950_p1 == 7'd24) & (1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1) & (cnn_op_V_read_read_fu_224_p2 == 4'd0))) begin
        weight_buf_V_24 <= trunc_ln647_6_fu_954_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((w_ptr_load_load_fu_950_p1 == 7'd4) & (1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1) & (cnn_op_V_read_read_fu_224_p2 == 4'd0))) begin
        weight_buf_V_4 <= trunc_ln647_1_fu_1100_p1;
        weight_buf_V_5 <= {{rs1_data_V[15:8]}};
        weight_buf_V_6 <= {{rs1_data_V[23:16]}};
        weight_buf_V_7 <= {{rs1_data_V[31:24]}};
    end
end

always @ (*) begin
    if ((icmp_ln107_1_fu_1168_p2 == 1'd1)) begin
        ap_condition_pp0_exit_iter0_state2 = 1'b1;
    end else begin
        ap_condition_pp0_exit_iter0_state2 = 1'b0;
    end
end

always @ (*) begin
    if ((icmp_ln107_fu_1424_p2 == 1'd1)) begin
        ap_condition_pp1_exit_iter0_state6 = 1'b1;
    end else begin
        ap_condition_pp1_exit_iter0_state6 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp1_iter1 == 1'b0) & (ap_enable_reg_pp1_iter0 == 1'b0))) begin
        ap_idle_pp1 = 1'b1;
    end else begin
        ap_idle_pp1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1) & (cnn_op_V_read_read_fu_224_p2 == 4'd3))) begin
        rd_data_V = acc_reg_V;
    end else begin
        rd_data_V = rd_data_V_preg;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1) & (cnn_op_V_read_read_fu_224_p2 == 4'd0))) begin
                ap_NS_fsm = ap_ST_fsm_state10;
            end else if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1) & (cnn_op_V_read_read_fu_224_p2 == 4'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state9;
            end else if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1) & (cnn_op_V_read_read_fu_224_p2 == 4'd2))) begin
                ap_NS_fsm = ap_ST_fsm_pp1_stage0;
            end else if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1) & (cnn_op_V_read_read_fu_224_p2 == 4'd6))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else if ((~(cnn_op_V_read_read_fu_224_p2 == 4'd1) & ~(cnn_op_V_read_read_fu_224_p2 == 4'd0) & ~(cnn_op_V_read_read_fu_224_p2 == 4'd2) & ~(cnn_op_V_read_read_fu_224_p2 == 4'd6) & (1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_pp0_stage0 : begin
            if (~((1'b0 == ap_block_pp0_stage0_subdone) & (icmp_ln107_1_fu_1168_p2 == 1'd1) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (icmp_ln107_1_fu_1168_p2 == 1'd1) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        ap_ST_fsm_pp1_stage0 : begin
            if (~((1'b0 == ap_block_pp1_stage0_subdone) & (icmp_ln107_fu_1424_p2 == 1'd1) & (ap_enable_reg_pp1_iter0 == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_pp1_stage0;
            end else if (((1'b0 == ap_block_pp1_stage0_subdone) & (icmp_ln107_fu_1424_p2 == 1'd1) & (ap_enable_reg_pp1_iter0 == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state8;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp1_stage0;
            end
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state9 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state10 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign a_ptr_load_load_fu_732_p1 = a_ptr;

assign add_ln68_1_fu_1658_p2 = ($signed(sext_ln107_1_fu_1636_p1) + $signed(sext_ln107_fu_1632_p1));

assign add_ln68_2_fu_1668_p2 = ($signed(sext_ln68_2_fu_1664_p1) + $signed(sext_ln68_1_fu_1654_p1));

assign add_ln68_fu_1648_p2 = ($signed(sext_ln107_2_fu_1640_p1) + $signed(sext_ln107_3_fu_1644_p1));

assign add_ln700_1_fu_1413_p2 = ($signed(sext_ln700_fu_1409_p1) + $signed(add_ln700_2_fu_1392_p2));

assign add_ln700_2_fu_1392_p2 = ($signed(acc_reg_V_load_reg_2052) + $signed(sext_ln107_6_fu_1384_p1));

assign add_ln700_3_fu_1397_p2 = ($signed(sext_ln107_5_fu_1380_p1) + $signed(sext_ln107_4_fu_1376_p1));

assign add_ln700_4_fu_1403_p2 = ($signed(add_ln700_3_fu_1397_p2) + $signed(sext_ln107_7_fu_1388_p1));

assign add_ln700_fu_668_p2 = (acc_reg_V + rs1_data_V);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_pp1_stage0 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd5];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp1_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp1_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp1_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_block_state2_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state6_pp1_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state7_pp1_stage0_iter1 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_condition_235 = ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0));
end

always @ (*) begin
    ap_condition_294 = ((1'b0 == ap_block_pp1_stage0_11001) & (ap_enable_reg_pp1_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0));
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_pp1 = (ap_idle_pp1 ^ 1'b1);

assign ap_phi_reg_pp0_iter0_phi_ln68_1_reg_302 = 'bx;

assign ap_phi_reg_pp1_iter0_phi_ln68_reg_384 = 'bx;

assign cnn_op_V_read_read_fu_224_p2 = cnn_op_V;

assign final_max_V_fu_714_p3 = ((icmp_ln895_2_fu_708_p2[0:0] === 1'b1) ? max1_V_fu_686_p3 : max2_V_fu_700_p3);

assign i_1_fu_1174_p2 = (i_0_i_reg_291 + 4'd1);

assign i_fu_1430_p2 = (i_0_i167_reg_373 + 4'd1);

assign icmp_ln107_1_fu_1168_p2 = ((i_0_i_reg_291 == 4'd8) ? 1'b1 : 1'b0);

assign icmp_ln107_fu_1424_p2 = ((i_0_i167_reg_373 == 4'd8) ? 1'b1 : 1'b0);

assign icmp_ln895_1_fu_694_p2 = (($signed(act_buf_V_2) > $signed(act_buf_V_3)) ? 1'b1 : 1'b0);

assign icmp_ln895_2_fu_708_p2 = (($signed(max1_V_fu_686_p3) > $signed(max2_V_fu_700_p3)) ? 1'b1 : 1'b0);

assign icmp_ln895_fu_680_p2 = (($signed(act_buf_V_0) > $signed(act_buf_V_1)) ? 1'b1 : 1'b0);

assign max1_V_fu_686_p3 = ((icmp_ln895_fu_680_p2[0:0] === 1'b1) ? act_buf_V_0 : act_buf_V_1);

assign max2_V_fu_700_p3 = ((icmp_ln895_1_fu_694_p2[0:0] === 1'b1) ? act_buf_V_2 : act_buf_V_3);

assign phi_ln68_2_fu_1448_p33 = {{trunc_ln68_fu_1436_p1}, {2'd0}};

assign phi_ln68_3_fu_1192_p33 = {{trunc_ln68_1_fu_1180_p1}, {2'd0}};

assign sext_ln107_1_fu_1636_p1 = p_0111_0_i164_reg_337;

assign sext_ln107_2_fu_1640_p1 = p_0107_0_i165_reg_349;

assign sext_ln107_3_fu_1644_p1 = p_0103_0_i166_reg_361;

assign sext_ln107_4_fu_1376_p1 = p_0217_0_i_reg_243;

assign sext_ln107_5_fu_1380_p1 = p_0111_0_i_reg_255;

assign sext_ln107_6_fu_1384_p1 = p_0107_0_i_reg_267;

assign sext_ln107_7_fu_1388_p1 = p_0103_0_i_reg_279;

assign sext_ln107_fu_1632_p1 = p_0217_0_i163_reg_325;

assign sext_ln68_1_fu_1654_p1 = $signed(add_ln68_fu_1648_p2);

assign sext_ln68_2_fu_1664_p1 = $signed(add_ln68_1_fu_1658_p2);

assign sext_ln68_3_fu_1674_p1 = $signed(add_ln68_2_fu_1668_p2);

assign sext_ln68_fu_722_p1 = $signed(final_max_V_fu_714_p3);

assign sext_ln700_fu_1409_p1 = $signed(add_ln700_4_fu_1403_p2);

assign tmp_2_fu_660_p3 = acc_reg_V[32'd31];

assign trunc_ln647_10_fu_814_p1 = rs1_data_V[7:0];

assign trunc_ln647_11_fu_780_p1 = rs1_data_V[7:0];

assign trunc_ln647_12_fu_746_p1 = rs1_data_V[7:0];

assign trunc_ln647_13_fu_736_p1 = rs1_data_V[7:0];

assign trunc_ln647_1_fu_1100_p1 = rs1_data_V[7:0];

assign trunc_ln647_2_fu_1066_p1 = rs1_data_V[7:0];

assign trunc_ln647_3_fu_1032_p1 = rs1_data_V[7:0];

assign trunc_ln647_4_fu_998_p1 = rs1_data_V[7:0];

assign trunc_ln647_5_fu_964_p1 = rs1_data_V[7:0];

assign trunc_ln647_6_fu_954_p1 = rs1_data_V[7:0];

assign trunc_ln647_7_fu_916_p1 = rs1_data_V[7:0];

assign trunc_ln647_8_fu_882_p1 = rs1_data_V[7:0];

assign trunc_ln647_9_fu_848_p1 = rs1_data_V[7:0];

assign trunc_ln647_fu_1134_p1 = rs1_data_V[7:0];

assign trunc_ln68_1_fu_1180_p1 = i_0_i_reg_291[2:0];

assign trunc_ln68_fu_1436_p1 = i_0_i167_reg_373[2:0];

assign w_ptr_load_load_fu_950_p1 = w_ptr;

always @ (posedge ap_clk) begin
    w_ptr[1:0] <= 2'b00;
    w_ptr[6:5] <= 2'b00;
    a_ptr[1:0] <= 2'b00;
    a_ptr[6:5] <= 2'b00;
end

endmodule //CNN_ALU_Top
